### ISSUE TITLE
applied is crashing my server with mods 1.16.5

### ISSUE THREAD

**Issue by TainanRezende** [AppliedEnergistics/Applied-Energistics-2#5797] opened 2021-12-16 00:13 UTC
### Describe the bug

Hi, I have a problem on my server that when I open the applied system (the inventory, graft terminal and other terminals) my server starts allocating ram without stopping and the processor reaches 100% of use (in my case the percentage of use is given in 100 for each nucleus at 400% b and use) until it triggers the watchdog and knocks down the server (turns off) and in the crash report it points to the applied container. I wanted to know if it really is the responsible or is another mod causing conflict or something else, I'll set the crash report

### How to reproduce the bug

it basically fills the system with items and recipes and I don't know if it happens in other modpacks, but it's like that in mine after we're advanced (many items and automatons in the system)

### Expected behavior

it may or may not happen, it is intermittent but when it happens, the use of processed, the server laga(tps) and stays until the watchdog of the server is activated or it can stop overloading dps for a while (in my case I increased the time by 60 second to 180 second to trigger the watchdog to avoid restarting the server too often)

### Additional details

I'm playing a modpack that I created and I update it almost every day and play with friends.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/TainanRezende/00be9309ca23734bf34b301b5f055ad7

**Comment by shartte** [comment] 2021-12-16 00:24
Looks like a duplicate of #5752 
Please remove polymorph and see if the issue persists.

**Closed by shartte** 2021-12-16 00:24 UTC
Labels: bug
