### ISSUE TITLE
Two crashes in a row when moving away from base

### ISSUE THREAD

**Issue by Dimentive** [AppliedEnergistics/Applied-Energistics-2#4004] opened 2019-04-17 07:54 UTC
I simply flew from my base to the wilderness, and my game crashed. I got two separate crashes at the same time (one minute apart from each other).

**Crash report 1:** [“Exception in server tick loop”](https://pastebin.com/raw/69mkeD9M) (java.lang.NullPointerException)
**Crash report 2:** [“Batching chunks”](https://pastebin.com/raw/wsB6vgi1) (java.lang.IllegalStateException: Not building!)

The first crash named Applied Energistics 2 (and no other mods) in as the suspected mod to have caused this crash, which is why I’m posting this on the AE2 issue tracker.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.65a](https://minecraft.curseforge.com/projects/enigmatica2/files/2700051), latest)
* **Applied Energistics 2:** [rv6-stable-6](https://minecraft.curseforge.com/projects/applied-energistics-2/files/2652453) (latest)

**Comment by mindforger** [comment] 2019-04-17 08:51
Try to chunkload the me system to workaround temporarily .. (Is that even spelled right?)

**Comment by Dimentive** [comment] 2019-04-17 11:13
My entire ME system is already chunk-loaded.

**Comment by yueh** [comment] 2019-04-18 07:21
Duplicate of #3987

**Closed by yueh** 2019-04-18 07:21 UTC
