### ISSUE TITLE
Rework of the me-cable routing system

### ISSUE THREAD

**Issue by rockseisen** [AppliedEnergistics/Applied-Energistics-2#5310] opened 2021-06-26 20:00 UTC
Hi there AE2-Team!

I recently played the direwolf20 pack on ftb and addiction stroke so i overdid the ME-System (especially the autocrafting) a little bit. Rather, i had the feeling that the autocrafting-system or more the fluix cable system is not designed to hold such a massive amount of attachments like i had on this system. 🙈 

The Problem i faced:
Since i was about to do an autocrafted pattern for most of the used items the amount of machinery (eg molecular assembler or smelting factories (Mekanism)) the usage of channels on even a dense (smart) me-cable was fully utilized. As seen in the picture below, after finishing the building of the molecular assemblers and the cable structure and connecting it to the me-system only 8 out of 32 channels are taken (It's the same for me smart cables as well).

Some structure information:
These are 16 molecular assembers. On the bottom is the power supply (doesn't take a channel), on the top a import bus and on the back a me-interface. All of these are attached to a dense me smart cable via fluix me-cables.

![image_cable_algorithm](https://user-images.githubusercontent.com/16632658/123523600-e5aa2800-d6c4-11eb-9712-c5765c254c8e.png)

In my opinion this is thanks to the algorithm not checking on the whole cable-structure (of the same cable type) but rather searching for the first possible channel users and stopping after all possible channels are taken.

**Describe the feature**
The feature is rather an enhancement than a feature. As i worked out the current cable-management-algorithm is run every time a cable is attached to the me-system. This is a very convenient method for simple constructions. But with rising complexicity and cable-channels this algorithm will face some problems (eg the one i explained earlier but more important are continuous performance issues when the algorithm is run on large cable-structures).
My solution to this problem is to provide the networking tool with a function to run the algorithm again or rather a updated version of that algorithm that detects every bus/interface/me-peripheral that needs a channel and manages the channel-structure that everyone gets a connection to the controller (As for graphical-beauty-aspects you could add a processing output on the network tool). Additional to that (as another motivation to build that tool) i'd restrict the dense-me-smart-cable to use only this method of channel-management (this would not only NOT effect the small me-system-structures but also decrease the performance issues when working with larger structures).

**Reasons why it should be considered**
As already explained in my text before this would not only increase the performance of the whole system but also give "grinders" more motivation to build large autocrafting systems because there are no more issues with large cable structures.

**Additional Context**
Since i would humbly call myself a programmer aswell hook me up if no one on your team wants to do that kind of stuff. In order to do that i would have to get a short introduction in the project sturcture and the minecraft modding engine aswell since i did this stuff as a kid (that was 2016 or sth) but am completely out of it now.

Sincerely 
rockseisen 

PS: i know the problem i wrote can be solved by attaching the cables the right way but what a solution is this if you just could do a right-click with the right tool 😒

**Comment by yueh** [comment] 2021-06-26 22:03
Duplicate of #5278

**Closed by yueh** 2021-06-26 22:03 UTC
