### ISSUE TITLE
Improve wireles  connection of  wireles terminal

### ISSUE THREAD

**Issue by pd200** [AppliedEnergistics/Applied-Energistics-2#4929] opened 2021-01-11 02:54 UTC
**Describe the feature**
Make an object that permis to have wireles connection to the terminal in all dimension and without limits of range.
Add a crafting wirels terminal

**Reasons why it should be considered**
Why consider this ??
Because it is really boring when for example you have to do a job or you are in another dimension, therefore outside the range, and maybe you forget a simple cable or you run out of torches and then you have to go back through the range and then return to where you were.
And if you add that, you also add a crafting wireles terminal, so you don't have to go back and forth to craft items.
Because, I repeat, it is really boring, and they make us regret the lack of plug-ins in 1.16

**Comment by yueh** [comment] 2021-01-11 10:07
Duplicate of #1158

**Closed by yueh** 2021-01-11 10:07 UTC
