### ISSUE TITLE
Autocrafting request

### ISSUE THREAD

**Issue by castilio20** [AppliedEnergistics/Applied-Energistics-2#4987] opened 2021-02-15 15:38 UTC
**Describe the feature**

a feature that lets know if you have the items in the system for the crafting  +lets you autocraft somthing if you have that recipe and you dont have make another recipe like for a machine you dont need to make another recipe you just request all the ingredients to be make
**Reasons why it should be considered**

i know that is rs feature but is a nice feature and is a QoL and helps players bc i love ae2 and i dont like rs i want to play with ae2
**Additional Context**

![2021-01-02_21 39 56](https://user-images.githubusercontent.com/76228548/107965607-96f2c180-6f5f-11eb-982f-7e831659b66b.png)

**Comment by yueh** [comment] 2021-02-15 16:20
Duplicate of #4856

**Closed by yueh** 2021-02-15 16:20 UTC
