### ISSUE TITLE
Server crash and world corruption upon removal and placement of dense energy cell. 

### ISSUE THREAD

**Issue by Gunner76th** [AppliedEnergistics/Applied-Energistics-2#4070] opened 2019-06-20 04:03 UTC
**Describe the bug**

Upon removing and replacing a dense energy cell, the server crashes. 
**To Reproduce**

Unknown. 
**Expected behavior**

Be able to remove and replace the dense energy cell at will without risk of server crash or world corruption. 
**Additional context**

[crash-2019-06-19_23.48.20-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3308692/crash-2019-06-19_23.48.20-server.txt)

https://gist.github.com/Gunner76th/e1824c7c1bdc5bb46ccb8f2f0017eabe

**Environment**

Sky Factory 4 modpack from the Twitch Launcher. 

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 2838

**Comment by Gunner76th** [comment] 2019-06-20 04:40
To prevent this crash, you need to blacklist AE energy cells as well as the energy acceptor in the Flux Network config. The config change is supplied below, copy it and replace what is in your current config in the blacklist section. 

```
blacklists {
    # a blacklist for blocks which flux connections shouldn't connect to, use format 'modid:name'
    S:"Block Connection Blacklist" <
        actuallyadditions:block_phantom_energyface
	appliedenergistics2:energy_acceptor
	appliedenergistics2:dense_energy_cell
	appliedenergistics2:energy_cell 
     >

    # a blacklist for items which the Flux Controller shouldn't transfer to, use format 'modid:name'
    S:"Item Transfer Blacklist" <
	appliedenergistics2:energy_acceptor
	appliedenergistics2:dense_energy_cell
	appliedenergistics2:energy_cell 
     >
}

```

**Comment by yueh** [comment] 2019-06-20 08:23
Duplicate of #4012

**Closed by yueh** 2019-06-20 08:23 UTC
