### ISSUE TITLE
Devices go offline when ME Quantium Link online

### ISSUE THREAD

**Issue by Valleriani** [AppliedEnergistics/Applied-Energistics-2#1664] opened 2015-07-01 09:09 UTC
Devices go offline when letting the chunks despawn (I.E. travelling to another dimension). I've made a simple video here:

https://www.youtube.com/watch?v=ZC3Qne8XmNE&feature=youtu.be

You can see that everything is online, I go to another dimension (The dimension with the quantum  link chamber receiver to the main base), come back, and some things are offline. It is always the same devices. In the video it does show I use enderIO cables here and there however, I also removed those and get the same effect. Some areas in the video you can see it's using basic ME dense cables.

The solution is to break the cable at the base and reconnect it. It's sort of a problem though since I have to do it constantly.

When the ME quantum link chamber (the one you see in the video) is removed, everything works FINE. The devices going offline only occur when it is activated on both sides

forge-1.7.10-10.13.4.1448-1.7.10-universal.jar
appliedenergistics2-rv2-stable-9.jar

**Comment by Valleriani** [comment] 2015-07-01 09:20
Would like to point out when I add a chunk loader to the space base (I.E. where i teleported too in the video with only the quantum link and me Interface), nothing breaks. Obviously it will when the server reboots though.

This means the issue occurs right when I teleport back to the main base and the space base chunks despawn.

**Comment by yueh** [comment] 2015-07-02 23:31
Might be a  duplicate of #1611, could you please test this [build](http://ci.tsr.me/repository/download/AppliedEnergistics_PullRequests/3232:id/appliedenergistics2-rv3-alpha-pr1668.jar)?
It says rv3, because the CI is configured to name all PR builds in this way. If it did not mess something up, it is a fixed rv2 build. But as usual, make a backup before testing it.

As another question, did you replace the EnderIO conduits on the QNB?

**Comment by Valleriani** [comment] 2015-07-03 06:58
I am using only AE2's wires to the QNB. However, the good news is the issue is resolved in the build you posted. Power stays online.

**Comment by yueh** [comment] 2015-07-03 12:15
Ok, then it is a duplicate. I still hope some other user can report back, if the build fixes it. I still have no idea or a good description on how to reproduce it.

**Closed by yueh** 2015-07-03 12:15 UTC
Labels: state-waiting
