### ISSUE TITLE
 Applied-Energistics-2 system freezze bug

### ISSUE THREAD

**Issue by zverje** [AppliedEnergistics/Applied-Energistics-2#1748] opened 2015-07-28 19:18 UTC
After restart my game world my Applied Energistics 2 system freeze.System consumes energy but not working.Verison of Applied-Energistics-2 rv2-stable-10.Video http://youtu.be/t6l5gHXwpmQ

**Comment by Ianaver** [comment] 2015-07-29 04:17
that's strange, did you ever get it back up? I think maybe replacing one of the wires will send an update and possibly make the system reboot if it happens again

**Comment by yueh** [comment] 2015-07-29 07:45
Can you post the `settings.cfg` inside your world folder on pastebin?

**Comment by zverje** [comment] 2015-07-29 08:45
@yueh 
Yes of course. http://pastebin.com/HnRkpKm6

@Ianaver 
Helps only full  dismantling of machines from AP2 , Its happens every time when entering the world.

**Comment by yueh** [comment] 2015-07-29 15:22
Looks like a duplicate of #1266

**Closed** 2015-08-04 14:31 UTC
