### ISSUE TITLE
[1.16.3] Single player world creation halted at %15 crash log in client console. java.lang.NullPointerException: Exception generating new chunk at appeng.worldgen.meteorite.MeteoriteStructureStart.getFalloutFromBaseBlock

### ISSUE THREAD

**Issue by ProsperCraft** [AppliedEnergistics/Applied-Energistics-2#4785] opened 2020-10-20 05:18 UTC
**Describe the bug**
I started a world, and it failed to create a chunk and crashed.

**Additional context**
Complete log with the crash report at the end as it didn't actually fully crash and create a report-
https://gist.githubusercontent.com/ProsperCraft/87ace8c43e8eab41812c86e8b686b6e5/raw/6af7948ce62b05172e2634ff80d4e8093cc24147/gistfile1.txt

**Environment**
Client locked up F3+c would not do anything.

- Environment: 
appliedenergistics2-8.1.0-alpha.3
forge-1.16.3-34.1.23
Modpack- [TownCraft TWO for 1.16.3](https://www.curseforge.com/minecraft/modpacks/towncraft)

**Comment by ProsperCraft** [comment] 2020-10-20 23:08
Dedicated server just crashed with the same stacktrace-
https://gist.github.com/ProsperCraft/00c9f6eb41967c3be98f33f05fb903a6

Here is the server debug.log
https://gist.githubusercontent.com/ProsperCraft/409b9435427cff0d544945ae9561a127/raw/7f95b0bf20bcfb3c55af23f9577841ed8de1bf1a/gistfile1.txt

**Comment by yueh** [comment] 2020-10-21 14:58
This looks be caused by some biome not implementing the necessary details. Sadly no idea which mod it might cause it, maybe your modpack author has more insight about it.

Technically we could safeguard against it, but I have no idea how minecraft itself would handle it. So there might certainly be other bugs caused by it. At least they should return air as blockstate for the top layer when it's a void biome or similar.

**Comment by ProsperCraft** [comment] 2020-10-21 17:11
I am the modpack author.

Perhaps it is the Oh The Biomes You Will go mod, this is the only biome mod we are using.

I did disable worldgen of the meteors and this did work as a workaround to stop the server crashing.

**Comment by yueh** [comment] 2020-10-22 08:43
Yes, they ignore the vanilla methods to determine the top/under block of each biome and replace it with their own implementation. Looks like they now fixed it a few hours ago by defaulting to air (always). So it should no longer crash, but it will certainly generate the wrong crater for desert, snow, or similar biomes. But that is nothing we can really account for and try to correct it.

**Closed by yueh** 2020-10-22 08:43 UTC
Labels: awaiting-feedback
