### ISSUE TITLE
Recipe error with grinder/crusher

### ISSUE THREAD

**Issue by hehe3301** [AppliedEnergistics/Applied-Energistics-2#3440] opened 2018-03-24 14:56 UTC
#### Description
Error is these recipes are not present in the Immersive Engineering Crusher.

AE is not properly registering recipes with grinders/crushers, in the log file I find this:

Recipe Error 'Invalid crafting type: grindfz' near line:9 in processing/factorization.recipe with:
[ae2:material.fluix_crystal, ->, ae2:material.fluix_dust]
[ae2:sky_stone_block:0, ->, ae2:material.sky_dust]
[mc:ender_pearl, ->, ae2:material.ender_dust]
[ae2:material.certus_quartz_crystal_charged, ->, ae2:material.certus_quartz_dust]
[ae2:material.certus_quartz_crystal, ->, ae2:material.certus_quartz_dust]
[ae2:quartz_ore, ->, 2, ae2:material.certus_quartz_dust]
[ae2:charged_quartz_ore, ->, 2, ae2:material.certus_quartz_dust]

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.2624
- Immersive Engineering Version: -0.12-80

**Comment by yueh** [comment] 2018-03-24 15:00
Duplicate of #2959

**Closed by yueh** 2018-03-24 15:00 UTC
