### ISSUE TITLE
Applied Energistics 2 "Station can not be located" 

### ISSUE THREAD

**Issue by SnuggleBear110802** [AppliedEnergistics/Applied-Energistics-2#3047] opened 2017-08-19 11:51 UTC
Hello! I'm playing on the latest version of the dw20 pack 1.10.2, and I'm playing on a server that has no additional mods added. My issue is that every now and then my wireless terminal gives me a message in the chat saying: "Station can not be located". For my to fix it, I would have to break and replace the security terminal and re-link my wireless terminal. The version of AE2 in the pack is "appliedenergistics2-rv4-alpha-11.jar".Im playing on Minecraft 1.10.2 and the version of Forge is: "forge-12.18.3.2316
The server does restarts to prevent any lag, its usually on a timer and I am not sure what the timer is.
My wireless access point is directly hooked up to my controller.

**Comment by fscan** [comment] 2017-08-21 14:23
Duplicate of #2984

**Closed by fscan** 2017-08-21 14:23 UTC
