### ISSUE TITLE
Game constantly crashes after removing a smart cable

### ISSUE THREAD

**Issue by BrunnerLivio** [AppliedEnergistics/Applied-Energistics-2#4094] opened 2019-07-13 17:17 UTC
**Describe the bug**
When I removed a smart cable from my connected ME Network, my game crashed. Whenever I start the world again, it crashes again, making it unable to play my map again.

**To Reproduce**
I am not able to reproduce the error :/

**Expected behavior**
Should not crash ^^

**Additional context**
Crash logs

```
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source) ~[?:1.8.0_45]
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:199) ~[EnergyGridCache.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2026_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```

Seems like the affected line which causes to throw a `java.util.ConcurrentModificationException` exception is the following:

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fdcba13369d5010fe982b993bf53ee00777fd15c/src/main/java/appeng/me/cache/EnergyGridCache.java#L316

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: Build rv6.stable.6

**Comment by yueh** [comment] 2019-07-13 17:35
Duplicate of #3800

**Closed by yueh** 2019-07-13 17:35 UTC

**Comment by Shybella** [comment] 2019-08-30 17:04
I don't understand why these keep getting closed. It's killing everyone's singleplayer worlds.

**Comment by mindforger** [comment] 2019-08-30 17:21
Because like in the original issue is told, something else (probably sponge, by experience and just as an example) is trying to load chunks in an multithreaded manner, which forge does normally not. And only forge is supported by the devs.
So if you can try to either find an option in your configs for your Server or optimizing mods to disable this multithread chunkloading. Or you can try to reproduce this issue with your server running plain old forge and provide a new and complete crashreport

**Comment by BrunnerLivio** [comment] 2019-08-30 17:31
I was not running with Sponge, it was a plain ol' Direwolf20 Singleplayer world. Though I had JourneyMap activated + loaded chunk and I was in a custom RFTools dimension. I could resolve the issue by breaking my Quantum Ring. Took a couple of tries, since my game crashed in a matter of seconds. Unfortunately, I can not give further details on this issue. Am' not a Java-Minecraft-dev so it was hard to find the actual cause :/

**Comment by Shybella** [comment] 2019-08-30 17:37
Can confirm one was with a Quantum Ring. This needs some sort of debugging.
Plenty of people want to help. Stop the Sponge bullshit.

**Comment by Shybella** [comment] 2019-08-30 17:39
Brunner, did you have Draconic Evolution extracting/import power into the controller with Draconic Energy Crystals?

**Comment by mindforger** [comment] 2019-08-30 17:47
Stop bitching about others kind meant and experienced opinion you are extremly rude

**Comment by BrunnerLivio** [comment] 2019-08-30 17:48
@Shybella no need to be disrespectful towards @mindforger. 

> Brunner, did you have Draconic Evolution extracting/import power into a AE2 controller with Draconic Energy Crystals then that runs into a Quantum Ring?

Not I did not :/ What let you think this is related to this issue?

**Comment by Shybella** [comment] 2019-08-30 17:49
Fixed one players world by removing Energy Crystals off the controller and using a different method of supplying power.

Blaming other mods when they are not installed is disrespectful, I wouldn't do that with AE2.
