### ISSUE TITLE
Game crash when charging Energy Cell

### ISSUE THREAD

**Issue by Raydd** [AppliedEnergistics/Applied-Energistics-2#3157] opened 2017-10-14 07:45 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  LoadingPlugin (Quark-r1.3-111.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 10/14/17 12:40 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:191)
	at appeng.me.NetworkEventBus$EventMethod.access$400(NetworkEventBus.java:166)
	at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:215)
	at appeng.me.NetworkEventBus$MENetworkEventInfo.access$200(NetworkEventBus.java:201)
	at appeng.me.NetworkEventBus.postEvent(NetworkEventBus.java:120)
	at appeng.me.Grid.postEvent(Grid.java:222)
	at appeng.me.cache.EnergyGridCache.publicPowerState(EnergyGridCache.java:277)
	at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:223)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:226)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1033_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:184)
	... 18 more
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:191)
	at appeng.me.NetworkEventBus$EventMethod.access$400(NetworkEventBus.java:166)
	at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:215)
	at appeng.me.NetworkEventBus$MENetworkEventInfo.access$200(NetworkEventBus.java:201)
	at appeng.me.NetworkEventBus.postEvent(NetworkEventBus.java:114)
	at appeng.me.Grid.postEvent(Grid.java:222)
	at appeng.tile.storage.TileChest.recalculateDisplay(TileChest.java:194)
	at appeng.tile.storage.TileChest.powerRender(TileChest.java:536)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:184)
	... 30 more
Caused by: java.lang.NullPointerException
	at appeng.me.cache.GridStorageCache$CellChangeTrackerRecord.<init>(GridStorageCache.java:322)
	at appeng.me.cache.GridStorageCache$CellChangeTracker.postChanges(GridStorageCache.java:338)
	at appeng.me.cache.GridStorageCache.lambda$addCellProvider$2(GridStorageCache.java:184)
	at appeng.me.cache.GridStorageCache$$Lambda$2100/651916518.accept(Unknown Source)
	at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354)
	at appeng.me.cache.GridStorageCache.addCellProvider(GridStorageCache.java:180)
	at appeng.me.cache.GridStorageCache.cellUpdate(GridStorageCache.java:243)
	... 35 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1930232344 bytes (1840 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.0.2509 Optifine OptiFine_1.12.2_HD_U_C6 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID                   | Version                  | Source                                          | Signature                                |
	|:----------- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAA | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.0.2509.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge                | 14.23.0.2509             | forge-1.12.2-14.23.0.2509.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAA | mercurius_updater    | 1.0                      | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCHIJAAAAAA | actuallyadditions    | 1.12.1-r121              | ActuallyAdditions-1.12.1-r121.jar               | None                                     |
	| UCHIJAAAAAA | applecore            | 2.2.2                    | AppleCore-mc1.12.2-2.2.2.jar                    | None                                     |
	| UCHIJAAAAAA | jei                  | 4.8.0.105                | jei_1.12.2-4.8.0.105.jar                        | None                                     |
	| UCHIJAAAAAA | appleskin            | 1.0.8                    | AppleSkin-mc1.12-1.0.8.jar                      | None                                     |
	| UCHIJAAAAAA | appliedenergistics2  | rv5-alpha-8              | appliedenergistics2-rv5-alpha-8.jar             | None                                     |
	| UCHIJAAAAAA | quark                | r1.3-111                 | Quark-r1.3-111.jar                              | None                                     |
	| UCHIJAAAAAA | autoreglib           | 1.3-13                   | AutoRegLib-1.3-13.jar                           | None                                     |
	| UCHIJAAAAAA | baubles              | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCHIJAAAAAA | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAAAA | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJAAAAAA | biomesoplenty        | 7.0.1.2298               | BiomesOPlenty-1.12.2-7.0.1.2298-universal.jar   | None                                     |
	| UCHIJAAAAAA | bookshelf            | 2.2.462                  | Bookshelf-1.12.2-2.2.462.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAA | botania              | r1.10-349                | Botania r1.10-349.jar                           | None                                     |
	| UCHIJAAAAAA | codechickenlib       | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | redstoneflux         | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAAAA | brandonscore         | 2.3.3                    | BrandonsCore-1.12-2.3.3.132-universal.jar       | None                                     |
	| UCHIJAAAAAA | cfm                  | 4.1.5                    | cfm-4.1.5-mc1.12.jar                            | None                                     |
	| UCHIJAAAAAA | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAAAA | chesttransporter     | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| UCHIJAAAAAA | ctm                  | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCHIJAAAAAA | chisel               | MC1.12-0.0.14.18         | Chisel-MC1.12-0.0.14.18.jar                     | None                                     |
	| UCHIJAAAAAA | chiselsandbits       | 14.8                     | chiselsandbits-14.8.jar                         | None                                     |
	| UCHIJAAAAAA | cofhcore             | 4.3.5                    | CoFHCore-1.12-4.3.5.13-universal.jar            | None                                     |
	| UCHIJAAAAAA | cofhworld            | 1.0.1                    | CoFHWorld-1.12-1.0.1.8-universal.jar            | None                                     |
	| UCHIJAAAAAA | cookingforblockheads | 6.3.6                    | CookingForBlockheads_1.12.1-6.3.6.jar           | None                                     |
	| UCHIJAAAAAA | cucumber             | 1.0.2                    | cucumber[1.12]-1.0.2.jar                        | None                                     |
	| UCHIJAAAAAA | darkutils            | 1.7.176                  | DarkUtils-1.12.2-1.7.176.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAA | draconicevolution    | 2.3.3                    | Draconic-Evolution-1.12-2.3.3.261-universal.jar | None                                     |
	| UCHIJAAAAAA | excompressum         | 3.0.7                    | ExCompressum_1.12.1-3.0.7.jar                   | None                                     |
	| UCHIJAAAAAA | mantle               | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJAAAAAA | tconstruct           | 1.12-2.7.3.30            | TConstruct-1.12-2.7.3.30.jar                    | None                                     |
	| UCHIJAAAAAA | extrautils2          | 1.0                      | extrautils2-1.12-1.6.3.jar                      | None                                     |
	| UCHIJAAAAAA | zerocore             | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCHIJAAAAAA | bigreactors          | 1.12-0.4.5.44            | ExtremeReactors-1.12-0.4.5.44.jar               | None                                     |
	| UCHIJAAAAAA | ic2                  | 2.8.16-ex112             | industrialcraft-2-2.8.16-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAAAA | natura               | 1.12-4.3.0.17            | Natura-1.12-4.3.0.17.jar                        | None                                     |
	| UCHIJAAAAAA | forestry             | 5.6.0.200                | forestry_1.12.2-5.6.0.200.jar                   | None                                     |
	| UCHIJAAAAAA | farmingforblockheads | 3.1.5                    | FarmingForBlockheads_1.12-3.1.5.jar             | None                                     |
	| UCHIJAAAAAA | flatcoloredblocks    | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar                | None                                     |
	| UCHIJAAAAAA | ftbl                 | 4.1.6                    | FTBLib-4.1.6.jar                                | None                                     |
	| UCHIJAAAAAA | ftbu                 | 4.1.6                    | FTBUtilities-4.1.6.jar                          | None                                     |
	| UCHIJAAAAAA | gravestone           | 1.10.0                   | gravestone-1.10.0.jar                           | None                                     |
	| UCHIJAAAAAA | theoneprobe          | 1.4.18                   | theoneprobe-1.12-1.4.18.jar                     | None                                     |
	| UCHIJAAAAAA | immersiveengineering | 0.12-74                  | ImmersiveEngineering-0.12-74.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAAAA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAAAA | ironchest            | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCHIJAAAAAA | journeymap           | 1.12.2-5.5.0rc1          | journeymap-1.12.2-5.5.0rc1.jar                  | None                                     |
	| UCHIJAAAAAA | jeresources          | 0.8.5.26                 | JustEnoughResources-1.12.2-0.8.5.26.jar         | None                                     |
	| UCHIJAAAAAA | mekanism             | 9.4.1                    | Mekanism-1.12.1-9.4.1.326.jar                   | None                                     |
	| UCHIJAAAAAA | mysticalagriculture  | 1.6.5                    | mysticalagriculture-1.12-1.6.5.jar              | None                                     |
	| UCHIJAAAAAA | harvestcraft         | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                  | None                                     |
	| UCHIJAAAAAA | projecte             | 1.12-PE1.1.0             | ProjectE-1.12-PE1.1.0.jar                       | None                                     |
	| UCHIJAAAAAA | reborncore           | 3.4.6.131                | RebornCore-1.12.2-3.4.6.131-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAAAA | reccomplex           | 1.4.5                    | RecurrentComplex-1.4.5.1.jar                    | None                                     |
	| UCHIJAAAAAA | thermalfoundation    | 2.3.5                    | ThermalFoundation-1.12-2.3.5.14-universal.jar   | None                                     |
	| UCHIJAAAAAA | thermalexpansion     | 5.3.5                    | ThermalExpansion-1.12-5.3.5.19-universal.jar    | None                                     |
	| UCHIJAAAAAA | redstonearsenal      | 2.3.5                    | RedstoneArsenal-1.12-2.3.5.13-universal.jar     | None                                     |
	| UCHIJAAAAAA | xreliquary           | 1.12.2-1.3.4.719         | Reliquary-1.12.2-1.3.4.719.jar                  | None                                     |
	| UCHIJAAAAAA | rftools              | 6.13                     | rftools-1.12-6.13.jar                           | None                                     |
	| UCHIJAAAAAA | roguelike            | 1.7.2                    | RoguelikeDungeons-1.12.2-1.7.2.jar              | None                                     |
	| UCHIJAAAAAA | roots                | 0.103                    | roots-2-0.103.jar                               | None                                     |
	| UCHIJAAAAAA | storagedrawers       | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCHIJAAAAAA | techreborn           | 2.7.7.283                | TechReborn-1.12.2-2.7.7.283-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAAAA | thermaldynamics      | 2.3.5                    | ThermalDynamics-1.12-2.3.5.12-universal.jar     | None                                     |
	| UCHIJAAAAAA | torohealthmod        | 1.12.2-11                | torohealth-1.12.2-11.jar                        | None                                     |
	| UCHIJAAAAAA | veinminer            | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAAAA | veinminermodsupport  | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAAAA | wearablebackpacks    | 3.0.4                    | WearableBackpacks-1.12-3.0.4.jar                | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark-r1.3-111.jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv5-alpha-8 for Forge 14.23.0.2491
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.4.6.131
		Runtime Debofucsation 1
		RenderEngine: 1
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['CyberNinjaWeeb'/4187, l='New World', x=-255.24, y=64.00, z=217.28]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 384.76
	OpenGlRenderer: GeForce 940M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by yueh** [comment] 2017-10-14 08:20
Duplicate of #3150

**Closed by yueh** 2017-10-14 08:20 UTC
