### ISSUE TITLE
'Automatic' Crafting CPU Selection Improvement

### ISSUE THREAD

**Issue by Lordfirespeed** [AppliedEnergistics/Applied-Energistics-2#5373] opened 2021-08-19 19:26 UTC
**Describe the feature**

'Automatic' crafting CPU selection should select the smallest CPU available that the crafting process will fit in. 

**Reasons why it should be considered**

Currently, say I would like 32 ME Interface and 960 Acceleration cards. I have 1 4k CPU and 1 64k CPU.
If I put in the acceleration cards first, all is fine as the 'automatic' selection will select the largest CPU first and both crafting process will fit.
If I ask for the interface first, however, 'automatic' selection will place the crafting request into the 64k CPU despite the process being <2000 bytes. Then, when I request the acceleration cards (>4000 bytes) the 64k CPU is in use, and so no CPUs are available to perform the process.

**Additional Context**

**Comment by yueh** [comment] 2021-08-19 20:03
Duplicate of #1055

**Closed by yueh** 2021-08-19 20:03 UTC
