### ISSUE TITLE
Server Keeps Crashing... not sure what the problem is.

### ISSUE THREAD

**Issue by carterisonline** [AppliedEnergistics/Applied-Energistics-2#3529] opened 2018-06-03 14:15 UTC
#### Description
Hey there! So, I have a server with my friends that I've been modding, and it keeps crashing as of now. I started it up with some handpicked mods, then got bored and switched to All The Mods 3, but my friend couldn't load Minecraft with all of the mods so I switched to All The Mods 3 Lite. The server worked when I got on it, but my friend still couldn't load Minecraft with all of the mods. I finally deleted about 15 big mods from the modlist to speed things up, and we could both load Minecraft, but the served kept crashing about ten seconds after we joined it. I thought this was an AE2 problem because I see people with the same problem as I do mostly on this forum, but I still can't figure out what to do to make it work.

#### Environment
System Details:
CPU: Intel(R) Core(TM) i7-2600 @ 3.40GHz
RAM: 16.0 GB
System Type: 64-bit Operating System, x64-based processor
GPU: Nvidia Geforce GTX 1080 Founders Edition

"Handpicked Mods": https://drive.google.com/open?id=1gRF7-fCMEqxctwU1MTuXjGtyLenz7HVE
All The Mods 3 (Server Files): https://minecraft.curseforge.com/projects/all-the-mods-3
All The Mods 3 Lite (Server Files): https://minecraft.curseforge.com/projects/atm-3-lite
Modified All The Mods 3 Lite: http://www.mediafire.com/file/yn9oa115x9earrm/Desktop.zip

Crashlog: https://pastebin.com/3mNwuFNQ

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-10
- Forge Version: 14.23.4.2705

**Comment by yueh** [comment] 2018-06-03 17:11
Duplicate of #3318

**Closed by yueh** 2018-06-03 17:11 UTC

**Comment by carterisonline** [comment] 2018-06-03 20:26
Thanks for that, @yueh, the only possible answer is to restore from a previous backup. (If you're a viewer on this forum and have the same issue)
