### ISSUE TITLE
Dimension ID 2 Confliction

### ISSUE THREAD

**Issue by EisbarGFX** [AppliedEnergistics/Applied-Energistics-2#3456] opened 2018-04-08 02:59 UTC
#### Description
While starting up Minecraft 1.12.2 with the following: https://imgur.com/a/7dTQl mods installed, minecraft crashed during mod loading. EDIT: The mod DungeonDQ was causing the error. I have since uninstalled it, but would still love some advice on how to play with both.

#### Environment
Crash report: https://pastebin.com/jh7LENj1
Apparent cause of crash: Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.1.2554

**Comment by Ommina** [comment] 2018-04-08 04:14
Change the config for one or the other (AE's is under spacialio -> I:storageDimensionID=2; I would be surprised if DungeonDQ didn't have a config for their dimension id as well) to something other than 2.

**Comment by yueh** [comment] 2018-04-08 08:36
Duplicate of #3444

**Closed by yueh** 2018-04-08 08:36 UTC
