### ISSUE TITLE
[1.12.2] Tinkers Cast Unable to be removed from AE System

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#3166] opened 2017-10-19 07:42 UTC
After an undertermined time period im unable to remove various casts in this instance the Tough Tool Rod Cast from my AE system. Once this occurs, if i swap all my drives positions, im then able to remove the casts from the system.

AE  rv5 Beta1
Forge *.2512

**Comment by yueh** [comment] 2017-10-19 09:16
Duplicate of #951, #1581

**Closed by yueh** 2017-10-19 09:16 UTC
