### ISSUE TITLE
Double-clicking storage cells into ME Drive...

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3221] opened 2017-11-13 14:23 UTC
#### Description
Double-clicking storage cells into ME Drives send all the same storage cells into the ME Drive, BUT, also extract all the same storage cells from the ME Drive into your inventory.
https://youtu.be/ODmqEdz5yEY

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-2
- Forge Version: 2540
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1467155/list.txt)

**Comment by fscan** [comment] 2017-11-13 14:35
Duplicate of #3220

**Closed by fscan** 2017-11-13 14:35 UTC
