### ISSUE TITLE
Game crashed when placing an Energy Cell next to Flux Networks Flux Point

### ISSUE THREAD

**Issue by TheGreatAutismo** [AppliedEnergistics/Applied-Energistics-2#4362] opened 2020-04-28 11:06 UTC
**Describe the bug**

The game crashed when I placed an Energy Cell next to a Flux Point from the Flux Networks mod

**To Reproduce**

Place an Energy Cell next to a Flux Point from Flux Networks

**Expected behavior**

The Energy Cell would be charged by the Flux Point

**Additional context**

Crashlog: https://paste.dimdev.org/mibahedexu.mccrash

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: Unknown, SkyFactory 4 version 4.1.0
- Forge Version: Also unknown. Twitch should say it but it's being dumb right now. It should hopefully be easy information to get.

**Comment by yueh** [comment] 2020-04-28 11:09
Duplicate of #4037

**Closed by yueh** 2020-04-28 11:09 UTC
