### ISSUE TITLE
Sorting Options

### ISSUE THREAD

**Issue by beiarii** [AppliedEnergistics/Applied-Energistics-2#7022] opened 2023-04-05 06:13 UTC
### Describe the feature

Refined Storage comes with the abiltiy to sort by Last Modified, and as i tried to make the transition to AE2 this missing feature put me off from completing said transition.

### Reasons why it should be considered

it's just a general QoL change that would be nice to have as somebody transitioning to a more stable central storage system mod.

**Comment by Technici4n** [comment] 2023-04-05 08:19
Duplicate of #4995

**Closed by Technici4n** 2023-04-05 08:19 UTC
