### ISSUE TITLE
Sugestion [Fluid Storage]

### ISSUE THREAD

**Issue by CTH999** [AppliedEnergistics/Applied-Energistics-2#3348] opened 2018-01-23 16:33 UTC
I like how Extra Cells and Refined Storage have fluid cells, but sometimes I don't want an addon, and I think it would be nice if AE2 Did fluid cells in an AE2-y way. Just a little suggestion idea.

**Comment by yueh** [comment] 2018-01-23 17:53
Duplicate of #286

**Closed by yueh** 2018-01-23 17:53 UTC

**Comment by CTH999** [comment] 2018-01-23 21:05
Sorry, My Bad.
