### ISSUE TITLE
Crafting CPU: Automatic to lowest byte capacity CPU (suggestion)

### ISSUE THREAD

**Issue by danikk14g** [AppliedEnergistics/Applied-Energistics-2#3198] opened 2017-11-05 21:59 UTC
Hello, i have been using AE2 for 3 years or so, but recently i asked myself why the automatic crafting cpu assignation always takes the cpu with the highest capacity in terms of bytes and not the lowest one.
This is a bit tricky if you are planning to craft big things while other minor crafts are in process, because it always takes the big crafting cpu and you have to wait it to finish to leave the big cpu free.

If automatic is set to the one with the lowest priority this would never happen and it would use more efficiently the different CPU's so the higher ones are always available when it is really needed.

Thanks.

**Comment by yueh** [comment] 2017-11-05 22:07
Duplicate of #1055

**Closed by yueh** 2017-11-05 22:07 UTC
