### ISSUE TITLE
Molecular assembler having its own pattern storage.

### ISSUE THREAD

**Issue by LuxusDarkangel** [AppliedEnergistics/Applied-Energistics-2#884] opened 2015-02-11 22:11 UTC
I wish to have a molecular assembler like the AE1 one. I don't care about separated crafting cpu, but i think molecular assembler has to have its own pattern storage, so you don't have to fill your house with A LOT of them and its own ME Interface.
This method is very annoying for unexpert users and people that automates everything, and it result on things like this one: http://oi60.tinypic.com/rhlmwp.jpg

**Comment by yueh** [comment] 2015-02-11 22:44
Duplicate of #393

**Closed by yueh** 2015-02-11 22:44 UTC
