### ISSUE TITLE
1.11.2, trying to build, or backport from 1.12

### ISSUE THREAD

**Issue by Fungie2134** [AppliedEnergistics/Applied-Energistics-2#3020] opened 2017-08-09 10:30 UTC
This what I get when running "./gradlew build" or"./gradlew eclipse" in the cloned 1.11 repository. Is this branch active ? Working ? Or abandoned... 
So maybe another question : Is 1.11.2 support planned? 

https://pastebin.com/g49eRZnj

**Comment by Fungie2134** [comment] 2017-08-09 10:35
Maybe solved by replacing "compileOnly" with "mods" in dependencies.gradle.

**Comment by Fungie2134** [comment] 2017-08-09 11:02
I found a working 1.11.2 fork. This one : https://github.com/thiakil/Applied-Energistics-2/releases
May I close the issue now?

**Comment by GuntherDW** [comment] 2017-08-09 12:05
duplicate of #2989 

For what it's worth you start from my personal 1.11.2 branch, that was before I moved on to 1.12 but I wouldn't recommend that one on production worlds just yet because there are a bunch of lingering issues that we resolved in the 1.12 version.

**Closed by GuntherDW** 2017-08-09 12:05 UTC
