### ISSUE TITLE
Server Crash related to fuzzy crafting (inconsistent range)

### ISSUE THREAD

**Issue by PhanaticD** [AppliedEnergistics/Applied-Energistics-2#3768] opened 2018-10-09 17:36 UTC
**Describe the bug**

Server crashes on chunk load of affected setup
**To Reproduce**

not sure exactly
**Expected behavior**

no crash
**Additional context**

here is the crash report: https://pastebin.com/raw/7s9EgZpu

here is the affected region file: https://www.dropbox.com/s/sny87w07k2c7wly/r.-1.-5%20-%20Copy.zip?dl=0

I was able to fix it by deleting both the crafting cpus and output buses with fuzzy cards in them from the players base in nbtexplorer

**Environment**

All the Mods 3 - Remix modpack version 0.1.2
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-1
- Forge Version: 1.12.2-14.23.4.2760

**Comment by yueh** [comment] 2018-10-11 21:18
I cannot do anything with the region file itself. Also to actually debug these particular crashes, it needs to be reduced to basically AE2 plus one or two mods. Otherwise it is simply impossible.

As this is the second occurrence lately and no others before, I would assume some mod did start doing funny things lately with meta or damage values. (This code is pretty much unchanged since 1.7.10).

**Comment by PhanaticD** [comment] 2018-10-11 21:38
the player whos base it was said they were crafting a garden scythe from cyclic, using a export bus with a crafting card (which was going into a mechanical user from extra utilities)

**Comment by RustyXXL** [comment] 2018-10-11 22:46
https://pastebin.com/raw/SfehSmgZ

I got pretty much the same issue in my slightly modified ssp enigmatica 2 expert skyblock instance.
Funny thing is the instance pretty much ran for about 12 hours with the same autocrafting exports without crashing.
I just started autocrafting a plant gatherer from industrial foregoing a few moments prior to the crash.
The recipe for that is heavily modified.
I then tested further in a test world with the same mod pack, and could reproduce the issue pretty quickly.
I added the minimum required crafting recipes and as soon as I tried to craft the plant gatherer the game crashed again.
Most of the components were used in other recipes, and crafted without issues there.
The only 2 unique ones I added, apart from the plant gatherer were the iron axe and the iron hoe. Both of them are modified by a mod, so that they are pretty much useless for anything else than crafting, so I suspect that those are the issue in my case. I'm currently trying to figure out, what mod alters them. Once I figure out more, I will report back.

**Comment by yueh** [comment] 2018-10-12 10:16
Most likely the modified tools as they are damagable and therefore subject to fuzzy filtering. And it sounds like they break some stuff to enforce a very special behaviour.

**Comment by mindforger** [comment] 2018-10-12 13:08
i looked into the scripts and configs of the pack, it doesn't look like they changed the recipe for it but i can't see in the original recipe what item except for the machine case (which shouldn't have damage value) could cause this, can you tell the (most exact) recipe you programmed to nail down the item in question?

**Comment by RustyXXL** [comment] 2018-10-12 14:00
I will post screenshots of all related recipes in the pattern terminal in a bit.
I tried to craft the plant gatherer manually and in doing so I tried to put the iron hoe in the system out of habit. It didn't go in, and when closing and reopening the crafting terminal it didn't show any more items.
Restarting the game did seem to fix it, but now I can't craft anymore with the system. I noticed it while trying to craft crafting cards, which I have done multiple times before.
I can choose it, but when trying to click next on the select amount screen, nothing happens.
Something is horribly borked now in my system :/

**Comment by NillerMedDild** [comment] 2018-10-15 15:51
The issue still occurs if all scripts modifying the ingredients are removed.

**Comment by RustyXXL** [comment] 2018-10-15 20:06
Yeah, sorry, I forgot to update this.
We narrowed it down to the iron hoe. I tried removing all craft tweaker scripts and cyclic. Both didn't help.
I also removed the Thaumcraft aspects, the 5x5 grass breaking feature from Quark, and  a line from the rustic config, that mentioned the iron hoe, all without success.
There is another report now for the ender io farming station on @NillerMedDild Enigmatica 2 Expert 2 Skyblocks Github, that uses the supremium hoe in its recipes, so it would seem it is related to the hoes in that pack, but I'm out of ideas as to which mod is causing it.

**Comment by NillerMedDild** [comment] 2018-10-17 07:32
I can confirm that the issue is the `toolHoe` oredict that is on the hoes used. Some mod generates it and applies it to all hoes, after CraftTweaker runs.

**Comment by mindforger** [comment] 2018-10-18 11:45
you can accelerate the sear by doing a binary search

backup your mods folder and now remove around half the mods without breaking the pack to badly (move not delete)

if the issue persists, do it again, if the issue is gone, switch the current mods with the moved (plus the ones bein neccesary at all times)

repeat this until you are left over with few enough mods to nail the culprit down

**Comment by lombax5832** [comment] 2018-10-22 06:36
> https://pastebin.com/raw/SfehSmgZ
> 
> I got pretty much the same issue in my slightly modified ssp enigmatica 2 expert skyblock instance.
> Funny thing is the instance pretty much ran for about 12 hours with the same autocrafting exports without crashing.
> I just started autocrafting a plant gatherer from industrial foregoing a few moments prior to the crash.
> The recipe for that is heavily modified.
> I then tested further in a test world with the same mod pack, and could reproduce the issue pretty quickly.
> I added the minimum required crafting recipes and as soon as I tried to craft the plant gatherer the game crashed again.
> Most of the components were used in other recipes, and crafted without issues there.
> The only 2 unique ones I added, apart from the plant gatherer were the iron axe and the iron hoe. Both of them are modified by a mod, so that they are pretty much useless for anything else than crafting, so I suspect that those are the issue in my case. I'm currently trying to figure out, what mod alters them. Once I figure out more, I will report back.
> 
> Edit:
> It is definitely the Industrial Foregoing Plant gatherer that was the issue for me. I'm either not smart enough or to tired, or possibly both to figure out if the problem is related to the modified axe and hoe or the plant gatherer itself, but removing the crafting task via nbtexplorer fixed my world so far.

How did you go about the fix via nbtexplorer? I'm having trouble finding the crafting task.

**Comment by lombax5832** [comment] 2018-10-22 06:58
@RustyXXL How did you go about the nbtexplorer fix? I'm having the exact same issue myself and would like to know. Did you just delete the entire crafting cpu entry from the tileentity tab in the region file?

**Comment by yueh** [comment] 2018-10-22 07:46
Closing as it is pretty much confirmed that some other mods breaks tools in a way that these are no longer valid itemstacks.

**Comment by yueh** [comment] 2018-10-22 07:47
Closing as it is pretty much confirmed that some other mods breaks tools in a way that these are no longer valid itemstacks.

**Comment by RustyXXL** [comment] 2018-10-22 13:13
@lombax5832 Update the pack or look on the Enigmatica 2 Expert Skyblock github for the issue where I posted a workaround, so that you shouldn't need to nbtedit your save.
I deleted the crafting cpu that was crafting the farmer and the controller just to be save. That allowed me to reload the save. Just to be completly save I completly tore down my ae system, saved, restarted and rebuild it. (I planned to do that anyway, because it was a mess) but it was a major pita.

**Comment by RustyXXL** [comment] 2018-10-22 13:32
@lombax5832 Update the pack or look on the Enigmatica 2 Expert Skyblock github for the issue where I posted a workaround, so that you shouldn't need to nbtedit your save.
I deleted the crafting cpu that was crafting the farmer and the controller just to be save. That allowed me to reload the save. Just to be completly save I completly tore down my ae system, saved, restarted and rebuild it. (I planned to do that anyway, because it was a mess) but it was a major pita.

**Comment by PhanaticD** [comment] 2018-10-22 21:09
@yueh maybe we could have it print a warning and fail nicely then instead of completely crashing the server?

**Comment by mindforger** [comment] 2018-10-23 01:08
How should this fail nicely in your opinion? Abort the job and spamming into the log with every crafting attempt? Spamming the chat? I ask seriously, because this would mean a spam of issues because autocrafting would abort for unknown reason...

**Comment by PhanaticD** [comment] 2018-10-23 01:12
tbh anything is better, spam time limits might be too much to ask, but as long as the coordinates and the error are in console

even just having the coordinates prior to a crash would have helped a lot

**Comment by GStefanowich** [comment] 2018-10-23 15:48
Kind of laughed to myself when @RustyXXL said they ruled it down to the iron hoe. Was just trying to use my AE crafting interface to craft a recipe that involved an iron hoe. Tossed one of the hoes into the system, and it locked up. Couldn't take items in or out. Decided to try throwing it into the system by tossing it into an AE Interface. Getting a similar crash now.

Playing on the revelation pack, my only fuzzy card is in a storage bus attached to a trash can. Fuzzy card in general doesn't like the item for some reason. Going to try to do some of my own investigating.

**Comment by RustyXXL** [comment] 2018-10-23 19:39
Updated the list of potential mods, to reflect the Revelation info and some of my own testing. Still not found the mod responsible, but couldn't do to much testing for rl reasons.

**Comment by dkowis** [comment] 2018-11-10 22:42
Just for others, we're experiencing the same crash when trying to autocraft a Plant Gatherer from Industrial Foregoing.

Our list of mods that intersects with these mods is as follows:
```
Akashic Tome
Apple Skin
Astral Sorcery
elulib
Just Enough Resources
Open Computers
Quark
Quick Leaf Decay
Rustic
Thaumcraft
Thaumic Inventory Scanning
Thaumic JEI
```

**Comment by martmists** [comment] 2018-12-06 15:32
So how can we fix this issue permanently without having to remove the affected block every time?

**Comment by Derkades** [comment] 2018-12-18 20:04
I got this when crafting the Plant Gatherer from Industrial Foregoing, using a recipe I had just added to a molecular assembler + interface setup. I was able to craft a Plant Sower (also from IF) just fine. On FTB Revelation.

**Comment by Nividica** [comment] 2018-12-20 01:21
I also have encountered this issue.
Added the recipe for the plant gatherer, clicked start, instantly brought down the server, and have not been able to keep it running. The server will come up for the breifest moment and then it hits the `java.lang.IllegalArgumentException: inconsistent range` again.
I have a ton of recipes added to my system, several use tools and weapons, however this was the first time that I needed either the iron axe or iron hoe. I do not have any cable parts which are using the fuzzy card.

Pack: FTB Revelation
Action: Start crafting job for Industrial Foregoing: Plant Gatherer
Relevant recipes: All three recipes, Iron Axe, Iron Hoe, and Plant Gatherer have 'Allow Substitutions' enabled.

If I make any discoveries as to the root reason of the issue, I will report back.

**Comment by Nividica** [comment] 2018-12-20 03:19
I have been able to reproduce the issue with the following setup:
Mods: AE2@rv5.11, EnderCore@0.5.39, EnderIO@5.0.33, Mantle@1.3.2.24, and TConstruct@2.10.1.87
Setup:
* Creative energy cell
* Smart Cable
* Export bus + Fuzzy(Match All)
* Oak Chest
* Any vanilla hoe

Steps:
Place energy cell, attach cable to cell, attach export bus to cable, place chest next to export bus
Put fuzzy card in export bus
Set hoe as export bus filter
Wait 1-2 seconds
*Crash*

Of note: AE2 added hoes do not cause crash, no other tools cause crash.
Removing either TConstruct or EnderIO prevents the crash.
Mantel and EnderCore were never removed, it seems solely an interaction between TCon and EIO.
While testing patterns in the Molecular Assembler, I encountered the following output in the log
```
[21:19:47] [Server thread/WARN]: Using CraftingManager fallback: Recipe <minecraft:iron_hoe> for output <1xitem.hoeIron@0> rejected inputs [32xitem.stick@0, 1xitem.ingotIron@0, 1xitem.stick@0, 1xitem.stick@0]. NOT FOUND, please report.
[21:19:47] [Server thread/WARN]: Using CraftingManager fallback: Recipe <minecraft:iron_hoe> for output <1xitem.hoeIron@0> rejected inputs [1xitem.ingotIron@0, 32xitem.stick@0, 1xitem.stick@0, 1xitem.stick@0]. NOT FOUND, please report.
[21:19:48] [Server thread/WARN]: Using CraftingManager fallback: Recipe <minecraft:iron_hoe> for output <1xitem.hoeIron@0> rejected inputs [1xitem.ingotIron@0, 1xitem.ingotIron@0, 32xitem.ingotIron@0, 1xitem.stick@0]. NOT FOUND, please report.
[21:19:48] [Server thread/WARN]: Using CraftingManager fallback: Recipe <minecraft:iron_hoe> for output <1xitem.hoeIron@0> rejected inputs [1xitem.ingotIron@0, 1xitem.ingotIron@0, 1xitem.stick@0, 32xitem.ingotIron@0]. NOT FOUND, please report.
```

**Comment by Nividica** [comment] 2018-12-20 04:02
I have found a work-around for the time being, if you have CraftTweaker installed. Bear in mind that this is taking a hammer to the problem, and it happens to work. I suspect with more time invested, a more pin-point solution could be found by adjusting the recipes for hoes.
What I *think* is happening:
AE2 starts a fuzzy search for hoes, it encounters the recipes added by TConstruct, because the hoes were added to the ore dictionary by EnderIO. *Something* about those recipes and/or iterating through them causes the inconsistent range exception.

I was able to get everything smoothly working again by removing all hoes from the ore dictionary.
Unfortunately EnderIO does not have an option to disable oredict+hoe integration, and is hard-coded [here](https://github.com/SleepyTrousers/EnderIO/blob/c11021ef733420adc377ea6792851b2fbbf2c511/enderio-base/src/main/java/crazypants/enderio/base/material/recipes/MaterialOredicts.java#L108)
I did this by adding a CraftTweaker script called `03_oredict_hoes.zs`(00-02 already exist in FTB) with the following:
```
#Name: oredict_hoes.zs
#Author: Nividica

print("Initializing 'oredict_hoes.zs'...");

for item in <ore:toolHoe>.items {
    <ore:toolHoe>.remove(item);
}

print("Initialized 'oredict_hoes.zs'");
```
You could easily just add the for loop to an existing script and it should work the same.

I have only tested this on single player, and will report back once we get it installed on our server.

**Comment by NillerMedDild** [comment] 2018-12-20 06:55
Cool, I'll try again then, thanks.

**Comment by tterrag1098** [comment] 2018-12-20 21:52
How exactly is this an EIO issue?

**Comment by Rseding91** [comment] 2018-12-21 00:48
I'm getting this same issue with AE when trying to import a Mattock from Tinkers Construct while using fuzzy storage busses to filter incoming items on Enigmatica 2 Expert 1.44. The tooltip in-game is saying it has an ore dictionary entry of toolHoe but it shouldn't. Some mod is adding it to the ore dictionary.

Why that causes a crash where I don't know but it seems like it shouldn't.

I can provide the entire save file (which crashes every time it's loaded) if it helps diagnose the issue. The above "remove all items from oredict::toolHoe" script doesn't work to remove the mattock from the ore dictionary for me.

**Comment by mindforger** [comment] 2018-12-21 06:32
@tterag1098

It kind of sounds something goes bogus with the oredict on tools between tcon and EIO that primarely causes AE to misbehave, and i might throw in, i may seen something similar with immersive enginerring and the assembler. Unfortunately i only got my phone with me while visiting my family, so i can not look for the links to the issues that easily.

**Comment by yueh** [comment] 2018-12-22 10:11
@tterrag1098 Nothing (most likely), people just tend to cling to bogus, yet easy solutions, which don't work at all.

@Rseding91 There is a small chance that a save might help. But the actual reason is most likely that some mod fucks up at runtime. Most likely some invalid metadata/damage value, screwing with caps, other itemstacks, or similar. Nothing oredict related at all.
So it needs to be debugged as whole modpack, which is pretty much impossible to get it running in dev.
Currently I can only thing of one option to try. But that is already pretty borderline as each try probably takes 20-30 minutes and I would have to anticipate the outcome in advance, otherwise it would be completely wasted effort.

**Comment by yueh** [comment] 2018-12-22 20:43
I cannot say if it applies to the other reports, too. But here the issue is that the mattock is broken from tinkers construct. So everything shares the same id and in case of broken, it has no damage value/metadata/etc, so it drops down until it hits our nbt compare. Which is a bit dodgy as it is highly optimized for speed as well as the vanilla/forge methods not even being sufficient for our needs.

No idea how we could currently prevent it without having a major break in behaviour. E.g. it would consider any tinkers construct tool as similar item. Say filtering for wooden swords will include every tinkers sword regardless of used materials. So have fun with it trashing your high end gear, because there is something set up to trash all wooden swords.

**Comment by yueh** [comment] 2018-12-23 11:19
A crash can usually be fixed, destroyed data never. So it simply is not an option. Also it is not just tinkers construct. There are a couple of other broken mods like mekanism, which use a single item with the same metadata for at least a part of there items and just store the actual itemtype as NBT somehow. 

I have a couple of ideas to evaluate. Yet they are not that easy to really test in terms of performance indev aus long as there is no way to mock these itemstack somehow. And there are a couple of strange assumptions by vanilla/forge, which might actually be a bit too restrictive with our current approach. E.g. any item outside the range of `[-2^15,2^16]` (Yes ^16 not 2^15-1 as expected with a short) are considered empty.

1.13/1.14 will certainly make it easier, but it pretty much is guaranteed to consider everything with the same id as the same item. That is simply the way minecraft handles it and as long as mods do not flatten their ids, it will be that way. Also Oredict/tags probably have to go. They will get way too ambiguous, like iron could have tags like `ingotIron`, `anyIngot`, `mobDrop`, or `iWantToTagEveryItemForRandomReasons`.
Even we might have a `anyIngot` tag for crafting cable anchors. So a fuzzy export bus set to export iron, will also export gold or any other existing (metal?) ingot.

**Comment by yueh** [comment] 2018-12-23 12:37
There is a PR which should fix it while maintaining the current behaviour.  The CI currently builds it as rv5, in case some other mods depend on rv6, you probably have to build your own jar in case you want to test it before a new release is done.

With 1.13 it is pretty much guaranteed to make it less complicated as I plan the change the internal data structures. But that means it will consider everything with the same item id as the same item in fuzzy mode. At least as long as forge provides a simple way to compare NBT based types without having a special case for every mod out there (or any successor should the not manage to release it for 1.13+)

**Comment by Shybella** [comment] 2018-12-23 17:33
Is there any way to stop this other than updating?

**Closed** 2018-12-23 21:42 UTC
Labels: type-bug

**Comment by Flextt** [comment] 2019-01-08 13:19
Nividicas [workaround](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3768#issuecomment-448857949) worked for me in ATM3 Remix 1.0.1. I too had attempted to craft a Plant Gatherer and inserted patterns for an Iron Hoe and Plant Gatherer into my MAs with an immediate crash to desktop upon issueing the request.
