### ISSUE TITLE
Game crash when right clicking with a Wooden Crank

### ISSUE THREAD

**Issue by lorenzonotaro** [AppliedEnergistics/Applied-Energistics-2#4163] opened 2019-09-26 10:23 UTC
#### Description
My game crashed after I accidentally right-clicked with a Wooden Crank on a block that wasn't the Quartz Grindstone or the Charger (a Marble block from Astral Sorcery).
After re-opening the game, the Wooden Crank was successfully placed on the Marble block, but the item wasn't removed from my inventory.

[Crash report (pastebin)](https://pastebin.com/3ef4azzn).

#### Environment
- Gamepack: FTB Direwolf 1.12 v2.5.0
- Minecraft Version: 1.12.2
- AE2 Version: AE2 rev6-stable
- Forge Version: 14.23.5.2821

**Comment by yueh** [comment] 2019-09-28 21:45
Duplicate of #3981

**Closed by yueh** 2019-09-28 21:45 UTC
