### ISSUE TITLE
Crash with `Roughly Enough Items` when playing on a `quilt` server

### ISSUE THREAD

**Issue by BeastLe9enD** [AppliedEnergistics/Applied-Energistics-2#6485] opened 2022-08-07 21:02 UTC
### Describe the bug

This error came up on my quilt server firstly by just running around the server and also by using `Roughly Enough Items` and scrolling through item pages.
I think there is a duplicated item registration with the same id which leads to this crash.
Maybe it's an user issue but hopefully it isn't because I don't know what I should've done wrong.

### How to reproduce the bug

I think by setting up a quilt server, positioning `Roughly Enough Items` and `Applied Energistics 2` in the `mods` folder and running around or scrolling through the item list, thats at least where it crashed for me.

### Expected behavior

No crash

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/BeastLe9enD/2a2b8f56fb51362baa974d6c3ae392d0

**Comment by Mari023** [comment] 2022-08-07 21:32
Possibly a duplicate of #6092

**Comment by Technici4n** [comment] 2022-08-11 13:43
It's an issue with not enough crashes causing some things to initialize a second time after crashing. We might have to add a breaks clause with that mod, it's a bad concept anyway.

**Closed by Technici4n** 2022-08-11 13:43 UTC
Labels: bug
