### ISSUE TITLE
Placing Fluix Glass ME Cables crashes the server.

### ISSUE THREAD

**Issue by GreezyJR** [AppliedEnergistics/Applied-Energistics-2#4487] opened 2020-07-20 15:49 UTC
**Describe the issue**
Any time the cable is placed the server immediately crashes.

https://pastebin.com/8n0mb2pZ

**Comment by mindforger** [comment] 2020-07-20 16:28
>.... [10:44:42] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/container/./crash-reports/crash-2020-07-20_10.44.42-server.txt

**Additional context**
><! Screenshots, crashlogs, etc. -->
><! **A complete crashlog is required when reporting a crash. No excerpts.** -->
><! **Please use pastebin or gist for posting the complete crashlog.** -->

**Comment by GreezyJR** [comment] 2020-07-20 16:31
Yea those were not shown in the one that I got shown when creating the issue, will update it now.

**Comment by shartte** [comment] 2020-07-20 17:35
Duplicate of #4467, already fixed. Fix will be available in the next alpha version.

**Comment by GreezyJR** [comment] 2020-07-20 17:36
Any idea when that will be released? Also thanks for the reply!

**Closed** 2020-07-20 20:57 UTC

**Comment by shartte** [comment] 2020-07-20 21:33
It's out
