### ISSUE TITLE
Items like Mystical Agricultures Infusion Crystal keeps trying to build numerous times

### ISSUE THREAD

**Issue by djoveryde** [AppliedEnergistics/Applied-Energistics-2#6083] opened 2022-02-26 01:33 UTC
### Describe the feature

I have set up the recipes for each of the essences (inferium, prudentium etc) which require an infusion crystal, however when I go to build numerous items say 10 it wants to build 10 infusion crystals as well.
The infusion crystal is a multi-use item so is there a way of preventing it from creating numerous copies of these if the item hasn't been used up?

### Reasons why it should be considered

A lot of mods have multi-use items, so if it can be implemented to check if the item has been used up or not would be great for those items that cost a lot to make each time.

**Comment by minenine** [comment] 2022-02-28 16:31
AE use to do this, as i know it used items that consume durability in crafting instead of the whole item well enough before, at least if you set it to allow item substitutes. but as of the latest 1.18 version it does not appear to do this anymore. key example would be the cable anchors with the knife 
![image](https://user-images.githubusercontent.com/1365542/156020743-4334c5e6-475d-4b28-adb5-2d1b132fe083.png)

**Comment by minenine** [comment] 2022-02-28 16:55
oh, this is a duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6050

**Closed** 2022-04-03 20:45 UTC
Labels: bug
