### ISSUE TITLE
AE2 Fabric causes boot loop with latest Fabric API

### ISSUE THREAD

**Issue by sschr15** [AppliedEnergistics/Applied-Energistics-2#4690] opened 2020-09-04 14:31 UTC
(reported on behalf of march#9696 in the Fabric Discord)

**Describe the bug**

The `QuadRotator` [calls a method](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fabric/master/src/main/java/appeng/client/render/cablebus/QuadRotator.java#L98) in `transform` which [does not exist](https://github.com/FabricMC/fabric/compare/0.19.0+build.398-1.16...1.16#diff-c3fd00dad9a5d67dbe756212066d09f1L84) in Fabric API 0.20.0 and later.

**To Reproduce**

1. Use the latest AE2 and FAPI builds for Fabric 1.16
2. Attempt to start the game

**Expected behavior**

Game starts normally.

**Additional context**

[Video of boot loop](https://cdn.discordapp.com/attachments/511324119728521285/751424244025655446/8Amh162CwV.mp4)

Gif if wanted:

![Example gif](https://cdn.discordapp.com/attachments/511324119728521285/751447459758211122/aah.gif)

[Log](https://hatebin.com/rbbawunjim)

A [related issue](https://github.com/FabricMC/fabric/issues/987) shows that the reason for the code being added is resolved, I think.

**Environment**

- Environment: 
- MultiMC 0.6.11
- OpenJDK 1.8u252
- Windows x64 (unsure of version)
- Minecraft 1.16.2

**Comment by shartte** [comment] 2020-09-05 10:55
Known incompatibility with fabric-api 0.20 at this point.
This is caused by the fix for #4651 being merged into fabric-api, which now means we have to remove our workaround.
You'll have to downgrade to 0.19 and wait for the next AE2 alpha which will remove the workaround (this should also enable compat with canvas).

**Closed by shartte** 2020-09-05 10:55 UTC
