### ISSUE TITLE
ME Controller block issues w/ Storage Buses and infinite channels

### ISSUE THREAD

**Issue by zarillion** [AppliedEnergistics/Applied-Energistics-2#6432] opened 2022-07-10 04:03 UTC
### Describe the bug

Took a bit to track this one down so bear with me. We are playing on FTB Plexiglass Mountain 1.18.2, which has infinite channels turned on by default. The [channels documentation](https://appliedenergistics.github.io/features/me-network/channels) states controllers still reduce power consumption with infinite channels, so I added some controllers to our network.

Once our network grew to a certain size, with multiple quantum bridges and numerous storage mediums added, we starting having troubles with things disappearing from our ME network. After every server restart, a number of our storage drawers would stop appearing. Breaking the storage bus or storage drawer controller would cause them to reappear. The network had plenty of dense energy cells attached for a power buffer, so we weren't sure what was causing it.

Eventually we got tired of tracking down each missing drawer on server restarts and put every ME power source across all our quantum bridges behind ME toggle buses. We then added a master lever that would cut every part of our ME network off from power across all dimensions, allowing us to cycle it to see if that would fix it. What ended up happening is we inadvertently created a 100% reproducible way of breaking our ME network without restarting the server. Every time the network was fully shut off and then powered back on, the same storage drawers would be gone from the network. We experimented with multiple things and eventually found that removing the ME controller blocks entirely and making the entire system on giant ad-hoc network fixed the problem for us.

Its unclear what the exact cause of the issue is, we only know that removing the controllers fixes the issue. I can provide the world files (4.9G zipped) if looking at our server setup would help. Let me know if there is any additional information I can provide.

### How to reproduce the bug

Exact reproduction scenario unclear at this time, other than run with infinite channels on and build a large network with multiple quantum bridges and lots of connected storage drawers.

### Expected behavior

An infinite channel ME network with controllers attached for reduced power consumption should not break storage buses on power-on.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/zarillion/a70a2124a8bb0da3899beb335a8122c1

**Comment by Technici4n** [comment] 2022-07-11 07:55
I thought that this was fixed as of 11.1.2, but apparently not? The world files would definitely help, though 5 Gb is a lot. If possible, you could maybe try to only send the relevant region files? Otherwise my connection should be able to handle the full world download.

**Comment by zarillion** [comment] 2022-07-13 18:10
Forgive my inexperience. Is there a tool I can use to filter the files in the `region/` directory by coordinates? Our ME network spans 3-4 different spread out places in the world.

**Comment by rootwalla** [comment] 2022-08-11 09:07
For me all my storage busses and drives would dissapear if I connected a speciffic ME interface to the network, at first. After some testing to figure out what was happening, only placing it in the world (not connected to network) reliably kills the network so that only craftables are visible. To reset, I have to remove the interface and destroy-rebuild the controllers.

**Comment by Technici4n** [comment] 2022-08-11 13:40
I was able to reproduce and identify the issue a few weeks ago, but I am currently not able to wrote a fix. It will come eventually.

**Comment by rootwalla** [comment] 2022-08-11 18:17
Any suggestion how to avoid this bug and/or fix our current games?

**Comment by zarillion** [comment] 2022-08-11 19:04
If you are using infinite channels, our work-around was to remove all controllers from the network and make it one big ad-hoc network. Your power consumption will rise, but by the time our network got this large we had a couple Mek reactors running so it was barely noticeable.

**Comment by klassekatze** [comment] 2022-08-12 03:35
I'm running into a similar issue with a 480-channel network on AQM2. Since channels aren't disabled, going ad-hoc isn't an option in my case. Any information that could be used to mitigate or work around this in the meantime would be great.

**Closed** 2022-08-23 10:29 UTC
Labels: bug
