### ISSUE TITLE
Add a toggle option to terminals for "sort frequency", to be able to freeze item positions

### ISSUE THREAD

**Issue by Jack-McKalling** [AppliedEnergistics/Applied-Energistics-2#5425] opened 2021-09-11 21:11 UTC
**Describe the feature**

A new button could be added to the terminals, named "Sort frequency". It would have two modes: "Always sort items" or "Sort items once". This setting would be saved per player. The button would be complementary to the sorting mode and sorting direction buttons.

Sorting items once would allow the player to freeze the positions of items in the terminal. This way even when the network runs out of an item, it doesn't cause the entire grid of items to shift but simply keeps its cell empty. Any item types that become newly available to the network, do appear in their appropriate sorting position while the GUI is opened, but will maintain their new positions during this mode. Item stacksizes are never affected, and will keep being updated each unit of time regardless of the setting.

If set to "once", the gui will sort item positions once only when the grid of items is initially presented or when the sorting settings change. If set to "always", the gui will always update item positions as the network contents change on each unit of time (the current behaviour).

**Reasons why it should be considered**

This would make it possible to keep a close eye on items that would otherwise keep rapidly shifting position back and forth. Consequenly it would also allow the player to actually take some of them out when desired, as opposed to misclicking or having to search for the specific item eventhough they are already in view.

It could potentially prevent or ease down real life visual problems for the player, if they're having sensitive sight problems.

It isn't relevant where items are stored in or outside the network, as long as they're visible/available to a terminal of any kind. A player may still decide to overview externally stored items in a terminal by using a storage bus, and be confronted with the rapidly shifting grid eventhough the items are never causing any active AE/t.

**Additional Context**

Although I call this a button, it may not necessarily work best as a button, in your GUI design. It may be additional modes for an existing button, or it may not be a button at all. I'm just referring to it as a button for simplicity reason.

**Comment by yueh** [comment] 2021-09-12 17:16
Duplicate of #27

**Closed by yueh** 2021-09-12 17:16 UTC
