### ISSUE TITLE
Req lag goggles feature

### ISSUE THREAD

**Issue by hambabam** [AppliedEnergistics/Applied-Energistics-2#4131] opened 2019-08-24 19:37 UTC
I am using lag goggles on a server, I've been playing. I've notice that lag goggles can't pick up the effects of applied energistics 2 on the server. I asked the author of lag goggles about it, and they told me because of the way ae2 works that it would be better to ask the owner of ae2 to make a simple profiler. 
I was wondering if maybe there was a way to make such a feature or perhaps a sup mod for ae2 that could simply be added to a pack to be able to see what effects the mod has on a server or computer.
It could greatly help with server lag by finding areas that are causing more lag than necessary. 

![2019-08-24_14 30 49](https://user-images.githubusercontent.com/54450516/63641919-127df600-c67c-11e9-8f42-e4cdca45f341.png)
This screen shot is of part of my ae2 system with some other mods around it being viewed with lag goggles. The red block in the middle of the controllers is a power cell from RFTools that is causing 42 micros sec. / tick. 

This is the link to my request to the author lag goggles. 
https://github.com/TerminatorNL/LagGoggles/issues/78

If there is anything I can do to help just ask. My knowledge of programming is less than none, but I'll try what I can.

**Comment by yueh** [comment] 2019-08-24 20:04
LogGoogles is pretty much useless for performance problems for anything but the simplest machines (anything which cannot work with other machines). Otherwise it's by design hiding the actual cause.

E.g. in exactly this case, it's most likely not the power cell being a bit costly, but actually inserting the energy into the AE2 network. But even that isn't really important. We are talking about less than .1% of each tick here and it could probably be cut by about 75% when the cell would face only one controller side.

Performance problems can pretty much only be resolved by actual profiling or sampling. Which is already provided by java with jvisualvm or similar tools. Or even player's sampler mod.
All LagGoogles can achieve is to blame some random mod as false positive, followed by admins disabling this block without ever fixing the real issue. As well as starting rumours about modA being so bad for servers, when it's actually modB.

**Closed by yueh** 2019-08-24 20:04 UTC

**Comment by hambabam** [comment] 2019-08-25 01:46
I'm sorry but that picture didn't represent any kind of problem but was actually just there to show how lag goggles worked on other blocks that were not ae2.
It seems to me that maybe your just too aggressive here. I'm using lag goggles as a tool like a capenter would use a ruler, to measure the affects of things on a server. I use this to help keep the server from having to do as much work. For example, using an item conduit from ender io and a lot better than using a hopper from vanilla or how mana spreaders from botania can be used in a tree farm, it's just better to use a tree farm machine from forestry.

To be honest the whole reason I even noticed it was because when I kicked on an ae2 system I set up for my ore processing everything started to lag. I would have liked to know what part of my machine was the reason behind that so that i can fix it.

**Comment by yueh** [comment] 2019-08-25 10:16
If you prefer analogies, then you are using a hammer to measure distance instead of a ruler. It is simply the wrong tool. Even if you could say it's about 3 hammers long. Pretty much nobody except you could make any sense from it, or just their own hammer with a different size.

The picture is pretty much shows the problem with LagGoggles as well as your reasoning. Ultimately it does not solve anything, just swept it under the rug. Iirc EnderIO uses a similar system to our ticking, but at least TD ducts will use it.  So all it would achieve is to hide the ducts from it, while still working in the background. Or in case of AE2, it's mostly some external storage mods, which are abysmal in terms of performance, But all you would see is that buses, interfaces, etc would suddenly appear as issue. While it's actually some storage everything accesses.

**Comment by hambabam** [comment] 2019-09-18 02:43
Thank you, Flash, as that is pretty much what I wanted. I just didn't really know how to word it. I'm not very knowledgeable with the technicalities. Nor do I have any background in coding or anything. I actually learned about lag goggles from a friend.

I just wanted a way to see the effects of AE2 on the server. I don't care if it's even accurate because I really just wanted a general idea. The color coding from lag goggles isn't even a good representation, I just take it that anything over 500 microseconds per tick is somewhat bad.

The server I'm playing on hosts the Direwolf20 pack. We were trying to find the reason our server was having problems. It had the same results that TheFlash showed. 

It turns out that my AE2 system was the cause for it. The owner of the server figured it out thanks to the command /sponge timers report. I believe it showed that Applied Energistics 2::TickHandler_onTick was using 1,983% of tick. If the chunks because loaded, it would start to lag. Even if you left to unload them, they would stay loaded for some reason even when I the chunk loaded was destroyed. Once I destroyed my controller, it let up on the problems. I left the server and it turned out it started lagging again. The owner restarted the server and it hasn't caused any more problems. TBH, it could be any number of things on my base, but it does look like something from AE2 is going on.

In the very least I believe it would help show that AE2 is not the cause. I'm actually going to have to do like a full-blown investigation on my base.
