### ISSUE TITLE
Black Hole Unit (IF) autocrafting issues

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#3223] opened 2017-11-13 15:44 UTC
If an autocrafting operation requires more than a stack from a single black hole unit (Industrial Foregoing), you cant initiate the autocrafting because AE2 will try to extract everything it needs, but if it's more than 64 it's not available because the units "only gives access" to 64 items at a time. This is done on a server.

I can test more if needed.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-1
- Forge Version: 14.23.0.2531
- Industrial Foregoing: 1.5.5-92

**Comment by GuntherDW** [comment] 2017-11-14 08:33
This is not our problem.
This is something Industrial Foregoing should fix. We decided to stop supporting all kinds of hacks in favour of the Forge interfaces.

Sort of duplicate of #2550

**Closed by GuntherDW** 2017-11-14 08:33 UTC
