### ISSUE TITLE
Crash with Thaumcraft

### ISSUE THREAD

**Issue by krisjenner** [AppliedEnergistics/Applied-Energistics-2#3975] opened 2019-03-27 01:00 UTC
Client crashes when hovering over item in AE terminal

**Describe the bug**
Hovering over seemingly any item causes client crash.

**To Reproduce**
Thaumcraft-1.12.2-6.1.BETA26

Expected behavior
Able to hover over item without crash

Additional context
[LOG](https://gist.github.com/krisjenner/7c61758bfa3f07262fc61bee991d82bc)

Environment
Minecraft Version: 1.12.2
AE2 Version: rv6-stable-4
Forge Version: 2815

**Comment by krisjenner** [comment] 2019-03-27 01:01
I am also using Thaumic Energistics.

**Comment by yueh** [comment] 2019-03-28 16:24
Duplicate of #3973

**Closed by yueh** 2019-03-28 16:24 UTC
