### ISSUE TITLE
Speed up charger

### ISSUE THREAD

**Issue by johnlage** [AppliedEnergistics/Applied-Energistics-2#368] opened 2014-11-01 17:01 UTC
How this would be implemented should be debated, maybe adding a GUI, but I think that this would be really nice to have.

**Comment by DavidJotta** [comment] 2015-09-10 00:54
+1 for a way to speed the charger up. It usually takes more than 5 seconds to charge 1 certus quartz in my case. Maybe use its sides? Attach upgrades?

**Comment by Blue64** [comment] 2015-10-14 08:33
+1 here too, Vibration Chambers can work faster without GUI, this shouldn't be too different. Blood Magic Mod uses Multipart structures that include blocks which can be swapped out to modify their Blood Altar, including Speeding it up.

**Comment by mindforger** [comment] 2015-10-14 08:42
so the problem is the sync between client and server? i also noticed this very inconsitent chargerate when doing it manually, while piping it through is somewhat more consistent

**Comment by Blue64** [comment] 2015-10-14 09:01
It's possible that sync is an issue, but even a *2 speed option would be nice, also keep in mind that highly customized ModPacks might have tweaked the ticks required, or in my case, I'm just on a really old laptop (dual core with barely enough RAM to run all the mods).

**Comment by DavidJotta** [comment] 2015-10-14 11:20
@mindforger Well, I actually had it setup with an ME Interface inserting 1 certus quartz into the charger and outputting the charged one with an import bus, a pretty standard way to do it. It is true sometimes it is instantaneously, but other times it takes so long to charge, while being at 20tps :/

**Comment by yueh** [comment] 2017-10-08 16:58
Duplicate of #114

**Closed by yueh** 2017-10-08 16:58 UTC
Labels: type-enhancement
