### ISSUE TITLE
Proper capture of keypresses while search box is focused

### ISSUE THREAD

**Issue by juanitierno** [AppliedEnergistics/Applied-Energistics-2#3366] opened 2018-01-30 12:20 UTC
I'm using the REVELATIONS FTB pack.

Like many people (I hope) I have "r" bound to show recipe in JEI, and "u" to show uses.

While the interface is open, and the searchbox is focused, those keys should be "captured" by the textbox, so other events don't fire. they are not, and they fire JEI events.

It's very common (at least for me) that the mouse pointer ends up over an item somewhere (most of the screen is inventory) and I end up checking recipes and uses accidentally (other hotkeys might end up being applied accidentally too, but I disable anything I don't use so I don't know).

- Minecraft Version: REVELATIONS FTB pack
- AE2 Version: REVELATIONS FTB pack
- Forge Version: REVELATIONS FTB pack

**Comment by Tahakk** [comment] 2018-01-30 12:35
it is nice to say you are using pack, but in different versions of pack you can have different versions of mod/forge. Just for next time you will report some issue, you can find all of this info in Twitch App - I suppose you are using it, if not in folder where is your pack installed.

**Comment by mindforger** [comment] 2018-01-30 13:04
or do a forced crashlog by pressig and holding f3+c while ingame (not menu) and post it via pastebin or attachment , but please not as wall of text :)

**Comment by yueh** [comment] 2018-01-30 13:06
Duplicate of #2634

**Closed by yueh** 2018-01-30 13:06 UTC
