### ISSUE TITLE
Null Pointer Exception saving chunk

### ISSUE THREAD

**Issue by zpprsprk** [AppliedEnergistics/Applied-Energistics-2#5074] opened 2021-03-17 05:57 UTC
See: #5068 in which I first reported this bug but was ignored since I said some words that mod devs don't like to hear...

Reproduced with Forge version 36.0.58 and ONLY AE2 installed. See below:

[20:15:52] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@4aad0e00 onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		2: ASM: class net.minecraftforge.client.model.ModelDataManager onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2959/676752045@39922326
java.lang.NullPointerException
	at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:403)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:388)
	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:366)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:323)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[20:15:52] [Server thread/ERROR] [minecraft/ChunkManager]: Failed to save chunk [-11, 58]
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_171] {}
	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:388) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:366) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:323) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171] {}
Caused by: java.lang.NullPointerException
	at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180) ~[?:8.3.0-alpha.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:403) ~[?:?] {re:classloading}
	... 13 more

**_Forced crash log:_** 
https://pastebin.com/yLEUGr8Q

_Originally posted by @zpprsprk in https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5068#issuecomment-799724301_

**Comment by yueh** [comment] 2021-03-17 07:47
Duplicate of #5069

**Closed by yueh** 2021-03-17 07:47 UTC
