### ISSUE TITLE
Intermittent crash on server. (Using quantum ring links) 

### ISSUE THREAD

**Issue by Erosion139** [AppliedEnergistics/Applied-Energistics-2#4302] opened 2020-03-02 13:37 UTC
When the server is idling, at a random time the server will crash. The crash log seems to point to AE2 as being the culprit and before having these crashes it seems that while messing with the ME quantum link chambers for the first time it wasnt behaving as I expected. Randomly the links would shutoff across dimensions (even while being chunk loaded) and having sufficient power etc. Just stops and also disables the network on the opposing side. One link is in the overworld and the other is in the tropicraft dimension. After deciding that it wasnt going to be a reliable system I decided to move the tropicraft link into the overworld, however the crashing still persisted. I think it only happens when the server is completely idle or the regions are unloaded. However I havent been kicked off personally as I played but I know others have been kicked off because of it. The issue originally occured while I was running on RV6S7 and the world was created using RV6S6 so I tried to revert back to that previous version. But it seems to exist there as well. 
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: RV6S6 (also reproducable on RV6S7)
- Forge Version: 14.23.5.2838
[debug.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4275663/debug.log)
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4275664/latest.log)

**Comment by yueh** [comment] 2020-03-05 18:53
Duplicate of #3800

**Closed by yueh** 2020-03-05 18:53 UTC
