### ISSUE TITLE
Cannot get EU from IC2 via cable.

### ISSUE THREAD

**Issue by kice** [AppliedEnergistics/Applied-Energistics-2#3135] opened 2017-10-05 03:26 UTC
I placed a cable next to ME Contorller to power it by EU. The controller can get the power for the first time. But If I remove the ME Controller or the cable and place it again, the controller cannot get any EU. If I remove the controller first, the cable stay connected (it was longer than normal). 

Here is the error log may help.

```
[02:59:53] [ic2-poolthread-1/WARN] [IC2.EnergyNet]: Tile appeng.integration.modules.ic2.IC2PowerSinkAdapter@3c8f3bff (dim 0: 256/58/221), sub tile 256/58/221 (appeng.integration.modules.ic2.IC2PowerSinkAdapter@3c8f3bff) addition is conflicting with a previous registration at the same location (appeng.integration.modules.ic2.IC2PowerSinkAdapter@2cfc2dec).
[03:00:53] [ic2-poolthread-2/WARN] [IC2.EnergyNet]: Tile appeng.integration.modules.ic2.IC2PowerSinkAdapter@4f0b25a5 (dim 0: 256/58/221), sub tile 256/58/221 (appeng.integration.modules.ic2.IC2PowerSinkAdapter@4f0b25a5) addition is conflicting with a previous registration at the same location (appeng.integration.modules.ic2.IC2PowerSinkAdapter@2cfc2dec).
[03:01:06] [ic2-poolthread-2/WARN] [IC2.EnergyNet]: Tile ic2.core.block.wiring.TileEntityCable@4606ceb5 (dim 0: 256/59/221) removal without registration
[03:01:24] [ic2-poolthread-2/WARN] [IC2.EnergyNet]: Tile appeng.integration.modules.ic2.IC2PowerSinkAdapter@450a898e (dim 0: 250/58/219), sub tile 250/58/219 (appeng.integration.modules.ic2.IC2PowerSinkAdapter@450a898e) addition is conflicting with a previous registration at the same location (appeng.integration.modules.ic2.IC2PowerSinkAdapter@568af912).
[03:01:31] [ic2-poolthread-1/WARN] [IC2.EnergyNet]: Tile appeng.integration.modules.ic2.IC2PowerSinkAdapter@8c5c982 (dim 0: 256/58/221), sub tile 256/58/221 (appeng.integration.modules.ic2.IC2PowerSinkAdapter@8c5c982) addition is conflicting with a previous registration at the same location (appeng.integration.modules.ic2.IC2PowerSinkAdapter@2cfc2dec).
[03:01:45] [ic2-poolthread-2/WARN] [IC2.EnergyNet]: Tile ic2.core.block.wiring.TileEntityCable@414d348f (dim 0: 256/59/221), sub tile 256/59/221 (ic2.core.block.wiring.TileEntityCable@414d348f) addition is conflicting with a previous registration at the same location (appeng.integration.modules.ic2.IC2PowerSinkAdapter@1f54532d).
```

- Minecraft Version: 1.10.2
- AE2 Version: rv4-1
- Forge Version: 12.18.3.2185
- IC2 Version: 2.6.254-ex110

**Comment by fscan** [comment] 2017-10-05 10:44
Duplicate of #3094

**Closed by fscan** 2017-10-05 10:44 UTC

**Comment by kice** [comment] 2017-10-05 11:51
https://github.com/SonarSonic/Calculator/issues/255
Is it the same issue as this one?

**Comment by fscan** [comment] 2017-10-05 18:47
i dont know, does it matter? if you read the issue i linked you will know what the cause is and how to fix it.
