### ISSUE TITLE
Sponge-Forge crashes when AE2 is installed

### ISSUE THREAD

**Issue by Keanu73** [AppliedEnergistics/Applied-Energistics-2#2705] opened 2016-12-15 19:47 UTC
#### Description

I installed AE2 and started up my server, the server failed to startup, because of a class that was loaded prematurely? I know it's AE2, because when I removed it, the server started up again.

#### Environment

I'm running a SpongeForge server, with mods and plugins, and this was on a Multiplayer server. The SpongeForge version is 5.1.0-BETA-1992. Log when AE2 is in the mods folder: http://paste.ubuntu.com/23635126/    Log when AE2 is NOT in the mods folder: http://paste.ubuntu.com/23635194/
As you can see, there's a subtle difference there.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-9
- Forge Version: 12.18.3.2185

**Comment by XFactHD** [comment] 2016-12-15 20:27
This is a known issue which is already being worked on. Please use the search next time before making the 20th duplicate of an issue.

**Closed by XFactHD** 2016-12-15 20:27 UTC

**Comment by Keanu73** [comment] 2016-12-16 07:49
Huh?? I'm sure I searched and nothing came up..

**Comment by Keanu73** [comment] 2016-12-16 07:52
Please reference the issue that's a duplicate before closing this..? I'm sure I couldn't search for anything that was similar.

**Comment by XFactHD** [comment] 2016-12-16 07:57
#2482

**Comment by mcsnetworks** [comment] 2017-01-05 02:19
This is a duplicate yes, but the original, #2482 was closed and since ignored...
