### ISSUE TITLE
Server crash - runtimeException: Slot 14 not in valid range - [0,1)

### ISSUE THREAD

**Issue by ProsperCraft** [AppliedEnergistics/Applied-Energistics-2#3113] opened 2017-09-27 04:49 UTC
#### Description
Server crash, I don't know what the players were doing at the time.

#### Environment
https://gist.github.com/ProsperCraft/5b6cc7a57ffb495f4bdd1248546c44cd
All the mods 3

- Minecraft Version: 1.12.1
- AE2 Version:  appliedenergistics2-rv5-alpha-4
- Forge Version: forge-1.12.1-14.22.0.2459-universal

**Comment by yueh** [comment] 2017-09-28 07:00
Duplicate of #3098

**Closed by yueh** 2017-09-28 07:00 UTC
