### ISSUE TITLE
JEI channel

### ISSUE THREAD

**Issue by Shucai99** [AppliedEnergistics/Applied-Energistics-2#4892] opened 2020-12-28 15:36 UTC
**Describe the feature**

i dont see The channel how much i use how i will take it
https://i.imgur.com/cshVv4Z.png in last time i useed in 12.2 i see it but in 1.16.3 not and how i can see it maybe i need to user other mod 
**Reasons why it should be considered**

**Additional Context**

**Comment by yueh** [comment] 2020-12-28 17:35
Duplicate of #4838

**Closed by yueh** 2020-12-28 17:35 UTC
