### ISSUE TITLE
Problem with witchery and auto crafting (1.7.19 #2

### ISSUE THREAD

**Issue by LordViperagyil** [AppliedEnergistics/Applied-Energistics-2#2867] opened 2017-04-12 05:01 UTC
Witchery poppets aside from the base one can't to be crafted. when the computer trys to craft the actual poppet it stay in the quoe forever. witchery doesn't exist in higher version than 1.7.10 so can't be tested in higher version. already tried with rv210 fix provided was to try this version of ae2.
mods are: witchery 0.24.1 ae2 rv3beta6

version:1.7.10
ae2:rv3beta6
forge: 10.13.4.1614

**Comment by bookerthegeek** [comment] 2017-04-12 05:06
Duplicate of [2865][1], that being said you are setting it up incorrectly. The meta or NBT data (Which ever one it is that you can not see, I always get those mixed up) on whatever item you are using in the crafting pattern is not the same as the one that will be the actual result of the one you craft. 

If you can not figure it out, you can set up to dump the materials into another crafter you can get to work, then import the poppet back into the A.E. system.



[1]:https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2865

**Closed by bookerthegeek** 2017-04-12 05:06 UTC
