### ISSUE TITLE
Annihilation Plates voiding blocks

### ISSUE THREAD

**Issue by aaronhowser1** [AppliedEnergistics/Applied-Energistics-2#5275] opened 2021-06-06 06:58 UTC
**Describe the bug**
I have this setup:
![image](https://user-images.githubusercontent.com/15698722/120915575-fa694200-c669-11eb-8fc8-63909faafc33.png)
When I place a block in front of the plane, it gets broken, as expected.
However, it doesn't enter the Cell, it just gets voided. The Cell isn't partitioned or anything, it's a normal, blank Cell.

https://user-images.githubusercontent.com/15698722/120915593-1a990100-c66a-11eb-98fd-d576ae8727f0.mp4

When I remove the Drive entirely, it still breaks blocks (and voids them):

https://user-images.githubusercontent.com/15698722/120915618-4a480900-c66a-11eb-9403-7fa349bbcf50.mp4

**Environment**
MC 1.16.5, Forge version 36.1.4, AE2 version `appliedenergistics2-8.3.1`
Force crash report: https://pastebin.com/Qz8TktuL
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6603763/latest.log)
[debug.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6603764/debug.log)

**Comment by yueh** [comment] 2021-06-06 07:57
Duplicate of #4692

**Comment by aaronhowser1** [comment] 2021-06-06 08:01
Wait so, everyone's just giving up on this? The Forge issue was closed 9 months ago. Is there really nothing that can be done?

**Comment by aaronhowser1** [comment] 2021-06-06 08:05
That thread says that they removed ForgeHooks.canToolHarvestBlock, so how can it be the same issue?

**Comment by Technici4n** [comment] 2021-06-06 09:07
I'll have a look

**Comment by redgoblin88** [comment] 2021-06-06 09:22
i have gone into creative and have tried every. single. block

the image shows every single block that does get destroyed/voided when using the anihilation pane, when in fact they SHOULD be giving something when broken

notes:
- when a block was "voided", i tried two more attempts in case they were a fluke, in which 100% of the time, no it was not
- the anvils are all three states
- the iron door is an odd case in which the bottom half voids where as breaking the top half sort of works
- the bottom left blocks are warped and crimson nylium "grass" from the nether
- it seems if one type of block fails (such as terracotta or prismarine), then all the variants will too

mods:
AE2 - 8.3.0-beta.2
forge - 36.1.4

![2021-06-06_10 15 25](https://user-images.githubusercontent.com/13396472/120919346-03313680-c6b1-11eb-83ae-26347ba318ed.png)

**Comment by Ommina** [comment] 2021-06-06 09:54
Mild speculation, but are these blocks that are supposed to be mined with a pick?  I don't [i]think[/i] I see any shovel- or axe-harvested blocks there.

**Comment by redgoblin88** [comment] 2021-06-06 11:13
> Mild speculation, but are these blocks that are supposed to be mined with a pick? I don't _think_ I see any shovel- or axe-harvested blocks there.

if that is the case then that would mean  stone, andesite, granite, diorite blocks would also be affected, which they are not

however i did think that most of them have special properties, like most can be waterlogged, terracotta doesnt stick to slime, some have inventories/redstone behaviour
but again that theory falls flat as comparators, redstone dust, obsidian, sea pickles and chests arent affected

**Comment by Mari023** [comment] 2021-06-06 11:22
my theory would be that only blocks added or blocks where the blockid changed after 1.12 are affected 
tho I think there are some blocks affected which do not fit in this category (dropper, dispenser, enchanting table, enderchest, hopper, brewing stand, furnace)

**Comment by Technici4n** [comment] 2021-06-06 11:39
Some blocks report that they require a tool to be broken, but not which one. #5276 should fix this by breaking with a pickaxe if we know the block requires a tool, but we don't know which one.

**Closed** 2021-06-06 12:30 UTC

**Comment by aaronhowser1** [comment] 2021-06-07 06:25
If the commit was reverted, shouldn't this be reopened?

**Comment by Technici4n** [comment] 2021-06-07 07:16
It's not been reverted on the `master` branch. :-P
