### ISSUE TITLE
Autocrafting crashed client and unable to open save file

### ISSUE THREAD

**Issue by phonymacoroni** [AppliedEnergistics/Applied-Energistics-2#4907] opened 2021-01-04 04:43 UTC
**Describe the bug**

After requesting a previously setup automatic crafting recipe the client crashes, and the world file is unable to be opened.

**To Reproduce**

Crash occurred when requesting to craft a fluix me cable, with all needed recipes in a molecular reassembler. Recipes did have allow substitutes on. 

**Expected behavior**

Not crash the client and make the save file unopenable? 😝 

**Additional context**

full log (with usernames removed): https://pastebin.com/bE4CSKKW

**Environment**

- Environment: 
Using the direwolf20 pack from FTB
Crash log pastebin: https://pastebin.com/G85NaiWB
Reproduced crash log pastebin: https://pastebin.com/UUXi5bnb

**Comment by Linux123123** [comment] 2021-01-05 13:42
👍 Exactly the same error on the same modpack. Happened the second I pressed craft. I also can't go to my saved world now.

**Comment by Linux123123** [comment] 2021-01-05 15:05
@phonymacoroni  The fix is already in beta-2 so, just update mod manually and you will be able to autocraft and open the saved world.

**Comment by yueh** [comment] 2021-01-05 18:03
Duplicate of #4893

**Closed by yueh** 2021-01-05 18:03 UTC
