### ISSUE TITLE
Thermal Expansion's Tank turns P2P into FE instead of Fluid

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3217] opened 2017-11-11 22:16 UTC
#### Description
When right-clicking a P2P with a Thermal Expansion Tank it turns it into a P2P FE instead of a P2P Fluid.
I don't know if it's Applied Energistics' or Thermal Expansion's responsability.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-1 
- Forge Version: 2537
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1464047/list.txt)

**Comment by GuntherDW** [comment] 2017-11-14 08:38
This is due to a bit of oversimplified code in the Attunement code on my part.

This is something I should indeed fix. If I remember correctly I check for FE capabilities first before setting it to FE? I'll take a look at it when I can.

**Comment by yueh** [comment] 2017-11-14 08:51
That is caused by the whole mod being assign to FE as fallback once no item is assigned to something else.

In this case it might be an idea to check for fluid containers similar to the FE cap itself before using the mod id map. But otherwise it is something we can only handle to some degree on our side. It is simply not possible to monitor every other mod and fix our default mappings for every added or removed item variant.

**Comment by Xiaminou** [comment] 2017-11-14 13:58
Yeah I did remember someone mentioning that P2P checks for capabilities which is why it seemed weird to me that a fluid container would bind it to FE.
It's low priority of course, just using a bucket in the meantime.

**Closed** 2017-12-01 20:14 UTC
