### ISSUE TITLE
Redstone duping with Interface and Formation Plane

### ISSUE THREAD

**Issue by xILikepuddingx** [AppliedEnergistics/Applied-Energistics-2#3275] opened 2017-12-11 12:15 UTC
See here: https://minecraft.curseforge.com/projects/modern-skyblock-2/issues/436

Minecraft-Version: 1.12.2
AE2-Version: appliedenergistics2-rv5-stable-3
ModerPack-Version: 2.7.2.2

**Comment by yueh** [comment] 2017-12-11 12:18
Duplicate of #2791

**Closed by yueh** 2017-12-11 12:18 UTC
