### ISSUE TITLE
[Wireless] Crash server When every it's place down

### ISSUE THREAD

**Issue by Mini-kun** [AppliedEnergistics/Applied-Energistics-2#6080] opened 2022-02-21 20:15 UTC
### Describe the bug

When every Wireless acc. point

### How to reproduce the bug

Just place the block down in the world

### Expected behavior

Place it and Look for a Cable and open the UI for the block

### Additional details

it just Crash the Server and wont let the player how place the block rejoin or anyother that are in the same area

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Mini-kun/34b3279c599aca78b27dcf2b1acb06b2

**Comment by Technici4n** [comment] 2022-02-21 20:16
Duplicate of #6077

**Closed by Technici4n** 2022-02-21 20:16 UTC
Labels: bug
