### ISSUE TITLE
Fuzzy Export crash with tinker's items

### ISSUE THREAD

**Issue by Nyagi** [AppliedEnergistics/Applied-Energistics-2#3849] opened 2018-12-05 02:47 UTC
In Enigmatica Expert 2 Expert mobs sometimes drop tinker's tools so i tried setting up powered anvils to repair them. But it seems once i started adding the tinker's tools to the export bus the game crashed 

**Describe the bug**
Usually the game simply freezes and refuses to close so a shut down of my computer was necessary. Upon opening it again it 'properly' crashed and generated the report which is attached (Downloaded from pastebin)

. 

**To Reproduce**
The 'repair room' was located within a compact machine, using an adapter to allow channels through. Exporters were lined up to export into iron chests. When adding tinker tools to the export buses the freezing and crash happened. 

**Expected behavior**
Game freezes and refuses to close, chance of crash when reopening it or freezing again. 

**Additional context**

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-4.jar
- Forge Version: 1.12.2-14.23.5.2768

**Comment by yueh** [comment] 2018-12-05 07:07
Duplicate of #3768

**Closed by yueh** 2018-12-05 07:07 UTC
