### ISSUE TITLE
Search box does not clear text with right-click

### ISSUE THREAD

**Issue by mille449** [AppliedEnergistics/Applied-Energistics-2#4499] opened 2020-07-25 19:06 UTC
Seen in the crafting terminal.  After text is entered, right-clicking in the text box does not clear the text. Instead the text is selected.  Previously this cleared the text, just like JEI does. Also JEI sync does not seem to work, but that's a separate issue.

**Comment by yueh** [comment] 2020-07-25 20:44
Duplicate of #4492

**Closed by yueh** 2020-07-25 20:44 UTC
