### ISSUE TITLE
Storage Busses (FTB Beyond)

### ISSUE THREAD

**Issue by MrMadPenguin** [AppliedEnergistics/Applied-Energistics-2#2872] opened 2017-04-14 16:10 UTC
Hello i got problem with Storage busses not showing the right amount of items stored in quantum storage  from QuantumStorage Mod. I got 1.5 Mill cobble in storage but in system it only shows 64, and its taking the cobble from storage but it does not show the 1.5 Mill in the system. 

![m1](https://cloud.githubusercontent.com/assets/27504769/25048585/1d1b905c-2135-11e7-9080-e85df34c3d6e.png)
![m2](https://cloud.githubusercontent.com/assets/27504769/25048586/20dfd2fc-2135-11e7-949a-437d6b7a1a01.png)
![m3](https://cloud.githubusercontent.com/assets/27504769/25048589/22d0cff8-2135-11e7-8a3e-a83036864d2a.png)
![m4](https://cloud.githubusercontent.com/assets/27504769/25048590/23c60d2e-2135-11e7-957f-a90df89a7da1.png)
![m5](https://cloud.githubusercontent.com/assets/27504769/25048592/2467045e-2135-11e7-84c2-8576a48b140d.png)
![m6](https://cloud.githubusercontent.com/assets/27504769/25048594/259427b2-2135-11e7-9f12-27461e0fcd45.png)
![m7](https://cloud.githubusercontent.com/assets/27504769/25048595/266fecfc-2135-11e7-8fad-6103873b7369.png)

- Minecraft Version:  1.10
- AE2 Version:  rv4-alpha-11
- Forge Version:  12.18.3.2254

**Comment by ThomasAunvik** [comment] 2017-04-15 19:00
Duplicate of #2550

**Closed** 2017-04-16 10:00 UTC
