### ISSUE TITLE
Login Crash Ticking block entity AEFluidInventory

### ISSUE THREAD

**Issue by Zeronic** [AppliedEnergistics/Applied-Energistics-2#4791] opened 2020-10-24 17:50 UTC
Crash on login after server crash, I believe the AE Cable was removed and the AEFluid Interface was trying to request more from the storage drive. 

java.lang.NullPointerException: Ticking block entity
	at appeng.fluids.util.AEFluidInventory.drain(AEFluidInventory.java:201) ~[?:7.0.4] {re:classloading}
	at mekanism.common.tile.transmitter.TileEntityMechanicalPipe.func_73660_a(TileEntityMechanicalPipe.java:77) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:1410) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_271] {}

[crash-2020-10-24_12.45.19-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5433457/crash-2020-10-24_12.45.19-server.txt)

**Comment by yueh** [comment] 2020-10-26 14:21
Duplicate of #4733

**Closed by yueh** 2020-10-26 14:21 UTC
