### ISSUE TITLE
Lack off network/p2p management.

### ISSUE THREAD

**Issue by Craftypiston** [AppliedEnergistics/Applied-Energistics-2#786] opened 2015-01-20 14:58 UTC
*Issue:*

When creating larger networks and when using many p2p (all of them; power. me, redstone etc) connections it becomes rather easy to loose track of what p2p is connected to the other. It would be nice to get a mechanic to keep track of this.

*Ignore this solution, look at my latest post down here for the new solution*

*Possible solution's:*

- **Add an mode for the network tool (just like you can toggle facade visibility when holding the tool or having it on the toolbar). This could do a number of things; **

- solution 1) When you right click (with this mode enabled) with the network tool on any p2p cable it will show an glow/outline on all the other connected p2p cables (same tunnel). The input p2p should have a different glow/outline then the output ones. 
- solution 2) When you right click (with this mode enabled) with the network tool on any p2p cable it will show with a "part number" for that p2p along with all the other part numbers it is connected to. This way you can run over the the other p2p's to see if they have the correct part number. An other take on this can be that instead of having a part number it can be a connection number. So you can right click an set of p2p's to see that they have the same connection number. This might get a bit hard for the user so maybe giving the user a way of naming the p2p's would be the more easy way to go about it. The problem with this solution is that you can't see what the direction of the connection is.

*Personal note:*

When ae1 turned into ae2 i had huge problems adjusting to the concept of channels. Now that i finally get how the new mod works i have had much fun with it but now i use many p2p connection to give each room it's own full 32 channels by connecting a p2p straight to the controller. This works pretty good but that does make it hard to manage. (example for my autocrafting room/ p2p http://imgur.com/a/8Sndt).

**Comment by TheJulianJES** [comment] 2015-01-20 16:09
I would also like it :)

**Comment by yueh** [comment] 2015-01-20 16:53
1) P2P tunnels do not know the path how they are connected, just that the are online/powered
Also the network does not really know how everything is connected, the displayed channel usage is just "this cable transmit x channels, but not between which devices".
So highlighting a path is not really possible as there is none and we need to take something like the QNB into account.

2) They have already an internal number, but I doubt showing a 64-digit number is helpful for the user.

As it is already possible to name them, we are looking into using this.
But it mostly takes a good idea how to display it. A simple GUI or Waila is just a bad solution.

And the other request with similar/identical suggestions: #38, #43, #395, #691, #707, #739

**Comment by Craftypiston** [comment] 2015-01-20 17:01
Okay informative responds. 

As for the first "solution" the idea was not to show the path but rather the two (or more) linked ones via the outline methode. I can make an image to clarify if necessary.  

And as for the second "solution" it indeed is possible to name them but it still is not a good solution in my humble opinion. Maybe rounding the number down can already help but i see the issue with that for the end user..

**Comment by yueh** [comment] 2015-01-20 17:15
Outlining similar how Botania handles it is not really possible.
Botania has the advantage that it is limited to about 10 blocks or so, at least something cleary in visible range. But P2P tunnels might be hundreds or thousands of blocks away or even in other dimensions.

Condensing the number down has always the issue of collisions. So it will give false information about the links. It would be possible to map it to a colorcode. But that would still be 16 different colors and using all 16 vanilla colors.

Naming is probably still the best option as AE2 has it's own way, which does not require experience or an anvil.

**Comment by Craftypiston** [comment] 2015-01-20 20:30
I have come to the conclusion that this is indeed a rather complicated issue. The most simple solution that *can work* is indeed like you said it would but it is missing some features to make it work. This is the best and most simple solution i came up with:

- Since it is possible to rename the p2p's via the name plates and the inscriber, the most easy way to show what p2p the player is looking at (once it is already placed) is to have a name plate (kinda like a player) that is only visible when the network tool has been set to that mode "Show custom parts". This way the player can at least keep track of the p2p once it is placed what is not possible atm as far as i know (apart from looking in the list of parts via the network tool). 

![modes](https://cloud.githubusercontent.com/assets/10615515/5825393/41dcd0bc-a0eb-11e4-89a9-fad87f14e790.png)

- The first part helps the player identify the p2p unit but not the connection. To help the player the following gui addition could be made; since the p2p has a custom name it will not group it self under the installed p2p's (non custom) in the network tool. This allows the user to inspect that p2p independently of the others. When the user rolls over that custom p2p it already shows some statistics so in that menu it should have an other line stating either the child or parent connection (see image). It might be a good idea to add a search line that that gui since it can be a little messy when you have many maaaannyy p2p's.

![connection](https://cloud.githubusercontent.com/assets/10615515/5825406/5a52539c-a0eb-11e4-947a-3e2842fec0dc.png)

I think this might be the solution if this is technically viable.

**Comment by yueh** [comment] 2015-01-21 15:58
The nameplate is basically what we have already considered. But I am in general not a fan of hiding stuff behind some options (I am not even sure, if I like the button to toggle the facade rendering).

And you have one flaw in your logic. If you link a p2p tunnel, the name will be overwritten with name of the other side.

I have already tried to implement it some days (probably weeks) ago. But I am missing some directly accessable data like the player position, to be able to render it only in a limited range and translate it according the player position, etc.

**Comment by OldOpa** [comment] 2015-01-23 05:48
I fixed the problem for now that I don't connect the P2P-Tunnel direct to the controller. I'm using a dense cable and color it with for example a green color. The advantage is that you first of all see your channels used and the second advantage is that you can use the color to connect the other P2P-output with the same color. The difficult part would then only be the limit of the 16 colors (I never used this much).
But wouldn't it be possible to color the cable, and then adjust the color with other dyes (much like Extra Utilities Colored Blocks) but not in so "small steps" but in "bigger steps", so that you easily can remember how often you clicked with that dye?

**Comment by yueh** [comment] 2015-01-23 10:46
To throw some numbers into the discussion.
The theoretical limit for the amount of P2P tunnels is `18 446 744 073 709 551 616`. This is not each tunnel part, but each tunnel linked together. This is how many different colors you would need to distinguish them and you probably already noticed the issue.

There are some practical limits currently as is depending on the time in milliseconds, but they could change at any time

* only positive numbers => cutting the limit in half ( `/2` )
* the precision is 1 magnitude worse in most cases => `/10` (maybe under best assumptions)
* 1 player can only place/link once per tick => `/200` (20 ticks per second => 200 msec, only applies to singleplayer)
* you will not be able to make 1 action per tick, maybe 1 or 2 a second => `/5` (best case 1 per second)

Reducing it from `18 446 744 073 709 551 616` to `922 337 203 685 477`. Still a bit too much for colors. Also we would now have issues in multiplayer or if you can place it faster than once per second.
Worst case would be checking `922 337 203 685 476` numbers of they are already used, each time you create a link

It might be possible to reduce the amount of 16 different colors per link without causing collision (different tunnels will show up as the same color, even if they are different) to something less.
Maybe 8, but I would consider anything above 4 to not be usable and that is the point were collisions are pretty likely.

**Comment by epicnational** [comment] 2015-02-06 17:44
In my build, I had to get very organized in how i utilize my p2p tunnels so that I don't get so mixed up, to the point where i have a complex naming system for each p2p tunnel. For example: N-1H-3 (each of the letters and numbers designates where on the huge controller i use where the p2p sits. My biggest issues, and what would probably help me TO NO END, is simply an ability (the network tool would be great) is to see how many channels any p2p is using, and having whatever i named the p2p actually display in waila. 

First, displaying channels. It would be perfect if when you click on a p2p tunnel with the networking tool (or even in waila, but i like using tools for these things  ^_^  Maybe just having the networking tool in your inventory makes waila display it, you could even just make it need a blank diamond card to give it this functionality, sort of just a generic upgrade). The best way for this to be implemented, imo, would just be each p2p usage, so for instance, clicking on a controller p2p would display 16/16 used channels, the first number being the actual number of channels THIS P2P is using, while the second is the total in the p2p chain used, so a "destination" tunnel would have something like 8/16. This would tell you if you could pull anymore channels out (in this case, yes, since only 16 channels are being used total, with this particular one pulling 8.)

Second, when i name a p2p in an anvil/inscriber, it doesnt display the name when placed in the world. I have to physically pick it up to see whatever i named it. Simply being able to see the name i gave it, and its channel usage would basically solve all of my p2p networking issues.

**Comment by Deshiba** [comment] 2015-02-10 19:27
@epicnational "... adding functionally through other mods is always better than nothing, since currently we dont have ANY way to view their names. "

Relying on another mod to do something with your own is allways going to be a risk. Not only are you depending on functionality that is in that mod, but also the specific build of that mod. So if you rely on that mod to do something with your mod, you will have to support every version that comes out. And heaven forbid if the maker of the mod stops develpment/support.

A core functionality like P2P management should not rely on other mods IMO. Go native or go home :P

**Comment by RAnders00** [comment] 2015-02-17 20:59
Simply- see it as a challenge to keep track of them. I usually keep track of them using a floor identifier and then a number, basically labeling in a somewhat straight-forward way using Bibliocraft fancy signs.
http://prntscr.com/66f5ik

Whenever i connect a P2P i put a fancy sign up which connection it is.
http://prntscr.com/66f6on

Simply whenever you want to connect up a p2p, you see on the densecable (and in the latest versions even via Waila) if there are enough channels left. See it as a challenge to keep track of them.

I would not consider this a good feature to add.

**Comment by JacintUK** [comment] 2015-02-17 22:47
I don't have as many P2P networks as some people in this thread, but I find I am labeling them all with Bibliocraft signs, which just look so out of place in a futuristic tech mod!

Instead of naming the P2P tunnel endpoints, can we have at least have a Network Terminal that displays the network ID of the cable / controller it's attached to and / or an editable 1 line text field associated with that network? (It would take up a channel on that network, of course). You could also display the current / max number of channels on that network. You should be able to add more than one such terminal to the network - though you would mostly likely add one near each P2P endpoint.

**Comment by MysticAura** [comment] 2015-02-18 22:02
I'd be perfectly happy with the current nameplate option if Waila would show the dang name. It kind of defeats the purpose of naming, if you can't see the name when it's on the controller.  I'm not sure if this is a Waila or AE2 issue though.

It would be nice if there was an advanced memory card that would list all available named p2p's or a way to see how many channels has been used on said p2p connection (maybe clicking it with the network tool)

**Comment by yueh** [comment] 2015-03-01 13:44
Closing it is mostly a duplicate of older issues (the feedback will of course be considered)

**Closed by yueh** 2015-03-01 13:44 UTC
