### ISSUE TITLE
crash with inscription er

### ISSUE THREAD

**Issue by carlucci9660** [AppliedEnergistics/Applied-Energistics-2#3724] opened 2018-09-15 13:00 UTC
So last night with stable version 11 I put two name tags in the scriber with a 4K storage cell it was proceeding to label it me realizing I didn't want both the name tags in the inscriber I quickly pulled out the storage cell to stop it and I got game freeze. Now everytime I try to load my game It crashes rather it loads the game into the world but immediately freezes as a first frame comes in and stays Frozen.  I'll supply a log shortly, ahh f%÷ck me, I hope my world isn't fijcked.....one modder to another, thanks for your hard work bro. 

#### Environment

- Minecraft Version: 1.12.2
[crash-2018-09-15_00.11.03-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2385904/crash-2018-09-15_00.11.03-server.txt)
[2018-09-14-5.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2385907/2018-09-14-5.log.gz)

- AE2 Version:  5 r11
- Forge Version: .2759

**Comment by carlucci9660** [comment] 2018-09-15 16:37
[2018-09-14-5.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2385905/2018-09-14-5.log.gz)

**Comment by carlucci9660** [comment] 2018-09-15 16:43
going to try to set inscriber to false, try to disable it, see if the world loads....but prob not gonna work.....from now on going to run freesync with versioning turned on and save my saves folder.

**Comment by carlucci9660** [comment] 2018-09-15 16:46
ok becuse of the error mentioned above, turned off inscriber since the error accourded with it allowed me to unfreese my game, good news, the bad news is the error is still there and prob. can be recreated.

**Comment by yueh** [comment] 2018-09-22 17:57
Duplicate of #3476

**Closed by yueh** 2018-09-22 17:57 UTC
