### ISSUE TITLE
Tiny TNT Lighting Bug 1.10.2

### ISSUE THREAD

**Issue by ThomasAunvik** [AppliedEnergistics/Applied-Energistics-2#2874] opened 2017-04-15 18:53 UTC
#### Description

When placing a Tiny TNT it creates a dark spot where it is placed.

![Imgur](http://i.imgur.com/AbBOT0h.png)
![Imgur](http://i.imgur.com/KyyawIs.png)

#### Environment

JVM Args: `-Xmx12288m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\Bruker\AppData\Roaming\.minecraft\Instances\V1.10.2" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Xmx10G -Xms10G -Xmn768m`

Java 1.8.0_25

- Minecraft Version: 1.10.2
- AE2 Version: alpha-11
- Forge Version: 12.18,3,2272

**Comment by CraftMinerKyle** [comment] 2017-04-17 16:14
It is likely that the issue is that the Tiny TNT is considered and entire block, but the TNT is actually a partial block. The in game shaders are doing what they should, but the texture size is the problem. Please tell me if I'm wrong or not DEV, as I don't use 1.10 AE2.

**Comment by Mekadrom** [comment] 2017-07-04 01:56
The problem appears to be because the material that BlockTinyTNT has is Material.TNT, which has translucency and therefore always has to remove light that passes through it by some amount. Changing this to Material.CIRCUITS fixes the problem, but may cause other problems.

**Comment by mindforger** [comment] 2017-07-04 05:11
yeah, what @CraftMinerKyle said, this is known but not a big deal as you normally do not build things from this ... would have to search for the old topic to get a hand on what the decision was but i think it was too minor to address (but don't quote me on that i may be wrong on that)

**Comment by CraftMinerKyle** [comment] 2017-07-08 13:28
Perhaps making a special shader just for AE2 as an add-on could be a thing...

**Comment by fscan** [comment] 2017-10-20 22:22
fixed in dev (1.12.2)

**Closed by fscan** 2017-10-20 22:22 UTC
