### ISSUE TITLE
Possible Quantum tunnel server crash

### ISSUE THREAD

**Issue by 6269329** [AppliedEnergistics/Applied-Energistics-2#4053] opened 2019-05-27 23:31 UTC
**Describe the bug**
Server crashes after around 5 minutes of the bridge being connected. Doesn't happen with the singularity removed/deactivated.

**To Reproduce**
Have a tunnel active.

**Expected behavior**
Server closes after around 5 minutes.

**Additional context**
https://pastebin.com/9svAvzya

**Environment**
Two points ~1000 blocks apart
Both Chunk loaded.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 14.23.5.2836

**Comment by mindforger** [comment] 2019-05-28 05:47
did you install enough ae2 energycells in both parts of the me system? If you are using chickenchunks chunkloader, install a spotloader on top of the chunkloader.

Please try it out before responding with „i got enough production“ ;)

**Comment by 6269329** [comment] 2019-05-29 00:37
I can try that I have a few on both sides, but why would that crash the server, rather than the tunnel just not functioning?

**Comment by yueh** [comment] 2019-06-01 12:42
Duplicate of #3800

**Closed by yueh** 2019-06-01 12:42 UTC
