### ISSUE TITLE
Client Side Rendering Crash

### ISSUE THREAD

**Issue by godimbored** [AppliedEnergistics/Applied-Energistics-2#830] opened 2015-02-02 01:24 UTC
http://pastebin.com/dq3sqDHP

I got this crash various times now on rv2 beta 7 and now on 8. 
This may happen when connecting a part to a network (interface, level emitter)
First time it happened i had connected a level emitter to a covered cable - fluix connected to the network, this happened with several parts from the mod itself or from addons, weirdly enough it doesn't happen everytime you do this (after i deleted the level emiter on mcedit i went in, did the same thing and nothing happened). When this happens the world gets corrupted and you need to delete the block through mcedit or something else.
The only thing i changed on the config files is the channels, which i disabled.

**Comment by yueh** [comment] 2015-02-02 14:21
It is caused by the disabled channels as they remove the smart cables. (Reasons like rendering more then 8 channels or not necessary anymore).

But it looks like some rare conditions still require them to be available to render other parts.

**Comment by godimbored** [comment] 2015-02-02 14:24
Is there anything i can do to fix this (diferent type of cable) or just enable the channels again?

**Comment by yueh** [comment] 2015-02-02 16:03
Not really, you can probably try to avoid certain builds until it is fixed.

This for example causes it:
![cable render bug](http://i.imgur.com/chjQhmv.png)

If it is just a single line with a level emitter facing away from the end, it is fine. Just the moment you add that T or L section it will cause it. But there might be other parts which also causes it.

**Comment by godimbored** [comment] 2015-02-02 16:11
What about putting these parts on the sides of a single cable would that be ok?

**Comment by godimbored** [comment] 2015-02-02 23:19
I recreated exactly what you showed with normal fluix cables and nothing happened, then did the same thing with the covered cable and it crashed. Maybe it onlty happens with covered cables.

**Comment by godimbored** [comment] 2015-02-03 03:05
Ok, replaced all the covered cables with normal fluix cabes and everything seems to be fine. Recreated all the situations i had crashes with covered cables, using the normal one and it was all fine. I guess it's important to say on the config or the mod page that if you disable channels only use normal cables and not covered ones.

**Comment by yueh** [comment] 2015-02-03 10:17
There is just a bug how covered cables are rendered. But it is not obvious without disabled channels.

**Comment by yueh** [comment] 2015-02-07 10:51
Will be fixed when #855 gets pulled.

**Closed** 2015-02-27 10:07 UTC
Labels: state-fixed, type-bug
