### ISSUE TITLE
Crash when using cell workbench(fabric)

### ISSUE THREAD

**Issue by k3nw4y** [AppliedEnergistics/Applied-Energistics-2#4841] opened 2020-11-25 16:39 UTC
**Describe the bug**
when clicking the partition button in the cell workbench with a cell in it crashes the client
**To Reproduce**

insert a storage cell into a cell workbench and click partition
**Expected behavior**

it will allow you to partition storage disks
**Additional context**
crash log: https://gist.github.com/k3nw4y/1f6b90c8089cd335b43a659ebb1d3315

**Environment**

- Environment: 
All of Fabric modpack 2.4.4
MC 1.16.4 + AE2 8.1.0-alpha.12 (Fabric)

**Comment by Accia121** [comment] 2020-12-30 21:39
I haven't noticed this with normal storage disks but have ran into this problem with fluid storage disks in all of fabric 2.5.4

**Comment by MSandro** [comment] 2021-02-20 22:27
MC 1.16.5 + AE2 8.2.0-alpha.1 (Fabric), it doesn't crash but I can't open it
here is what my server outputs in the log on clicking on the cell workbench.
```
[22:24:39] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at appeng.container.implementations.CellWorkbenchContainer.getCellUpgradeInventory(CellWorkbenchContainer.java:177) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.util.inv.WrapperSupplierItemHandler.getSlotCount(WrapperSupplierItemHandler.java:59) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at alexiil.mc.lib.attributes.item.SingleItemSlotView.<init>(SingleItemSlotView.java:24) ~[d99bab67-57e9-4be2-a0b5-a3801afdc1ba.jar:?]
	at alexiil.mc.lib.attributes.item.SingleItemSlot.<init>(SingleItemSlot.java:23) ~[d99bab67-57e9-4be2-a0b5-a3801afdc1ba.jar:?]
	at alexiil.mc.lib.attributes.item.FixedItemInv.getSlot(FixedItemInv.java:176) ~[d99bab67-57e9-4be2-a0b5-a3801afdc1ba.jar:?]
	at appeng.container.slot.AppEngSlot.<init>(AppEngSlot.java:55) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.slot.RestrictedInputSlot.<init>(RestrictedInputSlot.java:76) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.slot.OptionalRestrictedInputSlot.<init>(OptionalRestrictedInputSlot.java:33) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.implementations.CellWorkbenchContainer.setupConfig(CellWorkbenchContainer.java:127) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.implementations.UpgradeableContainer.<init>(UpgradeableContainer.java:136) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.implementations.CellWorkbenchContainer.<init>(CellWorkbenchContainer.java:71) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.implementations.ContainerHelper$HandlerFactory.createMenu(ContainerHelper.java:153) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at net.minecraft.class_3222.method_17355(class_3222.java:956) ~[intermediary-server.jar:?]
	at appeng.container.implementations.ContainerHelper.open(ContainerHelper.java:116) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.implementations.ContainerHelper.open(ContainerHelper.java:93) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.container.implementations.CellWorkbenchContainer.open(CellWorkbenchContainer.java:80) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.block.misc.CellWorkbenchBlock.onActivated(CellWorkbenchBlock.java:54) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at appeng.block.AEBaseTileBlock.method_9534(AEBaseTileBlock.java:270) ~[appliedenergistics2-fabric-8.2.0-alpha.1.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:894) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:328) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by pavuk300** [comment] 2021-03-14 14:26
The same problem, but not crash, just don't open the inventory.

**Comment by Technici4n** [comment] 2021-05-31 22:15
Can't reproduce, I assume it was fixed in the latest builds.

**Closed by Technici4n** 2021-05-31 22:15 UTC
Labels: fabric
