### ISSUE TITLE
Crashes when used together with SpongeForge

### ISSUE THREAD

**Issue by Hax165** [AppliedEnergistics/Applied-Energistics-2#2609] opened 2016-11-12 23:22 UTC
#### Description
Crashes quickly (3 seconds) when loaded together with spongeforge. Removing AE2 fixes it though.

#### Environment
I'm using spongeforge with a few plugins and 100 other mods. Note everything works fine without spongeforge installed. While keeping spongeforge but removing AE2 will also fix the issue.

Here is the server log: http://pastebin.com/KVzN64q5

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-5
- Forge Version: forge-1.10.2-12.18.2.2125-universal
- SpongeForge Version: spongeforge-1.10.2-2123-6.0.0-BETA-1877

**Comment by shartte** [comment] 2016-11-12 23:53
Duplicate of #2482

**Closed by shartte** 2016-11-12 23:53 UTC
