### ISSUE TITLE
Inventory conflict

### ISSUE THREAD

**Issue by Jly4** [AppliedEnergistics/Applied-Energistics-2#4405] opened 2020-06-09 16:39 UTC
ME terminal conflicts with interface not enough items

![2020-06-09_23 39 00](https://user-images.githubusercontent.com/65804380/84175631-6d1cfd00-aaaa-11ea-9d51-93cfcb717478.png)

- Minecraft Version: 
- AE2 Version: rv6(stable7)
- Forge Version: 14.23.5.2854

**Comment by fdevx** [comment] 2020-06-10 08:03
Duplicate of #3922

**Comment by Jly4** [comment] 2020-06-10 08:18
I did not understand how to do this. May I have more detailed instructions?

**Comment by mindforger** [comment] 2020-06-10 08:49
Take a cup of your preferred beverage, make yourself comfortable

„Will be considered once there is time to refactor the whole GUI part to make these things easier.“

**Closed** 2020-06-10 08:49 UTC
