### ISSUE TITLE
Crafts that require multiple items in a single cell do not work.

### ISSUE THREAD

**Issue by Venia04** [AppliedEnergistics/Applied-Energistics-2#8042] opened 2024-07-17 23:18 UTC
### Describe the bug

There are recipes from other mods (In particular, in IC2c) that require multiple items in one crafting slot. And it doesn't work with the workbench in ME Crafting Terminal. And in a regular workbench, these crafts work as they should.

### How to reproduce the bug

1. Use any mod that has an item recipe that requires at least one cell to have multiple items in it.
2. Try laying out this recipe in the ME Crafting Terminal workbench
3. You get nothing

### Expected behavior

You get an item that provides for this kind of recipe

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

No crash log needed

**Comment by 62832** [comment] 2024-07-18 01:32
Duplicate of #7448.

**Closed by 62832** 2024-07-18 01:32 UTC
Labels: bug
