### ISSUE TITLE
Storage Bus + Quantum Storage Unit seems to be completely broken

### ISSUE THREAD

**Issue by TheVanoq** [AppliedEnergistics/Applied-Energistics-2#2849] opened 2017-03-27 10:58 UTC
Attaching a storage bus to a Quantum Storage Unit will not make the QSU act as expected, even when the bus is configured correctly.

#### Description
When items are being imported into the AE-System, SOME of them will go into the QSU and some of them will land on disks, even when the QSU has the highest priority. Also, at one point the AE-System will stop showing the correct amount and start glitching by jumping from (for example) 1664, 1665, 1666 and then back to 1664.

#### Environment
- Single/Multiplayer
- Minecraft 1.10.2
- appliedenergistics2-rv4-alpha-11
- Forge 1.10.2-12.18.3.2254
- QuantumStorage-1.10.2-3.3.0

**Comment by Lupoid** [comment] 2017-03-30 17:20
Exact same issue, using ftb beyond build 1.2.1, same mod versions as above

**Comment by ThomasAunvik** [comment] 2017-04-15 19:05
Duplicate of #2550

**Closed** 2017-04-16 10:01 UTC
