### ISSUE TITLE
Huge Update Time for the AE Handler

### ISSUE THREAD

**Issue by Neodark7** [AppliedEnergistics/Applied-Energistics-2#882] opened 2015-02-11 05:24 UTC
![ae](https://cloud.githubusercontent.com/assets/7981869/6142423/8c995504-b1b6-11e4-991c-c60f290dd1c9.PNG)

here's the profil https://www.dropbox.com/s/mlroa6acs65xprh/ae2%20lag.nps?dl=0
here's my log https://www.dropbox.com/s/ahk9a6fqrl0w5nx/fml-server-latest.log?dl=0

**Comment by yueh** [comment] 2015-02-11 20:20
There should be two potential causes. Either it is a duplicate of #670 or the usual issues with EnderIO ME Conduits. It might even be both.

**Comment by Neodark7** [comment] 2015-02-11 20:41
ok i check i'll test removing the EIO me conduits

**Comment by Neodark7** [comment] 2015-02-11 21:14
![capture](https://cloud.githubusercontent.com/assets/7981869/6156532/516d8f74-b23b-11e4-8a45-2cbc2a26499d.PNG)
Yeah i have remove all the me conduits now i have 100k :D

**Comment by MatthiasMann** [comment] 2015-02-11 21:38
the ME conduits have been fixed since build 2.2.8

**Comment by Neodark7** [comment] 2015-02-11 21:38
i'm using EnderIO-1.7.10-2.2.8.346

**Comment by yueh** [comment] 2015-02-12 13:55
Closing in favor of #670

**Closed by yueh** 2015-02-12 13:55 UTC
