### ISSUE TITLE
Auto-crafting more than one Plant Interactor (Industrial Foregoing) crashes the server

### ISSUE THREAD

**Issue by Sythe777** [AppliedEnergistics/Applied-Energistics-2#3834] opened 2018-11-24 19:45 UTC
First time I've experienced an issue with auto-crafting any of the Industrial Foregoing machines. Simply put, the entire server crashes if a player attempts to automatically craft more than one plant interactor and must be rolled back to a backup to fix.

**Describe the bug**

Server crashes and stays crashed until a rollback occurs.

**To Reproduce**

Attempt to automatically craft more than one Plant Interactor from Industrial Foregoing. I've tested each precursor item to ensure it was only the Plant Interactor and none of them cause the crash.

**Expected behavior**

The ME network takes the resources from the storage cells and creates precursor items to the plant interactor. Using the precursor items, it creates a plant interactor.

**Additional context**

Screenshots of example setup: https://imgur.com/a/iUJOvJZ
Crash log: https://pastebin.com/cQeKqJbX

**Environment**

Running the FTB modpack Revelation 1.12.2 with 8GB RAM allocation. The suspect mods include appliedenergistics2-rv5-stable-11 and industrialforegoing-1.12.2-1.11.2-212.

Computer specs: 
    CPU: AMD FX-8350
    GPU: AMD RX 480
    RAM: 32GB DDR3-1600 Hz

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: unknown

**Comment by yueh** [comment] 2018-11-24 19:54
Duplicate of #3768

**Closed by yueh** 2018-11-24 19:54 UTC
