### ISSUE TITLE
Using JEI "+" in pattern terminal destroys items

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2645] opened 2016-11-21 18:25 UTC
#### Description
https://youtu.be/eo7PmLtobuY

#### Environment
[list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/614353/list.txt)

- Minecraft Version: 1.10.2
- AE2 Version: alpha 6
- Forge Version:

**Comment by yueh** [comment] 2016-11-21 18:33
Cannot reproduce.

**Comment by Tsukiumy** [comment] 2016-11-21 19:25
just to add, it seem only some itens are destroyed, in this case the covered cable, gets destroyed, and in this recipe in specific

**Comment by yueh** [comment] 2016-12-02 23:38
Most likely duplicate of #2626.

**Closed by yueh** 2016-12-02 23:38 UTC
Labels: state-waiting
