### ISSUE TITLE
Searching 'E' can close the screen

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#6001] opened 2022-01-13 11:18 UTC
### Describe the bug

In `Remember Search: Off` and `Auto-Focus: Off` mode on an ME Terminal, if you search anything containing the letter E, typing E in REI search (while the screen is open) will close the inventory, and pressing backspace doesn't work

### How to reproduce the bug

Make sure your open inventory keybind is 'E'

1. Place an ME Crafting terminal
2. Set its search settings to `Remember Search: Off` and `Auto-Focus: Off`
3. Search 'E'
4. Type anything into REI (not containing E)
5. Try pressing backspace (doesn't work)
6. Try typing 'E' (closes inventory)

### Expected behavior

REI works normally

### Additional details

All of Fabric 5, 0.2.11

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by BLovegrove** [comment] 2022-01-15 18:51
I'm getting the same issue in the Valhelsia: Vanilla Enhanced pack for 1.18.1 on fabric. This seems to be part of a larger problem that prevents me from viewing recipes using the 'r' hotkey or even typing in the REI menu until i jump out  off the terminal and back in again.

**Comment by Iskandos** [comment] 2022-01-22 00:16
I'm also getting this -- started with the 1.18 Fabric package for Better Minecraft (plus a few other mods, mostly decor), and added the 10.0.0 [FABRIC] version of Applied Energistics 2. The game launches just fine, world opens just fine, I can run around and do things just fine, but when I hit E to open my inventory the game freezes for a moment, saves, then crashes.

Here's a link to a ZIP of the crash report:
https://www.dropbox.com/s/kodej0vs312c53j/crash-2022-01-21_19.03.07-client.zip?dl=0

**Comment by shartte** [comment] 2022-01-22 16:45
@Iskandos Your crash is completely unrelated to this issue. You are using polymorph's AE2 integration, which is incompatible with AE2.

**Comment by shartte** [comment] 2022-01-22 16:46
I am able to reproduce this issue, but it's somewhat weird.
Either we are doing something incorrectly with Minecraft's focus, or REI is.
This issue occurs if you focus the search field, and then unfocus it by clicking outside the textbox.

**Comment by Technici4n** [comment] 2022-06-27 16:12
Might be fixed now, some needs to confirm.

**Closed** 2022-08-30 22:08 UTC
Labels: bug, awaiting-feedback
