### ISSUE TITLE
Crash: Ticking GridNode on rv6-stable-3

### ISSUE THREAD

**Issue by martmists** [AppliedEnergistics/Applied-Energistics-2#3852] opened 2018-12-06 15:17 UTC
**Describe the bug**
The server crashes just after it's ready to launch.

**To Reproduce**
unknown.

**Expected behavior**
Server launches just fine

**Additional context**
http://termbin.com/rzxl

**Environment**
Multiplayer server, modpack ATM3-Remix
OS: Arch Linux x64, all packages up to data
Java: 1.8.0_191

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version: 1.12.2-14.23.5.2768

**Comment by yueh** [comment] 2018-12-06 15:22
Duplicate of #3768

**Closed by yueh** 2018-12-06 15:22 UTC
