### ISSUE TITLE
Help me please!!!!

### ISSUE THREAD

**Issue by 828bkg** [AppliedEnergistics/Applied-Energistics-2#712] opened 2015-01-08 19:48 UTC
I'm Italian and if the translations will not be 100% accurate to blame It 's translator :
Then ...... When I use for example quartz grindstone , I find ore Certus quartz or other alright ..... But When A place with ME in the Subject Name ( ME access terminal, control ME , etc . ) my world is crashing and I can not open it More Until I delete Block with external Programs THIS crash report:
shutting down internal server ....... a fatal error is occured , this connection will be terminated ( I play in single player ) help me , I saw the mod on youtube and I want to use it , please

**Comment by Cisien** [comment] 2015-01-09 03:03
We need the full crash log, and not just the last few lines

**Comment by 828bkg** [comment] 2015-01-09 16:07
Is only this

**Comment by Cisien** [comment] 2015-01-09 17:21
Post the full log from where this came from if there was no crash

**Comment by 828bkg** [comment] 2015-01-09 17:29
there isn't a crash log!
leaves only the inscription : a fatal error is occured , this connection will be terminated 
And back to minecraft home menu

**Comment by Cisien** [comment] 2015-01-09 22:07
There is a runtime log. That is what I need. It tells me what mods are installed,at the least.

Without that log, ill just have to close this issue since there is no help I can provide

**Comment by Ianaver** [comment] 2015-01-10 18:23
@828bkg go reproduce the error, and look in your logs folder in .minecraft it will be the log down at the bottom of the page [format: year-month-day-number (only if more than one are in the same day)]

**Comment by Cisien** [comment] 2015-01-18 23:21
lack of response

**Closed by Cisien** 2015-01-18 23:21 UTC
Labels: state-waiting
