### ISSUE TITLE
I have no idea how to describe this bug.

### ISSUE THREAD

**Issue by samlovebutter** [AppliedEnergistics/Applied-Energistics-2#5039] opened 2021-03-04 12:18 UTC
**Describe the bug**
I've restarted minecraft. Can't describe the bug, Just look at this.

**To Reproduce**
Enter the singleplayer world with AE2.

**Expected behavior**
I expected bug to not happen.

**Additional context**
![image](https://user-images.githubusercontent.com/17319180/109960847-508cb900-7cfa-11eb-9d0f-019e478a77e5.png)
![image](https://user-images.githubusercontent.com/17319180/109960902-613d2f00-7cfa-11eb-89f3-669017450f37.png)

**Environment**
F3+c crashlog:
[crash-2021-03-04_15.01.46-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6083466/crash-2021-03-04_15.01.46-client.txt)

- Environment: 
MC 1.16.4
forge - 35.1.37
appliedenergistics2-8.2.0

**Comment by yueh** [comment] 2021-03-04 12:21
Duplicate of #5017

**Comment by samlovebutter** [comment] 2021-03-04 12:21
> Duplicate of #5017 (Most likely)

Alright, thank you

**Closed by yueh** 2021-03-04 12:21 UTC
