### ISSUE TITLE
Dense Energy cell refusing to accept power past 1.5MAE. Will not charge until broken/re-placed

### ISSUE THREAD

**Issue by PiggyWhiskey** [AppliedEnergistics/Applied-Energistics-2#3322] opened 2018-01-11 04:21 UTC
FTB Revelations 1.2.0 using appliedenergistics2-rv5-stable-4
SMP Hosted on my second computer.

http://puu.sh/yYM6H/291d685266.jpg

Dense Energy Cell placed directly next to an Energy Acceptor will stop charging at 1.5MAE and won't accept any power again until broken/replaced.

Items are all within 1 chunk within [Simply Void World](https://minecraft.curseforge.com/projects/simple-void-world) dimension
Tested with various Creative/legitimate energy sources with no change.

No errors noticeable in Server Console.

Restarting Client: No change.
Restarting Server: No change.

Once a network is "corrupted" the only solution is to break everything and re-build.
Replacing the Energy Acceptor/Energy Cell's doesn't fix the issue.

I can provide a save if necessary.

**Comment by fscan** [comment] 2018-01-11 19:52
hmm .. i rebuilt your setup in a new single player world and cannot reproduce it. I'll try smp when i find the time.

**Comment by PiggyWhiskey** [comment] 2018-01-12 01:43
With the example, it only bugged out occasionally. The other AE network partially within the chunk has it as a permanent issue

**Comment by yueh** [comment] 2018-01-12 12:15
Could also be another forge chunk loading bug corrupting tile entitites.

**Comment by PiggyWhiskey** [comment] 2018-01-12 13:29
If that's the case, what can I do to check/fix it?

**Comment by yueh** [comment] 2018-01-13 10:32
Probably nothing besides scanning through a (few) full heap dump once it's happened and try to compare the actual state with the expected one. Which will of course require some very deep knowledge about Minecraft, Forge and AE2 internals.

**Comment by Loatan** [comment] 2018-01-21 18:25
Same problem 3:
![2018-01-21_17 37 05](https://user-images.githubusercontent.com/34774105/35197540-8e937796-fef1-11e7-9ef9-3d54b9b92676.png)

**Comment by yueh** [comment] 2018-01-29 14:44
This might be fixed in rv5.stable.7, but only for very large amounts being inserted/extracted in a single operation. But there is still a chance that forge does handle tile entities incorrectly during a chunk unload/load causing it to corrupt until being broken or even a restart.

**Comment by positivereturn** [comment] 2018-02-01 22:03
Are you using flux network power plugs to supply it? I'm seeing weird behavior from that mod similar to this interacting with AE, which is not an issue with other power sources. Controller blocks do not store power, show 0 AE stored even when running, and the energy cells do not completely fill, but sit just below full.

**Comment by PiggyWhiskey** [comment] 2018-02-02 04:53
In that world, yes. I used Flux Networks everywhere.

**Comment by positivereturn** [comment] 2018-02-02 07:27
I did not see the same issue with RFtools powercells - I think the bug is in flux networks.

**Closed** 2018-02-09 18:21 UTC
Labels: state-waiting
