### ISSUE TITLE
AE2 and YABBA makes the game freeze

### ISSUE THREAD

**Issue by nycolassoares** [AppliedEnergistics/Applied-Energistics-2#4382] opened 2020-05-14 12:04 UTC
**Describe the bug**

Im playing Project Ozone 3, no mods added, latest version.

If i hook up a Storage Bus to a Barrel Connector that has barrel with millions of items in it, it makes my tps go to 5.

**To Reproduce**

Hook up a Storage Bus to a Barrel Connector that has barrel with millions of items in it

**Expected behavior**

Not make the game unplayable

**Additional context**

https://gist.github.com/nycolassoares/8bac1991eda44652bda21a9bd61f82b1#file-gistfile1-txt
https://www.youtube.com/watch?v=FIjV_JHOa0I&feature=youtu.be

**Environment**

Single player world
Im playing the lastest version of Project Ozone 3

- Minecraft Version: 1.12.2
- AE2 Version:  appliedenergistics2-rv6-stable-7.jar
- Forge Version:  forge-14.23.5.2847

**Comment by Tahakk** [comment] 2020-05-14 12:42
it's because of the very large number of items
and it's duplicate of #4069

**Closed** 2020-05-14 13:00 UTC
