### ISSUE TITLE
Quartz Grindstone - powered option

### ISSUE THREAD

**Issue by Arstahd** [AppliedEnergistics/Applied-Energistics-2#4900] opened 2021-01-02 07:37 UTC
Why doesn't the Quartz Grindstone have the ability to run off of power in addition to hand cranking?   The Charger runs off both.  

I've recently come back to MC and started running the latest version, limiting my mod choices to those that have been updated.  My tech mod of choice has yet to update, and I 'm not keen on the ones which have, leaving me largely machine free.  This puts me in a situation where I can have an advanced storage and fabrication network from AE2, but I'm left hand cranking ores into dusts.  It just seems silly.

I can understand not wanting to implement redundant items that would overlap with other common tech mods, but adding an extra power option to an already existing item doesn't seem like a bad idea.

**Comment by yueh** [comment] 2021-01-02 11:09
Duplicate of #23

**Closed by yueh** 2021-01-02 11:09 UTC
