### ISSUE TITLE
Config Option to disable channels.

### ISSUE THREAD

**Issue by SpeedCuber1** [AppliedEnergistics/Applied-Energistics-2#4886] opened 2020-12-23 21:59 UTC
**Describe the issue**
In older versions of AE you could disable the channel system.  In the 1.16.4 version I looked and there is no option.  I like certain aspects of the mod but the channel system is a little too complicated for me.
 Minecraft Version: 1.16.4
Forge Version: 1.16.4-35.1.4

**Comment by yueh** [comment] 2020-12-23 22:14
Duplicate of #4621

**Closed by yueh** 2020-12-23 22:14 UTC
