### ISSUE TITLE
Issues with Canvas Renderer

### ISSUE THREAD

**Issue by DariusSG** [AppliedEnergistics/Applied-Energistics-2#4651] opened 2020-08-27 10:40 UTC
**Describe the bug**
Textures that are dynamic such as cables and facades don't renderer.

**To Reproduce**
Include Canvas Renderer

**Expected behavior**
Well, everything should render.

**Additional context**
![2020-08-27_18 32 00](https://user-images.githubusercontent.com/39219301/91431932-a1c37800-e893-11ea-821c-e5c998145b6e.png)

https://pastebin.com/YPe26NiR

Without Canvas
![2020-08-27_18 39 14](https://user-images.githubusercontent.com/39219301/91432679-a5a3ca00-e894-11ea-9afa-58f60e95619e.png)

https://pastebin.com/RXQf9r0M

**Comment by shartte** [comment] 2020-08-27 10:43
There is at least one open issue with canvas right now that will need to be merged before we can fix this.

However, rest assured, canvas compat is planned.

**Comment by grondag** [comment] 2020-08-28 20:10
I should have looked before I posted this one: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4657

There are the two lines to remove we saw earlier, but that will also need to be addressed.  Otherwise, everything from my end is ready to go AFAIK.

**Comment by petabyteboy** [comment] 2020-09-06 09:48
With the following combination of versions:

  [✔️] appliedenergistics2-fabric-8.1.0-alpha.7
  [✔️] canvas-mc116-1.0.927
  [✔️] fabric-api-0.20.1+build.401-1.16

I get the normal loading screen, but when it fades away the client looks very messed up:

![screenshot1](https://user-images.githubusercontent.com/3250809/92323173-d6bf8f80-f036-11ea-9913-6ddf8d083006.png)

**Comment by petabyteboy** [comment] 2020-09-06 09:57
A little further testing of different version reveals that this is caused by the combination of the new Canvas renderer version and AE2. Downgrading Canvas Renderer to one release earlier (canvas-mc116-1.0.878) fixes this issue, but shows the old behaviour of cables and some other AE2 stuff not getting rendered.

**Comment by shartte** [comment] 2020-09-06 10:01
@petabyteboy weird. I did test this yesterday with AE2 alpha.7, and canvas 913, which worked for me.
i did not test it with canvas 927. are you sure that is not a canvas problem?

**Comment by petabyteboy** [comment] 2020-09-06 10:52
I see there is an issue for this in the Canvas repo and you even found it already: https://github.com/grondag/canvas/issues/100

If it works with canvas 913, it might very well be an issue in the canvas code. I will try to bisect the commits in canvas to find the change that broke it.

**Comment by petabyteboy** [comment] 2020-09-06 10:58
Nope, the main menu is borked with canvas 913 + AE2 alpha.7 as well.

**Comment by grondag** [comment] 2020-09-06 15:33
This should be fixed in Canvas build 929, [available now on CF](https://www.curseforge.com/minecraft/mc-mods/canvas-renderer/files/3050976).

**Closed** 2020-09-06 16:59 UTC
Labels: fabric

**Comment by petabyteboy** [comment] 2020-09-07 09:44
I can confirm that it works fine. Thanks everyone for the great work :+1: 
One last nitpick: The ME Drive indicators are constantly flashing around when I move. Maybe they are rendered at the same depth as the background and the order is not always the same with Canvas?

**Comment by shartte** [comment] 2020-09-07 09:56
It is probably z-fighting, yes, I did observe something similar.
For now I'll leave it at that. Once our sizable backlog has been reduced somewhat I'll look at making actual canvas-specific improvements and fixes (such as making AE2 lights glow).
