### ISSUE TITLE
[fabric 0.14.6, MC 1.18.2] cant start large automation process

### ISSUE THREAD

**Issue by AmonRay** [AppliedEnergistics/Applied-Energistics-2#6320] opened 2022-06-02 17:28 UTC
### Describe the bug

any automation with a lot of steps doesn't want to run. For example, 10х256k cells, the START button is active, but when you click on it, nothing happens. But everything works fine when you start crafting 1 or 2 cells.

same for export buses with crafting module

### How to reproduce the bug

hard to say. I just tried to run large automation process :)

### Expected behavior

run automation

### Additional details

![2022-06-02_20 25 23](https://user-images.githubusercontent.com/4718043/171688294-d25bba5b-c1d5-4a53-a39d-6a92943bef8b.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/AmonRay/e1f0b9ab538d39f192743835201372c6

**Comment by icywhisker-official** [comment] 2022-06-03 23:03
I've had this issue recently as well. I narrowed my problem down to the ME system not being able to autocraft redstone dust by itself. I recommend checking each individual component to see which one is causing the craft to fail

**Comment by Frazzer951** [comment] 2022-06-04 04:30
I had a similar issue, I looked through all my patters and found I actually had a duplicate of the one I was trying to craft, and even though both the patterns were the same it wouldn't let me start the craft, but when I removed the duplicate it worked fine

**Comment by Technici4n** [comment] 2022-06-10 13:33
Closing as this will be resolved by #5884.

**Closed by Technici4n** 2022-06-10 13:33 UTC
Labels: bug
