### ISSUE TITLE
Fluid dupe 

### ISSUE THREAD

**Issue by Shadedstalker2** [AppliedEnergistics/Applied-Energistics-2#7017] opened 2023-04-03 00:49 UTC
### Describe the bug

Having a tank with 2 or more storage buses it will times the fluid stored inside the tank by however many storage buses there is which then can be pulled out of a terminal with a second tank. This can fill a max size industrial foregoing tank in around 7 clicks

### How to reproduce the bug

2 or more storage buses on a tank with a terminal

### Expected behavior

It will show more than what’s stored in the tank and can be pulled out through the terminal

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

No crash log

**Comment by cplir-c** [comment] 2023-04-03 00:52
I think the expected behavior is more like "It will show more than what’s stored in the tank and can only remove the amount in the tank"

**Comment by Mari023** [comment] 2023-04-03 00:53
probably a duplicate of #6987

**Comment by Shadedstalker2** [comment] 2023-04-03 00:54
> I think the expected behavior is more like "It will show more than what’s stored in the tank and can only remove the amount in the tank"

No it will remove what the terminal sees

**Comment by Technici4n** [comment] 2023-04-03 06:08
It's indeed a duplicate of #6987. I will release the fix in a few days.

**Closed by Technici4n** 2023-04-03 06:08 UTC
Labels: bug
