### ISSUE TITLE
ME Cables issue

### ISSUE THREAD

**Issue by Swakech** [AppliedEnergistics/Applied-Energistics-2#5343] opened 2021-07-20 03:50 UTC
Hey, i just faced a problem on my private mod's server with my friends that ruined all our progress, AE2 was one of the main mods on our pack, thats sad, because of that many of us lost interest to play. Everytime when someone tries to put ME Glass Cable, or any other cable he instantly crashes and thats is unreal to play without using it. I hope there is a simple solution so we can continue playing without ruining all our progress and wipe the server. 

- Environment: 
crash reports attached 
[crash-2021-07-20_06.32.35-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6845348/crash-2021-07-20_06.32.35-client.txt)

[crash-2021-07-20_06.40.25-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6845347/crash-2021-07-20_06.40.25-client.txt)

**Comment by mindforger** [comment] 2021-07-20 05:51
the first crash does have nothing to do with AE2
the second one contains optifine code in the trace, try without it please 

also on a sidenote, sad stories do not help the iessue at all, it just feels like you are blaming the devs for your experience and they owe you an appology

i will still close this issue, since 1.12 will not be supported by the devs at all, this game version is now literally ages old

i am pretty sure the issue is a mod interaction problem

1. if able to reproduce the issue with a small setup, you can try to do a binary search and remove around half the mods and retest

a) the issue persists, repeat 1.
b) the issue is gone, copy back the removed half of mods and ditch the other (besides require lirbary mods) and continue with 1.

so you can narrow down the list of mods that are causing this. even with the issue closed, you can still report back which mod interaction it is, so other people playing on 1.12 can lookup this issue!

**Closed by mindforger** 2021-07-20 05:51 UTC

**Comment by Ommina** [comment] 2021-07-20 06:17
As an aside, if you (or the affected player) are using a pirate launcher to avoid buying the game, all bets are off.

**Comment by mindforger** [comment] 2021-07-20 07:35
@Ommina what gave you the hint? (i am just curious)

**Comment by Ommina** [comment] 2021-07-26 08:32
Apologies @mindforger -- I put off replying right away, and suddenly it is six days later.

It is the presence of _tlauncher_custom_cape_skin_ that leaves me suspicious.  Coupled with the NoSuchMethodError (not exception) in the second crash report leaves me pretty convinced that something quite goofy is going on, and it certainly isn't AE2.

**Comment by mindforger** [comment] 2021-07-26 09:11
hah, nice spotting, i did miss the "t" on the tlauncher line :D, thx for the response
