### ISSUE TITLE
Modern Industrialization pipe fell into hopper attached to Inscriber, NPE on world load

### ISSUE THREAD

**Issue by WilloftheWay** [AppliedEnergistics/Applied-Energistics-2#4867] opened 2020-12-12 22:17 UTC
I was breaking and replacing some piping in my base in the most up to date version of All of Fabric 3. One of the pipes fell into the hopper that is attached to one of my inscribers, crashed with NPE. Now gives same on world load. Pastebin https://pastebin.com/EH6c1bcD

**Comment by Technici4n** [comment] 2020-12-12 22:21
Duplicate of #4840. I think I outlined a potential fix there.

**Comment by Technici4n** [comment] 2021-03-07 18:52
Should be fixed in 0.8.2-alpha.3.

**Closed by Technici4n** 2021-03-07 18:52 UTC
Labels: fabric
