### ISSUE TITLE
Viewing in REI Throwing in water(fluix dust) causes crash

### ISSUE THREAD

**Issue by Lapish** [AppliedEnergistics/Applied-Energistics-2#5947] opened 2022-01-01 20:24 UTC
### Describe the bug

When viewing in REI throwing in water(flux dust) a game crashing

### How to reproduce the bug

1. Open REI
2. Find fluix dust
3. Click on throwing in water

### Expected behavior

Game crash only client side.

### Additional details

I installed 2 mods("No null processors" and "Not enough crashes") yesterday but they don't help. 

[REI log](https://pastebin.com/tpkFQnCk)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/J67btcCh

**Comment by mindforger** [comment] 2022-01-05 10:27
because of the other report i just noticed this as well, there is not a crash report that you posted 
it is the normal log and is very hard to read and to support, there should be a crash report folder with the related crash report ... you should refrain from using mods that mess with the crash report system, the crash logs created by default are best to debug in most cases, can you please check if you can pull or recreate the crash without any erport modifying mods?

**Comment by Technici4n** [comment] 2022-04-03 15:41
Duplicate of #5966.

**Closed by Technici4n** 2022-04-03 15:41 UTC
Labels: bug
