### ISSUE TITLE
Hangs the server and the load on the CPU 200%

### ISSUE THREAD

**Issue by MySt1k** [AppliedEnergistics/Applied-Energistics-2#1559] opened 2015-06-07 17:07 UTC
KCauldron-1.7.10-1420.108
appliedenergistics2-rv2-stable-5

Starts the server in console writes these messages:

[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerISidedInventory_CableBusPart loaded successfully - 5282 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIFluidHandler_CableBusPart loaded successfully - 2442 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerITileStorageMonitorable_CableBusPart loaded successfully - 1070 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIEnergySink_CableBusPart loaded successfully - 4248 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIEnergySource_CableBusPart loaded successfully - 4184 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIEnergyHandler_CableBusPart loaded successfully - 1801 bytes
[20:03:52] [Server thread/INFO]: Force loading chunk [172, 95] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [172, 96] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [172, 97] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [173, 95] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [173, 96] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [173, 97] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [174, 95] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [174, 96] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [174, 97] in class net.minecraft.world.WorldProviderSurface

Then the server crashes and ship much CPU.

**Comment by yueh** [comment] 2015-06-07 18:32
The log does not really say anything besides something keeping chunks loaded.

We do not actively support any cauldron version, but you might have luck in reading some other issues about chunkloading like #1023

**Comment by MySt1k** [comment] 2015-06-07 18:43
It started then Crash
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
	at java.util.HashMap$KeyIterator.next(HashMap.java:874)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:271)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MySt1k** [comment] 2015-06-07 20:28
I have a suspicion integration with BuildCraft.
When I moved to BC 7.0.8 I got this error, before everything was normal.

Could you verify and update the integration of BC 7 + AE?

**Comment by thatsIch** [comment] 2015-06-07 21:33
BC 7 was just released and we did not move to it yet.

**Comment by MySt1k** [comment] 2015-06-07 21:42
Oh ... and I'm already using BC 7

**Comment by MySt1k** [comment] 2015-06-07 21:52
I found a clue

I test for Regen each region of 20k ... on coordinates figured hovering place ... and found the area ... When I regen the chat I wrote what was in hover and

http://joxi.ru/BA04joPTvKaLAy

**Comment by MySt1k** [comment] 2015-06-08 08:21
One of my players said:
"He put the wire from under ProjectRed ME Lever Emitter"
and then I started the server crash, blunt and to give a high load on the server.

**Comment by thatsIch** [comment] 2015-06-08 11:39
We have no integration with P:R

**Comment by MySt1k** [comment] 2015-06-08 11:42
The essence remains the essence ... when he put the wire ... the server crash

**Comment by thatsIch** [comment] 2015-06-08 11:44
Yea, that you have issues with mods which are not programmed for Cauldron.

We can update the BC integration, but I doubt that this will solve your issue, cause there is nothing in the crash log indicating something went wrong.

**Comment by MySt1k** [comment] 2015-06-08 11:46
I believe the problem is not BC, and ME Level Emitter with P: R

**Comment by yueh** [comment] 2015-06-08 12:14
The AE2 BC integration will be disabled when using BC7.

It should also be expected that a major version increase will have horrible effects on any related (or even unrelated at first glance) mod, especially when upgrading a production server on the same day as the official release (or even a couple of days later). Instead of first testing it and waiting on related mods to update too.

The best idea is to try it without cauldron. If it is still reproduceable, then report the crashlogs to the corresponding mods. If not it is most likely an issue with cauldron and hoping a dead software will be fixed eventually.

**Comment by sliterok** [comment] 2015-06-09 12:38
I checked and found that it was not because of the cauldron. I've repeated it in singleplayer.
When i place that wire under Level Emitter i have only 2-3 seconds before minecraft crashes.
Also, that block near the Level Emitter is important, and witout it nothing happens

Screenshot: http://i.imgur.com/1Bet6Ca.png

Im not sure if it helps, but here is crash log:


---- Minecraft Crash Report ----
// There are four lights!

Time: 09.06.15 17:37
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_147460_e(World.java:714)
	at net.minecraft.world.World.func_147459_d(World.java:653)
	at codechicken.multipart.TileMultipart.notifyPartChange(TileMultipart.scala:137)
	at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:280)
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:98)
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:599)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at mrtjp.projectred.transmission.ItemWireCommon.mrtjp$core$item$TItemSound$$super$onItemUse(items.scala:17)
	at mrtjp.core.item.TItemSound$class.onItemUse(coreitem.scala:32)
	at mrtjp.projectred.transmission.ItemWireCommon.func_77648_a(items.scala:17)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 294061008 bytes (280 MB) / 652378112 bytes (622 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 18 mods loaded, 18 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-stable-5} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-stable-5} [Applied Energistics 2] (appliedenergistics2-rv2-stable-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0.5.12} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.12-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjectE{1.7.10-PE1.5.0} [ProjectE] (ProjectE-1.7.10-PE1.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.6.2.82} [ProjectRed] (ProjectRed-1.7.10-4.6.2.82-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transmission{4.6.2.82} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transportation{4.6.2.82} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.6.2.82-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Exploration{4.6.2.82} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.6.2.82-World.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Compatibility{4.6.2.82} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.6.2.82-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Integration{4.6.2.82} [ProjectRed-Integration] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Illumination{4.6.2.82} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.6.2.82-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Expansion{4.6.2.82} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.6.2.82-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: stable rv2-stable-5 for Forge 10.13.2.1291
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['sliterok'/355, l='New World2', x=110,22, y=63,00, z=251,74]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by thatsIch** [comment] 2015-06-10 07:56
It does help, since now it is a real crash log. 

This is probably happening due to infinite loop of `notifyBlockOfNeighborChange`.

**Comment by NitroxydeX** [comment] 2015-06-10 21:45
@MySt1k your first crash with

```
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
at java.util.HashMap$KeyIterator.next(HashMap.java:874)
at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:271)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
at java.lang.Thread.run(Thread.java:745)
```
comes from Buildcraft. There will be a fix soon. BuildCraft/BuildCraft#2782

**Comment by MrTJP** [comment] 2015-06-11 17:36
The alloy wires under the torch should not be getting powered at all. The level emitter should not be powering the entire face, just the center.  Dont know how the parts are set up, but my guess is it does not implement the IMaskedRedstonePart trait.

**Comment by thatsIch** [comment] 2015-06-11 18:06
We are just using the regular `IRedstonePart`

**Comment by MrTJP** [comment] 2015-06-11 18:13
While IRedstonePart is adequate for part to normal block interactions, a multipart redstone device, such as a wire, needs to know that that face is not connectable on the outer edges.  IMaskedRedstonePart (which is a sub interface of IRedstonePart) defines one more function that is given a side and returns an integer mask.  For the Level Emitter, since it only emits from the center, would return 0x10 as the mask. (Masks are indexed by 1<<r, where r is a rotation about the face, r=4 being center)

**Comment by thatsIch** [comment] 2015-06-11 19:23
I tried to implement that as far as I understood,

is this the expected result? https://imgur.com/a/AvT8e 
basically there is no way to power the alloy wire through level emitters directly.

**Comment by MrTJP** [comment] 2015-06-11 19:27
Yes, that would be correct. A framed alloy wire can direct the signal. See if it works.

**Comment by thatsIch** [comment] 2015-06-11 19:30
Nice, works perfectly

https://imgur.com/a/dUd7o

**Comment by MrTJP** [comment] 2015-06-11 19:35
From what I've seen, the cable and emitter are the same part. If the framed wire is connecting to sides that don't have the emitter, simply return a zero mask for those sides.

**Comment by thatsIch** [comment] 2015-06-11 19:37
It is not connecting to them, so no need for that

**Closed** 2015-06-13 20:45 UTC
Labels: state-fixed, type-bug
