### ISSUE TITLE
ME system crafting does not support IC2C recipes (some of them at least)

### ISSUE THREAD

**Issue by OHOgameplay** [AppliedEnergistics/Applied-Energistics-2#7481] opened 2023-11-25 16:44 UTC
### Describe the bug

Some items in that mod needs a crafting recipe with more than 1 item in some slots. 
Example:
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/124529188/aa2998c3-3ee6-4517-98ad-03a64f49def9)

If i attempt to make a crafting pattern, it will only accept one item per slot, therefore making it impossible to autocraft items like those.
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/124529188/139ee3e0-58c9-4d3a-9b61-9bf1a2eb0574)

Even the normal manual crafting does not work in the ME crafting terminal:
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/124529188/12c34c66-4cf7-44f9-8820-727abfa8d25f)

It will still not be able to craft said item, even if i put the correct amount ot items in:
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/124529188/471e3946-1f29-408a-81eb-60175db506d6)

Therefore i am asking for this to be fixed, and allow recipes like this to be able to be crafted.

### How to reproduce the bug

Install bot mods, and try to craft one of the said recipes.

### Expected behavior

The item to be crafted.

### Additional details

Forge 43.2.0, and IC2C version 1.19.2-2.0.8.1.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

I don't think it is needed here.

**Comment by 62832** [comment] 2023-11-25 17:08
Duplicate of #7448.

**Closed by 62832** 2023-11-25 17:08 UTC
Labels: bug
