### ISSUE TITLE
Support "Nameable" interface for Pattern Provider

### ISSUE THREAD

**Issue by Zeitheron** [AppliedEnergistics/Applied-Energistics-2#6695] opened 2022-10-13 16:21 UTC
### Describe the feature

Pattern providers currently ignore custom names for blocks like hoppers/chests/etc, that implement Minecraft's Nameable interface, allowing for custom names.

### Reasons why it should be considered

Adding support for Pattern Providers to read out the custom names instead of the block's name could help organize the Pattern Access Terminal even further.

**Comment by 62832** [comment] 2022-10-13 16:26
The Pattern Provider itself can already be renamed to get what is probably the very feature you're asking of for organisation.

**Comment by Zeitheron** [comment] 2022-10-13 16:36
What if another block reports as being another block due to various reasons? For example, if there is a block that is a proxy to another block, and reports the remote block's name, then I would still have to rename the Pattern Provider to get the desired result.

**Comment by Technici4n** [comment] 2022-11-07 21:33
Duplicate of #6456, fixed by #6764.

**Closed by Technici4n** 2022-11-07 21:33 UTC
