### ISSUE TITLE
Spatial Storage does not work with Biomes o Spatial Storage does not work with Biomes o plenty world type

### ISSUE THREAD

**Issue by SavageCabbage64** [AppliedEnergistics/Applied-Energistics-2#5141] opened 2021-04-11 05:22 UTC
**Describe the issue**
Spatial Storage does not work with Biomes o plenty world type, I hit the button nothing happens, tested it on other world with same setup worked perfectly

**Environment**
windows 10
intel i7 8700
nvida 1080 ti

**Comment by SavageCabbage64** [comment] 2021-04-11 05:23
pressed enter too early Spatial Storage does not work with Biomes o plenty world type, I hit the button nothing happens, tested it on other world with same setup worked perfectly

**Comment by sagesse-cn** [comment] 2021-04-11 05:41
you can take a look at #5136 maybe fix your issue. 

when can't resoled, please change `DebugLogging` to `true` in `config/appliedenergistics2-common.toml`, and restart the game and hit the button again, upload your log after.

**Comment by shartte** [comment] 2021-04-11 09:31
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by shartte** [comment] 2021-04-11 11:27
There's an additional issue with different world-types that relates to how datapack dimensions are loaded. This might be the case here. Dimensions in 1.16.x are a veritable nightmare.

**Comment by yueh** [comment] 2021-04-11 17:39
Duplicate of #4842

**Closed by yueh** 2021-04-11 17:39 UTC
Labels: awaiting-feedback
