### ISSUE TITLE
Me Controller needs to be replaced

### ISSUE THREAD

**Issue by Janik400** [AppliedEnergistics/Applied-Energistics-2#8064] opened 2024-07-25 12:32 UTC
### Describe the bug

Hi, 
i am currently playing All of Fabric 7 Version 2.4.2 (MC Version 1.20.1).
I have a rather big ME System with subnets etc with channels set to infinite. Sometimes after just a seemingly random amount of time my me System shut of. Then i look into Power Delivery and everything but its all fine. Solar Panel with Storage from the Mod Powah. I replace Solar Panels, Storages and Cable to the Controller but nothing helps until i just break the Controller and place it again. Power Consumption should not be a Problem. (The Cables can Transfer 500FE/t). 

I hope this is how i can attach files:
[2024-07-25-7.log.gz](https://github.com/user-attachments/files/16377572/2024-07-25-7.log.gz)
[latest.log](https://github.com/user-attachments/files/16377573/latest.log)
![image](https://github.com/user-attachments/assets/95be9153-2f0e-48c1-b5e1-83b447849f85)

### How to reproduce the bug

Have Channels set to infinite and after a seemingly random amount of time the system Shuts off. Power from the Powah mod.

### Expected behavior

The System should stay on :)

### Additional details

The Server is running on a linux vm and only 2 people play here. TPS is always at 20 if that matters.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

I uploaded the logs to the bug desription, i hope thats fine as well :)

**Comment by Technici4n** [comment] 2024-08-01 22:09
Duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7819

**Closed by Technici4n** 2024-08-01 22:09 UTC
Labels: bug
