### ISSUE TITLE
Inscribers not going past 21 percent

### ISSUE THREAD

**Issue by grydian** [AppliedEnergistics/Applied-Energistics-2#2500] opened 2016-10-23 23:14 UTC
I am using the latest build for 1.10.2 downloaded it today.  I have a series of inscribers that I have tried to power just about every way I can think of.  I have used ae2 and know how it all works.  When I give it power via enderIO conduits the inscribers get to 21 percent and reset.  I also have tried powering them directly with the energy acceptor and it still did not work.  Any ideas why its not finishing the crafting process?

**Comment by shartte** [comment] 2016-10-23 23:15
Please provide the exact version of AE you are using.

**Comment by grydian** [comment] 2016-10-23 23:16
appliedenergistics2-rv4-nightly-30a978

**Comment by shartte** [comment] 2016-10-23 23:50
Have you tried using a creative energy cell? (Just to make sure)

**Comment by grydian** [comment] 2016-10-23 23:52
Yes I have.  I went into creative and tested every kind of power source I could find.  The inscribers are accepting power but resetting in the middle of crafting at 21 percent

**Comment by grydian** [comment] 2016-10-24 02:21
Ok after much experimenting I have found out that when my EnderIO item conduits are trying to put an item in the inscriber when an item is already in it resets the progress.  IF I turn off the item conduit and manually place the items into the inscriber it works.  I hope that helps.  If you need any more information let me know.  I was also using a basic item filter set for silicon/gold/cert/diamond etc.

**Comment by shartte** [comment] 2016-10-24 06:40
Yes that helps. Will check it out.

**Comment by yueh** [comment] 2016-10-24 08:18
#1563

**Comment by shartte** [comment] 2016-10-24 12:17
I want to take a look at this and see if IItemHandler is able to fix this with the simulation ability.

**Comment by yueh** [comment] 2016-10-24 12:55
Sure we can fix it with throwing more cpu power at it. But the issue is just that TE and now apparently EnderIO also do not care about an inventory being full and simply push an umodified stack into it just to save a single branch with `if(stackInSlot.stackSize < slot.maxStackSize) {}` and now force a full item comparison on us to detect any real change. Potentially even with having to revalidate the recipe each time, which is potentially not nice, should it happen many times per tick due whatever reasons.

Currently they claim it is a very marginal improvement, but they already have to compare the items, but force us to do the same thing again, because we treat any modification to the inventory as "something changed, reset". Especially as the next mod might come around and simply no longer handles the removal of an itemstack at all, because we can save performance, if we simply overwrite the current itemstack and dupe it for inserting it into their inventory.

**Comment by grydian** [comment] 2016-10-24 13:06
If guys would like I can open an issue with EnderIOs github.  I understand this is a mod interaction issue and if EnderIO could more easily fix it on their end I sure don't mind creating the issue and referencing here.  Just let me know what to do :)

**Comment by shartte** [comment] 2016-10-25 11:47
@yueh What I am thinking about is implementing IItemHandler and enforcing our own inventorySlotImit or whatever it is called in the simulation step. I have it almost implemented and will validate it today.

**Comment by yueh** [comment] 2016-10-25 12:02
If we can solve it with simulate/modulate via `IItemHandler` that is certainly an option.

But as long as someone calls `insertItem` or even the `setStackInSlot` as modulate, we should always reset the progress. Because logically it can mean remove and extract in the same tick, just that they do not remove it first, just replace it. So we should err on the side of caution here.

**Comment by shartte** [comment] 2016-10-25 22:48
@grydian Can you retry this with the latest nightly? This should be fixed now.

**Closed** 2016-10-25 22:47 UTC

**Comment by grydian** [comment] 2016-10-25 23:41
Working great now!  Thanks guys!
