### ISSUE TITLE
AE2 crashes my client when trying a private server pack

### ISSUE THREAD

**Issue by Thenexus96** [AppliedEnergistics/Applied-Energistics-2#1512] opened 2015-05-25 22:01 UTC
I have been working on a private modpack for me and my friends. The modpack itself is fine till we join the custom server I've created which crashes us out due to "Exception in thread "AE2 VersionChecker" AL lib: (EE) alc_cleanup: 1 device not closed"

I'm no code expert in anyway but I do know this shouldn't happen

(By the way I'm using a Macbook Pro to run the server and play the client side with MultiMC)

Crash log here:
https://copy.com/XJNt3NSQmg8mkQlC

**Comment by yueh** [comment] 2015-05-25 22:09
I cannot view the crashlog. But based on what you wrote in the issue, it is a duplicate of #1397.

**Closed by yueh** 2015-05-25 22:09 UTC
