### ISSUE TITLE
Item P2P not respecting inventory limits in all cases.

### ISSUE THREAD

**Issue by Jorvalt** [AppliedEnergistics/Applied-Energistics-2#1937] opened 2015-10-09 03:26 UTC
Title is pretty self-explanatory. I was trying to automate an inscriber that made processors and when using P2P tunnels, the input items would stack and the inscriber would stop working until I manually un-stacked them.

Screenshot:
![2015-10-08_22 19 02](https://cloud.githubusercontent.com/assets/5514973/10385204/4740b292-6e0b-11e5-89b3-413e2719e595.png)

**Comment by XFactHD** [comment] 2015-10-09 07:03
It seems that the Item P2P is not forwarding any information about the stacklimit of the attached inventory.

**Comment by Jorvalt** [comment] 2015-10-09 07:56
Apparently you can also do this place items in slots where they shouldn't be able to go or when they shouldn't be able to go there. For instance, you can place an engineering press in the top slot of the inscriber while a gold bar is in the middle input slot. You can also place a press in the middle input slot. Apparently it DOES still check for item types, though. I tried doing dirt and it didn't work. FYI, I also just discovered that this can be done with export buses as well.

**Comment by Jorvalt** [comment] 2015-10-09 08:08
Another note: I just attempted this using an Interface and it nets the same result. I tricked it into pushing through an inscriber press using a nonsense recipe, queued it for crafting, and voila. Silicon inscriber press in the middle input. Someone told me that this problem was supposed to have been fixed as of december of last year.

**Comment by Jorvalt** [comment] 2015-10-09 08:14
One more note: This is actually possible with any item pipe it seems. I've only tried Ender IO item conduits, but I would assume if it happens with these then it probably applies to any other item pipe. However, the stacking doesn't happen. That may be exclusive to P2P tunnels.

**Comment by mindforger** [comment] 2015-10-09 09:13
which exact version of AE are you on? the things you described all sound uncommonly familliar and should have been fixed already (at least for export busses and interfaces!!!)

**Comment by Jorvalt** [comment] 2015-10-09 22:08
I'm currently using the recommended version of the FTB infinity pack, which contains build rv2.stable.10.

**Comment by thatsIch** [comment] 2015-10-10 16:30
Can reproduce, even in latest version. I also thought this was fixed

There are actually two issues:

1. the item p2p is not respecting the machine and/or
2. the inscriber stops if overstuffed

**Comment by yueh** [comment] 2015-10-10 16:43
1) P2P do respect the machine/inventory. The problem they cycle through everything with every access. Thus checking if the item is valid for a slot and actually inserting it into a slot are using different targets (I think even slots)...

2) Is probably fine, same as when the output is stuffed. The inventory handling in minecraft is simply broken and forge also refuses to provide a sane alternative..

**Comment by thatsIch** [comment] 2015-10-10 18:42
the second case should technically not happen but apparently if you can force inject item stacks into it, it breaks. Only way to resolve it is to manually remove the stacks. Stuffing on output is automatically resolved by the inscriber and does not stuck.

**Comment by yueh** [comment] 2015-10-10 19:18
Second case is intentionally by minecraft/forge. The inventory stuff is simply designed to work like 

1. Ask if the inventory accepts an item.
2. (Optional) Ask the inventory about its potential stacksize limit.
3. Ignore everything you have done before and just stuff something completely different into the inventory.

Instead of 

1. Hand everything to the inventory, and let it return any overflow.

But forge simply does not want something like this. Because it would actually work, make it easier and prevent stupid bugs like this one.

**Comment by Jorvalt** [comment] 2015-10-10 20:03
ThatsIch, have you tried it with item conduits or an interface like I did?

**Comment by thatsIch** [comment] 2015-11-03 22:46
with P2P

**Comment by yueh** [comment] 2018-01-28 21:30
No longer relevant in 1.12.

**Closed by yueh** 2018-01-28 21:30 UTC
Labels: type-bug
