### ISSUE TITLE
1.16.5 [Immersive Engineering] Missing integration for Fluix Dust Crusher recipes.

### ISSUE THREAD

**Issue by bluev1121** [AppliedEnergistics/Applied-Energistics-2#4975] opened 2021-02-08 07:59 UTC
Can only assume this is a bug, since other crushing recipes from AE2 were ported, but the only way to produce Fluix dust is in the Quartz Grindstone atm.(havent tested with other mods)

**Comment by bluev1121** [comment] 2021-02-08 08:21
Create mod also crushes Certus Quartz and Nether Quartz into dust, but not Fluix. (millstone)

**Comment by yueh** [comment] 2021-02-08 10:35
Duplicate of #4897

**Closed by yueh** 2021-02-08 10:35 UTC

**Comment by bluev1121** [comment] 2021-02-08 11:56
Would it be possible to undo the fake player protections for the quartz grindstone? At least this way it can be automated mostly on its own. Or perhaps an attachment to the quartz grindstone that allows it to be automated for dust production at the cost of not being able to process ores? Or is the intention for users to install crafttweaker and make custom recipe scripts?

**Comment by XFactHD** [comment] 2021-02-08 12:23
You don't even need CraftTweaker for this. You can very easily build your own small datapack that contains the recipe json files. To get the format you can either search through the repository of the mod if it is open source or you open the mod jar with an archive program like WinRAR and get the files from there.
Here is an example of a crusher recipe file for IE: https://github.com/BluSunrize/ImmersiveEngineering/blob/1.16.5/src/generated/resources/data/immersiveengineering/recipes/crusher/blaze_powder.json
