### ISSUE TITLE
STORE by mod;  not SORT by mod

### ISSUE THREAD

**Issue by Waremaster** [AppliedEnergistics/Applied-Energistics-2#1795] opened 2015-08-13 00:08 UTC
I realize this request has been mentioned several times, and no real response has been given from what I could dig up here.

I do however understand the limitations of AE2 and wish to offer possible solutions for a storing method by Mod.

I have seen people ask for mod sorting through using view cells, which is reasonable.
However formatting cells to accept items from certain mods is not, since most mods these days CAN contain more than 60+ items ( which is more types than you can fit into the cells to begin with )

However lets say you have a Sub-network, and you have a drive filled with cells on that sub-network. Now we can look at storing items into that Sub-network through the use of a bi-directional interface/storage bus configuration where you COULD filter which mods enter that sub-network. I would imagine something along the lines of a new Advanced Card that you can insert into storage buses or interfaces that could be configured in the Cell Workbench to add selected mods in the fashion that logistics pipes has done.

A Mod-filtered Storage Bus or Interface is the answer here, as it will not confine you to have to get around limitations of how many types of items can fit into a cell, but instead just spread them out on a drive of cells sorted from the storage bus / interface.

I only offer this solution because it has taken much thought and I would like nothing more than NOT to have to settle for a Super Soaryn Drive full of everything. This just feels cluttered and disorganized from a network engineering point of view.

**Comment by ruifung** [comment] 2015-08-13 00:54
*offtopic* I've never even heard of the term Super Soaryn Drive until now =P

Although I've come up with that concept in one of my earlier builds when I just started playing AE2, I don't really like it though, It really messes up the priorities.

**Comment by yueh** [comment] 2015-08-13 09:46
Mostly a duplicate of #1000. Just with a slightly different approach.
It is mostly a design decision and not some technical limitations.


@ruifung I still prefer the term `Soaryn Server Destroyer` for it, because it is the worst possible approach in terms of the performance impact on a server, especially as main storage network. We can easily assume `O(n)` for inserting/extracting something in/out of this storage system as well as `O(n)` for propagating the changes back to all networks in the chain. Both can be easily changed into ´O(log n)´ with a different approach, which is a huge improvement. Also easily assume a base of 7 for it, which makes it even better as it is mostly about low numbers.
Just to give some numbers. Consider a (huge) storage network formed by 49 others.
`O(n)` means updating 49 network for every single itemstack entering or leaving it.
Compared to updating 3 networks in case of `O(log n)`.
Even with a smaller network of 7 ones would result in 7 vs 2 updates.

**Comment by ruifung** [comment] 2015-08-13 10:11
Pfft. Infinite recursion storage. I just use a SAN attached to my main network for all my storage!
(That is not going to kill servers... right?)

**Comment by Waremaster** [comment] 2015-08-14 03:05
@yueh Okay, a decision not to implement this type of feature or is it planned?

**Comment by thatsIch** [comment] 2015-08-20 18:03
Lets use something like MonoDB and sharding to store the documents nearer to each other (mod-sorted)

**Comment by expl0s1ve** [comment] 2015-09-03 10:39
About that, Algorithm said that he wants us to see our MC world not as a collection of mods, but like a real world, or something like that. So the very existence of the term mod in game would kill the realism for the player, that's why he didn't add mod based storage busses and such. Although there is a mod based sorting on the interface which is weird, I don't know if Algorithm or the new guys added that.

**Closed** 2015-09-17 19:14 UTC
Labels: state-waiting
