### ISSUE TITLE
A void card for Cells

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#5000] opened 2021-02-20 13:54 UTC
The card can be added to the cell in the workbench.
After using the card, even the card is full (either "kind" or "byte"), the card can still accept new items that fits the white list, but if it cannot store the coming item, the item will disappear.

**Reasons why it should be considered**
The affect would be similar to a storage bus + storage drawer(void upgrade)
However, it would be much more convenient:
1.More "slots", more density, and more items than drawers.
2.It will give less job to the computer,
3.Also sometimes use the cell in ME-IO port, so that exceeded cobble stone will be removed from the network. (The job of: emitter, output bus, and a matter condenser

It do have positive effect, but no negative effect.
If talking about balance, then it is simply making a easy but boring work to a really easy work, which does not affect that much.

**Comment by yueh** [comment] 2021-02-20 14:18
Duplicate of #465

**Closed by yueh** 2021-02-20 14:18 UTC
