### ISSUE TITLE
Device missing channel

### ISSUE THREAD

**Issue by nlogozzo** [AppliedEnergistics/Applied-Energistics-2#3142] opened 2017-10-08 00:23 UTC
The way I connect my network is using dense smart cables so I can carry more channels and keep track of them. The amount of channels I have is 10 out of 32, but when I add a new device I get device missing channel. Why is this happening? I don't have any crossing of cables, it is just a straight line.

**Comment by fscan** [comment] 2017-10-08 02:23
Duplicate of #3134

**Closed by fscan** 2017-10-08 02:23 UTC
