### ISSUE TITLE
Import bus not respecting the storable amount when importing.

### ISSUE THREAD

**Issue by maxpoulin64** [AppliedEnergistics/Applied-Energistics-2#1892] opened 2015-09-21 23:11 UTC
(Yes, I really wrote import bus)

I made a processor setup using inscribers and storage buses, where each inscriber has a storage bus with a filter as the input, and an import bus as the output. Pretty simple. However, from time to time, it gets jammed because one of the printed circuits ends up back in the inscriber's middle slot, which shouldn't happen because the storage bus is configured to only accept the correct items (ie. silicon, gold, pure certus or diamonds) and the only other thing connected to the inscriber is an import bus.

![storage-bus](https://cloud.githubusercontent.com/assets/5481612/10007162/11944f1e-6091-11e5-927a-1dc4d9b6325d.jpg)
![bus-config](https://cloud.githubusercontent.com/assets/5481612/10007251/a19ed534-6091-11e5-8bcd-a540f118f011.png)

After further investigation, it appears that:

* The last inscriber on the line (the one that assembles printed circuits into processors) needs to be running for the issue to present itself.
* Removing the storage buses on the first 4 inscribers doesn't make the issue go away.
* Adding a controller and making it all one network also fixes the issue.

I suspect the import bus pulls the items from the inscriber, tries to put it into the other network through the storage bus + interface combo, fails to do so because, and then tries to push it back into the inscriber. Since the sides of the inscriber puts items in the middle slot and not the output slot, the printed circuit ends back in the middle slot instead of the output slot where it comes from. Additionally, if there's items in the middle slot, the printed circuit is destroyed and lost in the process.

Happens in both rv2.stable build 10 and rv3.alpha build 6 downloaded less than an hour ago. AE is the only mod loaded, using the latest recommended forge (10.13.4.1448). Reproduced both in single player and multiplayer.

Video (on server): http://d.max-p.me/temp/irc/ftb/inscriber.mp4
Video (import bus alone): http://d.max-p.me/temp/irc/ftb/inscriber-2.mp4
World save exposing the issue: http://d.max-p.me/temp/irc/ftb/Inscriber.zip

**Comment by yueh** [comment] 2015-09-22 11:11
Import buses currently do not respect what amount is actually storable inside the network before extracting something and try to put these items back into the inventory they extracted it from.

If this is inventory is somehow restricted in what they accept (say invalid input), it will simply fail to do so.
In case of chests and similar things this works perfectly, but even furnaces could be an issue.

For your usecase the best option to prevent it for now is simply do not use acceleration cards, they will not even provide any speedup in your setup or give it a location to store any overflow.

**Comment by yueh** [comment] 2015-09-22 14:03
Actually even two bugs.
The import bus not testing how much it can actually import and prioritized inventories (for example storage buses with a whitelist) were traversed twice as potential storage location.

I would say it is even a duplicate of #1507.
A great example how a good issue description makes the difference between fixing it in like an hour vs. dismissing it as an user error.

Thanks a lot for it.

**Closed** 2015-09-23 13:28 UTC
Labels: state-fixed, type-bug
