### ISSUE TITLE
Fabric cables and facades lose textures

### ISSUE THREAD

**Issue by Phoupraw** [AppliedEnergistics/Applied-Energistics-2#5185] opened 2021-04-29 05:16 UTC
Version: 8.2.0-alpha.3 [FABRIC]
![2021-04-29_13 08 54](https://user-images.githubusercontent.com/50520903/116504956-2f0c1000-a8ec-11eb-8f03-6c349c7dec27.png)
So far I've found:
 - covered_cable
 - glass_cable
 - covered_dense_cable
 - smart_dense_cable
 - quartz_fiber
 - toggle_bus
 - inverted_toggle_bus
 - cable_anchor

Their items are normal. Only blocks are abnormal.
Besides, all facade items lose textures.
The log is below:
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6396433/latest.log)

**Comment by yueh** [comment] 2021-04-29 05:34
Duplicate of #4760

**Closed by yueh** 2021-04-29 05:34 UTC
