### ISSUE TITLE
Unable to clear contents of spatial storage cell

### ISSUE THREAD

**Issue by themechman** [AppliedEnergistics/Applied-Energistics-2#1897] opened 2015-09-23 02:58 UTC
After importing and then exporting the contents of a 16x16x16 cell, I am unable to re-use the storage cell a second time.
I can dismantle the pylons, move them and put them back, same arrangement and it will not place or capture anything. I have to make a new cell to capture anything new.

**Comment by yueh** [comment] 2015-09-23 11:41
Are you sure it is not a duplicate of #1674?

**Comment by themechman** [comment] 2015-09-24 03:35
Negative. Im afraid it is not. I deploy without issue. The contents are not removed from the cell.

I am going to test in creative single to see if this is repeatable.

**Comment by themechman** [comment] 2015-09-24 23:22
![2015-09-24_19 19 27](https://cloud.githubusercontent.com/assets/2990361/10089402/4288e41a-62f1-11e5-9af6-f29323cda512.png)

For example, the contents of that cell have already been deployed. Its very much empty. But when I moved the pylons to a new area to transport, and attempted to import; it failed. The pylon area was different (Larger) than those dimensions when I went to use it.

**Comment by yueh** [comment] 2015-09-25 10:35
Not sure what your issue is, as you just describe how spatialio is actually working.

**Comment by XFactHD** [comment] 2015-09-25 10:49
I think what he wants to say is that for example if you store a 13*13*13 area in a 16*16*16 storage cell you cannot use it anymore to store a room of another size after emptying the cell out. This would mean that some NBT data is not removed after deploying the cell contents (the same thing that happened with the item storage cells when completely emptying them out.

**Comment by themechman** [comment] 2015-09-25 14:12
Yes! Thats the phrase i was looking for. NBT data.

Its like the cell becomes write protected from further changes.

**Comment by thatsIch** [comment] 2015-09-25 19:21
the sio cells are directly linked to the dimension. You can not re-use them for a new dimension.

**Comment by themechman** [comment] 2015-09-25 23:21
Odd. As last time I used spatial pylons, cells were cleared out.

So what you're saying thatsIch, is that unless I make the pylons those EXACT dimensions, that cell is completely worthless?

**Comment by thatsIch** [comment] 2015-09-27 09:59
we have not touched SIO in about 2 years (intentionally). If you find the version which did make this, we can look up the changes and see how to revert it.

**Comment by mindforger** [comment] 2015-09-28 13:48
@themechman the moment you load a SIO Cell once, it copies the actual content and moves everythign to a fresh dimension! every subsequent access to the cell is only a swapping operation of the content inside your pylons and the created dimension, but only when exact the same size AND ORIENTATION! (sry  for caps just to make it more clear)
you can also enter this dimension while standing inside the pylons while activating FYI ... but be aware you are stuck there until someone reloads the cell

**Comment by thatsIch** [comment] 2015-09-29 10:42
@mindforger  you can use double star to make something bold like **this** so in text it looks like * * text * * (without the spaces)

**Closed** 2015-09-29 10:42 UTC
Labels: state-waiting

**Comment by themechman** [comment] 2015-09-29 10:54
Will murdering the dimension allow the cell's reuse?

**Comment by thatsIch** [comment] 2015-09-30 12:34
define murdering. You can manually delete it in your save game, this should free up the dimension storage. Also remove the ID entry in the settings, this will free up the ID. There should be probably some way to delete dimensions.. like stated in https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/17
