### ISSUE TITLE
Clicking on "Change Priority" Button crashes the game.

### ISSUE THREAD

**Issue by LTNightshade** [AppliedEnergistics/Applied-Energistics-2#4500] opened 2020-07-25 21:26 UTC
Clicking on "Change Priority" Button crashes the game.

**Describe the bug**
Clicking on "Change Priority" Button in Storage Bus or ME DRive crashes the game.

**To Reproduce**
Click on "Change Priority" Button

**Expected behavior**
Gui changes to Priority Change Gui.

**Additional context**
Crash Report:
https://gist.github.com/LTNightshade/97f1d29216b16ec12d0f79cc2b737ca3

**Environment**
java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

- Environment: 
Mod-Pack Enigmatica 5 + Forge Upüdate to forge-31.2.31 + added AE2 V7.0.0 Alpha 8

**Comment by yueh** [comment] 2020-07-25 21:29
Duplicate of #4490

**Closed by yueh** 2020-07-25 21:29 UTC
