### ISSUE TITLE
AE2 Seeds Problem with GregTech

### ISSUE THREAD

**Issue by lordjoda** [AppliedEnergistics/Applied-Energistics-2#1718] opened 2015-07-17 16:53 UTC
I already posted the issue at Blood-Asp/GT5-Unofficial#91 but since it seems GregTech is not directly involved in it, I want to mention it here again:
When crafting Fluix or Netherquarz seeds they are displayed and recognized as a different item then the crafting logic expects and therefore the autocrafting logic breaks. Tested with only ae2-rv2-stable9 and gt-5.08.24 and IC2-2.2.746 and default configs.
As seen in the other issue thread, the crafting recipe doesn't have a nbt tag "progress" but for whatever reason the crafted item has (immediately). Certus Quarz Seeds apparently don't have this issue. 
If I can provide further Information please let me know!
![ae2bug](https://cloud.githubusercontent.com/assets/1130533/8752530/e1e6d008-2cb4-11e5-9604-b5236e5ca88a.png)

**Comment by yueh** [comment] 2015-07-17 17:36
If I recall correctly, does GT not replace these and the certus ore with its own version?

**Comment by lordjoda** [comment] 2015-07-17 17:39
No the seeds are not replaced. The only "problem" really is the nbt tag

**Comment by yueh** [comment] 2015-07-17 17:59
Both spawned through creative and crafted ones have a NBT tag, when I try to reproduce it.

**Comment by lordjoda** [comment] 2015-07-17 18:21
Well yes indeed, but in the crafting recipe (so basically what the crafting logic searches for) it is not.

**Comment by yueh** [comment] 2015-07-17 18:48
The crafting handler is resolving it including the NBT tag. So if this is missing, something is messing with the crafting handler.

**Comment by lordjoda** [comment] 2015-07-17 21:10
Hmm but from my tests its the opposite way:
Without GT:
- Crafted item has no NBT Tag
- Crafting recipe has no NBT Tag

With GT
-Crafted item has NBT Tag
-Crafting recipe has no NBT Tag

(The item on slot 1 is freshly crafted without gt and "stacks" with the recipe, the other 5 items where crafted with gt installed and do not stack with the recipe even without gt beeing present)
![nbt](https://cloud.githubusercontent.com/assets/1130533/8757217/b24daaa0-2cd8-11e5-850b-e06faf8e7936.png)

**Comment by yueh** [comment] 2015-07-17 23:30
Looks like the different seeds are handled differently, but each type is still behaves consistent.

I am currently a bit reluctant about changing it as this does not cause any issue with AE2 itself and it is a breaking change. So at least it will not be happening in rv2 anymore. We might change it with rv3, but that is really tentative as it will break existing patterns and people usually do not read the changelogs.

Also the inconsistency in their behaviour and thus breaking it, is introduced by GT.

**Comment by lordjoda** [comment] 2015-07-18 10:15
I can understand your reluctance to do it right a way. I had hoped there might be a not breaking option.

**Comment by yueh** [comment] 2015-07-18 10:17
Which for now would be to not let GT mess with it at all.

**Closed** 2015-07-25 16:29 UTC
Labels: type-enhancement
