### ISSUE TITLE
Crafting terminal - very slow to craft - locks up

### ISSUE THREAD

**Issue by Loothor** [AppliedEnergistics/Applied-Energistics-2#958] opened 2015-03-01 19:01 UTC
Hi all,

If I attempt to craft an item that takes a full crafting grid (9 coal to 1 coal block or 9 iron nuggets to 1 iron ingot) and I shift click it to get 64, the crafting terminal lags for 5-15 seconds each time. If I click multiple times, it could be minutes before I see the items appear in my inventory. I also cannot do much as if I exit the terminal, I cannot go back in until its done.

https://www.dropbox.com/s/f9kg03p2fmt2bhr/LoothorAESnapshot.nps?dl=0

**Comment by Loothor** [comment] 2015-03-04 03:40
Anything else that I can upload to help troubleshoot this issue?

**Comment by Zaflis** [comment] 2015-03-04 12:54
Where are the coal stored in, also are there storage bus's or P2P tunnels in between?

**Comment by Loothor** [comment] 2015-03-04 14:47
The items are stored on the same network in me drives.  (Lots of storage) We do have some terminals with p2p tunnels, but this happens on direct network line with a terminal as well. 

My best guess says that everytime it has to craft something it does the calculations. So when you do stacks of 64, the timing is multiplied. Again, just a guess. Hoping a guru can figure it out with the attached snapshot.

**Comment by yueh** [comment] 2015-03-04 15:04
Shift click crafting is mostly handled by vanilla. Mods like ExtraBees/ExtraTrees are know to have some pretty bad performance caused by the huge amount of oredict items they add.

But otherwise the visualvm snapshot is a duplicate of #874.

**Closed by yueh** 2015-03-04 15:04 UTC

**Comment by Loothor** [comment] 2015-03-04 16:27
Thanks yueh. Any ideas what mod of mine might be causing it? I don't have extra bees or extra trees.

**Comment by yueh** [comment] 2015-03-04 16:34
Likely mekanism as in the linked issue.

**Comment by Loothor** [comment] 2015-03-04 17:10
Hmm we do not have mekanism. I will attempt to do the same crafting in a crafting table to see if it appears to be as slow. I do know TechJar found something in there that he said didn't seem right but unfortunately I don't think the picture uploaded. I am at work atm but I can try and find it later once I am at home.

**Comment by yueh** [comment] 2015-03-08 12:58
My fault for blaming mekanism. The finnicky Java FileChooser did open the wrong nps file.
But in general it is just another duplicate of multiple other issues.
