### ISSUE TITLE
[1.12]Calculation Processor only. 

### ISSUE THREAD

**Issue by Looke116** [AppliedEnergistics/Applied-Energistics-2#3007] opened 2017-08-04 18:07 UTC
So I just changed from applied llamagistics (I don't know I saw this mode on curse) because it crashes when I try to automate crafting with Inscribers to applied energistisc 2 basically the same mod but with different names again I don't know why.

My issue is that when I try to create any processor now it becomes a calculation processor.

Version:1.12
Singleplayer

Other Mods:
ActuallyAdditions-1.12-r116
angelRingToBauble-1.12-0.3.0.46+306787e
BetterBuildersWands-1.12-0.11.1.245+69d0d70
BetterFps-1.4.6
Chameleon-1.12-4.1.3
ChanceCubes-1.12-3.0.1.199
CTM-MC1.12-0.2.0.3
cxlibrary-1.12-1.5.1
extrautils2-1.12-1.5.1
Hwyla-1.8.19-B33_1.12
InventoryTweaks-1.63+beta.107
ironchest-1.12-7.0.31.818
jei_1.12-4.7.0.67
journeymap-1.12-5.4.9
Mantle-1.12-1.3.0.15
mcjtylib-1.12-2.4.4
MoreFurnaces-1.12-1.10.1
preview-OptiFine_1.12_HD_U_C5_pre
rftools-1.12-6.12
StorageDrawers-1.12-5.2.9
TConstruct-1.12-2.7.1.9
thut_wearables-3.0.4
VeinMiner-1.12-0.38.0.633+f768836
WailaHarvestability-mc1.12-1.1.11
Wawla-1.12-2.5.239
Wawla-1.12-2.5.239

- AE2 Version: 
appliedenergistics2-rv5-alpha-1

**Comment by GuntherDW** [comment] 2017-08-04 18:15
Duplicate of #2998

**Closed by GuntherDW** 2017-08-04 18:15 UTC
