### ISSUE TITLE
AE2 causing big TPS lag

### ISSUE THREAD

**Issue by Eufranio** [AppliedEnergistics/Applied-Energistics-2#2355] opened 2016-08-21 14:37 UTC
With a server running by ~2h, the TPS decrease really fast to 8~10.
WarmRoast report:
![4fe48c1d7fe64e45919d5b1c6dfebfcb](https://cloud.githubusercontent.com/assets/17598280/17842000/b977fc06-67f4-11e6-9441-5b373f459518.png)
I'm running 1.7.10 rv3-beta.6 and Thermos with forge 1614.
A file in server folder/world/AE2/settings.cfg is really big, a .cfg with 35MB...
Opis: 
![6d85b555d5e1438581af2a402e9aee8c](https://cloud.githubusercontent.com/assets/17598280/17842004/c63c52de-67f4-11e6-9d69-b2f7be163fa5.png)
After a restart everything works fine, but after about 2h running, even without players, the server starts lagging.
Sampler Mod report: http://files.magitechserver.cf/Pessoal/lag.nps

**Comment by yueh** [comment] 2016-08-26 13:05
1) Thermos is not supported, so reports using it are pretty much invalid. So please reproduce it without Thermos. 

2) `folder/world/AE2/settings.cfg` being that large is either an indication that thermos might have corrupted the world including the ME grids somehow. You could make a backup and remove the gridstorage section (nothing else). If you just use AE and no addons this would only cause the networks to lose their stored energy (but not energy cells). With addons I cannot predict it.
They will be regenerated when necessary after their chunks are loaded. Still try it without thermos and hope that the world itself is not corrupted.

3) If Thermos is not the issue, it is a duplicate of #558

**Closed by yueh** 2016-08-26 13:05 UTC

**Comment by Eufranio** [comment] 2016-08-26 17:25
Still lagging in a test server without Thermos, the reports still same, seems this is not going to be fixed then :/
