### ISSUE TITLE
Portable Cell Dupe Bug

### ISSUE THREAD

**Issue by Focamacho** [AppliedEnergistics/Applied-Energistics-2#4090] opened 2019-07-08 03:22 UTC
**Describe the bug**

**To Reproduce**
_1._ Put items inside a portable cell.
_2._ Open and drop the cell at the same time.
_3._ Take the items from the open cell, and take the cell from the ground.
_4._ It's all, see the video for more info.

**Expected behavior**
The GUI to close immediately after the portable cell is dropped

**Additional context**
Video: https://www.youtube.com/watch?v=UIduMndUMy8

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2836

**Comment by yueh** [comment] 2019-07-10 17:35
Cannot reproduce. We also check constantly, if there still is a portable cell hold and close it when needed. So please reproduce it with AE2 alone to rule out any other mod breaking it.

**Comment by Focamacho** [comment] 2019-07-10 18:27
Forge: 14.23.5.2838
AE2: rv6-stable-6
Only Forge & AE2 installed.

I still can reproduce the bug.
It's really hard to reproduce without some lag, so I changed my render-distance to 32, to try generate some chunks and get lagged.
Video: https://www.youtube.com/watch?v=DazdvVOeS4U

**Comment by iczero** [comment] 2019-07-10 23:38
It worked for me on a server to which I had quite a bit of lag. For me, I needed to right click a slight bit before hitting Q.

**Comment by pedrotest1** [comment] 2019-07-11 21:51
Working with 50ms, you must be very fast

**Comment by Trnrr** [comment] 2019-07-16 21:29
Is there any time frame on when this will be included in a new build on curseforge or the website? I've checked but there is not one yet and this is a fairly big issue/problem.

**Closed** 2019-07-23 18:13 UTC
Labels: state-waiting
