### ISSUE TITLE
incorrectly determined the amount of fluid in the tunnel p2p

### ISSUE THREAD

**Issue by nailfor** [AppliedEnergistics/Applied-Energistics-2#2195] opened 2016-03-14 18:54 UTC
I play on a server which has mod Binnie genetics. One of the devices "polimerizer" requires two types of liquid - polymerized DNA and bacteria.
To reduce the amount of pipe I use p2p tunnels for transferring liquid DNA, I noticed that the amount of DNA required for one operation is extremely large.

It was found that the compound of the tanker - buildcraft tube - a tunnel to another tunnel whith polimerizer uses "void" DNA .
For example: filling a DNA capsule consumes more than 6 buckets of liquid DNA!

Direct connection Tanker - trumpet - polymerizer consumes only 0.250 buckets.

Tested for MC 1.7.10 and AE2 v appliedenergistics2-rv3-beta-5.jar (some v rv2)

**Comment by fscan** [comment] 2017-11-05 12:53
duplicate of #2228

**Closed by fscan** 2017-11-05 12:53 UTC
