### ISSUE TITLE
Crash on startup with AE2 alpha6 & Sponge

### ISSUE THREAD

**Issue by mkrtes** [AppliedEnergistics/Applied-Energistics-2#2638] opened 2016-11-18 20:33 UTC
#### Description
Crash on startup with AE & Sponge

#### Environment
[21:27:24] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[21:27:24] [main/INFO] [FML/]: Forge Mod Loader version 12.18.2.2123 for Minecraft 1.10.2 loading
[21:27:24] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_45, running on Linux:amd64:3.16.0-4-amd64, installed at /opt/jdk1.8.0_45/jre
[21:27:24] [main/DEBUG] [FML/]: Java classpath at launch is forge-1.10.2-12.18.2.2123-universal.jar
[21:27:24] [main/DEBUG] [FML/]: Java library path at launch is /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[21:27:24] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[21:27:24] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[21:27:25] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[21:27:25] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[21:27:25] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[21:27:25] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[21:27:25] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[21:27:25] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to /home/fdw/home/server-2596x-daerwolf/.
[21:27:25] [main/DEBUG] [FML/]: Discovering coremods
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy appliedenergistics2-rv4-alpha-6.jar
[21:27:25] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in appliedenergistics2-rv4-alpha-6.jar, it will be examined later for regular @Mod instances
[21:27:25] [main/DEBUG] [FML/]: Instantiating coremod class AppEngCore
[21:27:25] [main/DEBUG] [FML/]: The coremod appeng.transformer.AppEngCore requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[21:27:25] [main/INFO] [FML/]: [AppEng] Core Init
[21:27:25] [main/DEBUG] [FML/]: Added access transformer class appeng.transformer.asm.ASMTweaker to enqueued access transformers
[21:27:25] [main/DEBUG] [FML/]: Enqueued coremod AppEngCore
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy Bagginses-1.10.2-3.0.4g.jar
[21:27:25] [main/DEBUG] [FML/]: Not found coremod data in Bagginses-1.10.2-3.0.4g.jar
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy Baubles-1.10.2-1.3.3.jar
[21:27:25] [main/DEBUG] [FML/]: Not found coremod data in Baubles-1.10.2-1.3.3.jar
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
[21:27:25] [main/DEBUG] [FML/]: Not found coremod data in BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar
[21:27:25] [main/DEBUG] [FML/]: Not found coremod data in BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy BloodMagic-1.9.4-2.1.0-66.jar
[21:27:25] [main/DEBUG] [FML/]: Not found coremod data in BloodMagic-1.9.4-2.1.0-66.jar
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy Bookshelf-1.10.2-1.4.2.334.jar
[21:27:25] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in Bookshelf-1.10.2-1.4.2.334.jar, it will be examined later for regular @Mod instances
[21:27:25] [main/DEBUG] [FML/]: Instantiating coremod class BookshelfLoadingPlugin
[21:27:25] [main/DEBUG] [FML/]: The coremod net.darkhax.bookshelf.asm.BookshelfLoadingPlugin requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[21:27:25] [main/DEBUG] [FML/]: Enqueued coremod BookshelfLoadingPlugin
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy Botania r1.9-337.jar
[21:27:25] [main/DEBUG] [FML/]: Not found coremod data in Botania r1.9-337.jar
[21:27:25] [main/DEBUG] [FML/]: Examining for coremod candidacy BrandonsCore-1.10.2-2.1.1.61-universal.jar
[21:27:25] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in BrandonsCore-1.10.2-2.1.1.61-universal.jar, it will be examined later for regular @Mod instances
[21:27:25] [main/DEBUG] [FML/]: Instantiating coremod class DepLoader
[21:27:26] [main/WARN] [FML/]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:26] [main/DEBUG] [FML/]: Enqueued coremod DepLoader
[21:27:26] [main/DEBUG] [FML/]: Examining for coremod candidacy Chameleon-1.10-2.1.7.jar
[21:27:26] [main/DEBUG] [FML/]: Not found coremod data in Chameleon-1.10-2.1.7.jar
[21:27:26] [main/DEBUG] [FML/]: Examining for coremod candidacy Chisel-MC1.10.2-0.0.7.3.jar
[21:27:26] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in Chisel-MC1.10.2-0.0.7.3.jar, it will be examined later for regular @Mod instances
[21:27:26] [main/DEBUG] [FML/]: Instantiating coremod class ChiselCorePlugin
[21:27:26] [main/WARN] [FML/]: The coremod team.chisel.common.asm.ChiselCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:26] [main/DEBUG] [FML/]: Enqueued coremod ChiselCorePlugin
[21:27:26] [main/DEBUG] [FML/]: Examining for coremod candidacy chiselsandbits-12.7.jar
[21:27:26] [main/DEBUG] [FML/]: Not found coremod data in chiselsandbits-12.7.jar
[21:27:26] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenCore-1.10.2-2.3.5.91-universal.jar
[21:27:26] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CodeChickenCore-1.10.2-2.3.5.91-universal.jar, it will be examined later for regular @Mod instances
[21:27:26] [main/DEBUG] [FML/]: Instantiating coremod class DepLoader
[21:27:26] [main/WARN] [FML/]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:26] [main/DEBUG] [FML/]: Enqueued coremod DepLoader
[21:27:26] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenLib-1.10.2-2.4.3.124-universal.jar
[21:27:26] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CodeChickenLib-1.10.2-2.4.3.124-universal.jar, it will be examined later for regular @Mod instances
[21:27:26] [main/DEBUG] [FML/]: Instantiating coremod class CCLCorePlugin
[21:27:26] [main/WARN] [FML/]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:26] [main/DEBUG] [FML/]: Enqueued coremod CCLCorePlugin
[21:27:26] [main/DEBUG] [FML/]: Examining for coremod candidacy spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar
[21:27:26] [main/INFO] [FML/]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar
[21:27:26] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:27:26] [main/INFO] [LaunchWrapper/]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:27:26] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.6 Source=file:/home/fdw/home/server-2596x-daerwolf/mods/spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar Env=SERVER
[21:27:26] [main/DEBUG] [mixin/]: Adding new mixin transformer proxy #1
[21:27:26] [main/DEBUG] [mixin/]: Initialising Mixin Platform Manager
[21:27:26] [main/DEBUG] [mixin/]: Mixin platform: primary container is file:/home/fdw/home/server-2596x-daerwolf/mods/spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar
[21:27:26] [main/DEBUG] [mixin/]: Adding mixin platform agents for container file:/home/fdw/home/server-2596x-daerwolf/mods/spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar
[21:27:26] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentFML for file:/home/fdw/home/server-2596x-daerwolf/mods/spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar
[21:27:26] [main/DEBUG] [mixin/]: spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar has core plugin org.spongepowered.mod.SpongeCoremod. Injecting it into FML for co-initialisation:
[21:27:26] [main/DEBUG] [FML/]: Instantiating coremod class SpongeCoremod
[21:27:26] [main/DEBUG] [FML/]: The coremod org.spongepowered.mod.SpongeCoremod requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[21:27:26] [main/INFO] [mixin/]: Compatibility level set to JAVA_8
[21:27:26] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[21:27:26] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[21:27:26] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[21:27:26] [main/DEBUG] [FML/]: Added access transformer class org.spongepowered.mod.asm.transformer.SpongeAccessTransformer to enqueued access transformers
[21:27:26] [main/DEBUG] [FML/]: Enqueued coremod SpongeCoremod
[21:27:26] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentDefault for file:/home/fdw/home/server-2596x-daerwolf/mods/spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar
[21:27:26] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:27:26] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:27:26] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:27:26] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:27:26] [main/DEBUG] [FML/]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
[21:27:26] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[21:27:26] [main/DEBUG] [mixin/]: Preparing mixins for MixinEnvironment[PREINIT]
[21:27:26] [main/DEBUG] [mixin/]: Selecting config mixins.forge.preinit.json
[21:27:26] [main/DEBUG] [mixin/]: Preparing mixins.forge.preinit.json (9)
[21:27:26] [main/DEBUG] [mixin/]: Rebuilding transformer delegation list:
[21:27:26] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
[21:27:26] [main/DEBUG] [mixin/]:   Excluding: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
[21:27:26] [main/DEBUG] [mixin/]: Transformer delegation list created with 1 entries
[21:27:26] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/common/UsernameCache to metadata cache
[21:27:26] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/Loader to metadata cache
[21:27:26] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/LoadController to metadata cache
[21:27:26] [main/INFO] [mixin/]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[21:27:26] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************/
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /* Oh dear. Sponge could not apply one or more patches. A required class was loaded prematurely!                                                                              */
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /* An essential class was loaded before Sponge could patch it, this usually means                                                                                             */
[21:27:26] [main/INFO] [Sponge/]: /* that another coremod has caused the class to load prematurely.                                                                                                             */
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /*           Class Name : net.minecraftforge.fml.common.ModContainer                                                                                                          */
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /* Loaded forge classes:                                                                                                                                                      */
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.DummyModContainer                                                                                                                        */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.SeekableSource                                                                                                      */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.versioning.ArtifactVersion                                                                                                               */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.GDiffPatcher                                                                                                        */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.ModMetadata                                                                                                                              */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.PatchException                                                                                                      */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.ModContainer                                                                                                                             */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.asm.transformers.PatchingTransformer                                                                                                     */
[21:27:26] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.patcher.ClassPatchManager                                                                                                                */
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /* Technical details:                                                                                                                                                         */
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /*      Failed on class : net.minecraftforge.fml.common.ModContainer                                                                                                          */
[21:27:26] [main/INFO] [Sponge/]: /*         During phase : PREINIT                                                                                                                                             */
[21:27:26] [main/INFO] [Sponge/]: /*                Mixin : fml.common.MixinModContainer                                                                                                                        */
[21:27:26] [main/INFO] [Sponge/]: /*               Config : mixins.forge.preinit.json                                                                                                                           */
[21:27:26] [main/INFO] [Sponge/]: /*           Error Type : org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException                                                                */
[21:27:26] [main/INFO] [Sponge/]: /*            Caused by : Unknown                                                                                                                                             */
[21:27:26] [main/INFO] [Sponge/]: /*              Message : Critical problem: mixins.forge.preinit.json:fml.common.MixinModContainer target net.minecraftforge.fml.common.ModContainer was already transformed. */
[21:27:26] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[21:27:26] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************/
[21:27:26] [main/INFO] [Sponge/]: Attempting to shut down the VM cleanly
[21:27:26] [main/INFO] [FML/]: Java has been asked to exit (code -1) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:656).
[21:27:26] [main/INFO] [FML/]: This is an abortive exit and could cause world corruption or other things
[21:27:26] [main/INFO] [FML/]: Exit trace
java.lang.Throwable
	at net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:663) [FMLCommonHandler.class:?]
	at org.spongepowered.mod.mixin.handler.TerminateVM.terminate(TerminateVM.java:113) [TerminateVM.class:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.mod.mixin.handler.MixinErrorHandler.onPrepareError(MixinErrorHandler.java:186) [MixinErrorHandler.class:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$ErrorPhase$1.onError(MixinTransformer.java:90) [spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:786) [spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:746) [spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:638) [spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:569) [spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:478) [spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar:1.10.2-2123-5.1.0-BETA-1879]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:182) [spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar:1.10.2-2123-5.1.0-BETA-1879]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_45]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:131) [forge-1.10.2-12.18.2.2123-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.10.2-12.18.2.2123-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.10.2-12.18.2.2123-universal.jar:?]
[21:27:26] [main/INFO] [Sponge/]: Clean shutdown failed, forcing VM termination

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-6.jar
- Forge Version: forge-1.10.2-12.18.2.2123 (with spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar)

**Comment by Aphex124** [comment] 2016-11-18 22:26
Duplicate of #2482

**Closed** 2016-11-18 22:36 UTC
