### ISSUE TITLE
Blocks not rendering while using Chocapic13_V9 shader

### ISSUE THREAD

**Issue by KompetenzAirbag** [AppliedEnergistics/Applied-Energistics-2#5028] opened 2021-03-02 14:24 UTC
Blocks are just invisible (X-ray like, I can see caves through the block) while using Chocapic13_V9_high shader (if I disable the shader, the blocks render).
I am using the lastest version of fabric and the lastest shader version (aswell as lastest Optifine and Optifabric version).

**Comment by yueh** [comment] 2021-03-02 16:57
Duplicate of #5027

**Closed by yueh** 2021-03-02 16:57 UTC
