### ISSUE TITLE
Null Pointer Exception when generating meteorites.

### ISSUE THREAD

**Issue by talonos2** [AppliedEnergistics/Applied-Energistics-2#918] opened 2015-02-19 19:35 UTC
When I run a new world, the following stack trace appears over and over in my console:

B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.helpers.MeteoritePlacer.<init>(MeteoritePlacer.java:416)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.hooks.MeteoriteWorldGen.tryMeteorite(MeteoriteWorldGen.java:127)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.hooks.MeteoriteWorldGen.access$100(MeteoriteWorldGen.java:39)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.hooks.MeteoriteWorldGen$MeteoriteSpawn.call(MeteoriteWorldGen.java:114)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.hooks.TickHandler.processQueue(TickHandler.java:287)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.hooks.TickHandler.onTick(TickHandler.java:271)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_239_TickHandler_onTick_TickEvent.invoke(.dynamic)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[B#272]  [12:30:29] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

It lets me play, but I worry this is an indication of a large problem. User error of some kind or bug?

**Comment by yueh** [comment] 2015-02-21 12:09
This is caused by the sky stone chest, probably as you have disabled it.

This is mostly a duplicate of #675 and there is PR ready to be reviewed, which fixes it.

**Closed by yueh** 2015-02-21 12:09 UTC
