### ISSUE TITLE
PROBLEM WITH applied energistics quantum network (added pictures in comments)

### ISSUE THREAD

**Issue by DOVIS123** [AppliedEnergistics/Applied-Energistics-2#2866] opened 2017-04-11 18:11 UTC
So, when i applie in my main world where all my applied energistics things are with AE power to quantum network my ME Controllers start to freak out and dont connect . There a lot of power but they just blinking and making 1-8FPS lag in my world . The 2nd quantum network is in void world MOD: SIMPLE VOID WORLD By:Modmuss50 . And when i go there the network is working without any lag at all , and can do all the auto crafting . If i disconnect the dense cable from the quantum network in the main world everything goes back to normal , but if i connect the dense cable back to the system the blinkings starts and massive lag . If you know the solution please help . Thank you .

- Minecraft Version: 1.10.2
- AE2 Version: rv-4-alpha-11
- MOD PACK : FTB Beyond 1.5.1 (Beta)

**Comment by mindforger** [comment] 2017-04-11 21:15
do you have enough (dense) energy cells attached to your entwork? it sounds like you have a ginormous system that lacks internal capacity. .. input power is always limited to "internal capacity / tick"

**Comment by DOVIS123** [comment] 2017-04-12 10:05
I added 3 dense energy cells but it still doesnt work . Energy cells are full and me controllers emty

![2017-04-12_12 26 13](https://cloud.githubusercontent.com/assets/27300617/24951123/074c6e14-1f7c-11e7-939e-7386074d4db0.png)
![2017-04-12_12 26 15](https://cloud.githubusercontent.com/assets/27300617/24951124/074c9e5c-1f7c-11e7-9a08-2ab1284280d4.png)
![2017-04-12_12 26 31](https://cloud.githubusercontent.com/assets/27300617/24951125/074f8568-1f7c-11e7-86b6-85894ea6a462.png)
![2017-04-12_12 26 35](https://cloud.githubusercontent.com/assets/27300617/24951127/075021bc-1f7c-11e7-8f40-62f5877c75ca.png)
![2017-04-12_12 26 38](https://cloud.githubusercontent.com/assets/27300617/24951126/074f9300-1f7c-11e7-804a-ad1ad9519a19.png)
![2017-04-12_12 27 06](https://cloud.githubusercontent.com/assets/27300617/24951128/0756f406-1f7c-11e7-8f93-abf5d7792418.png)
![2017-04-12_12 27 15](https://cloud.githubusercontent.com/assets/27300617/24951130/076943f4-1f7c-11e7-86ba-80dc6491b7e2.png)
![2017-04-12_12 27 35](https://cloud.githubusercontent.com/assets/27300617/24951132/076aa550-1f7c-11e7-8f95-0d0fe8b7ee77.png)
![2017-04-12_12 27 56](https://cloud.githubusercontent.com/assets/27300617/24951131/076a2792-1f7c-11e7-949e-8b9c221cbf2c.png)

**Comment by mindforger** [comment] 2017-04-12 10:27
controllers only show an internal storage when powered from external source directly as far as i know so everything is okay with that display

can you launch a **copy** of that world without ae2stuff mod (or any additional ae2 addon mods) to confirm the issue persists? the purple wireless terminal seems not to be part on the regular ae2 mod and the problem may be caused by an addon.

**Comment by DOVIS123** [comment] 2017-04-12 11:19
I found the problem its wasnt with ae2 stuff but i was connecting power in other dimmension to the quantum network so thats why the me controllers were flashing........ but do you know any tutorial that would show how to jump start quantum network in other dimmension if something went wrong so that quantum network would go back on , on its own ?

**Comment by mindforger** [comment] 2017-04-12 13:33
I can not imagine a solution wothout another mod that checks power in an Energy cell for example to temporaily power it from a battery until the Energy cell fills up again

PS you can close this issue yourself when it is resolved, right beside the comment button

**Closed** 2017-04-12 14:44 UTC
