### ISSUE TITLE
Choose the smallest CPU that can fulfill a crafting job

### ISSUE THREAD

**Issue by infogulch** [AppliedEnergistics/Applied-Energistics-2#1188] opened 2015-04-03 18:43 UTC
When starting a crafting job manually, the network picks the biggest cpu available, even if there are smaller cpus that could handle the job.

Instead, the network should choose the smallest cpu available that can handle the job.

Here's a test case demonstrating the problem: ([full res](http://i.imgur.com/naY4Xud.png))
![demo-thumb](https://cloud.githubusercontent.com/assets/133882/6986795/7f759d24-da06-11e4-8eba-bae61c849853.png)

(See also #61)

**Comment by yueh** [comment] 2015-04-03 18:51
Mostly a duplicate of #1055.

**Closed by yueh** 2015-04-03 18:51 UTC

**Comment by infogulch** [comment] 2015-04-03 20:55
Thanks for the link, I hadn't seen that.

I still think there are a few cases where choosing a weaker CPU is *clearly* an advantage, not subject to personal preferences or intent (even in the absence of additional information).

For example:

 * Given two CPUs with the same number of co-processors, *always* choose the CPU with the smaller storage that still fits the job.

Also, I see in the other issue you thought that "there is no information available on how many assemblers are attached to the same interface". Even if this is the true we know that it can be no more than 6, therefore, it is still possible to *estimate* the maximum possible concurrency a given job can employ. Specifically: `6 * [number of crafting recipes] + [number of processing recipes]`.[1]

So, for example, lets say we want to craft planks from logs again. It's not possible to use more than 5 co-processors, so if the network is choosing between one CPU with 10 co-processors, and another CPU with 100 co-processors, we should clearly use the former CPU rather than the latter.

 * Given two otherwise equivalent CPUs that *both* have more co-processors than the job's estimated maximum concurrency, *always* choose the CPU with the fewer co-processors.

Those two rules would go a long way towards making the automatic CPU choice more reasonable.

[1]: Of course, there are several ways of making this formula more accurate at the expense of making it more complicated. But this is an upper-bound and a good starting point.

**Comment by yueh** [comment] 2015-04-03 22:17
First of all to define an important point: I do not see any point in handling crafting and processing patterns differently as it just makes it more complex and the crafting as already complex enough.

But once you take processing patterns into your calculation, the maximum is not 6 anymore.
It is actually "we do not know", so we can assume +infinity for it. Which makes the cpu with the most coprocs always the best option.

And I have not really seen a setup which was using the same amount of coprocs in different cpus with different storage sizes. It is usually the more storage, the more coprocs.

**Comment by infogulch** [comment] 2015-04-03 23:39
All I propose is two simple rules for deciding which of several suitable CPUs to use, that would make the mod more ergonomic for both new and advanced users. If my explanation is confusing (I wouldn't be surprised. :smile:), I could write up some pseudo code that does this in a few lines.

> It is actually "we do not know", so we can assume +infinity for it.

Sure, you can't tell what happens behind the interface, but it doesn't matter because it still only requires one processor which is the whole point. If you want to smelt 10 ore, it doesn't do 1 at a time, even with zero co-processors. Therefore, each processing pattern in the plan needs a maximum of 1 co-processor.

**Comment by yueh** [comment] 2015-04-03 23:53
No, an interface can (theoretically) utilize an infinite amount of coprocs and not just a single one.
Also more will have a better effect than less, therefore the largest is still the best option.

**Comment by XFactHD** [comment] 2015-04-03 23:59
I think it would be enough if the crafting operation uses the smallest cpu available in terms of crafting storage.

**Comment by infogulch** [comment] 2015-04-04 00:07
What you're saying is that if I have zero co-processors, it can only process one instance of a processing recipe at a time. 

I just tested it with my toy network from above with zero co-processors; I added a vanilla furnace with the recipe `1 iron ore  =>  1 iron ingot`, then I added a job to craft 10 ingots. If what you are saying is true, the network will wait for first ingot to return before sending out the next one.

Yet that's not at all what happens. Can you explain to me how having 10 co-processors in this situation is better than one or even none?

@XFactHD, it's a bit more complicated than that. Please see issue #1055 that yueh linked to before. I'd prefer not to get these mixed up.


@XFactHD, it's a bit more complicated than that. Please see issue #1055 that yueh linked to before. I'd prefer not to get these mixed up.

**Comment by yueh** [comment] 2015-04-04 00:10
Fairly easy. Setup different cpus with different amounts of coprocs and watch how fast they dump items into a vanilla furnace.

**Comment by rashdanml** [comment] 2015-04-04 01:01
In addition to that, if you have multiple machines connected to an Interface, having varying numbers of  co-processor will dump ore into all of the machines (at varying rates).

**Comment by infogulch** [comment] 2015-04-04 01:44
Ah, that's what I was missing. I didn't realize co-processors affected the rate that items pass through an interface for processing recipes. How much faster is it per co-processor?

In any case, we can still get an accurate estimate! Lets say each additional co-processor pushes 10 more items/tick through the interface (these are made up numbers since I don't know). If a crafting job requires 40 items for a processing recipe, just 4 co-processors can push all of them through on the first tick, and adding more doesn't help!

This would require a slight change to the formula above (I'd have to have more info before I can say exactly), but it should still be a theoretical maximum.

**Comment by yueh** [comment] 2015-04-04 11:17
I do not know the actual maximum, but it is safe to assume between 1 and 576 additional items per coproc. As we need to assume the least amount of items per tasks, this means 1 item per task for any estimation and the best possible way. Which is try to dump all items in a single tick.
So a trivial estimation for it would be 1 coproc per created item including the intermediate products.
Which finally is still "always choose the one with the most coprocs".
Otherwise it will affect more complex requests in a negative way and cause them to be potentially slower.

It really needs a fully planned crafting tree containing every step of it, calculating the best number of coprocs per step (which is `requestedItems/craftedPerPattern`) and then using the maximum of all steps as final value. Without that it is nearly impossible to make a good estimation about it. Maybe except extremely trivial request like craft 2 vanilla furnaces, but these will be done the moment you open the terminal again.

Honestly it is not feasible to put time into such a complex task, which also puts more pressure on the calculation time and can introduce more bugs. Just for a few people actually affected by that change.
But as AE2 is open source, you can always contribute and provide a PR to fix it, of course it should provide a proof for not making certain requests suddenly slower.
