### ISSUE TITLE
AE2 Quantum Network bridge losses connection after world restart

### ISSUE THREAD

**Issue by Cop4Terminator** [AppliedEnergistics/Applied-Energistics-2#6323] opened 2022-06-04 12:21 UTC
### Describe the bug

After each time i re-load the world, the quantum bridge between two dimensions losses connection. It works again if i break the smart cable and replace it back, however. 
I have FTB chunks installed, and force-loaded the area, in both dimensions. 
This is not affected by going in between dimensions, only by exiting and going back in on the world.
The particular dimension where the quantum bridge links to is from mod JAMD, which provides a mining dimension, similar to the Aroma1997s Dimensional World from older versions.

### How to reproduce the bug

1 - Set up a bridge network between two dimensions
  1a - force load both areas in main world and dimension that it's connected to
2 - Reload the world, as far I noticed, re-loading the world from main screen and completely rebooting the game causes this issue.

### Expected behavior

For the connection be be intact upon rejoining the world, when loaded chunks are forced, with any force loader including FTB chunks. (Assuming that the quantum bridge doesn't have such a loaded chunk feature already.)

### Additional details

More details such as game/loader/mod versions are present in the log below.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/43KD89z9

**Comment by Technici4n** [comment] 2022-06-05 08:17
Thanks for the detailed reproduction steps, I will have a look.

**Comment by Technici4n** [comment] 2022-06-05 08:41
I tried to reproduce this issue using an overworld/nether portal with the following mods, and I have been unable to:
![image](https://user-images.githubusercontent.com/13494793/172042500-266d8cf1-9e68-4a97-b1d8-516753fe63bf.png)

Unfortunately, as long as I can't reproduce this issue, I won't be able to fix it. Could you do more testing, and let me know:
- If it happens with only AE2 and FTB Chunks installed to check if it might be another mod.
- If the issue is specific to the mining dimension (I don't see why it would be).

**Comment by Cop4Terminator** [comment] 2022-06-05 09:09
Updating to 11.1.1 did not seem to fix this issue.
This is the setup i am using.
![2022-06-05_12 05 48](https://user-images.githubusercontent.com/26202628/172043489-cdf808fd-379e-4945-b03c-ed574f480837.png)
 Going back to your test, it is most certain that another mod might be causing this issue, just can't figure out what could it be exactly.

**Comment by Cop4Terminator** [comment] 2022-06-05 09:10
I will try to use another container rather than then shulker boxes, since those hold millions of items on their own.

**Comment by Technici4n** [comment] 2022-06-05 09:12
There's many things that could be going wrong. Could you maybe try to reproduce the issue in creative with only AE2 at least? It might be one of the other blocks.

**Comment by Cop4Terminator** [comment] 2022-06-05 09:12
Copy that. will try it on a fresh client.

**Comment by Cop4Terminator** [comment] 2022-06-05 09:58
I have just discovered a new issue. Trying to create a new quantum bridge between nether and overworld, once i connect the two to the main ME network in the overworld, everything inside of the ME would disappear. it pops back up if i break the ME controller and place it back. Items that are in the nether don't even show up.

**Comment by Cop4Terminator** [comment] 2022-06-05 10:08
previously it would work if i broke the cable, now it seems like the network completely breaks if a bridge is connected. i tested this with the exact same mods you had on your test client.
![Desktop Screenshot 2022 06 05 - 13 07 29 71](https://user-images.githubusercontent.com/26202628/172045524-ceac24f0-158e-4b98-961b-2810bd13f36d.png)
.

**Comment by Technici4n** [comment] 2022-06-05 10:20
The video is private, could you maybe make it unlisted? You can also use https://streamable.com/ if you prefer.

**Comment by Cop4Terminator** [comment] 2022-06-05 10:21
> The video is private, could you maybe make it unlisted? You can also use https://streamable.com/ if you prefer.

apologies, it was still in draft state. should now be visible.

**Comment by Cop4Terminator** [comment] 2022-06-05 10:22
I have reverted back to 11.0.0 for now, it is somewhat stable for now, except for having to break the cable after each world restart

**Comment by Technici4n** [comment] 2022-06-05 10:23
Could you provide the world download so I can be sure to test the exact same setup? Thanks!

**Comment by Cop4Terminator** [comment] 2022-06-05 10:26
> Could you provide the world download so I can be sure to test the exact same setup? Thanks!
https://drive.google.com/file/d/1HeWlT7ueAgfww8OFxwzgwE8HP_d2FS3i/view?usp=sharing

**Comment by Cop4Terminator** [comment] 2022-06-05 10:28
> > Could you provide the world download so I can be sure to test the exact same setup? Thanks!
> > https://drive.google.com/file/d/1HeWlT7ueAgfww8OFxwzgwE8HP_d2FS3i/view?usp=sharing

i have provided the whole client instead, but map can be found in the saves folder.

**Comment by Technici4n** [comment] 2022-06-05 12:44
Should I close this?

**Comment by Cop4Terminator** [comment] 2022-06-05 12:49
> Should I close this?

Feel free, since you mentioned it's being worked on.

**Comment by Technici4n** [comment] 2022-06-05 12:51
You said the connection loss was fixed, and the ME Drive issue was fixed in #6337, so closing.

**Closed by Technici4n** 2022-06-05 12:51 UTC
Labels: bug, awaiting-feedback
