### ISSUE TITLE
Server Crashes on ME Wireless Access Point place

### ISSUE THREAD

**Issue by opschnecke** [AppliedEnergistics/Applied-Energistics-2#6242] opened 2022-05-03 14:30 UTC
### Describe the bug

Hello, im running a forge server on 1.16.5 with ae2 and[ some other mods](https://www.curseforge.com/minecraft/modpacks/mechcraft-os) and im having the issue that my server crashes if I place the ME Wireless Access Point. I cant reconnect anymore and have to reset the world :( 

### How to reproduce the bug

Server on 1.16.5 with the [MechCraft - OS Modpack](https://www.curseforge.com/minecraft/modpacks/mechcraft-os) and place a ME Wireless Access Point

### Expected behavior

something is wrong ...

### Which minecraft version are you using?

1.16 - MOSTLY UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/opschnecke/cd80cac211880544406980d1b7fb26a2

**Comment by Mari023** [comment] 2022-05-03 14:37
duplicate of #6028
removing the AEInfinityBooster mod should fix it

**Comment by Technici4n** [comment] 2022-05-03 14:38
Duplicate of #6028

**Closed by Technici4n** 2022-05-03 14:38 UTC
Labels: bug
