### ISSUE TITLE
Inscriber can only make engineering processors

### ISSUE THREAD

**Issue by Ionaru** [AppliedEnergistics/Applied-Energistics-2#3003] opened 2017-08-03 21:22 UTC
#### Description
No matter which processor components I put in the inscriber, it will only give me engineering processors.
Video of issue: https://my.mixtape.moe/kadhwf.mp4

#### Environment

FTB Unstable 1.12 modpack version 1.0.7
- Minecraft Version: 1.12
- AE2 Version: rv5-alpha-1
- Forge Version: 14.21.1.2443

**Comment by GuntherDW** [comment] 2017-08-03 21:23
Duplicate of #2998

**Closed by GuntherDW** 2017-08-03 21:23 UTC
