### ISSUE TITLE
Redstone dupe bug

### ISSUE THREAD

**Issue by PrincedelaLune** [AppliedEnergistics/Applied-Energistics-2#3647] opened 2018-07-23 22:50 UTC
Dupe bug (don't know what's causing it exactly) of redstone dust

#### Description
So that is the setup : a minecraft chest, an import bus importing from the chest, some cables, an ME controller with a source of power, cables again and a formation plane. While I place a redstone dust in any slot of the chest, it takes a redstone dust from the stack but it place it un the first slot af the chest, then a redstone dust is droped but the one in the chest stay there. If i place other items (I tested a few random one and some other dust) they are dropped like they should be.

#### Environment
I'm playing an a modpack based on Direwolf20 1.12 v2.1.0 modpack wich i added some mods.
Here is the the list of changes i made on the pack :
mod added :
    -Advanced Solar Panels 4.2.0
    -AE2stuff 0.7.0.4
    -Flux Network 3.0.15-19
    -Forge Multipart 2.4.2.60
    -Ore Excavation 1.4.119
    -Sonarcore 5.0.14-12
    -Steve's Cart Reborn 2.4.21.107
    -TechReborn 2.16.0.746-universal
    -TorchMaster 1.6.4.62
    -Translocators 2.5.0.73-universal
    -Woot 1.3.0
mod updated :
    Industrial Craft² 2.8.73-ex112 => Industrial Craft² 2.8.92-ex112

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2732

**Comment by fscan** [comment] 2018-07-23 22:58
Duplicate of #3590

**Closed by fscan** 2018-07-23 22:58 UTC
