### ISSUE TITLE
Troubles with fluix cables

### ISSUE THREAD

**Issue by danzio** [AppliedEnergistics/Applied-Energistics-2#4130] opened 2019-08-24 12:41 UTC
There's severe problems with Minecraft client, when looking at/destroying fluix cables - single server is crashing.
Probably could be a bug from The One Probe, but there wasn't any bugs/crashes earlier.

Log: [2019-08-24-2.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3537182/2019-08-24-2.log.gz)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable7
- Forge Version: 14.23.5.2838

**Comment by mindforger** [comment] 2019-08-24 13:48
when it ios crashing, there shopuld be a crashlog file in the crash logs folder, please paste this log via pastebin

**Comment by yueh** [comment] 2019-08-24 14:02
Duplicate of #4054

**Closed by yueh** 2019-08-24 14:02 UTC
