### ISSUE TITLE
Many items (like facades) aren't registering with the game

### ISSUE THREAD

**Issue by issuereporter123** [AppliedEnergistics/Applied-Energistics-2#4735] opened 2020-09-15 21:35 UTC
Im using this mod with some others including JEI (that may be the source of the problem? however my other friend is having the same issues as I am) and a bunch of the items come up as pink and black squares that are unusable

**Comment by shartte** [comment] 2020-09-15 21:48
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by SimonEnyo** [comment] 2020-09-16 20:20
I have the same issue.

![2020-09-16_22 18 40](https://user-images.githubusercontent.com/71408465/93388302-cd21fd00-f86a-11ea-836c-75c6d06d586a.png)

**Comment by yueh** [comment] 2020-09-16 20:24
Duplicate of #4613

**Closed by yueh** 2020-09-16 20:24 UTC
Labels: awaiting-feedback
