### ISSUE TITLE
Items not appearing on JEI and Creative Tab

### ISSUE THREAD

**Issue by Amancio302** [AppliedEnergistics/Applied-Energistics-2#4713] opened 2020-09-09 17:07 UTC
**Describe the issue**

None of the AE2 items are appering, both on JEI and Creative tab. Facades and tools are normal. In happened after upgrading to 7.0.3;
Tested on custom modpack (52 mods) and only-AE2-modpack;
Error on both server and client;
No errors or warnings on console;
***Note:*** Items still exist, are craftable and block (like ME Drive) still work, but players have no access (except with /give command);
**Environment**

- Environment: 
Minecraft 1.15.2
Forge: 31.2.36
AE2: 7.0.3

**Comment by yueh** [comment] 2020-09-09 17:09
Duplicate of #4685

**Closed by yueh** 2020-09-09 17:09 UTC
