### ISSUE TITLE
Missing textures in 1.16.5 in Fabric

### ISSUE THREAD

**Issue by ZestyBlaze** [AppliedEnergistics/Applied-Energistics-2#5348] opened 2021-07-26 13:33 UTC
**Describe the bug**
I've got the latest version of AE2 available on Curseforge for Fabric 1.16.5 and there are a bunch of items missing their textures

**To Reproduce**
1. Create a Fabric Instance with Fabric 0.11.6 and install the [following mods](https://mystb.in/ColemanVertexMelbourne.properties)
2. Load up the pack and check the AE2 creative tab and there should be some textures missing

**Expected behavior**
Quite a few items in the mod page will be missing textures

**Additional context**
[The photo that shows the missing textures](https://imgur.com/a/tdOiLBh)

**Comment by mindforger** [comment] 2021-07-26 13:52
can you add a forced crashlog? or do a binary search to thin out that list?
sodium was known in the past to casue such issues, but since you did not list it a few more details or less mods to reproduce would be helpfull

**Comment by shartte** [comment] 2021-07-26 19:13
9 out of 10 times, this is caused by some rendering mod.

Do you have something in your logs about fabric renderer?

**Comment by Desempregago** [comment] 2021-07-27 00:23
This is related to the Spational Anchor, added in one of the latest betas
but for some reason, it's asset file isn't present in the fabric version due to the asset folder structure being different from forge

**Comment by shartte** [comment] 2021-07-27 07:24
Spatial Anchor is not supported on Fabric due to lack of chunkloading infrastructure

**Comment by Mari023** [comment] 2021-07-27 11:26
> This is related to the Spational Anchor, added in one of the latest betas
> but for some reason, it's asset file isn't present in the fabric version due to the asset folder structure being different from forge

but the spatial anchor is just one item without texture
the screenshot shows more textures missing than that

**Comment by Desempregago** [comment] 2021-07-27 19:17
> 
> 
> > This is related to the Spational Anchor, added in one of the latest betas
> > but for some reason, it's asset file isn't present in the fabric version due to the asset folder structure being different from forge
> 
> but the spatial anchor is just one item without texture
> the screenshot shows more textures missing than that

yeah, it's missing the Quartz Wall and some other items

**Comment by mindforger** [comment] 2021-07-28 05:57
anyone of you with this issue, can PLEASE add a crashlog? (hold F3+C while ingame) .... because saying "me too" is not helping at all!

**Comment by Desempregago** [comment] 2021-07-28 15:20
![image](https://user-images.githubusercontent.com/14002834/127348836-417c388c-030b-4097-b057-8477066aab74.png)
These are the missing models:

• Spatial Anchor (unimplemented)
• Sky Stone, Fluix, Certus and Quartz Walls
• Dummy Fluid Item

**Comment by shartte** [comment] 2021-07-28 15:45
Yes that might be legit a different issue. I added the walls relatively late on Forge and the datagen doesnt work on Fabric... Meaning the models are probably missing

**Comment by RyanAelen** [comment] 2021-08-16 16:09
> 
> 
> anyone of you with this issue, can PLEASE add a crashlog? (hold F3+C while ingame) .... because saying "me too" is not helping at all!
> 
> And please put it behind a pastebin link or similar!!!


Launcher Multimc
[Manually triggered debug crash](https://mystb.in/SensitiveReservationsEquation.yaml)
MC version: 1.16.5
Java: 16 and 11
Fabric loader 0.11.6
Mods:
- Fabric API (fabric-api-0.37.2+1.16)
- Applied Energistics 2 (appliedenergistics2-fabric-8.4.0-alpha.2)

![image](https://user-images.githubusercontent.com/62388903/129587017-928e2ed0-af89-460b-bda2-b1a398461a6d.png)
![image](https://user-images.githubusercontent.com/62388903/129589671-fde13274-0b0c-4856-ab35-71ebde13fbe1.png)
extra: [Exception Wall on game startup](https://mystb.in/ProgrammersFebCommit.sql)

===

Launcher Multimc
[Manually triggered debug crash](https://mystb.in/ClockTrunkCouple.yaml)
MC version: 1.16.5
Java: 16 and 11
Fabric loader 0.11.6
Mods:
- Fabric API (fabric-api-0.37.2+1.16)
- Applied Energistics 2 (appliedenergistics2-fabric-8.4.0-alpha.2)
- **Sodium** (sodium-fabric-mc1.16.3-0.1.0)

![image](https://user-images.githubusercontent.com/62388903/129590095-083ed952-16ab-4ce1-9c8b-b301619bff27.png)
![image](https://user-images.githubusercontent.com/62388903/129589893-4f7ea924-3c08-4835-b8dc-ee1adf6594a3.png)
![image](https://user-images.githubusercontent.com/62388903/129590143-6375186c-6430-44bb-a7d8-43c818cadb97.png)
extra:  [Exception Wall on game startup](https://mystb.in/BracketResetInstructions.sql)

**Comment by Kinsypoo** [comment] 2021-08-20 15:03
[crash-2021-08-20_10.59.55-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7022402/crash-2021-08-20_10.59.55-client.txt)

Here is a forced crash without sodium. Sodium exacerbates the issue causing cables, and various objects to stop having textures, but even without sodium installed there are still some, albeit less, items missing textures. I will go ahead, and check and see if the sodium devs are aware of these issues, and if not let them know, but there does seem to be something else going on here than just a conflict with sodium.

**Comment by embeddedt** [comment] 2021-08-20 15:10
@Kinsypoo Do you have Indium installed as well? Sodium by itself does not implement the Fabric rendering APIs so I believe incompatibilities with mods are expected and known already.

**Comment by Kinsypoo** [comment] 2021-08-20 15:45
@embeddedt i didn't realize that after looking into it you are right i need to install indium, and get a newer version of sodium off their github. Thanks.

**Comment by Technici4n** [comment] 2021-10-05 23:07
Fabric 1.16 is not supported anymore, this is probably fixed in 1.17.

**Closed by Technici4n** 2021-10-05 23:07 UTC
Labels: fabric
