### ISSUE TITLE
Inscriber accepts items through automation even if they can't be shift clicked in

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5434] opened 2021-09-19 23:15 UTC
**Describe the bug**
If an inscriber already has an item inside, it will still accept items which do not lead to a valid recipe

**To Reproduce**
If the inscriber already has a calculation press, a hopper into the side can still insert anything and not just pure certus quartz

**Expected behavior**
The hopper will be unable to push invalid items as it does not lead into any valid recipe

**Additional context**
(Done through hopper, also happens with any kind of item pipe)
![image](https://user-images.githubusercontent.com/19631324/133945959-6ac0ff8e-df8b-4028-b144-7eb3927c9ada.png)

**Environment**
AE2 8.4.1 from Curseforge
We're playing on [this modpack](https://github.com/ramidzkh/Cinnamon)

**Comment by yueh** [comment] 2021-09-20 07:22
Duplicate of #2008

**Closed by yueh** 2021-09-20 07:22 UTC
