### ISSUE TITLE
Crafting Recipes Not Working for certain  blocks

### ISSUE THREAD

**Issue by Cryotechnic** [AppliedEnergistics/Applied-Energistics-2#831] opened 2015-02-02 12:08 UTC
When I click, in NEI, the recipe button, on, for example, a grindstone, it wont give me the recipe, and I am not able to craft it.Please help me as fast as you can!

Thanks!
CryoTechnic

**Comment by bick88** [comment] 2015-02-02 17:29
I have the same issue with RV2 beta 8 and when i click on grindstone, for example, to give him to me in creative+ mod the game crash.
http://pastebin.com/GypkhKnH
With the beta 7 the problem disappears

**Comment by Cryotechnic** [comment] 2015-02-02 17:53
For me, I don't crash, it just doesn't show up. The item does, in NEI, but the recipe seems to be missing. I just updated to RV2 beta 8 and it works just fine.

**Comment by thatsIch** [comment] 2015-03-10 06:26
![2015-03-10_07 24 19](https://cloud.githubusercontent.com/assets/2210496/6570190/962f2968-c6f6-11e4-9e98-1fccf09e291e.png)

Works for me, cannot reproduce, sounds more like a problem of NEI, closing for now

**Closed by thatsIch** 2015-03-10 06:26 UTC
