### ISSUE TITLE
Interface blocking mode incompatible with Ender IO Alloy Smelter

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2678] opened 2016-12-03 13:45 UTC
#### Description
"do not push" mode will still push items in alloy smelters, is it the same as #681?
Should I open an issue for Ender IO?

#### Environment

- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/628886/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 7
- Forge Version: 2135

**Comment by yueh** [comment] 2016-12-03 13:46
Yes, duplicate of #681

**Closed by yueh** 2016-12-03 13:46 UTC

**Comment by Xiaminou** [comment] 2016-12-03 13:48
I just did a bit more testing and it actually does it with most mod's machines including Extra Utilities Furnace, IC² Furnace, Mekanism Energized Smelter. Is it really the same bug?
