### ISSUE TITLE
Synthetic card crash

### ISSUE THREAD

**Issue by xxlio109** [AppliedEnergistics/Applied-Energistics-2#5651] opened 2021-11-08 11:18 UTC
### Describe the bug

9.0.0-beta.1 for Fabric on Minecraft 1.17.1
Player used Synthetic card

Since the player has a lot of connected devices, he can only provide the name of the mod he is connected to [extra generators]、[deep mob learning: refabricated]、[industrial revolution]、[expanded storage]、[tech reborn]

### How to reproduce the bug

The server stopped crashing when he was not in use 

### Expected behavior

Server crashed 
https://gist.github.com/xxlio109/4f786ba249b4c254c6d6d21b2f8c9134

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/xxlio109/4f786ba249b4c254c6d6d21b2f8c9134

**Comment by Technici4n** [comment] 2021-11-08 11:31
Duplicate of #5638

**Closed by Technici4n** 2021-11-08 11:31 UTC
Labels: bug
