### ISSUE TITLE
Memory card issue with usage with torch in offhand

### ISSUE THREAD

**Issue by AzazeII** [AppliedEnergistics/Applied-Energistics-2#5332] opened 2021-07-11 21:34 UTC
**Describe the bug**

When you try to use memory card on P2P tunnel, having item in offhand causes memory card to think that machine is invalid

**To Reproduce**
1. Take memory card
2. Place any P2P tunnel (i've encountered bug with ME tunnel, so to be more specific use it)
3. Take torch in offhand
4. Click (or shift+click) on placed p2p tunnel

**Expected behavior**
I've expected memory card to read configuration from p2p tunnel (i.e. frequency), as it normally does without item in offhand

**Additional context**

**Environment**

- Minecraft 1.16.5,
-  forge version 36.1.32,
-  ae2 version 8.4.0 (md5sum f82920f237184d39d6f29760e2f8445d)  

https://pastebin.com/SXn9hJZ9

**Comment by yueh** [comment] 2021-07-12 10:49
Duplicate of #4123

**Closed by yueh** 2021-07-12 10:49 UTC
