### ISSUE TITLE
[1.16.5] Failed to save chunck server error

### ISSUE THREAD

**Issue by Alkasym** [AppliedEnergistics/Applied-Energistics-2#5081] opened 2021-03-20 14:21 UTC
Hi,

I have a Failed to save chunk server error who spam the console and finish to crash the server but without crashlog.

Logs : https://pastebin.com/PMADuNhR

-----------------------------------------------------------------------------------------------------------------------------

Forge : 36.1.1
AE 2 : 8.3.0-alpha.2

**Comment by yueh** [comment] 2021-03-20 14:39
Duplicate of #5069

**Closed by yueh** 2021-03-20 14:39 UTC
