### ISSUE TITLE
Crash when clicking "Throwing in Water" Tab in REI (Fabric 1.18)

### ISSUE THREAD

**Issue by Demsli** [AppliedEnergistics/Applied-Energistics-2#5966] opened 2022-01-05 08:15 UTC
### Describe the bug

The game crashes when checking Certus Quartz Crystal. All tabs work fine except the throwing in water one. 

### How to reproduce the bug

Use Another Quality Modpack 2 - 1.18.1. Find the item (Certus Quartz Crystal or Fluix Crystal for example), click on the last tab "Throwing in Water".

### Expected behavior

Visual of the seed dropping in water or text (in case the visuals are not implemented yet).

### Additional details

 No crashlog was created. Version of AE2: appliedenergistics2-10.0.0-beta.2.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

no Crashlog

**Comment by Technici4n** [comment] 2022-01-05 08:37
We can't do anything without the crash log or the log...

**Comment by Demsli** [comment] 2022-01-05 09:02
> We can't do anything without the crash log or the log...

[10:01:09] [Render thread/INFO]: Saved data for multiplayer-23_185_16_87_25599
[10:01:09] [Netty Client IO #2/INFO]: Left dedicated server, restoring config.
[10:01:09] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[10:01:09] [Render thread/INFO]: [STDOUT]: Finalizing world map session...
[10:01:10] [Thread-22/INFO]: [STDOUT]: World map force-cleaned!
[10:01:10] [Render thread/INFO]: [STDOUT]: World map session finalized.
[10:01:10] [Render thread/ERROR]: Unhandled game exception
net.minecraft.class_148: Rendering screen
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.14) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:884) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117) ~[?:?]
	at net.minecraft.client.MinecraftClient.reset(MinecraftClient:2235) ~[?:?]
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2204) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.cleanupBeforeMinecraft(InGameCatcher.java:54) ~[notenoughcrashes-4.1.3+1.18.1-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.handler$hji000$beforeCleanUpAfterCrash(MinecraftClient:32058) ~[?:?]
	at net.minecraft.client.MinecraftClient.cleanUpAfterCrash(MinecraftClient) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:753) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.IllegalStateException: Already building!
	at net.minecraft.client.render.BufferBuilder.begin(BufferBuilder:131) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.renderBackgroundTexture(Screen:427) ~[?:?]
	at net.minecraft.client.gui.screen.SaveLevelScreen.render(SaveLevelScreen:18) ~[?:?]
	at net.minecraft.client.render.GameRenderer.redirect$gfm000$onRenderCurrentScreen(GameRenderer:9029) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:875) ~[?:?]
	... 15 more
[10:01:10] [Render thread/INFO]: Stopping!
[10:01:10] [Render thread/INFO]: [STDOUT]: Saving config results
[10:01:10] [Render thread/INFO]: closing rrp carrier:gloves
[10:01:10] [Render thread/INFO]: closing rrp chisel:blocks
[10:01:10] [Render thread/INFO]: closing rrp modern_industrialization:general
[10:01:10] [Render thread/INFO]: closing rrp phonos:data
[10:01:10] [Render thread/INFO]: closing rrp phonos:assets
[10:01:10] [CraftPresence-ShutDown-Handler/INFO]: Shutting down CraftPresence...


Here`s my last.log file. Maybe it can help? Dont see anything about AE tho

**Comment by Demsli** [comment] 2022-01-05 09:04
Same issue as in #5947 btw

**Comment by mindforger** [comment] 2022-01-05 09:55
for future reports, there should be a crashlog folder with dedicated crash reports, the log should also contain the location of the file a little further up, those logs are way more usefull than the log in general

**Comment by Demsli** [comment] 2022-01-05 09:58
> for future reports, there should be a crashlog folder with dedicated crash reports, the log should also contain the location of the file a little further up, those logs are way more usefull than the log in general

Maybe Not Enough Crashes prevents the creation of crashlogs? I`ll try to replicate the issue with just AE and REI installed.

**Comment by mindforger** [comment] 2022-01-05 10:30
yeah please try that without not enough crashes ... your log seems to only be related to that and the other issues report seems to have an authentication issue since NEC complains about an 401 error ... this mod seems to break more than it does good

**Comment by Demsli** [comment] 2022-01-05 10:32
> 

Tried it in a small modpack - the render works and no crash at all. Tried both beta 2 and 3. Will have to continue to investigate which mod causes the render crash

**Comment by itsdinkd** [comment] 2022-01-05 11:20
Possibly roughly enough resources

**Comment by shartte** [comment] 2022-01-05 21:34
Duplicate of #5947 potentially?

That player also had roughly enough resources

**Comment by shartte** [comment] 2022-01-05 22:46
I tried with iris+indium+sodium and no crash either.

Someone else will have to track this down.

**Comment by mindforger** [comment] 2022-01-05 23:49
this is only an idea, try the modpack without kubejs ..  it is just a hunch based on gut feeling, maybe the recipe handling is borked

**Comment by Demsli** [comment] 2022-01-06 22:42
> this is only an idea, try the modpack without kubejs .. it is just a hunch based on gut feeling, maybe the recipe handling is borked
> 
> Make a world copy, this will break recipes

Deleted kubejs and its folder from the pack and created a new world. Still crashing. Has to be some conflicting render mod then?

**Comment by itsdinkd** [comment] 2022-01-09 19:26
If you all who are experiencing this issue and are not on Another Quality Modpack 2, send me your modlists and I will compare similar mods

**Comment by dotconnor** [comment] 2022-01-20 02:46
For anyone else still having troubles, I found that the BedrockWaters mod was the other mod causing conflicts.

[crash-2022-01-19_21.38.39-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7901901/crash-2022-01-19_21.38.39-client.txt)

**Comment by itsdinkd** [comment] 2022-01-20 09:28
Oh wow I unrelatedly deleted that mod in my pack yesterday lol. Good find
though

**Closed** 2022-01-20 14:50 UTC
Labels: bug

**Comment by Demsli** [comment] 2022-01-21 02:07
Updated the pack to v2.0a - the issue is gone. And Technici4n closed the issue. Nice
