### ISSUE TITLE
rv5-alpha-3 Patterns and ME Drives dissapearing.

### ISSUE THREAD

**Issue by gefailter71** [AppliedEnergistics/Applied-Energistics-2#3055] opened 2017-08-22 15:26 UTC
Server: yes
AE2 version: rv5-alpha-3
Forge version: 2459

Okay, so there will be multiple bugs in one ticket since they all seem to be somewhat related.

First, one where someone lost part of his crafting patterns when he unloaded the area by logging off
Pic: 

![](https://cdn.discordapp.com/attachments/349453066350755840/349571093675245568/Inked2017-08-22_08.07.49_LI.jpg)

Second, one where only Cables(any kind) and bus' disappeared but just after leaving the area(Still chunk-loaded by FTBU) Block Interface's/Molecular Assemblers was still there.
The same person had another issue earlier where only a certain chunk lost its AE2 parts, only Terminals, storage monitors, and cables.

If anything else is needed I will try to provide it asap.

**Comment by fscan** [comment] 2017-08-22 18:24
Duplicate of #3013

**Closed by fscan** 2017-08-22 18:24 UTC
