### ISSUE TITLE
Fluix Dust milling in other mods

### ISSUE THREAD

**Issue by Enuem** [AppliedEnergistics/Applied-Energistics-2#4978] opened 2021-02-09 18:36 UTC
**Describe the feature**

So a friend an myself play on 1.16.4 with ae2 and create. In create there is a crusher which crushes items into their dusts or nuggets. A normal certus quartz crystal can be crushed into certus dust, but the Fluix Crystal cant. There is no recipe for fluix dust in the crusher. I can only use the grinder from AE2. Maybe you can also make the fluix crystal compatible to crush or mill in other mods.

**Reasons why it should be considered**

It would be cool to have it, cause with this feature I can automate fluix dust. Things like normal certus dust are still working now, its just the fluix dust thats missing.

**Additional Context**

![image](https://user-images.githubusercontent.com/78817736/107410640-dc516200-6b0d-11eb-9283-2480f44d195f.png)
The first image is a certus quartz to certus dust with the crusher or other tools
![image](https://user-images.githubusercontent.com/78817736/107410736-fbe88a80-6b0d-11eb-9757-6354f87f61d3.png)
The second image is fluix crystal to fluix dust, but there is no alternate recipe.

**Comment by yueh** [comment] 2021-02-09 18:38
Duplicate of #4897

**Closed by yueh** 2021-02-09 18:38 UTC

**Comment by Enuem** [comment] 2021-02-09 18:40
oh sry my bad...didnt see that
