### ISSUE TITLE
Crafting CPU Broken!!

### ISSUE THREAD

**Issue by Vorador93** [AppliedEnergistics/Applied-Energistics-2#1304] opened 2015-04-22 06:38 UTC
Running beta version 28 of AE2

When I Assemble the Crafting CPU, it disapear or split out some blocks

http://imgur.com/3htFnUj
http://imgur.com/gUvyZnM

**Comment by Entoarox** [comment] 2015-04-22 14:26
Does your network have a security terminal? the above behaviour occurs if you try to modify a network you dont have permission to modify.

**Comment by Vorador93** [comment] 2015-04-22 14:33
yes i have the security terminal but, the biometric cards its completly configured

**Comment by yueh** [comment] 2015-04-22 14:36
But then it would drop the block. As this only happens when you do not have the permission.

**Comment by Entoarox** [comment] 2015-04-22 14:40
Did you recently change your name, configure the card while playing SSP offline (or online and are now playing offline) or while in LAN mode?
There are tons of possibilities, I'd start removing the terminal for a moment and see if the issue remains, if it does it is an actual bug, otherwise it is quite likely a issue with the card configuration (Note that I have noticed that in SSP the security has a slight tendency to stop working for inexplicable reasons, probably connected to offline/online)

**Comment by Vorador93** [comment] 2015-04-22 14:42
the card its configured, and i play the the game always offline and i dont open it to lan

http://imgur.com/lRUUucL

**Comment by Entoarox** [comment] 2015-04-22 14:50
@yueh, I noticed similar issues on my own SSP world, maybe build in an exception to ignore biometric cards in SSP?
Vorador, if you are playing SSP, you might simply choose not to use a biometric card at all, you do not need security in SSP i would presume, and you dont need a card to use the terminal to link a wireless.

**Comment by yueh** [comment] 2015-04-22 14:54
Could you please post the `settings.cfg` located in the `AE2` folder in your world save?

**Comment by Vorador93** [comment] 2015-04-22 14:54
ok, but i'm plaining open the world to lan once i finish the construction and this issue can be a problem

**Comment by yueh** [comment] 2015-04-22 22:44
This looks like a duplicate of #1266.

**Closed** 2015-05-03 19:50 UTC
Labels: state-waiting
