### ISSUE TITLE
Chisel 2 Masonry Rendering Facade

### ISSUE THREAD

**Issue by Keridos** [AppliedEnergistics/Applied-Energistics-2#1334] opened 2015-04-26 13:00 UTC
It looks as if the masonry from chisel gives back different textures on different y levels. The facades do not seem to do that so the edges look different and not smoothly between those 2 blocks. Maybe enable the facades to render that correct?
Using AE2-RV2-29

**Comment by yueh** [comment] 2015-04-26 13:24
Not directly a duplicate of #740, but more or less the same.
Just depending on the y level instead of adjacent blocks.

**Closed by yueh** 2015-04-26 13:24 UTC
