### ISSUE TITLE
Pattern Terminal Lag

### ISSUE THREAD

**Issue by Gowcu** [AppliedEnergistics/Applied-Energistics-2#5043] opened 2021-03-06 18:42 UTC
Using version 8.2.0-beta.3 on Explorico 1.16.5 mod pack, experiencing extreme lag whenever i am entering the pattern terminal. about 10% of the time it's severe enough that i have to restart the game.

**Comment by Met2348** [comment] 2021-03-11 14:04
Can comfirm for 8.2.0 release version

**Comment by Gowcu** [comment] 2021-03-15 00:14
8.2.0-beta.3 is the AE2 version, forge-36.0.21

It's hard to pin down the lag since the info i need to see is covered up by JEI, but it appears to be both. my RX jumps from 750-800 up to 1200-1400 and my FPS drops down to 1.

I've tried several different configurations for the pattern terminal
-attached to my main computer accessing my drives
-attached to my main computer via quartz fiber (thinking it was slowed down by the amount of items in my drives)
-not attached to my main computer at all just powered by a energy acceptor
they all cause the same lag.

**Comment by mindforger** [comment] 2021-03-15 01:01
Pictures of the setup would help, any kind of special storages attached or drives only? Enough energy cells present? (Input is limited by capacity/tick)

**Comment by Gowcu** [comment] 2021-03-15 01:29
no special storages. i may be limited on energy cells but it's not item input lag, it's game lag. I tried just making a pattern terminal computer that consisted of a pattern terminal attached to an energy acceptor and nothing else and it still caused my game to lag.

**Comment by mindforger** [comment] 2021-03-15 09:25
network rebuild due to powerloss can pack quite a punch on tickload in large network, but from what you describe it isnt big. Thanks for clarifying

**Comment by ProOrange** [comment] 2021-04-05 18:11
Faced same issue on both 8.3.0-alpha1 and 8.3.0-alpha2 on TMC Limitless 3 modpack

**Comment by ProOrange** [comment] 2021-04-05 22:56
Made few more tests and explored that when player inventory is empty lag almost unnoticeable. But once i'm fill full inventory and opened terminal client freezed for around 2 seconds. Also after 10+ minutes of playing Pattern Terminal openning may even freeze game for forever

**Comment by ProOrange** [comment] 2021-04-05 23:26
Sorry for lots of comments, but i guess i finally figured out what happens here.

Looked up through code, used some profilers (VisualVM), and got an idea. I've placed basic recipe (wood to planks) and freezes is gone! 

Seems like when we open Pattern Terminal and there's no active recipe it's trying to figure out which recipe currently setted up
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e76ca86602ac374b45328bffefd704f23396659a/src/main/java/appeng/container/implementations/PatternTermContainer.java#L172

In big modpacks there's lots of recipes and since crafting inventory is empty, it goes through every recipe in game just to check that emptiness isn't match any of recipe. 

I'm not sure how it can be fixed, but my suggestion, as a hot-fix, to not looking up for matching recipe if crafting inventory is empty. It won't help when user put some item that doesn't match for any recipe, but at least it will prevent lags when inventory is empty, which is most common case (at least for me).

P.S. I'm not into minecraft modding, and there's a possibility that i missing something important

**Comment by shartte** [comment] 2021-04-05 23:29
Yeah, that might be it. Thanks for looking at this in depth. On the crafting terminal we only do this check when the crafting grid changes. We're currently doing a larger pass over GUIs and will potentially look at doing sth similar here as well.

**Comment by Gowcu** [comment] 2021-04-06 00:20
upon further reflection, modifying the g code in the manner that i was
thinking wouldnt help in the slightest, it'd only result in the tip of the
bit grazing the top of the eventual cylinder instead of cutting deep
enough. my mistake was thinking that the g code had something of the
pattern outline in it and not the tip of the tool's path.

**Comment by yueh** [comment] 2021-04-06 05:31
@ProOrange If that is the problem, I would recommend reporting the problem to Forge. Fixing it at this level will benefit every mod out there with a similar problem. Further if an empty crafting inventory is a valid candidate for a recipe as minecraft/forge does search for it and not fast fail, then it is certainly not up to use to decide that a valid recipe is no longer a valid recipe by ignoring this case completely.

Another option could also be that some mod like crafttweaker or similar uses their own handler for crafting recipes for some cases and simply forgot to fast fail in this case. At least in the past CT did sometimes pop up in profiling with their custom handler. No idea if it is still possible and certainly not possible to make any definite statement about it without seeing a sampling snapshotbor similar.

Further we call this code only on an actual inventory change. Like once when the terminal is opened, but not continuously afterwards. So if this happens every frame, this sounds really more like some stupid mod decides to mixin into our code and break it. If so, that is something which further should be reported to the specific modpack for them to identify.

**Comment by ProOrange** [comment] 2021-04-06 07:28
@yueh yeah, i also thought about single call, but not calling every frame, but after getting bunch of new information during my explorations i completely forget about it :(  

I search throught different modpacks discord/github and found that ATM modpack reports that cause of similar behaviour was Performant mod. Will play without it and if crashes will gone - i'm going to post update here. 

Thanks guys

**Comment by shartte** [comment] 2021-04-06 07:47
@yueh I did a cursory investigation, I think we're calling it as part of "getOutput",  and as long as no output is cached, we might be calling it every frame. This might just end up being a problem of not properly caching the state "the recipe is not valid" and trying to recompute the cached output every frame.
Should actually be easy to fix if we already invalidate the cache when the crafting grid changes.

**Comment by yueh** [comment] 2021-04-06 07:55
There is only [getOutputs()](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e76ca86602ac374b45328bffefd704f23396659a/src/main/java/appeng/container/implementations/PatternTermContainer.java#L256), which is called when clicking the encode button. So as long as nothing is hammering a click on it every frame for whatever broken reason, it will not happen.

[getAndUpdateOutput()](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e76ca86602ac374b45328bffefd704f23396659a/src/main/java/appeng/container/implementations/PatternTermContainer.java#L163) is really only called on things like a slot is changed, some button presses like encode or clear, or similar. Never on a loop (outside some actively forced ones by constantly clicking buttons or someone else toggling the crafting mode serverside)

**Comment by shartte** [comment] 2021-04-06 08:14
I'll take a closer look later, should be easy to trace. If there's something else messing with the slots there's nothing we can do

**Comment by yueh** [comment] 2021-04-06 08:35
I also hooked up a breakpoint to [getAndUpdateOutput()](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e76ca86602ac374b45328bffefd704f23396659a/src/main/java/appeng/container/implementations/PatternTermContainer.java#L163) and it gets called 10 times when opening a terminal as each slot is initialised iteratively.

I guess we could eliminate one call for setting the slot for blank patterns itself and if really needed override `net.minecraft.inventory.container.Container.setAll(List<ItemStack>)`, so we can only do it once all 9 slots are done.
But that is a fixed cost for opening the terminal. Otherwise it just waits for something to happen. So whatever really.

Performant does a bunch of broken things, so I'd guess it could cause it on top of other things like potential data loss.

And just in case it comes up. Yes the crafting terminal behaves in a similar way. It will only update the cached recipe on an inventory change or performing a craft operation for some cases like someone places the correct amount of items to craft boots, a helm and legs in one go.

**Comment by ProOrange** [comment] 2021-04-06 09:59
I see you're found opportunities to improve performance, but regarding original bug:

Looks like Performant was the root of crashes, they're gone after i disabled it

**Comment by yueh** [comment] 2021-04-06 10:16
This won't increase the performance. maybe open the terminal 2 msec faster. Have fun trying to prove that with an A/B test.

**Comment by ProOrange** [comment] 2021-04-06 10:50
May be for small modpacks, but for me (300+ mods) both terminals opens for ~1-2 secs. I believe this can decrease open time to <1sec.

**Comment by Met2348** [comment] 2021-04-17 12:08
Still exists on 8.3.0-alpha3

**Comment by shartte** [comment] 2021-04-17 12:12
Didn't this turn out to be a problem with performant?

**Comment by Nidaelie** [comment] 2021-04-24 19:43
PAttern terminal crashing my client in atm6 1.6.1 with ae2 8.3.0 beta1

**Comment by shartte** [comment] 2021-04-24 21:53
I just tried this in the latest ATM6 with appliedenergistics2-8.3.0-beta.2.jar

At least in creative mode, superflat world, I don't notice _any_ performance issues with the pattern terminal.

Closing this, unless someone can tell me how to reproduce it.

**Closed by shartte** 2021-04-24 21:53 UTC

**Comment by Nidaelie** [comment] 2021-04-24 22:07
Why not testing with the repirted versions?

**Comment by DrPinguin98** [comment] 2021-05-24 07:12
Greetings,

the problem still exists in version 8.3.1. I also play in the modpack TNP Limitless 3 (version 1.10.3).The ME system is still pretty basic at the moment, but connected is 1 ME bus to a Quantum Storage Controller, a Diskdrive, a Crafting Terminal and just the Pettern Terminal. 

After joining the server you can access the terminal without any problems, but the longer you are on the server the stronger the lags become, up to the point when you open the terminal after about 10 minutes, the game simply freezes, but the sound keeps playing, so to speak, it hangs in a not displayed GUI.

**Comment by Nidaelie** [comment] 2021-05-24 07:36
Found out that just setting a simply pattern in the terminal like oak
planks the system stops scanning and stops freezing

**Comment by DrPinguin98** [comment] 2021-05-24 08:00
You mean just leave a sample pattern in the field? I do, it always has the last thing I craftet in it. Last time it was 1 iron ore to 4 iron ingots

**Comment by Nidaelie** [comment] 2021-05-24 08:07
yes, seems that the terminal starts lagging when trying to check all
recipes, leaving a simply one stops the freeze

**Comment by Crdguy** [comment] 2021-07-07 20:01
Getting this issue in ATM6, even with the terminal disconnected and it performed exactly as described by earlier replies. No fps lag with any recipe entered, but 4fps with no recipe. This happened on a server, and wasn't happening before today. I can't pin down exactly what made it happen. Since it's on a server, I asked two other people to try opening the terminal and they didn't get any lag at all. I got it with Java 8, then I switched to OpenJDK 11 and it was still prevalent.
