### ISSUE TITLE
AE2 data fixer issues with Forge Server for 1.16.1

### ISSUE THREAD

**Issue by FelixSabo** [AppliedEnergistics/Applied-Energistics-2#4588] opened 2020-08-11 10:13 UTC
**Description**
Applied-Energistics-2-Mod-1.16.1 does not work in Forge server.
Log reports "No data fixer registered for appliedenergistics2:tiny_tnt_primed"

**Log Report**
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5056303/latest.log)

**Environment**

- Brand new forge server latest release:
forge-1.16.1-32.0.108

- Latest AE2:
Applied-Energistics-2-Mod-1.16.1

(every other mod works, but AE2 crashes the server everytime it is added)

**Comment by shartte** [comment] 2020-08-11 11:33
Please append a full report.

**Comment by FelixSabo** [comment] 2020-08-11 16:56
[debug-1.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5058281/debug-1.log.gz)
[2020-08-11-1.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5058282/2020-08-11-1.log.gz)

**Comment by FelixSabo** [comment] 2020-08-11 17:05
This is the entire **Log-file** that got generated when I re-added AE2 on the server.
[2020-08-11-1.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5058309/2020-08-11-1.log.gz)

The **Debug.log** doesn't contain any mention of AE2 at all.
[debug-1.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5058318/debug-1.log.gz)

**Comment by yueh** [comment] 2020-08-11 17:44
Duplicate of #4531

**Closed by yueh** 2020-08-11 17:44 UTC
Labels: awaiting-feedback
