### ISSUE TITLE
Inscribers only accept items in the middle slot

### ISSUE THREAD

**Issue by Scoaex** [AppliedEnergistics/Applied-Energistics-2#2410] opened 2016-10-03 09:44 UTC
Inscribers only accept items in the middle slot (presses/silicon/gold...)
Your unable to put anything in the top/bottom slot. (tested over gui and hoppers/busses)

**Comment by shartte** [comment] 2016-10-03 10:00
You have not provided any version information...

**Comment by Scoaex** [comment] 2016-10-03 10:16
Oh sorry, actual 1.10 Branch

**Comment by yueh** [comment] 2016-10-03 10:17
Duplicate of #2375

**Closed by yueh** 2016-10-03 10:17 UTC
Labels: type-bug
