### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by zhourui123** [AppliedEnergistics/Applied-Energistics-2#4149] opened 2019-09-06 14:43 UTC
**Describe the bug**

le
Same question as #3800 .
You blame the problem on Sponge, but the author at #3800 didn't use sponge.
I don't know how to reproduce it, I can only ask for your help, if you must say it's sponge problem, I will post issue in the SpongeForge.

```
[18:36:22] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@479eb803:
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.remove(LinkedHashMap.java:732) ~[?:1.8.0_144]
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:199) ~[EnergyGridCache.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_256_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
```
**To Reproduce**

**Expected behavior**

**Additional context**

crash-report: https://gist.github.com/zhourui123/9b40bb7e32af0e78ee585e630a973b10
latest.log: https://gist.github.com/zhourui123/947a8c6111e9a911ed325cf7bd55aa5d

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-1.jar
- Forge Version: 1.12.2-2838
spongeforge-1.12.2-2838-7.1.7-RC3843.jar

**Comment by yueh** [comment] 2019-09-06 16:28
Duplicate of #3800

**Closed by yueh** 2019-09-06 16:28 UTC
