### ISSUE TITLE
WAILA  Support to 1.16.5 forge

### ISSUE THREAD

**Issue by litjohn50** [AppliedEnergistics/Applied-Energistics-2#5190] opened 2021-05-01 03:41 UTC
**Describe the feature**
This will allow information about the cables to be disabled in the top of the screen. Like how many channels are being used. If the P2P tunnel is connected or not.

**Reasons why it should be considered**
There is a mod called Jade that is a port of HWYLA for 1.16.5 forge, and we can not see ae2 cable information with the mod. The author has mentioned that they need ae2 to port their WAILA support from 1.12.2 to 1.16.5 in order for it to work.

**Additional Context**
Conversation with the Jade Dev: https://github.com/Snownee/Jade/issues/41

**Comment by yueh** [comment] 2021-05-01 05:49
Duplicate of #4838

**Closed by yueh** 2021-05-01 05:49 UTC

**Comment by shartte** [comment] 2021-09-25 21:03
This has now been completed, btw.
