### ISSUE TITLE
[1.10.2] Error in Sponge Envirement

### ISSUE THREAD

**Issue by mister-man** [AppliedEnergistics/Applied-Energistics-2#2589] opened 2016-11-06 15:21 UTC
Hallo together,

I tried to integrade AE2 in an modded Sponge server envirement, but it seems it doesnt work.

Forge: 12.18.2.2107
Minecraft: 1.10.2
Sponge: spongeforge-1.10.2-2107-6.0.0-BETA-1873

`
[16:16:20] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[16:16:20] [main/INFO] [FML/]: Forge Mod Loader version 12.18.2.2107 for Minecraft 1.10.2 loading
[16:16:20] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_101, running on Linux:amd64:3.19.0-30-generic, installed at /usr/lib/jvm/java-8-oracle/jre
[16:16:20] [main/DEBUG] [FML/]: Java classpath at launch is forge-1.10.2-12.18.2.2107-universal.jar
[16:16:20] [main/DEBUG] [FML/]: Java library path at launch is /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[16:16:20] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[16:16:20] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[16:16:20] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[16:16:20] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[16:16:20] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[16:16:20] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[16:16:20] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[16:16:20] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to /srv/server/minecraft/minecLobby/.
[16:16:20] [main/DEBUG] [FML/]: Discovering coremods
[16:16:20] [main/DEBUG] [FML/]: Examining for coremod candidacy AdminShop-1.10.2-1.8.2-universal.jar
[16:16:20] [main/DEBUG] [FML/]: Not found coremod data in AdminShop-1.10.2-1.8.2-universal.jar
[16:16:20] [main/DEBUG] [FML/]: Examining for coremod candidacy appliedenergistics2-rv4-alpha-4.jar
[16:16:20] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in appliedenergistics2-rv4-alpha-4.jar, it will be examined later for regular @Mod instances
[16:16:20] [main/DEBUG] [FML/]: Instantiating coremod class AppEngCore
[16:16:20] [main/DEBUG] [FML/]: The coremod appeng.transformer.AppEngCore requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[16:16:20] [main/INFO] [FML/]: [AppEng] Core Init
[16:16:20] [main/DEBUG] [FML/]: Added access transformer class appeng.transformer.asm.ASMTweaker to enqueued access transformers
[16:16:20] [main/DEBUG] [FML/]: Enqueued coremod AppEngCore
[16:16:20] [main/DEBUG] [FML/]: Examining for coremod candidacy EconomyLite-5.0.0-2.2.7.jar
[16:16:20] [main/DEBUG] [FML/]: Not found coremod data in EconomyLite-5.0.0-2.2.7.jar
[16:16:20] [main/DEBUG] [FML/]: Examining for coremod candidacy EssentialCmds-1.10.2-8.1.14-universal.jar
[16:16:20] [main/DEBUG] [FML/]: Not found coremod data in EssentialCmds-1.10.2-8.1.14-universal.jar
[16:16:20] [main/DEBUG] [FML/]: Examining for coremod candidacy industrialcraft-2-2.6.92-ex110.jar
[16:16:20] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in industrialcraft-2-2.6.92-ex110.jar, it will be examined later for regular @Mod instances
[16:16:20] [main/DEBUG] [FML/]: Instantiating coremod class IC2core
[16:16:20] [main/WARN] [FML/]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:16:22] [main/DEBUG] [FML/]: Enqueued coremod IC2core
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy jei_1.10.2-3.12.8.328.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in jei_1.10.2-3.12.8.328.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy Mantle-1.10.2-1.1.0.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in Mantle-1.10.2-1.1.0.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
[16:16:22] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar, it will be examined later for regular @Mod instances
[16:16:22] [main/DEBUG] [FML/]: Instantiating coremod class TransformerLoader
[16:16:22] [main/DEBUG] [FML/]: The coremod li.cil.oc.common.launch.TransformerLoader requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[16:16:22] [main/DEBUG] [FML/]: Enqueued coremod TransformerLoader
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy PermissionsEx-Sponge.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in PermissionsEx-Sponge.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy projectinventories-5.0.0-0.8.1.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in projectinventories-5.0.0-0.8.1.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy projectportals-5.0.0-0.13.1.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in projectportals-5.0.0-0.13.1.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy RedProtect-Sponge-6.5.1-b220.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in RedProtect-Sponge-6.5.1-b220.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar
[16:16:22] [main/INFO] [FML/]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy SpongyCord-1.1.0.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in SpongyCord-1.1.0.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy stackban-5.0.0-0.2.1.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in stackban-5.0.0-0.2.1.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy TConstruct-1.10.2-2.5.6b.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in TConstruct-1.10.2-2.5.6b.jar
[16:16:22] [main/DEBUG] [FML/]: Examining for coremod candidacy worldedit-sponge-mc1.10.2-6.1.4-SNAPSHOT-dist.jar
[16:16:22] [main/DEBUG] [FML/]: Not found coremod data in worldedit-sponge-mc1.10.2-6.1.4-SNAPSHOT-dist.jar
[16:16:22] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:16:22] [main/INFO] [LaunchWrapper/]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:16:22] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.5.17 Source=file:/srv/server/minecraft/minecLobby/mods/spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar Env=SERVER
[16:16:22] [main/DEBUG] [mixin/]: Adding new mixin transformer proxy #1
[16:16:22] [main/DEBUG] [mixin/]: Initialising Mixin Platform Manager
[16:16:22] [main/DEBUG] [mixin/]: Mixin platform: primary container is file:/srv/server/minecraft/minecLobby/mods/spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar
[16:16:22] [main/DEBUG] [mixin/]: Adding mixin platform agents for container file:/srv/server/minecraft/minecLobby/mods/spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar
[16:16:22] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentFML for file:/srv/server/minecraft/minecLobby/mods/spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar
[16:16:22] [main/DEBUG] [mixin/]: spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar has core plugin org.spongepowered.mod.SpongeCoremod. Injecting it into FML for co-initialisation:
[16:16:22] [main/DEBUG] [FML/]: Instantiating coremod class SpongeCoremod
[16:16:22] [main/DEBUG] [FML/]: The coremod org.spongepowered.mod.SpongeCoremod requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[16:16:22] [main/INFO] [mixin/]: Compatibility level set to JAVA_8
[16:16:22] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[16:16:22] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[16:16:22] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[16:16:22] [main/DEBUG] [FML/]: Added access transformer class org.spongepowered.mod.asm.transformer.SpongeAccessTransformer to enqueued access transformers
[16:16:22] [main/DEBUG] [FML/]: Enqueued coremod SpongeCoremod
[16:16:22] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentDefault for file:/srv/server/minecraft/minecLobby/mods/spongeforge-1.10.2-2107-6.0.0-BETA-1873.jar
[16:16:22] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:16:22] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:16:22] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:16:22] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:16:22] [main/DEBUG] [FML/]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
[16:16:22] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[16:16:22] [main/DEBUG] [mixin/]: Preparing mixins for MixinEnvironment[PREINIT]
[16:16:22] [main/DEBUG] [mixin/]: Selecting config mixins.forge.preinit.json
[16:16:22] [main/DEBUG] [mixin/]: Preparing mixins.forge.preinit.json (8)
[16:16:22] [main/DEBUG] [mixin/]: Rebuilding transformer delegation list:
[16:16:22] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
[16:16:22] [main/DEBUG] [mixin/]:   Excluding: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
[16:16:22] [main/DEBUG] [mixin/]: Transformer delegation list created with 1 entries
[16:16:22] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/common/UsernameCache to metadata cache
[16:16:22] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/Loader to metadata cache
[16:16:22] [main/INFO] [mixin/]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[16:16:22] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************/
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /* Oh dear. Sponge could not apply one or more patches. A required class was loaded prematurely!                                                                              */
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /* An essential class was loaded before Sponge could patch it, this usually means                                                                                             */
[16:16:22] [main/INFO] [Sponge/]: /* that another coremod has caused the class to load prematurely.                                                                                                             */
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /*           Class Name : net.minecraftforge.fml.common.ModContainer                                                                                                          */
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /* Loaded forge classes:                                                                                                                                                      */
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.DummyModContainer                                                                                                                        */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.SeekableSource                                                                                                      */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.versioning.ArtifactVersion                                                                                                               */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.GDiffPatcher                                                                                                        */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.ModMetadata                                                                                                                              */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.PatchException                                                                                                      */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.ModContainer                                                                                                                             */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.asm.transformers.PatchingTransformer                                                                                                     */
[16:16:22] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.patcher.ClassPatchManager                                                                                                                */
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /* Technical details:                                                                                                                                                         */
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /*      Failed on class : net.minecraftforge.fml.common.ModContainer                                                                                                          */
[16:16:22] [main/INFO] [Sponge/]: /*         During phase : PREINIT                                                                                                                                             */
[16:16:22] [main/INFO] [Sponge/]: /*                Mixin : fml.common.MixinModContainer                                                                                                                        */
[16:16:22] [main/INFO] [Sponge/]: /*               Config : mixins.forge.preinit.json                                                                                                                           */
[16:16:22] [main/INFO] [Sponge/]: /*           Error Type : org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException                                                                */
[16:16:22] [main/INFO] [Sponge/]: /*            Caused by : Unknown                                                                                                                                             */
[16:16:22] [main/INFO] [Sponge/]: /*              Message : Critical problem: mixins.forge.preinit.json:fml.common.MixinModContainer target net.minecraftforge.fml.common.ModContainer was already transformed. */
[16:16:22] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[16:16:22] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************/
[16:16:22] [main/INFO] [Sponge/]: Attempting to shut down the VM cleanly
[16:16:22] [main/INFO] [FML/]: Java has been asked to exit (code -1) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:656).
[16:16:22] [main/INFO] [FML/]: This is an abortive exit and could cause world corruption or other things
[16:16:22] [main/INFO] [FML/]: If this was an unexpected exit, use -Dfml.debugExit=true as a JVM argument to find out where it was called
[16:16:22] [main/INFO] [Sponge/]: Clean shutdown failed, forcing VM termination

`

Other Storage Mods like Refined Storages worked fine.

Thanks

**Comment by shartte** [comment] 2016-11-06 15:30
Duplicate of #2482

**Closed by shartte** 2016-11-06 15:30 UTC
