### ISSUE TITLE
1.16.5 support for Curseforge

### ISSUE THREAD

**Issue by whatthedrunk** [AppliedEnergistics/Applied-Energistics-2#4981] opened 2021-02-13 04:03 UTC
Everything works fine in 1.16.5 but with cursefore there always has to be issues. For some reason they need you guys to add the 1.16.5 support so we can export the new files. Thanks in advance.

**Comment by yueh** [comment] 2021-02-13 09:37
Duplicate of #4971

**Closed by yueh** 2021-02-13 09:37 UTC
