### ISSUE TITLE
[1.12.2] Ticking GridNode Crash (ImportBus)

### ISSUE THREAD

**Issue by andb-1** [AppliedEnergistics/Applied-Energistics-2#3827] opened 2018-11-17 17:42 UTC
**Describe the bug**

Just a crash, idk how to reproduce, just appears on my server.

**Additional context**
Crash: [here](https://gist.github.com/andb-1/ac7acd147b535c02ce0bd6214dad69c3)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3 
- Forge Version: 14.23.5.2768

**Comment by yueh** [comment] 2018-11-17 18:41
Duplicate of #3768

**Closed by yueh** 2018-11-17 18:41 UTC
