### ISSUE TITLE
Server and client crash appliedenergistics2-rv2-beta-7

### ISSUE THREAD

**Issue by Tsyklop** [AppliedEnergistics/Applied-Energistics-2#715] opened 2015-01-09 17:17 UTC
Server and client crash with appliedenergistics2-rv2-beta-7
Crash-report:
http://pastebin.com/Jjgh50jc

**Comment by Cisien** [comment] 2015-01-09 17:20
Please post the full crash log

**Comment by Tsyklop** [comment] 2015-01-09 17:24
http://pastebin.com/4Y4T5gb5

**Comment by Cisien** [comment] 2015-01-09 22:09
I think that log got cut off, I'm not seeing the expected details

**Comment by yueh** [comment] 2015-01-09 22:53
Duplicate of #675

**Closed by yueh** 2015-01-09 22:53 UTC
