### ISSUE TITLE
Dupe with interface

### ISSUE THREAD

**Issue by DontWorryMan** [AppliedEnergistics/Applied-Energistics-2#3673] opened 2018-08-09 19:21 UTC
#### Description
For dupe need: Two players, one ME Interface, items and wrench or pickaxe. So, place the ME Interface on a ground or cable. Than, first player need put items and reopen me interface and second player need break/wrench block. But during the dupe, both players must do both at the same time. The player that in the interface must take the object when his partner destroyed the unit. All this should be at the same time, by timer.

#### Environment
Used in MP

- Minecraft Version: All
- AE2 Version:  All
- Forge Version: Latest

**Comment by mindforger** [comment] 2018-08-09 20:37
>Minecraft Version: All
AE2 Version: All
Forge Version: Latest

Could you provide at least one single version to replicate the issue? Saying blatantly „all“ is very ignorant to the devs. I almost want to close this .... 

And the most important question here would be, what kind of Server you are running, plain forge or with sponge?

**Closed** 2018-08-09 20:48 UTC

**Comment by DontWorryMan** [comment] 2018-08-10 05:14
Mindforge: ae2-rv3 1.7.10 and ae2-rv6-1.12. Server vanilla forge.

**Comment by mindforger** [comment] 2018-08-10 05:17
thank you :)

i don't know why @yueh closed it ... may have been repaired already, so i won't reopen it and let yueh decide ;)

**Comment by DontWorryMan** [comment] 2018-08-10 05:28
Thank u, Mindforger for your answer :)

**Comment by soncemvo** [comment] 2019-08-08 13:29
dupe stil exist

**Comment by mindforger** [comment] 2019-08-08 15:10
@soncemvo 

>Could you provide at least one single version to replicate the issue? Saying blatantly „all“ is very ignorant to the devs. I almost want to close this ....

**Comment by soncemvo** [comment] 2019-08-08 15:11
> @soncemvo
> 
> > Could you provide at least one single version to replicate the issue? Saying blatantly „all“ is very ignorant to the devs. I almost want to close this ....

latest version of ae2.
Dupe woks ONLY with small ME Interface (small one wich u can place on cable)

**Comment by BOTAlex321** [comment] 2020-04-22 20:16
I was able to reproduce this in single player.

**Comment by mindforger** [comment] 2020-04-22 21:54
Did you even care to read?

**Comment by BOTAlex321** [comment] 2020-04-22 23:40
oh, did not read your message. (did not even see the date)
