### ISSUE TITLE
Inscriber is inconsistent.

### ISSUE THREAD

**Issue by Speiger** [AppliedEnergistics/Applied-Energistics-2#6648] opened 2022-10-02 02:32 UTC
### Describe the bug

When i try to insert redstone into the middle slot I can't for whatever reason.
But if I try to insert it via hopper it works fine. In fact the Hopper can have any item inserted even those that make no sense.

### How to reproduce the bug

Have a Empty inscriber or a inscriber with printed silicon and try to insert redstone into the middle slot via gui.
Or try to insert cobblestone into the center slot via hopper.

### Expected behavior

Honestly recipe lists have been invented since years ago.
And after 1.10.2 a "Valid Item for any recipe" was introduced to almost any mod that I know of.

Why does AE2 have no cache for its inscriber that fast checks if a item is valid for its slot?
Like you could simplify automation that much more.
But nope instead of having 1 hopper do it i have to have 3.
Also then I need a output hopper, and then add power, which i need to be careful about because sometimes power isn't shared through machines themselves.

I know IC2 doesn't do that too, but that mod is at least able to be automated with 2 hoppers, no matter the slot count.

### Additional details

Have a Item Set for the inscriber for each individual slot and validate if a item is actually EVER USED in that slot based on all known recipes. If not, that item isn't valid. And provide a option that all input slots are accessible from any side.

Last thing is: Please for the love of god, provide stacksize support, i am not asking 64 items, but 2 or 3... So the machine can actually run at 100% and not 25-50% or if you use 3 hopper 85% of the time...

Affects any version that has this behavior, so most likely all versions...

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

No Crash

**Comment by ramidzkh** [comment] 2022-10-02 02:35
Duplicate of #2008, although I don't think it'll be as bad on performance as yueh put it out to be

**Comment by Technici4n** [comment] 2022-10-02 15:58
The inscriber is sided by design, that's why it doesn't require any slot filtering. I'm not sure we should change that. There is always the advanced inscriber from the AE2Things mod if you want a braindead machine that will automatically filter the items instead of requiring some player configuration, but it hasn't been ported to 1.19 yet.

Increasing max stack size to 2 is something we could indeed do.

**Comment by Speiger** [comment] 2022-10-02 19:14
@Technici4n the thing i am asking. Make it consistent, don't do both at the same time.
The Gui does some filtering, while the BlockInteraction/Automation does not filter at all.

What i am asking you is to make it consistent. It isn't right now.

Also about braindead machines: There is difference between requiring like thought to setup machines, and just infuriating design.
Making all slots accessible itself or invalid item filtering do not make a machine braindead.
Now if there was a "Active Recipe Detection" I would agree, what i asking you with the invalid item filtering is that any item that isn't used in "ANY" recipe for that specific slot is banned from being inserted.
This would also reduce "Accidental Breaking" because a hopper picked up a Item that isn't valid.

you can not automatically automate any recipe with this, if you build a single use machine having 1 hopper or 3 hoppers to insert the items doesn't change anything.

All the 3 hoppers do is confuse the fuck out of any new player who doesn't know how to deal with it...
Or is rather new to modding.

**Comment by Speiger** [comment] 2022-10-31 02:32
Forgot to close

**Closed** 2022-10-31 02:32 UTC
Labels: bug
