### ISSUE TITLE
Import and Export bus to accept inverter cards

### ISSUE THREAD

**Issue by Pabsb** [AppliedEnergistics/Applied-Energistics-2#4071] opened 2019-06-20 06:35 UTC
Import and export bus to except inverter cards so that blacklisting items is possible.
**Describe the feature**

Adding in the ability to place inverter cards into the Import and Export busses and have them functional
**Reasons why it should be considered**

So that lets say in a mod pack trying to pull out of a machine that has an dual inventory like industrial foregoing with their laser base and you don't want to pull lens out when taking out the ores from the machine. Adding in the inverter card lets you pull everything out but the lens from the machine. 
**Additional Context**

**Comment by yueh** [comment] 2019-06-20 08:30
Duplicate of #147

**Closed by yueh** 2019-06-20 08:30 UTC
