### ISSUE TITLE
Filling Multiple Buckets with Liquid

### ISSUE THREAD

**Issue by salaza** [AppliedEnergistics/Applied-Energistics-2#5896] opened 2021-12-26 17:15 UTC
### Describe the bug

It's not possible to fill multiple buckets with liquid in one go from the terminal
![javaw_iBmUAj9EJy](https://user-images.githubusercontent.com/5289839/147415335-dfb5f200-9a73-4457-a2a9-bf0ca8e7d930.png)

### How to reproduce the bug

Take more than 1 bucket and try to leftclick a fluid in the terminal.

### Expected behavior

Filling all the held buckets.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/t4ebSKzi

**Comment by jackodsteel** [comment] 2021-12-27 12:12
You can't have a stack of filled buckets, so what would be the expected behaviour here?

It can't just give you a 10 stack of filled buckets, since they're not stackable.

**Comment by shartte** [comment] 2021-12-27 12:18
When you click it with >1 empty bucket in hand, it puts a filled bucket in your player inventory everytime you click until you only have 1 empty bucket in hand, then the filled bucket replaces the one you are holding.

That's how it is (or should be) on Fabric for example.

**Comment by shartte** [comment] 2021-12-28 02:29
Fixed in 10.0.0-beta.2

**Closed by shartte** 2021-12-28 02:29 UTC
Labels: bug, forge
