### ISSUE TITLE
If disable channels feature, the creative inventory in server will crash

### ISSUE THREAD

**Issue by CatMe0w** [AppliedEnergistics/Applied-Energistics-2#1245] opened 2015-04-09 10:12 UTC
If disable channels feature in config, open creative inventory IN A SERVER and turn to page of AE2 mod, the client will crash.
That's all, please fix it.Thank you.

**Comment by CatMe0w** [comment] 2015-04-09 10:17
Excuse me. I'm a chinese, so my English is not good.

**Comment by TheJulianJES** [comment] 2015-04-09 11:18
Crashlog?

**Comment by XFactHD** [comment] 2015-04-09 12:34
I think the problem is simple: When he goes to the page of the creative inventory where you find the ae2 tab, the mod tries to load a symbol for the tab of a block that doesn't exist when channels are disabled > the controller.

**Comment by thatsIch** [comment] 2015-04-09 15:16
The creative tab can handle the disabled controller just fine,
it has a priority list with like 8 entries, with stuff in it, which can not be disabled.

So without a crashlog, can just wait.

**Comment by CatMe0w** [comment] 2015-04-10 04:27
There are some SERVER log:
![1](https://cloud.githubusercontent.com/assets/7774491/7081883/e4dfca24-df7c-11e4-8121-aa9765352064.png)
![2](https://cloud.githubusercontent.com/assets/7774491/7081882/e4df36b8-df7c-11e4-8aee-c82ab613a30b.png)

**Comment by CatMe0w** [comment] 2015-04-10 04:32
There is client crashlog
Well, maybe it's of no use.
![3](https://cloud.githubusercontent.com/assets/7774491/7081941/ab04feea-df7d-11e4-8026-d208a9e72585.png)
![4](https://cloud.githubusercontent.com/assets/7774491/7081942/ab0856bc-df7d-11e4-97d7-ff4e5d042dbb.png)

**Comment by CatMe0w** [comment] 2015-04-10 04:34
But if in single player, this bug will not appear.

**Comment by thatsIch** [comment] 2015-04-10 05:08
pastebin or similar please

**Comment by thatsIch** [comment] 2015-04-10 05:09
My first guess is, you did not change the recipes when you disabled the channels, also you have to adept the recipes on both sides, not only the server.

**Comment by CatMe0w** [comment] 2015-04-10 13:17
Hmmm...That is, this bug was made by me? What should I do now?

**Comment by CatMe0w** [comment] 2015-04-10 13:21
There are 2 same issues: #896 #1136

**Comment by thatsIch** [comment] 2015-04-10 15:30
right.. forgot about that issue, 
closing this for https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1136

please follow the other issue for updates.

**Closed by thatsIch** 2015-04-10 15:30 UTC
Labels: state-waiting
