### ISSUE TITLE
Server crash when hoes enter ME system with fuzzy storage

### ISSUE THREAD

**Issue by Sleeeper** [AppliedEnergistics/Applied-Energistics-2#3853] opened 2018-12-06 19:04 UTC
**Describe the bug**

Whenever a hoe enters ME system with fuzzy storage bus (even if hoe would go to another bus and not to the one with fuzzy card), server crashes.

For some reason only hoes are the problem, either vanilla or from mods. Swords, (pick)axes, armor pieces etc. are fine.

After crash, if a ME system is chunkloaded, server will have crash loop until the bus/interface that imports a hoe is removed somehow.

**To Reproduce**

Have a storage bus with fuzzy card in system.
Use import bus or interface to let a hoe enter the system (damage value doesn't matter)

**Additional context**

made a gif when testing in SP
https://s2.gifyu.com/images/ae2_crash.gif

crash log is from singleplayer when testing, but on MP server they had same error.
https://pastebin.com/UsMRbC9i

**Environment**

- Minecraft Version: 
1.12.2

- AE2 Version: 
rv6-stable-3
playing on a server with not most recent version, but I hope it's fine because ItemList.java didn't change recently.

- Forge Version:
14.23.5.2768

Modpack: ATM3 Remix 1.0.1

**Comment by Sleeeper** [comment] 2018-12-06 19:04
After crash, if a ME system is chunkloaded, server will have crash loop until the bus/interface that imports a hoe is removed somehow.

**Comment by yueh** [comment] 2018-12-06 19:08
Duplicate of #3768

**Closed by yueh** 2018-12-06 19:08 UTC
