### ISSUE TITLE
1.16.1 appliedenergistics2-8.0.0-alpha.1.jar crashes on servers

### ISSUE THREAD

**Issue by FullMetalMaster** [AppliedEnergistics/Applied-Energistics-2#4540] opened 2020-08-02 18:57 UTC
Applied Energistics 2 (appliedenergistics2) has failed to load correctly

The mod seems to just hard crash the server on start up no crash report

Using a port forwarded forge server forge -1.16.1-32.0.88 because it is most stable using in a pack on curse forge called Ridiculous BS.

load the server start to load then crashes saying  Applied Energistics 2 (appliedenergistics2) has failed to load correctly then thats it.

No crash log but here is the log of the server. https://pastebin.com/WnpCXjGv

Running on home Pc with ryzen 5 processor and graphics card and the server having allocated 6 gigs of RAM. Thats all i really got it loads in single player just fine.

**Comment by yueh** [comment] 2020-08-02 19:02
Duplicate of #4531

**Closed by yueh** 2020-08-02 19:02 UTC
