### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by clienthax** [AppliedEnergistics/Applied-Energistics-2#4158] opened 2019-09-21 04:56 UTC
ConcurrentModificationException

**Describe the bug**

Server crash.

**To Reproduce**

Unknown

**Expected behavior**

Less crashes :)

**Additional context**

https://gist.github.com/clienthax/afe81b62b7fd28a0ed8da1a830035462

**Environment**

Mod details included on crash report

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2838

**Comment by yueh** [comment] 2019-09-21 06:46
Duplicate of #3800

**Closed by yueh** 2019-09-21 06:46 UTC

**Comment by clienthax** [comment] 2019-09-25 00:32
@yueh How would you suggest I go about finding the mod doing off thread world loading?

**Comment by Pingger** [comment] 2019-09-25 04:34
Probavly sponge is the culprit here. But I also can't rule out compact machines 3. Unfortunatly we have big issues in reproducing the issue without sponge maiking it difficult to fix something, as it looks like sponge is doing some magic to ae2, that breaks it
