### ISSUE TITLE
Grinding tin/silver/lead/copper in a quartz grindstone

### ISSUE THREAD

**Issue by pinter-gabor-at** [AppliedEnergistics/Applied-Energistics-2#5063] opened 2021-03-14 07:54 UTC
[grinder recipes.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6136334/grinder.recipes.zip)

**Describe the feature**
Please allow grinding tin, silver, lead and copper ores and ingots in a quartz grindstone, similar to iron and gold ores and ingots.

**Reasons why it should be considered**
It is a bit counter-intuitive that you can grind gold, but not silver or lead, because in real life gold is considered more precious than silver or lead. An alternative solution would be to remove the gold and silver recipes and allow only the grinding of non-precious metals.

**Additional Context**
I attached json files that define these rules.
[grinder recipes.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6136239/grinder.recipes.zip)

**Comment by yueh** [comment] 2021-03-14 09:52
Duplicate of #4897

**Closed by yueh** 2021-03-14 09:52 UTC
