### ISSUE TITLE
Use a button to stop Terminal automatically arranging showed items

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#4591] opened 2020-08-13 12:27 UTC
**Describe the feature**
Use a button to stop Terminal automatically arranging showed items.

**Reasons why it should be considered**
Make it much easier to select the item wanted without searching when have items going in and out through the network.
Though this situation can be avoided by using view cells, but it also occurs when taking out items and using amount based sorting on terminals

**Additional Context**
![1BB64565B51749DF8E446E806AD029D6](https://user-images.githubusercontent.com/66953201/90133690-84c27b80-dda2-11ea-8b33-6129f0cd81ef.gif)
(Though the picture is of old version, it's the same in later version)

**Comment by yueh** [comment] 2021-09-12 17:16
Duplicate of #27

**Closed by yueh** 2021-09-12 17:16 UTC
