### ISSUE TITLE
Meteor Compass

### ISSUE THREAD

**Issue by Floppa-8765** [AppliedEnergistics/Applied-Energistics-2#5415] opened 2021-09-03 21:54 UTC
for the love of god why does meteor compass track sky stone
**Describe the feature**

make it track sky stone chests please
**Reasons why it should be considered**

so you dont have to spend 8.5 years looking for that one block of skystone hidden 7 blocks underneath the meteor
**Additional Context**

**Comment by yueh** [comment] 2021-09-03 21:56
Duplicate of #550

**Closed by yueh** 2021-09-03 21:56 UTC
