### ISSUE TITLE
[1.18 forge] Crafting from JEI.

### ISSUE THREAD

**Issue by Skapupel** [AppliedEnergistics/Applied-Energistics-2#6345] opened 2022-06-07 23:32 UTC
### Describe the feature

I want to know is there any way to return back feature where you can click on item in jei, and when clicking plus button it will request for auto-craft items you need to craft this item. And also a feature that shows what items are missing when you try to craft from jei...

### Reasons why it should be considered

This was a really good feature that now refined storage has, but ae2 not. But i really love ae2 and i want to use it only....

**Comment by atlgeek007** [comment] 2022-06-08 01:03
Actually I'd thumbs up for this one too - being able to do a one off craft via JEI and control clicking the plus sign to request autocrafting for the components I can autocraft would be very nice.

**Comment by Technici4n** [comment] 2022-06-08 11:24
Duplicate of  #4856

It is planned, but a bit annoying to implement, so we will see when someone from the team gets to it.

**Closed by Technici4n** 2022-06-08 11:24 UTC
