### ISSUE TITLE
Automatically insert the cards when duplicating settings with memory cards

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#5760] opened 2021-12-11 13:46 UTC
### Describe the feature

When we are using the memory cards to duplicate machine settings, the cards should be automatically taken from the players' inventory and the Network Tool when needed. If it fails, it should give a warning in the chatting box.

### Reasons why it should be considered

Obviously, it's really inconvenient when you are duplicating lots of machines' setting without this feature, and I've wasted hours on this problem this weak since I easily forget to insert the cards. 

### Additional details

(Can we have this for 1171?)

**Comment by Technici4n** [comment] 2021-12-14 22:33
Duplicate of #1382

**Closed by Technici4n** 2021-12-14 22:33 UTC

**Comment by DoremySwee** [comment] 2021-12-15 07:38
> Duplicate of #1382

So when can the duplication of older issues be solved

**Comment by Technici4n** [comment] 2021-12-15 08:09
Whenever we will get to them. There is a ton of features that were suggested but never implemented, and we will slowly go through them, but this takes a lot of time.
