### ISSUE TITLE
ME Chests powered by other mods' cables interrupt the player moving stacks or fluids

### ISSUE THREAD

**Issue by saltyseadoggo** [AppliedEnergistics/Applied-Energistics-2#6303] opened 2022-05-27 23:36 UTC
### Describe the bug

When an ME chest is powered by cables provided by Tech Reborn, Industrial Revolution or Modern Industrialization, or generators from these three mods such as MI's turbines, the following behavior quirks take place:
- When the player has the chest's interface open and tries to put a stack of items into the chest, either by shift clicking the stack or by clicking and dragging, the slots in the chest will turn dark for a split second, and only approx. 40 items will be transferred to the chest; the rest will remain in the source slot.
- In the above situation, if the player clicks on a stack in their inventory to pick it up, then double clicks on another identical stack to try to move all stacks of that item to the ME chest, the chest slots will turn dark for a split second, and only approx. 40 items from the stack that was clicked on and approx. 40 items from another matching stack in the inventory will be transferred.
- When the ME chest's disk is a fluid disk containing fluid and the player tries to withdraw fluid into a large tank, such as Modern Industrialization's titanium tank, via clicking and dragging the tank, the chest slots will darken for a split second, and only a bit of fluid will move into the tank, when there is room for more in the tank.

If the chest is powered by a fluix cable, these quirks do not occur.

### How to reproduce the bug

- Start the game with AE2, any of Tech Reborn, Industrial Revolution or Modern Industrialization, and their dependencies loaded.
- Place an ME chest.
- If Tech Reborn is installed, place a `Glass Fiber Cable` adjacent to the ME chest, and a `Creative Solar Panel` next to the cable.
- If Industrial Revolution is installed, place a `Cable MK4` adjacent to the ME chest, and a `Lazuli Flux Container Creative` next to the cable.
- If Modern Industrialization is installed, place a `Tin Cable` adjacent to the ME chest, a `LV Steam Turbine` next to the cable, a `Fluid Pipe` next to the turbine, and a `Steel Boiler` next to the pipe. Shift right click the sides of the turbine and boiler that face the pipe to connect the pipe. Right click the part connected to the boiler and click on the `IN` in the interface until it changes to `OUT`. Place fuel and water into the boiler.
- Regardless of the tech mod used, attempt to perform the actions described in the above section with any stackable items to observe the behavior.

### Expected behavior

Moving stacks or fluids into or from an ME chests powered by other mods' cables would behave identically to if the chest was powered by a fluix cable.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A, this is not a crash

**Comment by Sea-Kerman** [comment] 2022-05-27 23:42
I have a suspicion as to what is happening. It sounds exactly like what happens if your network doesn't have enough energy storage. How are you supplying power to said fluix cable? Both an energy acceptor and a controller have internal energy storage so they will alleviate the problem you are experiencing. 

What happens is you send a command to insert or extract 64 items, but the network only has enough energy stored for 40 items to be transferred and it can't get more energy because this all happens within 1 gametick. The energy storage is drained, the network loses power and turns off, then gets more energy in the next gametick and turns back on. So probably not a bug.

**Comment by saltyseadoggo** [comment] 2022-05-27 23:47
This behavior does make sense to me now that you explain it. Would it perhaps be possible to give the ME chest a small internal energy storage like the acceptor and controller to prevent this issue? To someone who doesn't understand exactly how the power transfer works, it looks like a bug; I can say this from experience.

**Comment by Sea-Kerman** [comment] 2022-05-27 23:57
It must have some level of storage or you wouldn't be able to take a single item out but if it only has energy for 40 perhaps buffing the internal storage a bit would be good.

**Comment by saltyseadoggo** [comment] 2022-05-28 02:45
That sounds good.~ If you're looking for input on what to buff it to, I'd consider being able to transfer a stack at once a good minimum. For shift double clicking to send many stacks at once, a higher storage, capable of transferring 36 stacks (a player's entire inventory), would be appreciated so the second of the behaviours I mentioned doesn't continue to happen.

**Closed** 2022-06-04 14:01 UTC
Labels: bug
