### ISSUE TITLE
AE2 makes entire server crash

### ISSUE THREAD

**Issue by craving-death** [AppliedEnergistics/Applied-Energistics-2#4157] opened 2019-09-17 15:15 UTC
**Describe the bug**

makes server crash when someones base is loaded with AE stuff
appliedenergistics2-rv6-stable-6.jar
**To Reproduce**

**Expected behavior**

**Additional context**

https://gist.github.com/craving-death/321d7a33f6e01a7005613202605d5b87
**Environment**

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: 1.12.2 2838

**Comment by Pingger** [comment] 2019-09-17 15:34
Can you try again without sponge? (aka without the aaaaaaaaaaaaspongeforge-....jar)
This looks like a Spongeforge "optimization" issue, that causes non-deterministic stuff to happen

**Comment by yueh** [comment] 2019-09-17 16:12
Duplicate of #3800

**Closed by yueh** 2019-09-17 16:12 UTC
