### ISSUE TITLE
Autocrafting Colored Wool

### ISSUE THREAD

**Issue by Bestadd** [AppliedEnergistics/Applied-Energistics-2#967] opened 2015-03-04 00:31 UTC
So last night I was in my FTB Infinity 1.2.0 world and wanted to get all the Steve's Factory Manger blocks set up for auto crafting.  So I created all the patterns, but one causes an infinite loop (or what I'm going to call an infinite loop).  So AE2 uses ore dictionary during auto crafting, which is cool in 99% of the cases; however, SFM Camouflage block takes 1 SFM cable, 1 Blue wool, 1 Green wool and 1 Red wool since blue wool can be used to craft green wool which can be used to craft red wool which can be used to craft blue.... you get the idea.  so when I request this item it never completes.  

I also have this problem with blue die.  I want the system to use botana's die's but it insists on using laps.  the blue die is infinitely renewable for me, laps is not (close but not).

I think this could be fixed by using a crafting machine for each color of wool/items I want to force to use the blue die since I don't think machine recopies use the ore dictionary but I could be wrong on that, more testing to find a work around is need.      

As always,  any suggestions you have, I'm just a stupid user so there may be a very obvious solution to this that I'm just not seeing.

**Comment by yueh** [comment] 2015-03-04 15:16
Duplicate of #784, #439 and potentially #112

**Closed by yueh** 2015-03-04 15:16 UTC
