### ISSUE TITLE
More infinite power with RotaryCraft - Flywheel

### ISSUE THREAD

**Issue by jeremiahwinsley** [AppliedEnergistics/Applied-Energistics-2#1388] opened 2015-05-04 02:14 UTC
I found this one while looking at #1384. This is a separate issue.

I'm using version rv2.stable build 1 of AE2, and version v6f of RotaryCraft, in single player.

Steps to reproduce:

- Place down a RotaryCraft flywheel and a RotaryCraft power source.
- Charge the flywheel, then remove the power source. Using the Angular Transducer, you should see the flywheel speed remain constant.
- Place an Energy Acceptor at the flywheel's output. 
- Using the Network Tool, you'll see that the Energy Acceptor is producing power. Using the Angular Transducer, you'll see that the Energy Acceptor does not actually consume any power from the flywheel.

This may be due to [this function](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/de069980ced2b6525f6102735839271f079f963f/src/main/java/appeng/tile/powersink/RotaryCraft.java#L165-L168) returning 0, where [the api](https://github.com/ReikaKalseki/RotaryCraft/blob/f650baf0d6b88b8bb0e333da3fa86f6eab7832eb/API/Power/PowerAcceptor.java#L23-L26) suggests it should return 1.

**Comment by yueh** [comment] 2015-05-04 08:00
This is most likely a duplicate of the other issue and there is no need to report every single machine causing issues.

At least until the other is actually fixed and there are still issues left. But that might be caused by the actual issue missing some important information hidden in another issue.

**Closed by yueh** 2015-05-04 08:00 UTC
