### ISSUE TITLE
Slots cannot be swapped with the offhand in sky stone chests

### ISSUE THREAD

**Issue by haykam821** [AppliedEnergistics/Applied-Energistics-2#6182] opened 2022-04-17 04:35 UTC
### Describe the bug

In sky stone and sky stone block chests, pressing the key bound to 'Swap Item With Offhand' while the cursor is highlighting a slot does not do anything. This contrasts with vanilla containers, where the same action properly swaps the slot contents with the offhand.

### How to reproduce the bug

1. Place a sky stone chest
2. Open the sky stone chest
3. Place an item in any slot in the screen handler
4. Press the key bound to 'Swap Item With Offhand'

### Expected behavior

When the key bound to 'Swap Item With Offhand' is pressed, like with vanilla containers, the contents of the offhand and the highlighted slot should be swapped.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/haykam821/b468be8bdc66e7322495081779cf749f

**Comment by Technici4n** [comment] 2023-02-26 23:43
Duplicate of #6924

**Comment by Technici4n** [comment] 2023-02-26 23:43
(I know you were first :P)

**Closed by Technici4n** 2023-02-26 23:43 UTC
Labels: bug
