### ISSUE TITLE
Autocrafting Actually Additions Emeradic Crystal AIOT causes server crash

### ISSUE THREAD

**Issue by thaimichael** [AppliedEnergistics/Applied-Energistics-2#3802] opened 2018-10-26 14:50 UTC
Autocrafting Actually Additions Emeradic Crystal AIOT causes server crash

**Describe the bug**
Created a new AE2 system on FTB Sky Adventures 1.2.1 beta
Loaded mats necessary to autocraft the Emeradic Crystal AIOT
Created the Axe, Shovel, Hoe, Pickaxe, and Sword recipes manually crafted the tools in the crafting grid then finally created the AIOT recipe but did not manually craft.
Installed all of the recipes for the base tools plus the AIOT in my ME Interfaces.
Attempted to Autocraft the AIOT and the server subsequently crashed everytime I attempted to login with the following crash log.
https://pastebin.com/prdZyzzy
I was able to login several hours later with a different client, found the AIOT completed in the AE system.
Removed the completed AIOT without issue from the AE system.

**To Reproduce**
With mats in system tried to autocraft AIOT from base material and server immediately crashed with the following log.
https://pastebin.com/dP6dw8BU

**Expected behavior**
Craft without crashing

**Additional context**
Inline above

**Environment**
Multiplayer Server
FTB Sky Adventure 1.2.1-1.12.2 beta
Minecraft 1.12.2
Forge 14.23.5.2770
ActuallyAdditions 1.12.2-r143
appliedenergistics2-rv6-stable-3

**Comment by yueh** [comment] 2018-10-26 15:50
Duplicate of #3768

**Closed by yueh** 2018-10-26 15:50 UTC
