### ISSUE TITLE
///>Matter Cannon (AE2)<\\\ Crashes servers

### ISSUE THREAD

**Issue by Dval1nn** [AppliedEnergistics/Applied-Energistics-2#4997] opened 2021-02-18 15:11 UTC
If you load a matter cannon with paintballs and try to shoot it, it crashes the server.
The server name is 

1) Use a ME chest to put paintballs in matter cannon
2) right click with matter cannon in hand
3) server goes down

I am playing on ATM6
Version: 1.5.2
Game version: 1.16.5

![unknown](https://user-images.githubusercontent.com/79268448/108377853-6feff600-71d2-11eb-8100-630f95a48a6a.png)

**Comment by yueh** [comment] 2021-02-18 15:33
Duplicate of #4904

**Closed by yueh** 2021-02-18 15:33 UTC
