### ISSUE TITLE
crafting with fluids

### ISSUE THREAD

**Issue by Matthew-Bates** [AppliedEnergistics/Applied-Energistics-2#5277] opened 2021-06-06 11:39 UTC
When crafting something with a fluid in its recipe it is very tedious to switch out the empty bucket left after a craft so I feel it should it should be changed.

It's up to the creator really but I think instead of leaving an empty bucket either: 
1. replace with the same bucket item like other items do after a craft
2. allow crafting with fluids from the ME fluid storage cell, currently I cannot find a way for the crafting terminal to interact with the fluid storage cells

Either of them would make crafting with fluids a lot less tedious and more bearable, thanks

**Comment by Mari023** [comment] 2021-06-06 11:41
duplicate of #1917

**Comment by Technici4n** [comment] 2021-06-06 11:42
Replacing empty buckets with full buckets is not planned, and regarding 2. #1917 is the tracking issue.

**Closed by Technici4n** 2021-06-06 11:42 UTC
