### ISSUE TITLE
Native Curio Integration

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#7525] opened 2023-12-31 11:06 UTC
### Describe the feature

Add Curio support to the Wireless (Crafting) Terminal and Portable Cells

### Reasons why it should be considered

With Neo's Cap rework it is now possible to add Curio support without a compile time dependency on curio.

### Additional details

I am currently working on a PR for this feature.

Open questions:
- [ ] should the Network tool become a curio too?
(since it acts as a storage for Upgrade cards, and adds it's inventory to most ae2 GUIs)
- [ ] which slots should ae2 use?
(ae2wtlib just uses "Curio", which works as a wildcard for any slot)
- [ ] should ae2 add some curio slot on its own? and if yes, which one?
(adding slots can be done by the user with a datapack , or by other mods which do add slots on their own)
(ae2wtlib doesn't add a slot)

**Comment by LostQuasar** [comment] 2024-01-23 01:12
Duplicate of #6697 
No?

**Closed as completed** 2024-02-04 14:59 UTC
