### ISSUE TITLE
Crafting Terminals no longer working after using JEI

### ISSUE THREAD

**Issue by Scha7ten** [AppliedEnergistics/Applied-Energistics-2#6935] opened 2023-02-22 16:07 UTC
## Description of the Bug: 
I am plaing the modpack All The Mods 8 (added Project E and Project Expansion). After using the terminals both wired and wireless for a long time, suddenly they don't work anymore. The wired one needs to be broken to work and the wireless one can be thrown away. I don't know why, but using JEI in these terminals somehow messes something up.  This happens after crafting something

## Expected Behavior:
Using the terminals works fine

## Minecraft version:
1.19.2

## Modloader:
Forge

## Network Parts:
![grafik](https://user-images.githubusercontent.com/60462812/220683951-3c1987a5-09d8-489b-8e7d-c2bdc5ad2da1.png)

## Log file (not crashlog, as the game does not crash)
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/10805926/latest.log)

**Comment by Scha7ten** [comment] 2023-02-22 16:10
Restarting game does not work, reloading neither. The storage bus is connected to the Transmutation Interface of Project Expansion. But that does not seem to cause the issue as disconnecting it does not change the situation and the bug is still reproduced.

**Comment by Sea-Kerman** [comment] 2023-02-22 16:34
Was a machine frame from Industrial Foregoing involved?

**Comment by Mari023** [comment] 2023-02-22 16:56
I think this might be a duplicate of #6897, updating immersive engineering should fix this

**Comment by Sea-Kerman** [comment] 2023-02-22 16:58
> I think this might be a duplicate of #6897, updating immersive engineering should fix this

But this is Industrial Foregoing not Immersive Engineering

**Comment by Scha7ten** [comment] 2023-02-22 19:51
I crafted things from IF and I already did update it to fix the Fluid Laser Base bug

**Comment by Scha7ten** [comment] 2023-02-22 19:56
So is this an AE2 issue or an IF issue?

**Comment by Technici4n** [comment] 2023-02-26 18:34
I have no idea what's going on. Have you tried updating IE? Otherwise please try to reproduce this bug with as few mods as possible. It's impossible for us to track down in a modpack as large as ATM8, especially since it seems to be happening randomly.

**Closed** 2023-03-16 13:44 UTC
Labels: awaiting-feedback
