### ISSUE TITLE
AE2 still crashing with the one probe 7.0.0

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#6925] opened 2023-02-13 14:17 UTC
### Describe the bug

	Failure message: Mod ae2 only supports theoneprobe 1.19-6.1.0 or above, and below 1.19-7.0.0
		Currently, theoneprobe is 1.19.3-7.0.0
	Mod Version: 13.0.9-beta

### How to reproduce the bug

install both AE2 13.0.9-beta and the one probe 7.0.0

### Expected behavior

well, not to crash ;D

### Additional details

i might have missed a follow up issue but https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6816 was the only one i found and stated it should be fixed after 13.03-alpha 

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/ymxSq1bR

**Comment by mindforger** [comment] 2023-02-13 14:29
isn't it a bit strange that the upper end of compat list is not considered to be within the allowed version range ? is that a forge thing?

**Comment by mindforger** [comment] 2023-02-13 19:14
will give it a test with the other bracket tomorrow and close if it is enough, can not access my game yet

**Comment by mindforger** [comment] 2023-02-13 22:39
no it still says 1.19-7.0.0 at least in the 13.0.9-beta from curse launcher ( got i as zip since i use Multi MC) can tell exact content when back on my pc

**Comment by mindforger** [comment] 2023-02-14 08:03
yeah it is still 

>[[dependencies.ae2]]
    modId="theoneprobe"
    mandatory=false
    versionRange="[1.19-6.1.0,1.19-7.0.0)"
    ordering="AFTER"
    side="BOTH"

and 

>[[dependencies.ae2]]
    modId="theoneprobe"
    mandatory=false
    versionRange="[1.19-6.1.0,1.19-7.0.0]"
    ordering="AFTER"
    side="BOTH"

does not work but 

>[[dependencies.ae2]]
    modId="theoneprobe"
    mandatory=false
    versionRange="[1.19.3-6.1.0,1.19.3-7.0.0]"
    ordering="AFTER"
    side="BOTH"

does, thnx for the hints how to read the formatting :)

**Comment by Technici4n** [comment] 2023-02-24 22:55
Duplicate of #6910.

**Closed by Technici4n** 2023-02-24 22:55 UTC
Labels: bug
