### ISSUE TITLE
storage cells can not be interacted or pull out from drive after auto crafted

### ISSUE THREAD

**Issue by alanch522** [AppliedEnergistics/Applied-Energistics-2#3664] opened 2018-08-03 02:32 UTC
#### Description

This issue only occurred on server,  there is no problem on singleplayer at all.

I can confirm this bug when crafting 1k,4k or 64k storage cells, the crafted cells will be displayed in ME drive, but can not be selected or taken out. If I continue to craft storage cells, it will display lack of storage cells. 

The interesting thing is only if I take out the storage cell in ME drive and put it back, then I can pull out the crafted cells.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 14.23.4.2705

**Comment by fscan** [comment] 2018-08-03 09:48
Duplicate of #3449

**Closed by fscan** 2018-08-03 09:48 UTC
