### ISSUE TITLE
[Minecraft 1.18.2] [Forge] Mixins failure

### ISSUE THREAD

**Issue by TerminalHash** [AppliedEnergistics/Applied-Energistics-2#6224] opened 2022-04-30 17:34 UTC
### Describe the bug

After start of the game with only AE2, with many mods, game crashing.

### How to reproduce the bug

1. Install AE2 in you Minecraft 1.18.2
2. Use last stable Forge (40.1)
3. Start game.
4. ...
5. CRASH!

### Expected behavior

Watch up, please, for description.

### Additional details

Used TL Legacy (TLauncher Legacy) for launch game on Artix Linux.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/U79Lzfiv

**Comment by 62832** [comment] 2022-04-30 17:36
> `[30апр.2022 20:26:23.662] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: forge`

what

**Comment by Technici4n** [comment] 2022-04-30 17:36
Duplicate of #6193

**Closed by Technici4n** 2022-04-30 17:37 UTC
Labels: bug
