### ISSUE TITLE
Crafting cards still causing excessive lag?

### ISSUE THREAD

**Issue by jinks** [AppliedEnergistics/Applied-Energistics-2#2069] opened 2015-12-23 05:24 UTC
I had problems with high lag on our server without any obvious causes in Opis. The main symptom was entities (Golems, Railcraft trains) moving in "spurts" with long pauses in between. After some probing with VisualVM I found appeng.crafting.CraftingJob.handlePausing() to be the culprit. It seems to be similar to #982 and #670.

![AE2 crafting handler](http://i.imgur.com/YlliUDt.png)

Disconnecting parts of my network that have crafting cards alleviates the problem. I have a fairly extensive ME network without using subnets (lots of P2P though) since I was under the impression that subnet interaction was one of the main causes of slowdowns.

Is this expected behaviour on large networks? How can I work around this? Most of my crafting card interfaces rely on fairly long crafting chains involving several intermediate steps/machines (Dark Steel Balls, AE2 Processors, Pure Crystals, ...), is that compounding the issue?

I'm running version rv2-stable-10, pack is Infinity Evolved 2.2.2.

- - -

**Edit:** Some more observations. It would appear that the fact that I have stored many materials in StorageDrawers is adding to the problem quite a bit. The server spends a lot of time checking itemStacks inside the drawers. It looks to me like the ME system is *constantly* "simulating" the extraction of items needed for the recipes, even if it doesn't need to craft anything at the moment (i.e. an interface set to stock a stack of X is full).

**Comment by yueh** [comment] 2015-12-23 11:04
`handlePausing()` just puts the crafting calculation thread to sleep. Self time in this case just indicates how long it slept. `Self Time (CPU)` is actually the indicator how much cpu time it actually spent.

Simulating the extraction of items is required as some inventories are not reliably sending notifications about any change, thus we cannot trust any inventory and need at least simulate an extraction to obtain the stored items. As long as forge/minecraft does enforce a way to handle it reliably, we cannot change anything about it.
Storage Drawers is actually even worse as they cannot report the exact amount during the simulation, but only after actually extracting the items, causing more issues later on like broken autocrafting.

**Comment by jinks** [comment] 2015-12-23 17:38
Yes... after some further investigation I noticed myself that it only affects crafts that draw their items from Storage Drawers. Drilling sown into a snapshot of the server thread identifies NBTTagCompund.func_74737_b() as being called repeatedly by the drawer handlers.

As to the over-reporting of the drawers, I assumed that was common knowledge. I use them mainly for ingots and things like redstone to save on a sizeable number of nugget->ingot->block recipes and speeding up this part of crafting. I'm well aware of the limitations and just make sure to have enough of what I need at hand. As far as I know I could cause the same problem myself by starting a complex crafting process and then taking away the resources via terminal mid-craft, so it never bothered me.

What I don't quite understand is why the ME system has to simulate pointless crafts. In my case I have a crafting card interface set to stock several stacks of items and all those items are already in the interface, so there is no need to craft more. Why not defer the simulation until something actually needs to be crafted?

**Comment by yueh** [comment] 2015-12-23 17:52
Interfaces will not request any additional crafting once their configured stack is matched.

**Comment by jinks** [comment] 2015-12-23 18:03
It will not? But where do the many calls of CraftingJob.simulateFor() come from, then? When I took the above screenshot the ME hasn't been crafting anything for probably several hours and still SD was constantly being checked for available items.

Is there any way to see **what** craft it is trying to simulate at any given moment?

**Comment by yueh** [comment] 2015-12-26 12:26
Currently not possible. But the callstack reported by jvisualvm should at least indicate, if it is an interface or something else.

Might be an idea to improve the craftinglog with it. But out of head I cannot say, if it is actually possible.

**Comment by jaquadro** [comment] 2015-12-26 17:48
I tried to reproduce it on my end, but it did not continuously try to simulate crafting.

Your NBTTagCompound method is the stack copy call.  Every time the system simulates a job, a stack is copied at least once for every item in the inventory.  If you have a huge bank of drawers it will be costly, but I assume that's true for hooking up to a bunch of chests or anything else.

Calls also get made to getAvailableItems on a regular basis (more frequently than the drawer network refresh, anyway), and that also results in a full inventory stack copy.  That should be visible with or without your crafting card parts, though.

Perhaps yueh could spot opportunities for optimization in either case?
- https://github.com/jaquadro/StorageDrawers/blob/master/src/com/jaquadro/minecraft/storagedrawers/integration/ae2/DrawerMEInventory.java#L140
- https://github.com/jaquadro/StorageDrawers/blob/master/src/com/jaquadro/minecraft/storagedrawers/integration/ae2/DrawerMEInventory.java#L151

**Comment by yueh** [comment] 2015-12-26 19:54
Keeping a cache and just update it accordingly vs completely rebuilding it each time might improve it.

It is somehow the same issue I am currently trying to solve. But as long as the inventory handling with minecraft/forge is as broken as the current, there is simply no good approach to improve it.
With all the broken, shared, or voiding inventories around and no reliably/fast way to actually monitor any change happening, it basically means we need to visit each and every inventory as there is no way better way to determine, if the item was actually stored inside this inventory, voided, or stored in some in completely different inventory.

**Comment by jaquadro** [comment] 2015-12-26 21:40
That seems reasonable.

Could I expect to do significantly better with a grid device that interfaces directly with the storage and posts the changes?  Perhaps add a new part, and replace the stack from MEMonitorIInventory on up.

**Comment by Blue64** [comment] 2015-12-29 14:16
On topic, would ```JABBA```'s Barrels be better or worse than the drawers? Because I have both,  amongst other options (```Refined Relocation```, ```Iron Chests```, ```Iron Backpack```, ```IC2```'s DSU, etc.)… I like to have variety in my storage options ```:P``` I've heard good things about the DSU for factory stuff (smelting, grinding, etc.), but those are more expensive than Barrels or Drawers, so I was curious about the cheap storage, so I wouldn't accidentally cause lots of Lagg while moving to a bigger base for example.

Also, would using a Sub network to craft stuff (eg. Pure Crystals, or Certus Quartz Dust) be better or worse for lagg? I'm not exactly tech savvy in that area. Example:
```
Interface into Chest
Import into ME Chest
Drop Seed into Water via Formation Plane
Grab Pure Crystal
Import into Interface

I had to add the ME Chest because it doesn't recognize the Chest getting the items as a "Network Update",
despite the Storage Bus being correctly set up
```

**Comment by thatsIch** [comment] 2016-03-26 11:47
Generally the simpler the better.

**Closed by thatsIch** 2016-03-26 11:47 UTC
Labels: question

**Comment by trejkaz** [comment] 2016-10-09 01:29
We're seeing similar things on our server since adding a few more drawers a couple days ago. Did anyone ever file this one with StorageDrawers?

**Comment by jaquadro** [comment] 2016-10-09 03:14
The issues are known, but I wouldn't expect to see any kind of fix for it.  If you can show me an equivalent JABBA setup that has demonstrably better performance than the Storage Drawers one, I will take another look.

**Comment by trejkaz** [comment] 2016-10-09 07:30
The quick hacky test:

* Storage Drawers
    * 12x12 Oak Drawers
    * Drawer Controller on one corner
    * Storage Bus on one corner
    * Fill one drawer completely full of oak wood
* JABBA
    * 12x12 Better Barrels
    * Storage Bus on each barrel
    * For each 2x2 block of barrels, a separate coloured ME Smart Cable
    * Connect together each pair of columns (24 Storage Buses each) with ME Dense Cable, 6 cables in all
    * 6 pairs of P2P Tunnels to run those channels back into the controller
* Crafting setup
    * 8 64k Crafting Storage
    * 12 Crafting Coprocessor
    * One ME Interface for recipes, connected to 3 Molecular Assemblers
    * Crafting recipes set up to make Crafting Tables.

/forge tps reports 3.0~3.2ms for the JABBA setup and 8.0~8.2ms for the Storage Drawers setup.

Admittedly this is only for 12x12 drawers. I'm not actually sure how many we're using in the game because the setup isn't very uniform.

**Comment by Blue64** [comment] 2017-03-17 01:35
did you avoid recursion with your wiring on those JABBA Barrels? (from the sounds of it, you didn't), I'm asking because that could potentially slow things also.

**Comment by trejkaz** [comment] 2017-03-17 02:51
I didn't, no... it was a super-naïve barrel setup.
