### ISSUE TITLE
[1.16.5] Crash Fuzzy card / export bus

### ISSUE THREAD

**Issue by Alkasym** [AppliedEnergistics/Applied-Energistics-2#5111] opened 2021-04-03 13:29 UTC
Hi,

We have a crash when we have a fuzzy card in the export bus.

pastbin : https://pastebin.com/4QQEAf5E

-----------------------------------------------------------------------------------------------------------------------------

forge : 36.1.3
AE2 : 8.3.0-alpha1

**Comment by yueh** [comment] 2021-04-03 13:30
Duplicate of #4821

**Closed by yueh** 2021-04-03 13:30 UTC

**Comment by Alkasym** [comment] 2021-04-03 13:33
I see the dupplicate issue but my problem is on forge.
