### ISSUE TITLE
Crash when changing to processing recipe in pattern terminal

### ISSUE THREAD

**Issue by Natanaelel** [AppliedEnergistics/Applied-Energistics-2#5554] opened 2021-10-17 16:48 UTC
### Describe the bug

When clicking on the crafting table in the pattern terminal to change to a processing recipe, the game crashes.
After rejoining the world, the game crashes when you try to open the terminal.

### How to reproduce the bug

1. Place a pattern terminal.
2. Open it.
3. Click on the crafting bench icon to change pattern mode.
4. Crash.

### Expected behavior

The pattern mode should change to processing recipe instead of crafting recipe.

### Additional details

appliedenergistics2-9.0.0-alpha.2.jar
Playing all-of-fabric 4
Client crashes in both multiplayer and singleplayer.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.alloffabric.com/lihepesibu.yaml

**Comment by shartte** [comment] 2021-10-17 17:14
Duplicate of #5512. Already fixed, please update.

**Closed by shartte** 2021-10-17 17:14 UTC
Labels: bug
