### ISSUE TITLE
Dense Cables only giving 8 channels as opposed to 32

### ISSUE THREAD

**Issue by NimonoSolenze** [AppliedEnergistics/Applied-Energistics-2#2878] opened 2017-04-22 01:56 UTC
The official info site states that ME Dense Cables give a whopping 32 channels, but when using them to set up a Spatial Containment Structure, whose pylons are stated to need 1 channel per set, I discovered that dense cables are only giving the base 8, same as the basic ME Glass Cables, making them not even worth making at the moment. The same amount of pylons lit up whether it was dense or glass cable. Tested in multiplayer.

- Minecraft Version: 1.10.2
- AE2 Version:  rv4 alpha 11

**Comment by VT-14** [comment] 2017-04-22 05:23
ME Controllers output 32 channels per side.  Dense Cables and P2P Tunnels can handle 32 channels.  I think the Quantum Network Bridge can also handle 32 channels.

Everything else, including the Spatial Pylons you are almost certainly trying to send channels through, only support up to 8 channels.  Place a full line of Dense Cables underneath your Pylons and they should work properly.

**Comment by mindforger** [comment] 2017-04-22 06:37
Pictures of the setup please when you are sure you have no bottlenecks in your wiring

**Comment by Majestyc2k1** [comment] 2017-05-07 06:14
I have encountered the same problem. I had 5 TE machines with ME Interfaces and Import buses (should be 10 channels) in a row. A dense cable was connected to an ME Interface. 5 of the Interfaces and 3 of the Buses were online. The last two Buses were missing channels. The dense cable showed only 8 of out 32 channels in use.

**Comment by mindforger** [comment] 2017-05-07 07:11
As i already said, pictures pleas...

**Comment by Majestyc2k1** [comment] 2017-05-07 17:09
Pictures are not necessary. I have experience with both Applied Energistics and AP2. I know how the mod operates. My description should be sufficient.  Its obvious as the 1.10.2 version is still in Alpha and a few things aren't complete.

**Comment by GuntherDW** [comment] 2017-05-07 19:23
Pictures ARE in fact necessary to prove you haven't connected your setup up wrong.
As stated in the reply from VT-14 interfaces/other blocks can act like cables, but only spread up to 8 themselves.

So you'll need to run dense cable if you want more than 8.
I have a network of over 2-3K channels in use in my current playthrough, and my last 2 or 3 playthroughs  in 1.10.2.
If it is a bug you wouldn't mind proving that you didn't hook it up wrong.

**Comment by mindforger** [comment] 2017-05-07 19:24
how about pictures to reproduce the issue? ... seriously ...

**Comment by VT-14** [comment] 2017-05-08 00:19
@Majestyc2k1 Your descriptions reads as Controller -> Interface -> Dense Cable.  If that is your setup then please reread my previous response to know why this doesn't work (Hint: the Interface is NOT on that short list of items that transfer 32 channels).

If that is not your setup, then please provide a detailed, 1,000 word description.  A picture is an appropriate substitute.

**Comment by Majestyc2k1** [comment] 2017-05-08 19:22
3 at a time, wow. My description clearly stares Controller - dense cable - Interface.

BTW: how many of you are ACTUALLY involved in the making of this mod. I don't appreciate being ganged up on. Very unprofessional.

You know what, screw it. I came here to report a problem, not be harassed.

**Comment by mindforger** [comment] 2017-05-08 20:25
@Majestyc2k1  Removing comments and ripping apart another one's bug report is immensly rude just because somebody is telling you to post pictures to help analyzing it ... I am closing this issue, if it still persist open a new one and add pictures please

**Closed by mindforger** 2017-05-08 20:25 UTC
