### ISSUE TITLE
game crash and world softlock 

### ISSUE THREAD

**Issue by CMAE2** [AppliedEnergistics/Applied-Energistics-2#5274] opened 2021-06-06 05:50 UTC
As soon as the character hitbox collides with the top of all cables, the game crashes and any exempt to load the world results in the game crashing on the frame player physics are first calculated after joining the world.

 I first encountered it in my survival world as I was trying to pillar up to the controller using the cables. I then created a new creative world to repeat it and the moment the player hitbox collided with the top of the cable the game crashed, I tried to alter my players NBT data to alter my player cords but the game has to time to apply this when loading.

my current hypothesis is that the cable somehow causes an improper Z position generating the null pointer exception

[crash-2021-06-06_00.36.53-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6603657/crash-2021-06-06_00.36.53-client.txt)

**Comment by Technici4n** [comment] 2021-06-06 07:55
Duplicate of #5217

**Closed by Technici4n** 2021-06-06 07:55 UTC

**Comment by CMAE2** [comment] 2021-06-06 18:03
this was on forge, not fabric and only affected the cables, nothing else.

**Comment by Technici4n** [comment] 2021-06-06 18:12
> Sorry, we don't support hacked clients such as Baritone.

**Comment by CMAE2** [comment] 2021-06-06 18:25
I will see if removing Baritone from the mod folder changes anything.
here is a video if your wondering what I mean on what happens [](https://youtu.be/Ik9cwSaSPoQ)
P.S. I am using the forge mod version of Baritone

**Comment by CMAE2** [comment] 2021-06-06 18:26
[video](https://youtu.be/EP_3DRygYRc)

**Comment by CMAE2** [comment] 2021-06-06 18:32
I wander what is causing the true confliction, thank you, Have a Nice day
