### ISSUE TITLE
Text Panel

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#134] opened 2014-09-27 19:22 UTC
Basically, a High-Tech sign. A version of the illumination panel that showed text as well as emitted light.

Originally Posted by Sciencentistguy

This issue was migrated; For original details see http://ae-mod.info/Tracker/1134/

**Comment by Deshiba** [comment] 2015-02-03 13:02
Similar to or Duplicate of #110?

**Comment by Sn3akr** [comment] 2015-02-10 14:32
That would be an awesome idea, there's only the industrial information panel mod that's somewhat cool in my opinion, but to be able to have lighted signs using panels makes it a lot easier to hide them in a wall. Maybe be able to merge several panels to make a large sign? And it would be nice to be able to format the text as well. e.g. Make a large text header and have a line underneath with smaller letters.. Would make a sign for "BERT'S BAKERY.. We Got The Best Buns" a bit nicer too look at.

**Comment by thatsIch** [comment] 2015-03-09 17:16
I think I would favor this issue over #110, display free channels! blasphemy

**Comment by thatsIch** [comment] 2015-10-21 13:23
A somewhat working prototype

![2015-10-21_15 20 34](https://cloud.githubusercontent.com/assets/2210496/10637756/96e9ce2c-7807-11e5-82b7-e4a637a2cdc3.png)

**Comment by yueh** [comment] 2015-10-21 13:41
Looks nice.

Already any idea how to set the text? I always considered name presses in need of a bit more functionality/attention. But might feel a bit clunky to "press" them inside an inscriber.
But then there is also the issue about synchronizing the name between server and client.

**Comment by mindforger** [comment] 2015-10-21 13:59
@yueh sounds nice in my opinion, the name press as pattern, but make the dark panel with bright text then

**Comment by yueh** [comment] 2015-10-21 14:12
No idea currently about the design. But there are a few different approaches, like use the light color as background + dark as foreground (text, instead of simple black), inverted panels (dark background, light foreground). 
Should they have a GUI, it might be even an idea to use a configurable foregroundcolor (based on the 17 AE2 colors).
And whatever else could be an option like the bright/semi dark/dark panels.

**Comment by majic79** [comment] 2015-10-21 14:27
Use "illumination" colour taken from the cable they are attached to? Or dye them to override the colour?

Maybe you can make a negative text pattern (imprints the text on a dark panel allowing light through the text portion) to create a dark sign with illuminated writing, or apply that pattern to a blank (or coloured) inscriber plate to create a "positive" pattern that you apply to an illuminated panel to create dark text with an illuminated background

**Comment by thatsIch** [comment] 2015-10-28 10:37
You have several restrictions which you need to pay attention to. 

* if you use something like name presses, handling multiple lines gracefully is difficult
* font size: there is obviously just so much space, but there is a possibility to scale the font depending on the input length
* adding fancy coloring is not really simplistic  
* I wanted to stick as closely as possible to the vanilla sign post

What works so far:

* synching between server and client 
* persistence on saving and loading chunks
* setting the text
* multi line support
* rendering at static font size

Ideas to be considered:

* I think its rarely the case where you want duplicate the text content, but this would be aquired using a memory card
* merging text panels? not really a fan of it, but might be useful for "larger" stuff. Have to look into multi block rendering for that/how to see its aligned text panels and not single ones (need to consider color e.g.)

**Comment by yueh** [comment] 2015-10-28 11:08
Regarding restrictions:

1. Inscribers already provide the option to use 2 name presses, currently it simply concats it, but it could easily be changed to work differently based on the item. Thus handling two lines  gracefully is possible. Question is mostly "are two lines enough?"
2. This is probably the main issue, a GUI would allow to enforce a limit more easily. But even then the font is not monospaced, thus `i` and `m` have very different widths. Not trivial to solve.
3. I was thinking about inheriting the cable color as background color and then rework the color applicator that any part and not just the cable bus can intercept it. The support is mostly done, it just needs to iterate over `ForgeDirection` instead of simply using `UNKNOWN` and simply serialize it to the NBT tag for the part.
4. Probably a good idea. I mostly considered it as an option to give name presses a bit more usage as well as have a reason to synchronize part names between server and client.

Ideas:

1. Even when duplicating them is not that often used, at least it provides a way to save the text when relocating/replacing the part.
2. Formation/Annihilation planes have some rendering regarding their neighbours. Might want to look at this. Colour should either simply separate them or simply render them as is. If someone wants a checkerboard pattern, why not?
Issues I see with it are:
  * Synchronize the text over all adjacent panels
  * Non rectangular shapes, say a ring based on a 3x3 field, but the center one missing.

**Comment by mindforger** [comment] 2015-10-28 11:24
>
    if you use something like name presses, handling multiple lines gracefully is difficult
    adding fancy coloring is not really simplistic
    I wanted to stick as closely as possible to the vanilla sign post

you want it close to the vanilla AND simple multiline:
add a simple interface with 4 slots for 4 lines to be filled with a namepress each
every line has a font/scale size field right to the slot
alternatively insert an item to display it at this line (fancy sign example: Slot1=Press with "Machine Room" Size=2; Slot2=<SomeTechnicalLookingItem> Size=3)

overrunning text or symbol is an issue to be solved on user side


on the other side, i really like the idea of making it multiblock rendering!

**Comment by thatsIch** [comment] 2015-10-28 16:57
also interesting solution,

I just feel that the process of naming something is too tedious for a once in a lifetime thing.

**Comment by thepaperpilot** [comment] 2017-02-17 03:00
What about the panel asking for text when you place it, like vanilla signs? Then it wouldn't need a GUI, and you could use the whole colored cables determine text color idea, which I think is really good. Doing it this way wouldn't allow for merging text panels, but would solve the issues surrounding using name presses.

**Closed** 2020-07-17 12:59 UTC
Labels: type-feature
