### ISSUE TITLE
Recipe works on crafting table, cannot make a pattern for it.

### ISSUE THREAD

**Issue by mg-carlos** [AppliedEnergistics/Applied-Energistics-2#5449] opened 2021-09-25 03:34 UTC
**Describe the issue**
I have a recipe for 'constantan dust', made originally made from any forge copper and nickel dust.
This works fine on the crafting table but I can't create a pattern for it; I thought maybe this was due to having 2 variations (one from Immersive Engineering, one from Thermal)
I tried removing both recipes, then adding one without the dust tags (so no longer tag:forge/copper_dust) and just using the actual item from the same mod (item:thermal:constantan_dust).
I can again craft it on a regular crafting table/crafting terminal, but I can't create a pattern for it.

**Environment**
- Environment: mod versions and such are found on the crash log. Let me know if you need any other info.
- Crash log: https://pastebin.com/B2AL6akE

**Comment by Ommina** [comment] 2021-09-25 17:51
"This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff. "

**Comment by Technici4n** [comment] 2021-09-25 18:37
Wdym you can't create a pattern? Does it crash? Nothing happens when you click on the encode button?

**Comment by mg-carlos** [comment] 2021-09-25 21:52
Updated link for the log: https://pastebin.com/uW7ZvPQg

> Wdym you can't create a pattern? Does it crash? Nothing happens when you click on the encode button?

I mean if I move the items (1 copper dust, 1 nickel dust) from the terminal into the crafting grid, no recipe outputs, so I can't create the pattern; there's no crash or anything.

However, if I use JEI to move the items (the '+' sign on it JEI), I do see the output (constantan dust) and can craft the pattern; inserting this into an interface yields nothing though (basically the pattern is not doing anything).

**Comment by mindforger** [comment] 2021-09-25 22:03
did you make sure the terminal is in crafting mode and not machine mode?

**Comment by mg-carlos** [comment] 2021-09-25 22:51
@mindforger I tried checking and yes, I was now able to encode the pattern. I think my mind was just thinking ahead (about the need to make a machine pattern to smelt the dust) and messed up that step.

However, there's still an issue with the recipe.

Given that it's a non-machine recipe, it should just work as long as there's an assembler next to the interface, right? For some reason, it just sits there without completing the crafting order.

I also tried removing the alterations I'd done to the recipes to see if it worked then but it's still not working as intended.

**Comment by mindforger** [comment] 2021-09-26 06:56
>Given that it's a non-machine recipe, it should just work as long as there's an assembler next to the interface, right?

Actually no, it has to be a crafting pattern, since the Assembler can only work with those .. As a hint, you can use an Assembler standalone like an autocrafter with a pattern and pipe items in and out

**Comment by mg-carlos** [comment] 2021-09-26 07:21
Yeah I get that. So say the Interface has an encoded pattern to make sticks from wooden planks. That one works fine. So do other from mods (like a crafting recipe for a Gear for instance). But in the case of the constantan dust, it does not. The recipe shows up as available to craft, the materials are set aside, but then no crafting actually happens.

**Comment by mindforger** [comment] 2021-09-26 07:25
Ah okay sorry i did not catch that detail

**Comment by shartte** [comment] 2021-12-19 17:02
Will close this since we can't reproduce it (no version info, the crashlogs expired - i know, our fault, and due to massive crafting changes in 1.18)

**Closed by shartte** 2021-12-19 17:02 UTC
