### ISSUE TITLE
Advanced Patterns

### ISSUE THREAD

**Issue by Monniasza** [AppliedEnergistics/Applied-Energistics-2#4125] opened 2019-08-17 09:26 UTC
New patterns with higher capacities:
Better Pattern: up to 18 ingredients and 6 outputs
Extended Pattern: up to 27 ingredients and 9 outputs
Advanced Pattern: up to 54 ingredients and 18 outputs
Extreme Pattern: up to 81 ingredients and 27 outputs

**Describe the feature**
It will have patterns with increased capacity

**Reasons why it should be considered**
Useful for Avaritia Extreme Crafting and Extended Crafting Crafting Tables

**Additional Context**

***Existing patterns***
![image](https://user-images.githubusercontent.com/37037712/63209326-9e71aa00-c0df-11e9-9069-266b82c89ce4.png)

***Mockups of new pattern encoder GUIs***
![image](https://user-images.githubusercontent.com/37037712/63209363-09bb7c00-c0e0-11e9-90f1-0708646c1b4a.png)

![image](https://user-images.githubusercontent.com/37037712/63209368-2f488580-c0e0-11e9-9e53-c7fba67b1615.png)

![image](https://user-images.githubusercontent.com/37037712/63209376-45564600-c0e0-11e9-9c8c-30842ae2c377.png)

![image](https://user-images.githubusercontent.com/37037712/63209380-51420800-c0e0-11e9-8ae8-65f6560bb214.png)

***Mockups of new pattern recipes***
![image](https://user-images.githubusercontent.com/37037712/63209483-9c104f80-c0e1-11e9-939c-a2114f2ea595.png) (Better Pattern)

![image](https://user-images.githubusercontent.com/37037712/63209484-a599b780-c0e1-11e9-8649-b089a83d71b0.png) (Extended Pattern)

![image](https://user-images.githubusercontent.com/37037712/63209487-b0ece300-c0e1-11e9-8f80-822a1078f0ee.png) (Advanced Pattern)

![image](https://user-images.githubusercontent.com/37037712/63209491-bb0ee180-c0e1-11e9-87a4-711187dfaf62.png) (Extreme Pattern)

***Inventory mockup***
![image](https://user-images.githubusercontent.com/37037712/63209335-b9441e80-c0df-11e9-9f22-e1b34c6b7b0f.png)
Top row: unencoded patterns
Bottom row: encoded patterns
From left to right: ordinary, Better, Extended, Advanced, Extreme

**Comment by yueh** [comment] 2019-08-17 10:09
Duplicate of #3380

**Closed by yueh** 2019-08-17 10:09 UTC

**Comment by DAmNRelentless** [comment] 2019-09-26 16:36
This looks insane D:
