### ISSUE TITLE
Terminals Stop Functioning after java.lang.IllegalArgumentException: inconsistent range

### ISSUE THREAD

**Issue by drunkripper** [AppliedEnergistics/Applied-Energistics-2#3846] opened 2018-12-01 17:30 UTC
**Describe the bug**
all the terminals work fine until suddenly an error of "Caused by: java.lang.IllegalArgumentException: inconsistent range" is thrown and then all the terminals report no items in the AE system. The issue is that once one breaks, The rest will break as soon as there's an update in the network(Import bus, Export Bus, Storage bus gets an item in attached block, Player takes item out, Something gets auto crafted). no matter how far away, how long you wait, chunk loaded or not. (Please note that while the item terminal refuses to show any items export and import buses still work [The Storage Bus + ME Interface + Terminal doesn't fix the issue])

**To Reproduce**
It just happens. We have yet to be able to figure out what triggers it. Sometimes it's fine for hours sometimes it's not.

**Expected behavior**
Terminals to report items.

**Additional context**
error report: https://pastebin.com/Pk1SMHCX

**Environment**
!!! It is a sponge forge server !!!
- ATLauncher Industrial Box 0.7.16 With WCT removed trying to determine issue.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-4
- Forge Version: 14.23.5.2768
- IndustrialBox modpack 0.7.16 (WCT removed)

Server Info:
-   Minecraft: 1.12.2
-   SpongeAPI: 7.1.0-4f54ce0d
-   Sponge: 1.12.2-7.1.5-SNAPSHOT
-  SpongeForge: 1.12.2-2768-7.1.5-RC3506
-   Minecraft Forge: 14.23.5.2768

**Comment by yueh** [comment] 2018-12-02 09:04
Duplicate of #3768

**Closed by yueh** 2018-12-02 09:04 UTC

**Comment by drunkripper** [comment] 2018-12-02 22:40
I don't believe it's the same issue, as the server does not crash, Even AE2 still works, just items can't be displayed.

**Comment by MaxxPowers** [comment] 2018-12-29 22:39
I just had this problem and narrowed it down to view cells in my terminals that used fuzzy cards.  Not sure if it's the same for you drunkripper.
