### ISSUE TITLE
Autocrafting won't auto craft crafting tables or molecular assembelers.

### ISSUE THREAD

**Issue by Gamingmaster01** [AppliedEnergistics/Applied-Energistics-2#3766] opened 2018-10-07 14:54 UTC
My autocrafting won't auto craft crafting tables or molecular assemblers but just these two items from what I've seen. I've tried changing the patterns, breaking and replacing the interfaces, having the crafting tables in the system already, but nothing seems to work. It gets stuck on the select amount screen so when I hit next it does nothing, no crash or anything it wont move forward but I can exit it just as if I hadn't hot next. I've closed the world and restarted it. I've tried in a test world. Both are in SP in the stoneblock modpack version 1.0.17.
![2018-10-07_10 47 35](https://user-images.githubusercontent.com/11151264/46583044-90aebb00-ca1e-11e8-9189-9bbaa4dc809b.png)

- Minecraft Version: 1.12.2
- AE2 Version: first in rv5-stable-11
- Forge Version: 14.23.4.2760

**Comment by yueh** [comment] 2018-10-07 14:59
Duplicate of #3575

**Closed by yueh** 2018-10-07 14:59 UTC
