### ISSUE TITLE
[1.10.2-rv4-alpha-3] Crash when scrolling down the JEI's item list

### ISSUE THREAD

**Issue by QuantumSheep** [AppliedEnergistics/Applied-Energistics-2#2560] opened 2016-11-02 21:32 UTC
The game crash when scrolling down the item list in JEI:

- Minecraft 1.10.2
- Forge 12.18.2.2118
- AE2 1.10.2 rv4 alpha 3
- JEI 3.13.0.341

Crash Report: http://pastebin.com/TSiprLcC

**Comment by shartte** [comment] 2016-11-02 21:59
Duplicate of #2557
Fixed with next release or nightly build.

Just out of curiosity: Can you try deleting your Facades.cfg and creating a new world to check if the problem occurs there as well?

**Closed by shartte** 2016-11-02 21:59 UTC

**Comment by QuantumSheep** [comment] 2016-11-03 08:47
I deleted Facaddes.cfg and created a new world... It's work!
