### ISSUE TITLE
Inscriber name plate resulting in game crash

### ISSUE THREAD

**Issue by bkbarbee** [AppliedEnergistics/Applied-Energistics-2#3485] opened 2018-05-08 00:37 UTC
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 1.12.2 - 14.23.3.2655

So what I was doing was I had an Inscriber attached to my network, and a name plate already in it. It was not the name plate I wanted, but I went ahead and shift-clicked my Interface and other name plate into it. As the Inscriber began working (I assume using the top name plate) I shift-clicked the top nameplate out of the Inscriber, and the game crashed. I tried to reload my save, and the game crashed again. Unfortunately, I was unable to find the log for the first crash, but in the link below is the complete log from startup to crash when attempting to load the old save.

https://pastebin.com/MS3RYx9k

**Comment by bkbarbee** [comment] 2018-05-08 00:49
I was able to replicate the bug exactly as it happened the first time in a brand new game. The setup was simply a creative energy cell sitting beside a single controller, which had about 3 Dense ME Cables - Blue running directly into the Inscriber. I made two name plates, got an Interface (block version), and shift-clicked in the order of plate 1, Interface, and plate 2 in, and then plate 1 out. After about a second's time (I do not know if it was frozen or not), the game crashed. Below is the complete log.

https://pastebin.com/JSqJDKF1

**Comment by Pingger** [comment] 2018-05-08 08:15
Possible duplicate of #3476 ?

**Comment by bkbarbee** [comment] 2018-05-08 11:39
Crash replicated perfectly once again, but this time with only AE installed. Below is the log, but only the crash report portion this time (sorry about that).

https://pastebin.com/PnQrSya4

**Comment by mindforger** [comment] 2018-05-08 11:48
that is one good clear report, thank you :)

@Pingger was right, this is the same, i will close this issue then and the devs will pick up on that other issue then

**Closed by mindforger** 2018-05-08 11:48 UTC
