### ISSUE TITLE
Unlimited Redstone crafting (redstone shower)

### ISSUE THREAD

**Issue by fsedarkalex** [AppliedEnergistics/Applied-Energistics-2#3241] opened 2017-11-21 18:27 UTC
I don't know if thats an AE2 Bug or specific to Modern Skyblock 2 but I got told it also happens in other packs.
When you build a standard fluix crystal automation...
 
(ME Interface 1 -> Formation plane) -> water -> (annihilation plane -> Storage bus) -> ME Interface 2 connected to main ME containing the pattern and directed to interface 1
subnetworks enclosed in brackets
 
...you will notice that the ME Interface 1 will export an unlimited amount of redstone.
You can try this by putting one redstone dust into export slot 1 of interface 1. The formation plane will then drop about 1 redstone per tick (without consuming any redstone from ME of course as it has no access to it).

Video: https://www.youtube.com/watch?v=7L3NTd2dZGA

- Minecraft Version: 1.12.2
- AE2 Version: rv2-stable-2
- Forge Version: 14.23.0.2548

**Comment by yueh** [comment] 2017-11-21 18:33
Duplicate of #2791

**Closed by yueh** 2017-11-21 18:33 UTC
