### ISSUE TITLE
Last nightly builds crashing when placing some AE2 blocks

### ISSUE THREAD

**Issue by flonou** [AppliedEnergistics/Applied-Energistics-2#2590] opened 2016-11-06 18:00 UTC
[crash-2016-11-06_18.47.21-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/573995/crash-2016-11-06_18.47.21-server.txt)

I added the crash log file.

Tried it on an empty world, seems like some blocks (not ores for example, ae controller or energy converter for exemple) from AE2 are causing a crash when they are placed in the world

- Minecraft Version: 1.10.2
- AE2 Version: rv4-nightly-f85ab7 was the first to present this crash it seems. Last nightly also crashes
- Forge Version: 12.18.2.2107

**Comment by shartte** [comment] 2016-11-06 18:01
Duplicate of #2569. 
The fix is already in the pipeline (#2581), right now the workaround is to have IC2 installed. Sorry!

**Closed** 2016-11-06 18:01 UTC
