### ISSUE TITLE
Going into spatial storage brings me into ae2 dimension, and then the screen goes white and I start suffocating

### ISSUE THREAD

**Issue by kaweepatinn1** [AppliedEnergistics/Applied-Energistics-2#4906] opened 2021-01-04 04:35 UTC
**Describe the bug**
My spatial storage works perfectly fine with blocks, but when i try entering it, I just get located into a block and start suffocating, and I cannot mine the block.

**To Reproduce**
Create 128 by 128 spatial pylon setup (or 2by2 ive tested that too). Power spatial IO port with button while inside the zone covered by the pylons

**Expected behavior**
Meant to be teleported into a room which I can interact with, with the blocks that I put in there too

**Additional context**
![2021-01-04_12 27 30](https://user-images.githubusercontent.com/37656629/103501141-4f6d1600-4e88-11eb-85e5-4c7ddf701ffa.png)

**Environment**
Spatial storage cell says *unformatted*, unsure how to change.
https://pastebin.com/1w2WAZJE
Checked server console, says "could not serialze .... " many times while teleporting into world, but this happens quite often so I'm not sure if it changes anything

- Environment:

**Comment by kaweepatinn1** [comment] 2021-01-04 06:18
Update: I tried moving mobs there, and then going there too. It seems that the mobs suffocate, and items slowly go up, like they would with solid blocks.

**Comment by mindforger** [comment] 2021-01-04 09:37
your coordinates look kind of wrong, either ae does not teleport entities correctly or some other mod might interfere with the spawn location
Please try this again in a fresh world with the same pack and with only minimalistic mods to confirm the issue is within ae

**Comment by kaweepatinn1** [comment] 2021-01-04 12:22
Same pack and minimalistic mods? Can you clarify what you mean by these? they seem quite contradicting as the modpack I use (all the mods 6) is quite big.

**Comment by mindforger** [comment] 2021-01-04 12:42
make 2 new worlds, one with that exact same pack but only a couple of spatial test setups to verify the problem persists in new worlds and one with AE and some of the "quality" mods like optfiine, mapping mods or other cosmetic stuff you use to verify it is not a cross mod interaction with any other "dimension changing" mods ... a third world with just AE would also be nice but since i made a world and it did not happen to me i guess the issue is somewhere between mods or world specific!

also make sure to place your setups a couple blocks away from each other so you do not only test in one spot of the world!

i am yet not sure where exactly they are but try something close to 0

**Comment by kaweepatinn1** [comment] 2021-01-04 12:46
Took a look at the coords in the old world, looks like they just tp'd me to what my coords were initially in the overworld. Checked all quadrants within a 50 block area and couldn't find the spatial zone. Will try again later. Creating a new world right now to test if the problem persists!

**Comment by mindforger** [comment] 2021-01-04 12:47
you can also try to port something into the dimension that you can track or teleport to :D

**Comment by kaweepatinn1** [comment] 2021-01-04 12:51
yeah, I was trying to think of something that could do that, but modded blocks need to be whitelisted with ae2 first or something first, and entities just teleport to where I was before. If you think of any vanilla things that work though, do let me know!

**Comment by mindforger** [comment] 2021-01-04 12:52
well i am not exactly sure and i also have no experience with them beyong MC 1.12 but you could probably try to enable ans use a command block that broadcasts it's current coordinates

**Comment by kaweepatinn1** [comment] 2021-01-04 13:07
But if my spatial storage is 128 blocks high, shouldn't it go all the way up until above 128 blocks? Game crashed and I'm reloading it rn.

**Comment by kaweepatinn1** [comment] 2021-01-04 13:32
Got into the new world, looks like same issue persists. I tried putting some blocks into the spatial storage and looking for them, but they wouldn't show. Then I went into spectator, flew around and looked for them. no luck. I then filled an area with air and got some blocks placed, it seems like blocks should show, so there's no reason for me not being able to locate the other blocks. The storage still works the way it's meant to but I just can't find the things I stored 
![2021-01-04_21 28 07](https://user-images.githubusercontent.com/37656629/103539893-ca0f5300-4ed3-11eb-8d09-fce4f1257c86.png)

**Comment by mindforger** [comment] 2021-01-04 13:50
yes you are right, i just can't understand what this "& 15" bitmasking is all about i fogot a spatial can be way bigger than 15 :D

**Comment by kaweepatinn1** [comment] 2021-01-04 15:14
Haha that’s fine I really appreciate you helping :D Though it’s night in my time zone rn so i’m gonna sleep, i’ll see if i can work on this tomorrow! Again, thanks for all the help you’ve been!

**Comment by kaweepatinn1** [comment] 2021-01-05 00:43
So I tried a few things. First I tried a simple redstone timer to activate and teleport me to the command block after it was sent into the dimension, but that didn't seem to work. Then I tried a repeating command block being sent in. Didn't work. Then I tried a repeating clock rigged to a command block. It still didn't work. It seems like chunks probably aren't loaded in the dimension by default, which means that any command block I send will not work. Any ideas?

**Comment by mindforger** [comment] 2021-01-05 04:58
what are the coordinates the block has been ported to and what are yours compared to overworld?

**Comment by kaweepatinn1** [comment] 2021-01-06 12:13
AH sorry for not replying for a day I completely forgot about this. My Spatial setup put me at about 320, 65, -320, while my overworld coords were -100, 65, 375. All of these are approximate. The block I was ported to was _exactly_ that of what I had in the overworld.

**Comment by mindforger** [comment] 2021-01-07 10:06
i am currently a little lost in understanding the code, it looks to me like the coordinates should never be different, so my wildes guess is there is some other mod hooking into the process and the coordinates are changed between calls or mutated ... the problem here is one would have to take this big modpack and test it throughly by binary search to find the culprit

**Comment by yueh** [comment] 2021-01-07 13:26
Cannot reproduce this with AE2. 

As already assumed, it looks like some other mod does interfere with the teleport between dimension. I would recommend reporting it to the modpack itself, they should certainly be better setup to handle bugs introduced by their mod picks.

**Comment by kaweepatinn1** [comment] 2021-01-07 15:08
Alright thank you everyone for responding I will report this to the modpack owners. Thanks you!

**Comment by yueh** [comment] 2021-01-07 15:12
Also as additional information, we had a similar problem as Forge was missing a patch from earlier release, which was more or less needed to teleport between dimensions. We did provide our own patch for it, but Forge readded the old patch in one of the more recent releases and broke our one with it. So I guess any other mod providing a way to teleport between dimensions could be affected in a similar way. Or break the new behaviour of Forge again.

**Comment by kaweepatinn1** [comment] 2021-01-07 15:14
Is it still broken right now then? or fixed?

**Comment by yueh** [comment] 2021-01-07 15:21
Our teleport is fixed to work with the recent forge one. But in case some other mod tries to replace it with their own broken solution or the old Forge one, it can also cause our to break again. However we certainly won't fix or add workarounds for mods breaking the normal Forge/Vanilla behaviour.

**Comment by kaweepatinn1** [comment] 2021-01-07 15:25
I see, this makes sense. The modpack in question has updated recently though, and although it’s unlikely, I will test the spatial storage tommorow (it’s quite late where I live) to see if it’s been fixed. Otherwise will report the problem and wait for a fix.

**Comment by shartte** [comment] 2021-01-11 19:35
@kaweepatinn1 If you have op, you can use the `/ae2 spatial` command to easily teleport back and forth between spatial cells (called plots in that command) and the overworld.

**Comment by plebania** [comment] 2021-01-25 08:51
I Have same issue, but the ae2 is the only mod I've installed

**Comment by mindforger** [comment] 2021-01-25 12:43
go ingame, presss and hold F3 + C until it crashes, copy the crashlog content to pastebin and link it hre please for more detailed setup info

**Comment by plebania** [comment] 2021-01-25 18:14
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 25.01.21 19:13
Description: Manually triggered debug crash

java.lang.Throwable: null
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:423) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1539) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.29.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.29.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:423) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Plebania'/231, l='ClientLevel', x=6.50, y=74.00, z=-238.26]]
	Chunk stats: Client Chunk Cache: 441, 225
	Level dimension: appliedenergistics2:spatial_storage
	Level spawn location: World: (16,71,-240), Chunk: (at 0,4,0 in 1,-15; contains blocks 16,0,-240 to 31,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 5425 game time, 5425 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.29.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.29.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.4.0-45-generic
	Java Version: 1.8.0_265, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1713247176 bytes (1633 MB) / 3456106496 bytes (3296 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.29.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.29
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.29-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.29-universal.jar                |Forge                         |forge                         |35.1.29             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appliedenergistics2-8.1.0.jar                     |Applied Energistics 2         |appliedenergistics2           |8.1.0               |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
	Crash Report UUID: c41d0e84-8e68-48cf-a318-64cac65fb1a8
	Launched Version: 1.16.4-forge-35.1.29
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa Intel(R) HD Graphics 520 (SKL GT2) GL version 4.6 (Compatibility Profile) Mesa 20.0.8, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz

**Comment by mindforger** [comment] 2021-01-25 20:14
Thank you for the details, nur next time please use pastebin instead posting so much text here.
Hope the devs can figure it out, yueh already mentioned a forge based teleport bug

**Comment by plebania** [comment] 2021-01-25 20:30
Oh, sorry for that

**Closed** 2021-03-25 06:58 UTC
Labels: awaiting-feedback
