### ISSUE TITLE
An export bus with a crafting card is failing to craft, when the required materials are in a connected network

### ISSUE THREAD

**Issue by Stuienator** [AppliedEnergistics/Applied-Energistics-2#3830] opened 2018-11-18 09:18 UTC
#### Description

I'm attempting to set up an automatic ore-processing sub-network, that uses petrotheum from thermal foundation.

The expected behaviour of my setup is that the export bus connected to the YABBA barrel should see that there is space to export, and given that it has a crafting card and is set to craft only, it should craft a pair of petrotheum dust and output it to the barrel.

However no such action is taken. As you can see in the images, the whole network has power (provided by the parent network) and sufficent channels, and in fact I can manually issue a crafting request from the terminal attached to the subnetwork, and it works perfect, adding two dust to the barrel.

As a side note: I tried adding the required resources directly to the subnetwork, in its own me drive. And when I did that the autocraft worked perfectly, so the fact that the ingredients are stored in the parent network is crucial to the problem here

Relevant images:
The pink cables are the paren network, containing the resources needed to craft, in the image you can see pink -> interface -> storage bus -> blue, which gives the blue subnetwork access to the parent networks resources. There is also a quartz cable attached, which is providing power to the subnetwork.
You can ignore the background of the first image, it's was my first attempt at the setup in which I ran into the problem, I then simplified it until I reached this core problem, but now it's completely disconnected from the network.

Any assistance in telling me how I have incorrectly made the set up, or a work-around to the problem will be greatly appreciated
![0](https://user-images.githubusercontent.com/40689875/48670635-782bd780-eb6a-11e8-82dc-11f8c83dba76.PNG)
![1](https://user-images.githubusercontent.com/40689875/48670641-7f52e580-eb6a-11e8-8682-99e773b03b59.PNG)
![2](https://user-images.githubusercontent.com/40689875/48670642-824dd600-eb6a-11e8-9c8e-856fa39c301e.PNG)
![3](https://user-images.githubusercontent.com/40689875/48670643-82e66c80-eb6a-11e8-9de3-5d9422ca9bd8.PNG)
![4](https://user-images.githubusercontent.com/40689875/48670644-837f0300-eb6a-11e8-982e-cd160bade09a.PNG)
![5](https://user-images.githubusercontent.com/40689875/48670645-837f0300-eb6a-11e8-9fd2-26904f56b09c.PNG)
![6](https://user-images.githubusercontent.com/40689875/48670646-837f0300-eb6a-11e8-9b7f-183c034bcf39.PNG)
![7](https://user-images.githubusercontent.com/40689875/48670647-84179980-eb6a-11e8-8773-f2ce2384aebc.PNG)

#### Environment

- Minecraft Version: 1.12.2

- AE2 Version: rv5-stable-11
- Forge Version: 
- Modpack: MP FTB Revelation, with additional mods added. No pro

**Comment by yueh** [comment] 2018-11-18 10:10
Duplicate of #1949

**Closed by yueh** 2018-11-18 10:10 UTC

**Comment by mindforger** [comment] 2018-11-18 10:12
First issue is using rv5 which is ages old 

second MAYBE issue, is you don't have any power storing blocks on that subnet as it seems, which could probably mean your subnet is maybe bootlooping ...

You can Test the second issue by crafting more than one item and if it does not craft all, your subnet is stalling

@yueh can you give a hint for our all knowledge, if a subnet via glass fibre shares the capacity of both networks or has its own capacity, regarding input power limit?

**Comment by Stuienator** [comment] 2018-11-18 10:56
Turns out that the fix to #1949 did work here. I looked for ages and couldn't find a duplicate like that. Guess I'm just not good enough at looking haha. Thanks for the help!
