### ISSUE TITLE
Using Interface with Mekanism crash the server

### ISSUE THREAD

**Issue by worblood** [AppliedEnergistics/Applied-Energistics-2#2639] opened 2016-11-20 09:48 UTC
#### Description

> It's when I use an interface connected to machines from mekanism i get a server crash. If I'm right It have to do with copper grit or dust, when pushed into the advanced smelting factory. I use enderIO conduit to pull items from the interface and into the mekanism-machines. They auto-eject back directly into the interface. Could it be one or more items being incompatible with AE2?

edit: I traced to problem to copper dust from Mekanism. I also have a theory that it happens when pushing many items at once instead of just one and one.

#### Environment
Mods I use in this particular projekct are enderIO, RFToools, AE2,  Actually Additions and Mekanism. I also have some storagebus for modular storage from RFtools on my ME-system. Normal Biomesop overworld, working in a bunker downstairs.

Complete crashlog:
http://pastebin.com/zCsAqVrd

- Minecraft Version:  1.10.2
- AE2 Version: rv4-alpha-6
- Forge Version: 12.18.2.2147

**Comment by yueh** [comment] 2016-11-21 11:50
The crash here is actually intentional. Otherwise the interface would start destroying items.

If it is reproducible, can you please verify it with build 5?

**Comment by worblood** [comment] 2016-11-22 08:17
No, I've had no trouble with it in build 5, but in build 6 it's all the time.

**Comment by yueh** [comment] 2016-11-22 10:48
Than it is most likely a duplicate of #2626. You could try and fetch a nightly build. Except latest build did not succeed, probably some issue with the CI itself. But you can still try the build before.

**Closed by yueh** 2016-11-22 10:48 UTC
Labels: state-waiting
