### ISSUE TITLE
[1.12.2] Cable facades may be broken [No CTM] [No animation]

### ISSUE THREAD

**Issue by JonasCiss** [AppliedEnergistics/Applied-Energistics-2#3298] opened 2017-12-30 09:42 UTC
I was playing Minecraft when I noticed that some facades were broken. There texture was invisible and CTM did not work. First I thought it was a bug with Optifine but it happened again after I have removed Optifine. 
Here is a picture of the borken facades. I used Futura Blocks of Chisel.
![2017-12-30_10 28 42](https://user-images.githubusercontent.com/26455012/34453189-a7570faa-ed4d-11e7-982d-804b4098f759.png)

The I compared with other facades of Thermal Dynamics. This facades seem to be working. 
![2017-12-30_10 28 12](https://user-images.githubusercontent.com/26455012/34453192-be488a90-ed4d-11e7-8260-caf16d73073d.png)
![2017-12-30_10 28 21](https://user-images.githubusercontent.com/26455012/34453193-c28c970e-ed4d-11e7-8860-407c43fd9d04.png)

Forge: 14.23.1.2562 
appliedenergistics2-rv5-stable-3.ja
Chisel - MC1.12-0.1.1.24 
CTM - MC1.12-0.2.3.9

**Comment by JonasCiss** [comment] 2017-12-30 09:44
ThermalDynamics-1.12.2-2.3.8.16
ThermalFoundation-1.12.2-2.3.8.22
CoFHCore-1.12.2-4.3.8.29
CoFHWorld-1.12.2-1.1.1.12
CodeChicken Lib 1.12.2-3.1.5.331

**Comment by yueh** [comment] 2017-12-30 09:47
Duplicate of #285

**Closed by yueh** 2017-12-30 09:47 UTC
