### ISSUE TITLE
duplicate item provided using give command for singularities and quantum entangled singularity

### ISSUE THREAD

**Issue by DelviousCrafts** [AppliedEnergistics/Applied-Energistics-2#6779] opened 2022-11-18 23:29 UTC
### Describe the bug

When using the "give" command or any mod that provides items using this command (such as FTB Quests, which is the reason for reporting at all) provides a duplicate item for singularities and quantum entangled singularity.

### How to reproduce the bug

1. Use the "/give @p ae2:singularity" (or obviously quantum entangled singularity) command to provide a player with the said item. Alternatively, create a quest in FTB quests that provides either item for a reward. (obvious installation of FTB Quests required)
2. Be provided with an additional, unrequested item.

### Expected behavior

To be provided with only one of the requested items using the give command.

### Additional details

Occurs with no other mods installed aside from AE2.

AE2 version: 11.6.4

[Link](https://gist.github.com/DelviousCrafts/38bcb5fa6923497ce047ba2427af55e3) to latest log with only ae2 installed after the error occurred in case that helps as well. 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

[link](https://gist.github.com/DelviousCrafts/3842c5f94a6762fc91257c74fe699be5)

**Comment by DelviousCrafts** [comment] 2022-11-18 23:58
During further work I was completing this also appears to be an issue for both fluix and certus quartz seeds

**Comment by Technici4n** [comment] 2022-11-19 09:41
This is caused by our custom item entities for these items. This has been fixed in 1.19 already, and it's minor enough to not fix in 1.18. (The fix is not easy to backport). Thanks for the report though. ^^

**Closed by Technici4n** 2022-11-19 09:41 UTC
Labels: bug
