### ISSUE TITLE
MCFlux reports errors/bugs on AE2's implementation of energy network

### ISSUE THREAD

**Issue by kaitoyuuki** [AppliedEnergistics/Applied-Energistics-2#2598] opened 2016-11-07 18:58 UTC
#### Description
MCFlux reports bad forge energy implementation from Applied Energistics, printing errors to server console periodically and printing a massive number of errors to clients on loading a server/SP map.

I would appreciate if this could be rectified, as the errors cause significant strain on my system and I really can't go without either AE2 or MCFlux. I apologize if this issue has been previously reported, as searching MCFlux in the issue tracker turns up no relevant results.
#### Environment

FML log: https://gist.github.com/kaitoyuuki/a96f0da26f98466205011d45d9b8bdae
Single isolated stacktrace: https://gist.github.com/kaitoyuuki/0d4ae8f1c1d017e6810e1ffa5f24fd5e
(most of the error traces appear to be extremely similar, if not the same)
- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 4
- Forge Version: 12.18.2.2122 for Minecraft 1.10.2
- MCFlux version:  mcflux-1.4.0-b5

**Comment by yueh** [comment] 2016-11-07 19:26
I do not see any issue here with AE2. MCFlux expects a partially initialised object to behave correctly, which is pretty much flawed in every way.  Also forge does not specify anything about the initialisation behaviour of an object in terms of caps. Would there be an issue, they would already throw a warning similar to other common mistakes.

**Comment by gdude2002** [comment] 2016-11-07 19:44
Reporter is a user of my server; I've also reported this ticket to the McF guys [here](https://minecraft.curseforge.com/projects/minecraft-flux/issues/1).

**Comment by gdude2002** [comment] 2016-11-07 20:00
For whatever reason, my issue was automatically marked as spam. I'll update here once I've heard from the author.

**Comment by yueh** [comment] 2016-11-09 11:48
Closing it for now. I can understand their approach to avoid adding duplicate caps to a tile entity and thus wasting memory or potentially even having ticking ones around.

But the implementation/time is not ideal. At this point the tile is still invalid, not placed into a world and have not even be deserialised from any NBT config. Thus the might even expose the same cap on that side at sometime later. And return false or even crash until that has happened.

It can probably not be even resolved due to the cap initialisation at this time being a design flaw in forge itself. Except there would be an event for a tile entity becoming valid and would still be possible to attach a cap at that point.

**Closed by yueh** 2016-11-09 11:48 UTC

**Comment by gdude2002** [comment] 2016-11-09 11:53
Interesting, okay. I can confirm that the dev is aware of this ticket, I'll let him know your comments as soon as I can. Unless you guys want to DM him on curse or something.
