### ISSUE TITLE
Inscriber doesn’t work with AE2 cables

### ISSUE THREAD

**Issue by VisMortua** [AppliedEnergistics/Applied-Energistics-2#5324] opened 2021-07-04 07:05 UTC
Trying to Automate making chips. I set up the whole thing but the inscribers don’t have power. I hooked up the TRSolar to the Energy Acceptor and connected the ME Controller with smart cables; ME Controller Powered. In the same network, I placed smart cables and the inscriber but there was no power to inscriber. I place the inscriber above, below, left and right but no power. I placed 4 TRSolar, attached to a Energy Acceptor, used 4 different AE2 cables and none have power.
![49A0DD62-CB01-4C2E-9131-1429CC903D11](https://user-images.githubusercontent.com/86904010/124376350-da766f80-dc63-11eb-866d-28e716636e90.jpeg)
![2EEE86FD-2492-4185-89BE-47FC7EDF0340](https://user-images.githubusercontent.com/86904010/124376353-dcd8c980-dc63-11eb-9b99-127e3e069e96.jpeg)
![3EE00164-E4EF-4775-8AA7-561AF9F3AAE2](https://user-images.githubusercontent.com/86904010/124376354-dd716000-dc63-11eb-9042-938b131cf177.jpeg)
![A6A5B6B8-A308-4446-906B-AA2562DA1EAD](https://user-images.githubusercontent.com/86904010/124376355-de09f680-dc63-11eb-9ead-264c10225eba.jpeg)

**Comment by Technici4n** [comment] 2021-07-04 07:29
Please send us the information that is in the issue template.

**Comment by yueh** [comment] 2021-07-04 07:56
Duplicate of #1316

**Closed by yueh** 2021-07-04 07:56 UTC
