### ISSUE TITLE
Add support for more than 9 items to autocrafting.

### ISSUE THREAD

**Issue by kriNon** [AppliedEnergistics/Applied-Energistics-2#3540] opened 2018-06-16 18:29 UTC
I am aware that this functionality has been requested and dismissed multiple times in the past, however I would like to try to change your minds.

#### Description
In #3380 it was stated that not having support for more than 9 items in a recipe is "by design" and this will not be changed unless vanilla adds recipes larger than 3x3.

I would firstly like to state that the lack of this functionality does not prevent the automation of large recipes using AE2. It simply forces users to instead separate the recipes into multiple stages with token items being used to link between the individual recipes. This method is not in the spirit of AE2, however it is what users often resort to doing in modpacks where the automation of large recipes is a central part of the progression designed by the pack author.

Whilst on one hand I can agree that any large recipe can easily be separated into multiple smaller recipes by the mod/pack author, I do however believe that larger recipes do not fulfill the exact same role as regular vanilla recipes. Namely:

- Splitting one 9x9 recipe into 9 3x3 recipes introduces the need for more items to be created solely for the use of being crafting components. 

- Using 9 3x3 recipes adds tedium to crafting.

- Using 9x9 recipes for end-game content has a greater sense of scale, which is a feature that is useful for pack authors.

If it is the belief of the AE2 dev team that any recipe greater than a 3x3 was designed as such to prevent automation, then having a limit on the creation of greater than 3x3 recipes is logical. However I believe that this limit should not be on such a structural level, because it prevents the development of addon mods for AE2 which the user or pack author could install to bypass this limit.

Some mod packs are designed around the fact that the Automation of 9x9 recipes is an endgame goal (for example, Project Ozone 2: Reloaded), however without changes to the AE2 codebase, modpack authors are unable to achieve this using AE2. This functionality is already available using Refined Storage, through the use of the addon [Refined Avaritia](https://minecraft.curseforge.com/projects/refined-avaritia), however many of AE2's features make it preferable for expert-styled modpacks.

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2705

**Comment by yueh** [comment] 2018-06-16 19:06
Duplicate of #3380

**Closed by yueh** 2018-06-16 19:06 UTC

**Comment by XvBUSHvX** [comment] 2018-08-20 03:47
I can understand if this topic is a thorn in your side, my only request is your time, if even reluctantly, to read this. 

I'm not opening a new issue to weigh in on this topic, so it will save you the trouble of closing it if what I have to say makes no difference in your judgment. I am avoiding using the name of other mods in this comment out of respect that this issue tracker is for AE2, and the context of the mods I reference doesn't relate to compatibility with them.

Given the usefulness of the mods, for pack makers, that provide features you have been asked to provide compatibility for, I am at a loss understanding the reasoning for refusal. I do not possess the knowledge to code or even understand the complexities of making mods, though, that doesn't seem to play a role in it.

It is my intention to develop a high quality and challenging, yet not tedious, mod pack to the community. The concept I have been working with replaces the 2x2 crafting matrix in the inventory with the 3x3 crafting matrix from the beginning. My premise for the early game is intended to represent that much of what is created for survival came about before a special table to craft on.

The progression of this pack will replace the standard vanilla crafting table with specialized crafting tables. Even tables with 3x3 matrices will require accompaniment of specialized tools for the crafting task. Then utilizing other crafting mechanics provided by number of other mods with specialized crafting tables, beyond any NxN matrices, that reflect the current stage of progression. And eventually leading up to larger "assembly" recipes. All with the hope of avoiding the tedium of "rabbit hole crafting chains", by using a selection of common materials in a larger recipe to represent the evolution of technology akin to the realistic growth of the modern era. 

It is during these later stages of crafting that AE2's  storage, auto crafting, and eventually relocation mechanics, were to be implemented. Providing users with challenging, yet rewarding, aspects to explore. With its own innate complexity and the ability to begin automating the more involved crafting recipes that were planned, AE2 would have beautifully transitioned the pack from modern technology, to high tech, and into the sci-fi levels of technology. 

I have been highly resistant to using AE2 competitor mod, even when choosing packs for my own playing. It just too simplistic for my tastes. It serves a purpose and isn't a bad mod, just not my particular flavor. I play survival because I want to build fancy things with a challenge, which may not be preferred by anyone, but me anyways. 

I suppose the only real reason I'm even commenting in here, is because of the complete and total sense of disappointment when realizing that I won't be able to use AE2 as I had intended and that I was going to have to use a "watered down version" of AE2 to achieve my goal. It just honestly sucked when that sank in.

I can respect and appreciate your decision, regardless of if I get it, Still a loyal fan of the mod and will play it any chance I get. Thank you for your time in both reading this and continued development on one of my favorite late game mods.

**Comment by XvBUSHvX** [comment] 2018-08-20 07:31
Man, I honestly went out of my to be tactful in that post, I always do. I was expressing my own sentiment as a fan of the mod, and the let down it was to me personally. I conveyed how I had looked forward to using the mod in a Pack project I have been planning and how this mod played an integral role in that plan.

Now...

How was I wrong? What was I wrong about? Did I, as you claim, make any actual claim or lay blame? What so ever

Given as you quoted me stating:

> I am at a loss understanding the reasoning for refusal. I do not possess the knowledge to code or even understand the complexities of making mods, though, that doesn't seem to play a role in it.

Which was taken out of context. The complete sentence is;

> Given the usefulness of the mods, for pack makers, that provide features you have been asked to provide compatibility for, I am at a loss understanding the reasoning for refusal. I do not possess the knowledge to code or even understand the complexities of making mods, though, that doesn't seem to play a role in it.

I was referring to the explanation given in #3380, namely;

>  That is by design and will not change until vanilla itself uses recipes larger than 3x3 or something makes it absolutely necessary like no more InventoryCrafting.
>  
> **We pretty much assume recipes with more than 9 items are intentionally designed to prevent autocrafting and respect it.** Otherwise the mod/pack author could just use (micro)crafting and split it into multiple 3x3 recipes with intermediate products. 

That, honestly sounds like it was a decision to stay within the "conceptual limitations" of the vanilla game, I don't recall any "vanilla autocrafting mechanic" outside of the furnace. Perhaps that refers to pack developers, who are actually the people who are asking for the feature? Either way that doesn't sound like a technical programmatic reason if it's the "assumption that recipes with more than 9 items are designed to prevent autocrafting". Auto Crafting is an element that's not even in the game unless you are playing modded.

Now, I stated clearly that I do not have the technical knowledge to fully comprehend any other reasons, but that didn't sound like a technical reason.  Are you saying that I am wrong about my, not understanding? 

I will agree first that you are indeed quite rude. Personal opinion or otherwise, with a collaborator badge next to your name I would think you would conduct yourself with a bit more civility lest someone think you are speaking as a representative of the AE2 team. Fortunately you were quick to distance yourself in that aspect with the disclaimer. 

In further responses to this it would be appreciated if you could clearly define what I have done to deserve you taking such a tone with me. To clearly express why you felt the need to speak condescendingly in your response. 

First off, I made no claims and blamed no one. In no way, shape, or form, can anything I said be taken as accusation, attribution of fault, or blame of any nature. Perhaps I should have directly quoted the given reason I was having trouble understanding, as I have earlier in this response. However since the original poster of this thread addressed it, I didn't feel the need to be redundant. I felt safe in the belief that we were all on the same page.

Now, I'm not well known in the community, nor even someone very active, and honestly wouldn't want to be given I don't have the skills to be of any more use than an occasional idea. I've always been very honest about my inability to code, or even model or even create graphics. And try to conduct myself humbly among individuals I see as very talented and hold a great deal of admiration and reverence for. 

But that in no way gives you the right to take the what I said out of context and speak down to me like I have no clue or understanding of what it is like for the developers of the mods. 

On the contrary, I have a great deal of admiration for each and every mod developer I meet. I may not understand the intricacies of code and the exact steps that are needed to be taken to make something work. But, I'm not completely ignorant to anything you deemed to educate me on like the pitiful fool I am. 

I've learned to be very thoughtful of those types of roadblocks in the suggestions I make. I Respect that when it's all said in done the developers are making mods as a hobby and hold no obligation to do anything requested or suggested. I tend to speak to them with the utmost courtesy. If no better reason if it weren't for them I wouldn't be able to say I have a favorite mod. Or even that AppliedEnergistics 2 was one of them. 

You, are the one that is wrong. You were wrong in your interpretation of my statements in the first place. You don't really even appear to be versed in the reasons I am questioning in the first place. Then you're idea of defending the reasons appears in the form and manner of 'you stoopid noob you don't know what all it takes'. Is it excusable, because you say "...it may sound rude..." and that you're "making a point from your personal opinion", to speak someone that way? 

You managed to overlook the majority of anything I even wrote about in your zeal to berate someone you don't even appear to have understood. The entire post could have been summed up as;

> "Hey I don't really want to bother or be a problem. I don't get your reason for that not wanting to do that if you're able. I had all these plans for something I felt was going to be cool. Sucks that it won't work and makes me sad. Oh well that's life and it's your prerogative. Still love your shit. Thanks for hearing me out."
 
Maybe you had a bad day, maybe you're fed of with the number of people out there that don't have respect for the devs. I'm not one to tell, but I've snapped off before and gotten short with other users on CurseForge cause someone didn't express the proper respect in the comments. Felt like crap when I realized it was another dev and that I may not have understood everything involved. 

I've learned to take my time and make sure I understand what's actually being said. I'll get over this, but hopefully you'll find the time to learn that lesson yourself.

**Comment by mindforger** [comment] 2018-08-20 09:12
first of all sorry, english is not my native language so i often fail to sound more reasonable than technically (also the part with speaking like "it won't work that way duuuuhh") and i did not intend to offend you in any way but speak some clear words and not sound to soft to open up unnecceary discussions (an explanation to this is at the end, also please don't read it as harsh as i may sound, i really don't want to be mean but to explain)

my defense was made as simplistic as possible to show how the consequences most probably may look like to explain why there is so much resistance against such deeply impacting changes

i should have not left out the first part and if you feel it taken out of context, have my apology, but i wanted to be clear on the last part that there is indeed a big involvement of code required to get this into AE2 because crafting with the 3x3 grid is something that stronlgy relys on the default vanilla crafting.

PS: you have also taken my sentence there way out of context to let you know, i never spoke about autocrafting in vanilla ... but autocrafting in AE2 bases on the default vanilla crafting system and how recipes are handled.

To differentiate to the first part that io left out, many many compatibilitys are more like a "could you read that meta value as something else to let it work" or "could we comply about an interface where i can add my subsitutions or hook into the crafting to modify the items" or something like that

<details>
  <summary>Explanations slightly off topic inside</summary>
the part where i wrote about blame and contribution was maybe for you a bit of harsh but you are one of the more kind like people to ask things (and those are rare) ...

it's an unfortunate truth that mosty compats start with someone complaining, getting revoked about him beinng unpaitent or unreasonable until someone with common sense and a few hints on how to implement it or even a pullrequest ... so devs only havve to make sure it fits tight and can release it. But it is more common that people start questioning why or why not soemthing has be done this and not that way, which leads to some let's say preformed opinions on this kind of:

posts that are very old and closed and yet still someone without the technical background starts questioning the descision

i could say you just hit a nerve as it explaines it well but that would sound too cheap

you said you wouldn't bother the devs by making a new issue, but honestly ... better make a new one with references than poking at "closed ~~issues~~" wounds (i hope this translate well)

devs may sound more short than i am answering at most times because they have literally more urgent things to fix (1.12 is still a mess, even from forge side) so i try to be as specific as posible in my explanations and most times people just go away or start presenting solutiuons from their side when you come around with more detailed technical reasoning

>I've learned to take my time and make sure I understand what's actually being said. I'll get over this, but hopefully you'll find the time to learn that lesson yourself.

and as i think you were also in a bad mood when you responded liek that, so i won't take this as an offense but i have to make clear here that somebody taking his time to help or code stuff does not have the all time to read such big walls of text (no offense just for context) in every detail ... being polite is always a two way system but this time you put the pressure on me and that is also not nice

be conciderate in reading someones comments that he may not have the same language base like you or may not be able to give you an all nice and fluffy formated text (i am exeggarating for context) to be booted with the next answer (most time it is not worth to write everythign as nice as possible, but well i feel like havve still been but for other reasons than normally)

the contibution and blame thing is something i should explain but this would go way out of context

And finally a sorry that i did not answer all of you letter there, because i wanted to go into detail on what i can actually answer. What you are planning to do and what your opinions on other concepts are was not relevant to my answer there.

You can talk to me on discord if you want to talk it out, just hand me a PM

</details>

**Comment by XvBUSHvX** [comment] 2018-08-20 15:03
I appreciate you for taking the time to explain yourself, and attempting clear this out civilly. I can see there has been a slight barrier in communication at play here that was easily overlooked in your initial response, as most errors appeared to be typos not grammatical usage. 

I do tend to run into the "wall of text" complaint. It's a personal flaw I haven't been able to correct, and often apologize for it.

The comment I have been questioning was the reason @yueh had given in the #3380 issue, not yours. I can't say for sure if that wasn't taken out of context or an issue in communicating. That is where the auto crafting came up though. 

And yes, when I initially began to type that I was offended and upset about being spoken down to. Which I understand wasn't your intent. 

I'll keep in mind that even if I am discussing an old issue, even on that's been hashed out multiple times, it's better to open another issue. I had thought commenting in a closed issue would reduce pollution on the tracker and save devs or mods the trouble of closing a broken record. I understand the sentiment but if the issue is a "wound" then it would be no less a wound if it were fresh or reopened. 

Never the less, I have had an opportunity to sleep on it, and I'm sure we can both agree enough energy and effort has been has been exerted on this topic. I do thank you for you time,  and appreciate all the effort the team of devs, and collaborators, put into making this awesome mod. And Thank you for your time in addressing my comments.
