### ISSUE TITLE
Deletions in world

### ISSUE THREAD

**Issue by nlogozzo** [AppliedEnergistics/Applied-Energistics-2#3132] opened 2017-10-03 21:39 UTC
Minecraft Version: 1.12.1
AE2 Version: 1.12.1 RV5 Alpha 6
Forge Version: 1.12.1

Sometimes if I go out of the area of the ME network, the drives, wires, etc. will get deleted. I installed chunk loaders throughout the world where the blocks and network are, but it continues to happen and I am constantly backing up and restoring the world. PLEASE FIX!!

**Comment by fscan** [comment] 2017-10-03 21:43
Duplicate of #3013

**Closed by fscan** 2017-10-03 21:43 UTC
