### ISSUE TITLE
Clean install causing Failed to save chunk exceptions

### ISSUE THREAD

**Issue by sachaw** [AppliedEnergistics/Applied-Energistics-2#5088] opened 2021-03-23 09:01 UTC
**Describe the bug**

Clean install of MC & latest forge, only AE2 loaded, results in several `Failed to save chunk` and `Exception caught during firing event: null` exceptions, this seems to happen when exploring new chunks and at times spirals out of control spamming the log hundreds of times

**To Reproduce**

100% Clean MC, Forge `36.1.2` Latest AE2 jar from GitHub.
Create a new world and fly around for a few minutes.

**Expected behavior**

**Additional context**
https://pastebin.com/0HmsqA5m

**Environment**

- Environment: 
https://pastebin.com/jKgvYScP

**Comment by yueh** [comment] 2021-03-23 13:11
Duplicate of #5069

**Closed by yueh** 2021-03-23 13:11 UTC
