### ISSUE TITLE
Molecular Assembler locks up with items inside

### ISSUE THREAD

**Issue by icywhisker-official** [AppliedEnergistics/Applied-Energistics-2#6322] opened 2022-06-03 23:23 UTC
### Describe the bug

Upon auto-crafting what seems to be any random item, the ME system fails to complete the auto-crafting job. The items can be found in the Molecular Assemblers attached to the corresponding Pattern Assembler that the Problem resides in.
![unknown](https://user-images.githubusercontent.com/64947737/171965373-2ff37563-25ae-489c-b931-3f26fdc2c427.png)
 

### How to reproduce the bug

I have had this happen at least 8 times in my world. Usually it happens after extended play time, but within 2 hours. One time the bug happened right after I started the game. Begin an auto-craft, wait for the item to craft. Notice that the items needed to craft the item get stuck in the Molecular Assembler and do not craft.

### Expected behavior

The item requested will craft as expected and show up in the ME system

### Additional details

My world has a custom set Seed and the original chunks were deleted and the world was regenerated using prebuilt "vanilla items" only area as the base. I do not have Energy storage for the ME system and I have over 200 channels with over 40 pattern providers. attached is how I set up my Assemblers. I used cable anchors so each group of assemblers do not touch the Smart cables in more than one place. Note: the crash report does not contain the bug as it is happening as I did not know I would need one. I can gather another crash report upon request that DOES contain the bug as it is happening if that is necessary in the next few days. give me some time to get it though if you do need it
![unknown (1)](https://user-images.githubusercontent.com/64947737/171965682-691c281b-e593-4e41-bf15-940cd87ec5d4.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/0hFHQX47

**Comment by Technici4n** [comment] 2022-06-05 08:16
Is there anything of interest in the logs when this happens? Did the molecular assemblers unload and reload while they were crafting something? It _might_ be caused by the assemblers not being able to read the pattern again, then there should be `Unable to restore auto-crafting pattern after load` in the logs.

**Comment by icywhisker-official** [comment] 2022-06-05 08:59
Where should I locate the logs you're talking about? Is this the crash log?
The chunks are loaded by a chunk loader

**Comment by Technici4n** [comment] 2022-06-05 09:03
In the `logs` folder. In particular, `latest.log` will contain the latest log only - so make sure that you check it right after closing the game when the issue occurs, but before starting the game again.

**Comment by icywhisker-official** [comment] 2022-06-05 23:52
I have a logfile from march 15th with the issue happening shortly after having glass panes get stuck in the molecular assembler. unfortunately the log is too large to host in pastebin so I used google docs this time
https://docs.google.com/document/d/17xrT5B4-jFZxnWdrIr3dPJVeTPX8T4sYE7v0eU5BwkU/edit?usp=sharing

**Comment by Technici4n** [comment] 2022-06-09 18:20
The logs show that something is definitely wrong with your instance (somehow the piston recipe is missing from your client?). This is likely happening because of another broken mod, unfortunately I don't know which one it could be.

**Closed by Technici4n** 2022-06-09 18:20 UTC
Labels: bug, awaiting-feedback
