### ISSUE TITLE
[1.16.5]Server crashed with NoClassDefFoundError

### ISSUE THREAD

**Issue by ColdTearsYY** [AppliedEnergistics/Applied-Energistics-2#6319] opened 2022-06-02 14:38 UTC
### Describe the bug

My server crashed when playing and could not start even as I tried.Here is my crash report. https://paste.ubuntu.com/p/jP4Q56YYK7/
I guess it was something with the wireless network.

### How to reproduce the bug

I cannot figure out what made it.

### Expected behavior

Server went down.

### Which minecraft version are you using?

1.16 - MOSTLY UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://paste.ubuntu.com/p/jP4Q56YYK7/

**Comment by ColdTearsYY** [comment] 2022-06-02 14:42
And this is the log from the console when crashing.https://paste.ubuntu.com/p/jVWwmbDttN/

**Comment by Mari023** [comment] 2022-06-02 14:48
duplicate of #6028

**Closed** 2022-06-02 15:11 UTC
Labels: bug
