### ISSUE TITLE
Redstone Dust Duplication (Only in combination with other mods)

### ISSUE THREAD

**Issue by TheSirati97** [AppliedEnergistics/Applied-Energistics-2#2861] opened 2017-04-06 07:56 UTC
#### Description

An Inventory gets emptied by an import bus or interface. The item then gets dropped by an Formation Plane.  When the bug occurs the item gets dropped without getting removed from the inventory. Thereby duplicating the item. This behaviour was only seen with redstone (dust) so far.  Within my modpack this can be reproduced. 
It can be seen in action in this video:
https://www.youtube.com/watch?v=NG55vA5tg3o
Singleplay + simpler setup:
https://i.imgur.com/jTD01hd.jpg

Bug does not occur when only the latest version of Forge and AE2 are present. 

#### Environment

Both SP and MP
Mods:
Direworf20 and some other mods.
Full list of mods: https://pastebin.com/CxLG2Hdn

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: forge-12.18.3.2254

**Comment by mindforger** [comment] 2017-04-06 08:12
try this again one time with a normal chest and a second without ae2stuff

**Comment by TheSirati97** [comment] 2017-04-06 13:22
Hello.
I had already tried other inventories. For example I used a normal chest on the screenshot. But it also worked with every other inventory that  I checked. (All of the minecraft inventories and some mod inventories. I did not check all tho. There simply are to many)

I uninstalled AE2Stuff and the bug is occuring.

**Comment by GuntherDW** [comment] 2017-04-06 15:11
This is caused by Flux Networks.
#2791

Nothing the AE2 devs can do much about unless either mod adds special mod interaction cases.

**Comment by mindforger** [comment] 2017-04-06 17:37
oohhh i see, thx for the info, i'll close it because of duplicate bug then

**Closed by mindforger** 2017-04-06 17:37 UTC

**Comment by TheSirati97** [comment] 2017-04-07 02:46
I will fine a report there then.

**Comment by GuntherDW** [comment] 2017-04-07 03:15
There already was an issue on there. More than one even.
But the one specifically for SpongeForge got fixed.

https://github.com/SonarSonic/Flux-Networks/issues/58
Try to keep that in mind next time.

**Comment by TheSirati97** [comment] 2017-04-07 03:16
I looked for that actually and overlooked the report. :|
