### ISSUE TITLE
The storage cell world is missing

### ISSUE THREAD

**Issue by thetriangl** [AppliedEnergistics/Applied-Energistics-2#5250] opened 2021-05-24 23:41 UTC
When I send a Redstone input to a spatial storage bus it gives the error that The storage cell world is missing

**Comment by yueh** [comment] 2021-05-25 06:50
Duplicate of #5136

**Closed by yueh** 2021-05-25 06:50 UTC

**Comment by thetriangl** [comment] 2021-05-25 22:57
This happens on my fabric server not on a singleplayer world

**Comment by Technici4n** [comment] 2021-05-26 09:48
This is the same issue, please read #5136. We can't do more than what is written there.
