### ISSUE TITLE
[Fabric 1.16.5] Missing Textures on Blocks

### ISSUE THREAD

**Issue by JoytyNighty** [AppliedEnergistics/Applied-Energistics-2#5090] opened 2021-03-24 17:10 UTC
So I found this after I had crafted my first ME drives, terminal and cables in my world. The textures are missing and I'm unsure about how I put the cables. File: appliedenergestics2-fabric-8.2.0-alpha.3.jar
![2021-03-24_18 06 06](https://user-images.githubusercontent.com/41086683/112353634-3710d880-8ccc-11eb-88a3-606b6766c72c.png)
![2021-03-24_18 06 09](https://user-images.githubusercontent.com/41086683/112353636-38420580-8ccc-11eb-9f99-abc3a05deefb.png)
![2021-03-24_18 06 13](https://user-images.githubusercontent.com/41086683/112353637-38420580-8ccc-11eb-9ab9-d3e4a002a4d6.png)
![2021-03-24_18 06 16](https://user-images.githubusercontent.com/41086683/112353638-38da9c00-8ccc-11eb-8f68-bc5a2d7970bf.png)
![2021-03-24_18 06 32](https://user-images.githubusercontent.com/41086683/112353639-39733280-8ccc-11eb-9242-63184809de58.png)
![2021-03-24_18 06 34](https://user-images.githubusercontent.com/41086683/112353641-39733280-8ccc-11eb-8dfb-0a1e53da3ae8.png)

**Comment by yueh** [comment] 2021-03-24 17:20
Duplicate of #4760

**Closed by yueh** 2021-03-24 17:20 UTC
