### ISSUE TITLE
Server Crash Report - ArgumentException: inconsistent range

### ISSUE THREAD

**Issue by jc2xs** [AppliedEnergistics/Applied-Energistics-2#3835] opened 2018-11-24 21:29 UTC
**Describe the bug**
Server crashes when trying to craft the plant gatherer from Industrial Foregoing.

**To Reproduce**
This has been reproduced on my stoneblock server twice.  I've had to restore the server from backup in order to get it running again.  I was using the machine chassis from Thermal Foundation in the recipe for the plant gatherer.  The AE2 system had all of the patterns needed to create the final block from raw materials.  The crash happens as soon as I finish the request to craft the block.

**Expected behavior**
I expected the requested item (the plant gatherer) to be made.

**Additional context**
- Crash Report: https://pastebin.com/sUHDMdsd

**Environment**
- Stoneblock mod pack - v1.0.29

- Minecraft Version:  1.12
- AE2 Version:  appliedenergistics2-rv6-stable-4.jar
- Forge Version:  forge-1.12.2-14.23.5.2768-universal.jar
- Industrial Foregoing:  industrialforegoing-1.12.2-1.11.6-216.jar

**Comment by yueh** [comment] 2018-11-24 21:32
Duplicate of #3768

**Closed by yueh** 2018-11-24 21:32 UTC
