### ISSUE TITLE
encoded pattern can't display its output in ME interface with DragonAPI

### ISSUE THREAD

**Issue by lighdotdot** [AppliedEnergistics/Applied-Energistics-2#2902] opened 2017-05-05 06:53 UTC
#### Description
Encoded Pattern not show synthetic items.
Not shown on the Interface Terminal.
The other is the same, such as ME Interface, Terminal.
What should I do?

#### Environment
├─mods
│  │  appliedenergistics2-rv3-beta-6.jar
│  │  
│  └─1.7.10
│          DragonAPI 1.7.10 V16d.jar

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment] 2017-05-05 07:00
the image link is broken and your issue description does not fit in context with the headline
also what do you mean by "synthetic items" ?
what is "Not shown on the Interface Terminal." the pattern or the "synthetic items" ... i suspect you mean the icon of the item saying "craft" instead of the number?

**Comment by lighdotdot** [comment] 2017-05-05 10:09
Craft icon not show icon.
After viewing the code found that rv2api(DragonAPI 1.7.10 V16d.jar) and rv3api(appliedenergistics2-rv3-beta-6.jar) at the same time the problem makes the icon is not displayed.
What should I do?

**Comment by Ommina** [comment] 2017-05-05 10:38
Ah, OK.  Now this is familiar.

Normally when you create a crafting pattern and stick it into (for example) a molecular assembler, you see the icon for the item that will be crafted, not the icon of the blank pattern.

With DragonAPI installed, all you see is the blank pattern icon, although I _think_ pressing shift would work to display the "crafting result" icon instead.

I'm not aware of any fix.

**Comment by CraftMinerKyle** [comment] 2017-05-08 13:45
Ohhh...I've had similar issues with the Silicon Press textures being filled in and all I could see was the press outline, but when I clicked them or held "Shift", I could see the inside shape. I can't remember when or what caused this, but I remember seeing such things before.

**Comment by mindforger** [comment] 2017-05-08 14:17
@Yueh can you have at least a glance on this? i won't close it as such an API conflict would probably be not solved when all the changes get backported to rv3, this would then be a true rv3 issue that is not present in rv4

**Comment by GuntherDW** [comment] 2017-05-08 23:50
This is caused by DragonAPI ASM'ing the same place as AE2 does. I reported this bug in Reika's forum way back in 2014 even.
Let me see if I can get a link

**Comment by lighdotdot** [comment] 2017-05-09 03:29
@GuntherDW, Yeah, that's the problem.

**Comment by lighdotdot** [comment] 2017-05-09 03:33
@CraftMinerKyle @GuntherDW Yes, this question.

**Comment by xsun2001** [comment] 2017-05-09 05:16
I add the code to use a `IClassTransformer `reload the AE2 api bytecode before it is loaded by the classloader. You can try it. The CI build version can be find [there](https://ci.appveyor.com/project/xsun2001/applied-energistics-2-unofficial/build/artifacts)

**Comment by CraftMinerKyle** [comment] 2017-05-09 16:36
Ok. I will try to create this issue and compare the builds. Thank you.

**Comment by lighdotdot** [comment] 2017-05-10 02:32
@xsun2001 Thank you.
But the problem still exists. The craft icon is not shown.
You can try adding DragonAPI 1.7.10 V16d.jar and making Encode Pattern.

**Comment by xsun2001** [comment] 2017-05-10 05:10
Ahh...I find the problem. DragonAPI and AE2 all want to ASM one method `net.minecraft.client.gui.inventory.GuiContainer.func_146977_a`. DragonAPI want to fire a event by ASMing. But I don't know what does AE2 want to do. I will check it more carefully. I believe I can balance the two mods' changes. By the way, my code can only recovery AE2's API, so it isn't useful for minecraft's code and make no influence to this issue.

**Comment by GuntherDW** [comment] 2017-05-10 12:59
That's what I (and Reika) indeed back in 2014 said in that topic I linked.

**Comment by xsun2001** [comment] 2017-05-10 13:05
It may be difficult to solve this issue. @GuntherDW I read the topic but to find my English is too bad to understand it completely. But now, we cannot let DragonAPI to change itself and the change of AE2 cannot be ignored. I think I have to find another way to do something on the bytecode.

> So I never want anybody to change anything of Minecraft and Forge, which are instable enough.

**Comment by CraftMinerKyle** [comment] 2017-05-10 14:09
Perhaps an AE2 and DragonAPI Addon Compatibility mod could be created just for this very purpose...
Test to see if DragonAPI is present, download compat resource, execute compat addon, continue life with one less problem!

**Comment by lighdotdot** [comment] 2017-05-11 04:18
In minecraft1.7.10, AE2 has two versions of RV2 and RV3.
Reika is only compatible with the RV2 version.

**Comment by yueh** [comment] 2017-07-01 06:55
Tell Reika to stop shipping the AE2 api. We explicitly told him to not do it, but he choose otherwise. So that is on him.

**Closed by yueh** 2017-07-01 06:55 UTC

**Comment by Walkman100** [comment] 2019-01-13 16:45
Just got what I think is this issue too on 1.7.10 ([image](https://user-images.githubusercontent.com/5454764/51087937-688fd000-1762-11e9-941b-146cc4fe5430.png))
MC 1.7.10, Forge 10.13.4.1614, AE2 rv3-beta-6, DragonAPI 1.7.10+V22d
@yueh so does that mean there is no fix at the moment except removing DragonAPI?

**Comment by covers1624** [comment] 2019-01-16 16:19
1.7.10 is unsupported. DragonAPI has always done extremely questionable things, there is nothing that can ve done.

**Comment by Walkman100** [comment] 2019-01-17 19:06
Damn, alright. thanks for responding
