### ISSUE TITLE
Crash from AE2? (Or what is it from..?)

### ISSUE THREAD

**Issue by 34486** [AppliedEnergistics/Applied-Energistics-2#3530] opened 2018-06-03 16:58 UTC
Just updated my pack, shut down my world no issues, I added thebetweenlands and enviormental tec mod, went to start the server, and crashed. removed the mods, still crashed, I feel as if the world is now corrupted... but it gives me an error with ae2? I copy the world to the client, try to get on, crashes with the same log. 
[crash-2018-06-03_12.25.29-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2066166/crash-2018-06-03_12.25.29-server.txt)

Any ideas? :/

- Minecraft Version:  1.12.2
- AE2 Version:  Latest
- Forge Version:  2705

**Comment by yueh** [comment] 2018-06-03 17:11
Duplicate of #3318

**Closed by yueh** 2018-06-03 17:11 UTC
