### ISSUE TITLE
Suggestion: Gui For Planes

### ISSUE THREAD

**Issue by shobu9** [AppliedEnergistics/Applied-Energistics-2#1449] opened 2015-05-12 16:07 UTC
Could it be possible that anihalation planes to have a gui to blacklist or whitelist what it needs to harvest... because rigth now there is no way to tell them to not harvest certain things...

**Comment by jeremiahwinsley** [comment] 2015-05-12 16:09
I believe this is a dupe of #671.

**Closed** 2015-05-12 16:10 UTC
