### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by MTM210e** [AppliedEnergistics/Applied-Energistics-2#7277] opened 2023-07-18 07:33 UTC
### Describe the bug

When trying to run minecraft, it won't launch

### How to reproduce the bug

Just launch minecraft

### Expected behavior

Minecraft launch

### Additional details

Used mods:
Rubidium
Oculus
FerriteCore
Entity Culling
Create (0.5.1)
Roughly Enough Items (REI)
REI Plugin Compatibilities
Cloth Config v 10 API
Architectury API
Appleskin
I want to point out that ae2 version 15.0.4-beta runs without errors with the same mods and with the same version of the FORGE loader

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/MTM210e/09a17ad5e95642b37fd2830bb0480013

**Comment by Technici4n** [comment] 2023-07-18 07:38
Duplicate of #7276

**Closed by Technici4n** 2023-07-18 07:38 UTC
Labels: bug
