### ISSUE TITLE
Autocrafting with Rotarycraft - Doesnt work.

### ISSUE THREAD

**Issue by melekaiah** [AppliedEnergistics/Applied-Energistics-2#1943] opened 2015-10-11 22:35 UTC
So in rotarycraft there is an option in the config, to allow normal crafting tables to handle the recipies. 
with that option enabled. I went ahead and tried to craft somethign in the crafting interface

WHICH WORKS - with one caveat.. i seem to have to close the gui and reopen it to see the result of the pattern. 

This carries into the pattern interface, except here, restarting to gui, does not show you the result, which makes it impossible to make a working pattern for the assemblers to use. 

I am not sure if this is something that can be fixed on AE end, or if its something that reika needs to look at. just thought id mention it since, it seems close to working.

**Comment by thatsIch** [comment] 2015-10-12 16:00
Does the console prints some errors? Closing GUIs does not sound really good. Though I am sure reika could improve his config option. Since he closed his issue tracker, it is a bit difficult to contact him.

**Comment by bookerthegeek** [comment] 2015-10-12 20:37
https://github.com/ReikaKalseki/Reika_Mods_Issues

It's still their.

**Comment by lossycrypt** [comment] 2015-10-14 21:56
I've never had any problems using AE2 to autocraft machines. In my survival world i used it to make Gas Turbines amongst others.
For science i just set up a small test world with only RotaryCraft 9b(+API) and AE2 rv2stable10 and made some Steel Gearboxes for testing, which also showed no problems. Manually crafting in the Crafting Terminal, encoding a pattern, and auto-assembling work fine.

**Comment by ReikaKalseki** [comment] 2015-10-14 22:46
I have no issues either, and the "have to close GUI" behavior cannot be reproduced.

**Comment by thatsIch** [comment] 2015-10-18 18:41
Closing this due to no response

**Closed by thatsIch** 2015-10-18 18:41 UTC
Labels: state-waiting
