### ISSUE TITLE
Add more wireless terminals

### ISSUE THREAD

**Issue by josh-65** [AppliedEnergistics/Applied-Energistics-2#4945] opened 2021-01-14 12:56 UTC
**Describe the feature**
I would like to see Fluid, crafting and ultimate wireless terminal added. The ultimate would include the crafting terminal interface with a button to access the fluid side of the network.

**Reasons why it should be considered**
I think it would be nice to access all of a network resources especially if it big or a terminal is far away

**Comment by Mari023** [comment] 2021-01-14 12:58
basically https://github.com/p455w0rd/WirelessCraftingTerminal and https://github.com/p455w0rd/WirelessFluidTerminal for newer Minecraft Versions?

**Comment by josh-65** [comment] 2021-01-14 12:59
yeah

**Comment by josh-65** [comment] 2021-01-14 13:00
I think it would be better to include it all in the main mod and have the ultimate terminal as an addition

**Comment by yueh** [comment] 2021-01-14 13:33
Duplicate of #401

**Closed by yueh** 2021-01-14 13:33 UTC
