### ISSUE TITLE
ME-Bus can't interact with “Reactor Chamber” of IC2

### ISSUE THREAD

**Issue by 276562578** [AppliedEnergistics/Applied-Energistics-2#3420] opened 2018-03-08 09:00 UTC
AE2 version  =  rv5.stable build 9

It doesn't work when I put ME-Storage-Bus/ME-Import-Bus/ME-Export-Bus next to the Reactor Chamber which is belong industrial craft 2 experimental version 112.

- Minecraft Version: 1.12.2
- AE2 Version:  rv5.stable build 9
- Forge Version: forge-1.12.2-14.23.1.2555

**Comment by yueh** [comment] 2018-03-08 09:25
Duplicate of #2850

**Closed by yueh** 2018-03-08 09:25 UTC
