### ISSUE TITLE
Minecraft1.12.2 crash 

### ISSUE THREAD

**Issue by 2804409829** [AppliedEnergistics/Applied-Energistics-2#4303] opened 2020-03-05 08:16 UTC
**Describe the bug**

**To Reproduce**

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2020-03-05 14:27:56 CST
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source)
    at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248)
    at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:199)
    at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
    at appeng.me.Grid.update(Grid.java:280)
    at appeng.hooks.TickHandler.onTick(TickHandler.java:228)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_925_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2442114888 bytes (2328 MB) / 3646947328 bytes (3478 MB) up to 3670016000 bytes (3500 MB)
  JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3500m
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 85 mods loaded, 85 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version                  | Source                                                | Signature                                |
       |:------ |:--------------------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                         | None                                     |
       | LCHIJA | mcp                               | 9.42                     | minecraft.jar                                         | None                                     |
       | LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
       | LCHIJA | forge                             | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
       | LCHIJA | jecharacters                      | 1.12.0-3.4.3             | [JEI]JustEnoughCharacters-1.12.0-3.4.3.jar            | None                                     |
       | LCHIJA | anothercommonbugfix               | 1.0.7                    | minecraft.jar                                         | None                                     |
       | LCHIJA | smoothfontcore                    | mc1.12.2-1.16            | minecraft.jar                                         | None                                     |
       | LCHIJA | foamfixcore                       | 7.7.4                    | minecraft.jar                                         | None                                     |
       | LCHIJA | tnt_utilities_core                | 1.2.2                    | minecraft.jar                                         | None                                     |
       | LCHIJA | randompatches                     | 1.12.2-1.21.0.0          | randompatches-1.12.2-1.21.0.0.jar                     | None                                     |
       | LCHIJA | smoothfont                        | mc1.12.2-1.16.2          | SmoothFont-mc1.12.2-1.16.2.jar                        | None                                     |
       | LCHIJA | cucumber                          | 1.1.3                    | 1.12.2-Cucumber-1.1.3.jar                             | None                                     |
       | LCHIJA | jei                               | 4.15.0.268               | [JEI][本体]jei_1.12.2-4.15.0.268.jar                    | None                                     |
       | LCHIJA | inventorytweaks                   | 1.63+release.109.220f184 | [R键整理]InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT          | [优化]VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCHIJA | lunatriuscore                     | 1.2.0.42                 | [信息显示前置]LunatriusCore contents-1.12.2.jar             | None                                     |
       | LCHIJA | ingameinfoxml                     | 2.8.2.94                 | [信息显示]InGame Info XML contents-1.12.2.jar             | None                                     |
       | LCHIJA | chameleon                         | 1.12-4.1.3               | [储物抽屉][变色龙]Chameleon-1.12-4.1.3.jar                   | None                                     |
       | LCHIJA | storagedrawers                    | 1.12.2-5.4.0             | [储物抽屉]StorageDrawers-1.12.2-5.4.0.jar                 | None                                     |
       | LCHIJA | codechickenlib                    | 3.2.3.358                | [前置CCL]CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | mtrm                              | 1.2.2.30                 | [可视化合成表编辑器]MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar | None                                     |
       | LCHIJA | variedcommodities                 | 1.12.2                   | [各种物品]VariedCommodities_1.12.2%2829oct17%29.jar       | None                                     |
       | LCHIJA | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                  | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | jee                               | 1.0.7                    | [应用能源[JEI]]JustEnoughEnergistics-1.12.2-1.0.7.jar     | None                                     |
       | LCHIJA | libnine                           | 1.1.1                    | [应用能源][前置]libnine-1.12.2-1.1.1.jar                    | None                                     |
       | LCHIJA | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
       | LCHIJA | threng                            | 1.1.1                    | [应用能源][附属]lazy-ae2-1.12.2-1.1.1.jar                   | None                                     |
       | LCHIJA | flammpfeil.slashblade             | mc1.12-r29               | [拔刀剑]SlashBlade-mc1.12-r29.jar                        | None                                     |
       | LCHIJA | xcustomizedblade                  | 1.53                     | [拔刀剑附属]XCustomizedBlade[TinyCore][1.12.2]VER1.53.jar  | None                                     |
       | LCHIJA | pseudo                            | r1                       | [拔刀剑附属]伪刃：虚伪重构Pseudo-mc1.12-r1vA.jar                  | None                                     |
       | LCHIJA | slashblade_addon                  | 1.0.6                    | [拔刀剑附属]拔刀剑日系附属包SJAP_V1.0.6_MC1.12.2.jar               | None                                     |
       | LCHIJA | horocollectors                    | 1.0.0                    | [收藏家工艺V2]HoroCollectors-1.12.2.jar                    | None                                     |
       | LCHIJA | journeymap                        | 1.12.2-5.5.4             | [旅行地图]journeymap-1.12.2-5.5.4.jar                     | None                                     |
       | LCHIJA | avaritia                          | 3.3.0                    | [无尽贪婪]Avaritia-1.12.2-3.3.0.33-universal.jar          | None                                     |
       | LCHIJA | baubles                           | 1.5.2                    | [饰品栏]Baubles-1.12-1.5.2.jar                           | None                                     |
       | LCHIJA | endercore                         | 1.12.2-0.5.73            | [末影核心]EnderCore-1.12.2-0.5.73.jar                     | None                                     |
       | LCHIJA | redstoneflux                      | 2.1.0                    | [热力][rf能源]RedstoneFlux-1.12-2.1.0.6-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                          | 4.6.3                    | [热力前置]CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
       | LCHIJA | cofhworld                         | 1.3.1                    | [热力前置]CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalfoundation                 | 2.6.3                    | [热力基本]ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion                  | 5.5.4                    | [热力膨胀5]ThermalExpansion-1.12.2-5.5.4.43-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                           | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | p455w0rdslib                      | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar                       | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | ae2wtlib                          | 1.0.34                   | [无线合成终端前置]AE2WTLib-1.12.2-1.0.34.jar                  | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | wct                               | 3.12.97                  | [无线合成终端]WirelessCraftingTerminal-1.12.2-3.12.97.jar   | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | extrautils2                       | 1.0                      | [更多实用设备2]extrautils2-1.12-1.9.9.jar                   | None                                     |
       | LCHIJA | ironchest                         | 1.12.2-7.0.67.844        | [更多箱子]ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiobase                       | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduits                   | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiomachines                   | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | enderiopowertools                 | 5.1.55                   | [末影接口]EnderIO-1.12.2-5.1.55.jar                       | None                                     |
       | LCHIJA | neat                              | 1.4-15                   | [极简血量显示]Neat-1.12.2.jar                               | None                                     |
       | LCHIJA | botania                           | r1.10-361                | [植物魔法][本体]Botania+r1.10-361.jar                       | None                                     |
       | LCHIJA | botanianeedsit                    | 1.12.2-2.1-release       | [植物魔法][附属]botanianeedsit-1.12.2-2.1-release.jar       | None                                     |
       | LCHIJA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
       | LCHIJA | extrabotany                       | 55                       | [植物魔法][额外植物学]ExtraBotany-r1.1-55-fixed.jar            | None                                     |
       | LCHIJA | i18nmod                           | 1.12.2-1.0.8             | [汉化]i18nupdatemod-1.12.2-1.0.8.jar                    | None                                     |
       | LCHIJA | lootcapacitortooltips             | 1.3                      | [电容信息显示]lootcapacitortooltips-1.3.jar                 | None                                     |
       | LCHIJA | customskinloader                  | 14.10a                   | [皮肤补丁]CustomSkinLoader_Forge-14.10a.jar               | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
       | LCHIJA | wanionlib                         | 1.12.2-1.5               | [矿辞统一]WanionLib-1.12.2-1.5.jar                        | None                                     |
       | LCHIJA | reborncore                        | 3.18.0                   | [重生核心]RebornCore-1.12.2-3.18.1.514-universal.jar      | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | techreborn                        | 2.26.3.1066              | [科技复兴]TechReborn-1.12.2-2.26.3.1066-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | biomesoplenty                     | 7.0.1.2414               | [超多生物群系]Biomes O'Plenty-1.12.2.jar                    | None                                     |
       | LCHIJA | supertorch                        | 1.2.0                    | [超级火把]SuperTorch-1.12.2.jar                           | None                                     |
       | LCHIJA | mekanism                          | 1.12.2-9.8.3.390         | [通用机械]Mekanism-1.12.2-9.8.3.390.jar                   | None                                     |
       | LCHIJA | mekanismgenerators                | 1.12.2-9.8.3.390         | [通用机械发电机]MekanismGenerators-1.12.2-9.8.3.390.jar      | None                                     |
       | LCHIJA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
       | LCHIJA | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
       | LCHIJA | extendedcrafting                  | 1.5.6                    | ExtendedCrafting-1.12.2-1.5.6.jar                     | None                                     |
       | LCHIJA | foamfix                           | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                             | None                                     |
       | LCHIJA | foxex                             | 1.0.0                    | FoxExtra[1.12.2]v1.0.jar                              | None                                     |
       | LCHIJA | nei                               | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.244-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | packagedauto                      | 1.12.2-1.0.2.9           | PackagedAuto-1.12.2-1.0.2.9.jar                       | None                                     |
       | LCHIJA | packagedavaritia                  | 1.12.2-1.0.1.4           | PackagedAvaritia-1.12.2-1.0.1.4.jar                   | None                                     |
       | LCHIJA | packagedexcrafting                | 1.12.2-1.0.1.1           | PackagedExCrafting-1.12.2-1.0.1.1.jar                 | None                                     |
       | LCHIJA | surge                             | 2.0.77                   | Surge-1.12.2-2.0.77.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tnt_utilities                     | 1.2.2                    | tnt_utilities-mc1.12-1.2.2.jar                        | None                                     |
       | LCHIJA | techreborn_compat                 | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.4.0.73.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | unidict                           | 1.12.2-2.9.1             | [矿辞统一]UniDict-1.12.2-2.9.1.jar                        | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin ([优化]VanillaFix-1.0.10-99.jar)
                                        
                                      CustomSkinLoader ([皮肤补丁]CustomSkinLoader_Forge-14.10a.jar)
                                        customskinloader.forge.loader.LaunchWrapper
                                      TNTUtilities Core (tnt_utilities-mc1.12-1.2.2.jar)
                                        ljfa.tntutils.asm.ExplosionTransformer
                                      MekanismCoremod ([通用机械]Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      AnotherCommonBugFix ([通用bug修复]AnotherCommonBugFix-1.0.7-1.12.2.jar)
                                        com.anotherera.core.ACBFClassTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      Inventory Tweaks Coremod ([R键整理]InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      JechCore ([JEI]JustEnoughCharacters-1.12.0-3.4.3.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.18.0
              Runtime Debofucsation 1
              RenderEngine: 1
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Applied Energistics 2 (appliedenergistics2)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['shi_jie'/21643, l='世界丶好咹静的世界', x=379.56, y=101.92, z=-271.89]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 3
**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: stable rv6-stable-7
- Forge Version:14.23.5.2768

**Comment by mindforger** [comment] 2020-03-05 08:58
does this happen often or is it absolute random? 
and since your modlist ist somewhat smaller than the other reports of this, can you retest **without** the following? (MAKE A BACKUP OF THE WHOLE INSTANCE FIRST)
- foamfix
- anothercommonbugfix (where is this coming from?)
- vanillafix

if it does not happen with any of them, begin re-installing one after another until it happens again and then report back please when you find which combination is causing it

if it still happens without those mods, try if chunkloading the whole area (including any Quantum Network Bridges) fixes it

**Comment by yueh** [comment] 2020-03-05 18:53
Duplicate of #3800

**Closed by yueh** 2020-03-05 18:53 UTC
