### ISSUE TITLE
[1.16.1] Crash Upon Startup of Forge Server

### ISSUE THREAD

**Issue by zmg2008** [AppliedEnergistics/Applied-Energistics-2#4554] opened 2020-08-04 18:50 UTC
When loading AE2 on a Forge 1.16.1 server (latest update, v106), the loader crashes immediately and presents a log with fatal errors.

**Describe the bug**

Fresh install of all components. It was working with the client version of forge (with multiple mods and AE2 solo), but is not working on the server version of forge. I tried on two separate computers, one being a Dell Proliant DL380 with Java 1.8 (not sure on the version and lost connection to it at the moment), as well as my Laptop which has Java 1.8.0_261; both gave the same error listed below.
When launching the server, a fatal error appears within 5-10 seconds of startup, and the command prompt immediately closes. Removing the mod allows the game to launch.

**To Reproduce**

Create a folder for the minecraft server to reside it.
Download the latest version of Forge which complies with AE2 requirements (32.0.76 - 33.0.0) - latest version is 32.0.106, which I am using.
Run the Forge server installer.
Download the latest version of AE2 and put it in the mods folder - the version I installed from curseforge is: Applied-Energistics-2-Mod-1.16.1.jar
Using a .bat file, start the forge server jar.
Upon starting, the error listed below appears.

**Expected behavior**

The server should start and run with AE2 loaded.

**Additional context**

[04Aug2020 11:33:17.630] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 32.0.106, --fml.mcpVersion, 20200625.160719, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge]
[04Aug2020 11:33:17.633] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_261 by Oracle Corporation
[04Aug2020 11:33:18.117] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[04Aug2020 11:33:18.142] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/zgreenside/Desktop/Minecraft%20Server%20Test/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=SERVER
[04Aug2020 11:33:18.176] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Configuration file C:\Users\zgreenside\Desktop\Minecraft Server Test\config\fml.toml is not correct. Correcting
[04Aug2020 11:33:18.182] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[04Aug2020 11:33:18.762] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[04Aug2020 11:33:24.642] [modloading-worker-9/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.106, for MC 1.16.1 with MCP 20200625.160719
[04Aug2020 11:33:24.643] [modloading-worker-9/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v32.0.106 Initialized
[04Aug2020 11:33:26.216] [modloading-worker-11/ERROR] [net.minecraft.util.Util/]: No data fixer registered for appliedenergistics2:tiny_tnt_primed
[04Aug2020 11:33:26.844] [modloading-worker-11/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
[04Aug2020 11:33:26.845] [modloading-worker-11/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: appliedenergistics2, class appeng.core.AppEng
java.lang.ExceptionInInitializerError: null
	at appeng.core.FacadeItemGroup.<init>(FacadeItemGroup.java:43) ~[?:8.0.0-alpha.1]
	at appeng.core.AppEng.<init>(AppEng.java:123) ~[?:8.0.0-alpha.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[TestServer.jar:32.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:82) ~[modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:118) ~[modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134) ~[modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-6.1.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at appeng.block.AEBaseBlockItemChargeable.<init>(AEBaseBlockItemChargeable.java:49) ~[?:8.0.0-alpha.1]
	at appeng.bootstrap.BlockDefinitionBuilder.constructItemFromBlock(BlockDefinitionBuilder.java:203) ~[?:8.0.0-alpha.1]
	at appeng.bootstrap.BlockDefinitionBuilder.build(BlockDefinitionBuilder.java:147) ~[?:8.0.0-alpha.1]
	at appeng.core.api.definitions.ApiBlocks.<init>(ApiBlocks.java:478) ~[?:8.0.0-alpha.1]
	at appeng.core.ApiDefinitions.<init>(ApiDefinitions.java:41) ~[?:8.0.0-alpha.1]
	at appeng.core.Api.<init>(Api.java:72) ~[?:8.0.0-alpha.1]
	at appeng.core.Api.<clinit>(Api.java:42) ~[?:8.0.0-alpha.1]
	... 20 more
[04Aug2020 11:33:26.851] [modloading-worker-11/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: An error occurred while dispatching event CONSTRUCT to appliedenergistics2
[04Aug2020 11:33:26.851] [modloading-worker-11/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 7 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[04Aug2020 11:33:26.854] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[04Aug2020 11:33:26.856] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Applied Energistics 2 (appliedenergistics2) has failed to load correctly
§7null
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[TestServer.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [TestServer.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [TestServer.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [TestServer.jar:?]

**Environment**

- Environment: 
I'll just give you specs on my laptop, I assume that's what this is looking for.
Intel Core i9-9900 @ 3.10GHz
64GB DDR4 RAM
NVidia GeForce RTX 2070
460Gb SSD
1Tb HHD
Windows 10 Pro Version 1909
Java 1.8.0_261

**Comment by yueh** [comment] 2020-08-04 19:15
Duplicate of #4531

**Closed by yueh** 2020-08-04 19:15 UTC
