### ISSUE TITLE
Server crashes upon loading server.

### ISSUE THREAD

**Issue by Heinz2142** [AppliedEnergistics/Applied-Energistics-2#4106] opened 2019-07-24 20:45 UTC
**Describe the bug**
Upon hosting the server it won't go futher than it saying that the server crashed because of Applied Energistics 2.

**To Reproduce**
Just hosting the server.

**Expected behavior**
Hosting the server normal like for the past week or two.

**Additional context**
https://cdn.discordapp.com/attachments/603633700772773889/603647018702995456/latest.log
No actual crashlogs are to be found with this problem.
**Environment**
The Classic Pack via the TechnicLauncher.
Thaumic Additions: reconstructed, Last updated Jun 22, 2019

- Minecraft Version: 1.12.1
- AE2 Version: Not sure, The version before the 23-7-19 Version, don't know where to check where the version is listed.
- Forge Version: Not using Forge, Using Technic Launcher and added to the Classic Pack (tekkit)

**Comment by Pingger** [comment] 2019-07-24 20:51
Sponge isn't supported. Try if reproducible with Vanilla ForgeServer.

Additional Context:
Line in Question:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c483bd17f50957ac25e9af3b71a82845086ffe35/src/main/java/appeng/core/AppEng.java#L271
Can per definition not be the issue, as `instance()` must NOT return **null**. SpongeServer does return **null**. So this is a Sponge bug.

**Comment by Heinz2142** [comment] 2019-07-24 21:06
Sponge wasn't supported since day one of the server host and hasn't caused any problems with it. I am not really able to follow you but if you could tell me what to do for you to check something out I'll surely want to help if possible.

**Comment by Pingger** [comment] 2019-07-24 21:20
Need to wait @yueh to look at it. 
I have looked into the code and some information in it contradicts each other. Additionally, the call the causes the issue is already marked as **deprecated** and should no longer be used anywhere.

**Comment by Ommina** [comment] 2019-07-25 02:26
The thing is, how is it ending up in ServerStopped in the first place?  I can understand the stacktrace for the NPE, but when that trace is logged, the server is already stopping.  It doesn't seem to be the cause of the crash, but a side-effect.

**Comment by yueh** [comment] 2019-07-25 07:02
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.

**Closed by yueh** 2019-07-25 07:02 UTC
