### ISSUE TITLE
Storage Bus update issue

### ISSUE THREAD

**Issue by emperor06** [AppliedEnergistics/Applied-Energistics-2#1144] opened 2015-03-29 19:22 UTC
I have a weird bug for quite some time now and I was not sure I should report it since I cannot seem to be able to reproduce it on a minimalist network in single player mode. But well, maybe someone here has an idea.

If I place a storage bus on my network, partition it to store a give type of item (let's say potatoes for examples) then I place a storage on it (a vanilla chest for example), that storage won't be available on my network. That is, if I put some potatoes on the network via a terminal, they will end up on my ME Storage Cells instead of the chest. And if I put potatoes in the chest, they won't be available on the network.
Now if I alter the storage bus priority or partition, the chest will be available on the network as expected. Note that it has nothing to do with the priority itself: if I change it to +1 and immediately back to 0, the storage will be accessible. It's like changing (even temporary) any setting on the storage bus refreshes something.
As I said, I can't reproduce this on a solo world so I thought it may be an issue on my network but I can't figure out what. My network got quite complicated recently, using a lot of P2P and some quantum rings. On my server world, the bug occurs 100% of the time. Whenever I remove a Thermal Expansion cache from its storage bus (to upgrade it) and place it back, it won't be visible until I "refresh" the storage bus. It used to work perfectly a couple of months ago. I don't know what broke it (an update or some changes on my network). I'm currently using rv2-beta18.

**Comment by emperor06** [comment] 2015-03-29 20:05
Addendum:
If I change PartStorageBus.onNeighborChanged() to resetCache( true ), the bug completely disappears. But that may also slow down the server as it seems this method is called quite often.
Question is, why do I only get this bug on my server world…

**Comment by thatsIch** [comment] 2015-03-30 09:29
Are you using something, which can reduce the calls of neighbor updates? Unsupported software like cauldron or any other MCPC offspring?

**Comment by emperor06** [comment] 2015-03-30 09:32
Nope, plain forge server (10.13.2.1291)

**Comment by yueh** [comment] 2015-03-30 09:45
I remember another issue with the TE caches, but the reporter did mention that a more recent version of TE did fix it.

**Comment by emperor06** [comment] 2015-03-30 09:48
I first thought it was an issue with TE caches too but I did try with other containers (including vanilla chests) and it's still the same. I'm currently testing on a fresh new world on the same server (with the same mods) to see if it's an issue with my world (like lag or race condition or whatever).

**Comment by emperor06** [comment] 2015-03-30 09:53
Result: absolutely no issue on a new world. I'm puzzled.

**Comment by thatsIch** [comment] 2015-04-04 13:09
Maybe this is related to the "stopping import buses"

**Comment by thatsIch** [comment] 2015-05-03 19:55
Closing this as a potential duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1036

**Closed by thatsIch** 2015-05-03 19:55 UTC
Labels: state-waiting
