### ISSUE TITLE
Pattern Terminal: Ability to Keep Blank Patters Stocked

### ISSUE THREAD

**Issue by kthayes** [AppliedEnergistics/Applied-Energistics-2#4392] opened 2020-05-24 02:32 UTC
It would be nice to have the ability for the pattern terminal to keep itself stocked with blank patterns.

You could either add a card slot on the right that accepts a crafting card, and that would auto-craft a new pattern when one is used, or add another button on the left side of the GUI with configurable options. Those options could include: 'Don't Restock', 'Restock When Below 25%', and 'Always Stay Fully Stocked'.

I know I speak for at least my immediate friend group, and probably plenty of others, that this would be a much appreciated addition. By the time the 3rd stack of patters runs out and you realize you have to craft another, it's just an annoyance. I realize this is a small improvement, but when you're setting up a large system, every extra step takes time, and less is more!

**Comment by XerShade** [comment] 2020-05-24 07:41
You could always make a cache that hold a stack of patterns in  an interface, the only issue there is putting them into the terminal. I agree this would be nice though, last night just said screw it and auto crafted a thousand patterns because expert mode packs eat them. XD

**Comment by yueh** [comment] 2020-05-24 11:14
Duplicate of #119

**Closed by yueh** 2020-05-24 11:14 UTC
