### ISSUE TITLE
FE Energy P2P Tunnel crashing the server.

### ISSUE THREAD

**Issue by Splutty** [AppliedEnergistics/Applied-Energistics-2#4287] opened 2020-02-18 18:38 UTC
When running a large amount of energy from a draconic network into an energy P2P Tunnel, over a Quantum connection, back into a draconic network, the server crashes on:
- Changing energy provision/generation on either of the connected quantum rings.
- Loading into the game near a quantum ring.

- AE2WTLib 1.12.2-1.0.34
- ae2stuff-0.7.0.4
- Enigmatica 2 modpack 1.75b
- Forge 1.12.2-14.23.5.2847
- Multiplayer Forge server

**To Reproduce**
Build as laid out in the summary. Remove an acceptor. Crash.

Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source)
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316)
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248)
	at appeng.parts.p2p.PartP2PTunnel.queueTunnelDrain(PartP2PTunnel.java:407)
	at appeng.parts.p2p.PartP2PFEPower$InputEnergyStorage.receiveEnergy(PartP2PFEPower.java:146)
	at com.brandon3055.brandonscore.lib.EnergyHelper.insertEnergy(EnergyHelper.java:110)
	at com.brandon3055.draconicevolution.blocks.energynet.tileentity.TileCrystalDirectIO.func_73660_a(TileCrystalDirectIO.java:51)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by yueh** [comment] 2020-02-22 11:46
Duplicate of #3800

**Closed by yueh** 2020-02-22 11:46 UTC

**Comment by Prurite** [comment] 2020-04-11 01:21
Similar issue on my server. I've seen a lot of issues marked as duplicate of #3800 but where's the fix?
