### ISSUE TITLE
Spatial Storage works in Singleplayer, not in a mulitplayer server

### ISSUE THREAD

**Issue by LilliPJs** [AppliedEnergistics/Applied-Energistics-2#5350] opened 2021-07-30 10:29 UTC
**Describe the bug**
Sending a redstone signal to a Spatial IO port does nothing and causes a warning in the server console

**To Reproduce**
Play on a multiplayer server
Use a Spatial IO port as normally used

**Expected behavior**
Spatial IO should work as it normally does

**Additional context**
Server tread warning: https://pastebin.com/R5vdULhr

**Environment**
- Environment: 1.16.5 
- Playing modpack: Syndicate Dreams Lite (on Curseforge)
- Force crash log: https://pastebin.com/FeSxjiCE
- There are 3 extra mods that are only on the servers end and those would be Ferritecore, Morpheus, and Performant

**Comment by yueh** [comment] 2021-07-30 10:47
Duplicate of #5136

**Closed by yueh** 2021-07-30 10:47 UTC
