### ISSUE TITLE
Creative ME Storage Cell not working

### ISSUE THREAD

**Issue by MagicMalte1** [AppliedEnergistics/Applied-Energistics-2#5015] opened 2021-02-27 15:31 UTC
I build in 1.16.5 a Creative Storage with Create Storage Cells and couldnt put things in, after I switched the Cells to 64k Cells it worked.

**Comment by yueh** [comment] 2021-02-27 23:56
Duplicate of #5014

**Closed by yueh** 2021-02-27 23:56 UTC
