### ISSUE TITLE
AE2 not displaying contents in Terminal.

### ISSUE THREAD

**Issue by VladParshin** [AppliedEnergistics/Applied-Energistics-2#7057] opened 2023-04-19 03:06 UTC
**Describe the issue**
I'm running ATM8 modpack, and have run into an issue where, at some point during the night, AE2 stopped displaying items in the terminals.
I had hooked it up to a quarry, so that everything is stored in some 256M Cells from Mega Cells, and let the quarry run.
In the morning when I woke up, the world decided that I wasn't allowed AE2 Terminal visibility. Before I went to sleep everything was fine and displaying correctly.

I enabled debugging for AE2 and started from there. Came across these things so far:
`[Server thread/WARN] [AE2:S/]: Failed to send incremental inventory update to client
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.<init>(ClientboundCustomPayloadPacket.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraftforge.network.NetworkDirection.lambda$static$1(NetworkDirection.java:28) ~[forge-1.19.2-43.2.6-universal.jar%23844!/:?]
	at net.minecraftforge.network.NetworkDirection.buildPacket(NetworkDirection.java:79) ~[forge-1.19.2-43.2.6-universal.jar%23844!/:?]
	at appeng.core.sync.BasePacket.toPacket(BasePacket.java:67) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.core.sync.network.NetworkHandler.sendTo(NetworkHandler.java:123) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.menu.AEBaseMenu.sendPacketToClient(AEBaseMenu.java:857) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.menu.me.common.MEStorageMenu.lambda$broadcastChanges$0(MEStorageMenu.java:291) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.core.sync.packets.MEInventoryUpdatePacket$Builder.buildAndSend(MEInventoryUpdatePacket.java:243) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.menu.me.common.MEStorageMenu.m_38946_(MEStorageMenu.java:291) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38893_(AbstractContainerMenu.java:123) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.level.ServerPlayer.m_143399_(ServerPlayer.java:382) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:207) ~[forge-1.19.2-43.2.6-universal.jar%23844!/:?]
	at appeng.menu.implementations.MenuTypeBuilder.open(MenuTypeBuilder.java:177) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.menu.MenuOpener.open(MenuOpener.java:63) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.menu.MenuOpener.open(MenuOpener.java:52) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.parts.reporting.AbstractTerminalPart.onPartActivate(AbstractTerminalPart.java:111) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.parts.AEBasePart.onActivate(AEBasePart.java:361) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.parts.CableBusContainer.activate(CableBusContainer.java:682) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.block.networking.CableBusBlock.onActivated(CableBusBlock.java:235) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at appeng.block.AEBaseEntityBlock.m_6227_(AEBaseEntityBlock.java:229) ~[appliedenergistics2-forge-12.9.2.jar%23522!/:12.9.2]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:714) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:340) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]`

this is followed by a spamming of the message below while terminal is opened:
`
[Render thread/WARN] [AE2:C/]: First time seeing serial 4185, but incomplete info received`

I have 2 assumptions:
1) There's too many items in the AE2 system

2) An item is causing AE2 to throw a fit.

I will continue to poke at it, see if I can at least find the cell or cells that cause the issue.

**Comment by Technici4n** [comment] 2023-04-19 08:55
> 1. There's too many items in the AE2 system

is exactly the problem here

**Comment by Technici4n** [comment] 2023-04-19 09:03
Duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6725

**Closed by Technici4n** 2023-04-19 09:03 UTC
