### ISSUE TITLE
Create option in Storage Bus to import filtered items from Interface

### ISSUE THREAD

**Issue by zxvnm4** [AppliedEnergistics/Applied-Energistics-2#3682] opened 2018-08-18 08:23 UTC
#### Description

Just like most of the other options going down from the upper left side of the storage bus, I suggest you add another to enable/disable the filtering of items from an AE2 interface, so you cannot import or export items not in the filter from the interface. Make the default set to the way it was previously.

This was suggested in #330 I am simply stating that there should be an option for it instead of changing it to be the only option.

I would find this useful for reducing spam from an AE2 system, it would also allow one to filter the input of an io port without having to configure every cell you put into it.
#### Environment

- Minecraft Version: 1.12.1
- AE2 Version: rv6-alpha-3
- Forge Version: 14.23.4.2756

**Comment by yueh** [comment] 2018-08-18 09:41
Duplicate of #1573

**Closed by yueh** 2018-08-18 09:41 UTC

**Comment by zxvnm4** [comment] 2018-08-18 18:52
"But it is really not the job for a storage bus to filter the inventory, just what can enter it.
Else it will also break too many useful builds."
This would simply be only a problem if you have it as a default setting, making an option for it would be a better alternative would it not?
