### ISSUE TITLE
Crash in Pattern Terminal when Recipe Type button clicked (Crafting->Machine)

### ISSUE THREAD

**Issue by Dyonovan** [AppliedEnergistics/Applied-Energistics-2#4497] opened 2020-07-25 18:28 UTC
Minecraft: 1.15.2
Forge: 31.2.31
Version: 7.0.0-ALPHA.8

[crash-2020-07-25_14.29.00-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4976170/crash-2020-07-25_14.29.00-server.txt)

**Comment by yueh** [comment] 2020-07-25 18:33
Duplicate of #4488

**Closed by yueh** 2020-07-25 18:33 UTC

**Comment by Dyonovan** [comment] 2020-07-25 18:36
Ahh Sorry. Didn't realize it was the same issue. Is there any chance you could push an update out to curse? I have tried building it myself but for some reason it can't find the MCP mappings.
