### ISSUE TITLE
Strange display/sort issue with Storage Bus

### ISSUE THREAD

**Issue by MuteTiefling** [AppliedEnergistics/Applied-Energistics-2#6737] opened 2022-10-29 21:15 UTC
### Describe the bug

To put it briefly, the terminal is spastic when displaying items in storage containers connected via Storage Bus.

https://streamable.com/7l446j

In the video, there are no items moving into or out of the system. They're just sitting in barrels. I've tried using different sort types to no avail. 

### How to reproduce the bug

1. Setup a basic AE2 system. I set this up without a controller as I didn't need much, just to view items.
2. Attach external storage. 
3. Pump in a bunch of items. Seems to be worse with unstackables, like armor in this video.

I've replicated this by attaching Occultism storage, Functional Drawers (Armory Cabinet), or Sophisticated Storage (bunch of drawers attached by a controller). For what it's worth, these items are all from Apotheosis. I discovered this while testing loot tables by running the followin command on repeat to test the output. `/loot spawn 393.73 62.69 -150.40 loot minecraft:chests/village/village_armorer`

### Expected behavior

The items should remain in a static sort pattern without moving unless items are coming in or out of the system. 

### Additional details

Cannot replicate with disks. So it seems like it's just the Storage Bus. 

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

n/a

**Comment by mindforger** [comment] 2022-10-30 03:59
can you show a picture of the setup? Low but non zero chance it could be a setup issue (like a missing energy cell, since you did not use a controller)

**Comment by CyberFoxar** [comment] 2022-10-30 13:45
I have reproduced with a minimal setup.

## Here's the unwanted behavior:
![javaw_hb8TZOCweW](https://user-images.githubusercontent.com/1347036/198881634-ad1f727f-929c-4ae3-a369-05ac5f1dd1c8.gif)

## Versions:
- Minecraft: 1.18.2
- Forge: 40.1.80
- Applied Energistics 2, 11.6.2

And litterally nothing else.

## How to reproduce:
Here's the setup:
![2022-10-30_14 38 37](https://user-images.githubusercontent.com/1347036/198881721-968e4a0d-611e-460a-b65c-d558ba0ae3e7.png)

- ME Controller
- Creative Energy Cell
- Terminal
- Quartz Cable
- ME Storage Bus
- Chest

In the chest I put 4 of the same item, but with different names and enchantement combinations. The enchants and name doesn't seem to matter, but it seem to need to be the same item type (in my case, diamond sword). Item itself doesn't matter, it simply need to have the same type, but different enchant and names.

Here's a world save:
[New World.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9895975/New.World.zip)

Please tell me if it's enough @mindforger .

**Comment by MuteTiefling** [comment] 2022-10-30 14:49
Thanks @CyberFoxar 
For my part, I'm running the following:
appliedenergistics2-forge-12.8.3-beta
forge: 43.1.47

Very similar setup, only I had a mekanism creative cube providing power through an energy acceptor.

**Comment by Technici4n** [comment] 2022-11-07 19:29
Duplicate of #6732

**Comment by Technici4n** [comment] 2022-11-07 19:29
(fix is coming: #6759)

**Closed by Technici4n** 2022-11-07 19:29 UTC
Labels: bug

**Comment by CyberFoxar** [comment] 2022-11-08 09:06
> (fix is coming: #6759)

Gotcha, thanks. I'll keep watch and restest once you've published a version o/
