### ISSUE TITLE
No items showing in system after trying to insert certain item

### ISSUE THREAD

**Issue by Ravalli03** [AppliedEnergistics/Applied-Energistics-2#3847] opened 2018-12-04 05:31 UTC
**Describe the bug**

After trying to insert an Iron Hoe into my system, it won't allow me to put any items in  or take any out, and then about 20 seconds later, everything in my system disappears from showing in Terminal,. If I exit my save file and reload it, the issue is still there, but if I restart minecraft the issue goes away. This has happen twice.

**To Reproduce**
Try to insert Iron hoe.

**Expected behavior**
System to show my items.

**Additional context**

**Environment**
Using a system without channels
Have 4mil+ items in system
Modern Skyblock 3 Mod pack.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-4
- Forge Version: 2768

**Comment by yueh** [comment] 2018-12-04 06:17
Duplicate of #3768

**Closed by yueh** 2018-12-04 06:17 UTC
