### ISSUE TITLE
Some small improvements

### ISSUE THREAD

**Issue by ScottCTD** [AppliedEnergistics/Applied-Energistics-2#5414] opened 2021-09-02 11:33 UTC
**Describe the feature**
1. Currently, AE has @mod search but I believe add support for tag and tooltip search would largely improve the searching experience. Just like what JEI did: 
![image](https://user-images.githubusercontent.com/35100768/131836114-d17a10c0-aa2c-4a4f-9966-576fdea14104.png)
(I have many ingots in the network)
2. Add curios support for wireless terminal and also a keyboard shortcut to open it. (And probably add a wireless crafting terminal? That could be epic)

**Reasons why it should be considered**
Those will largely improve the gaming experience, to be more comfortable. 

**Additional Context**
- I'm using the latest version of AE2 and forge at this time.

Thanks for making this epic mod and I appreciate your time in dealing with my request.

**Comment by yueh** [comment] 2021-09-02 11:37
Duplicate of #4852

**Closed by yueh** 2021-09-02 11:37 UTC
