### ISSUE TITLE
Crash with export bus and fuzzy card

### ISSUE THREAD

**Issue by Bad-Printer** [AppliedEnergistics/Applied-Energistics-2#5012] opened 2021-02-26 20:50 UTC
**Summary**
When using an export bus and a fuzzy card the game crashes when set to split at 99% mode.
using version 8.2.0 with recommended forge version for 1.16.4.

**To Reproduce**
Use an export bus with a fuzzy card set to export some armor piece.
Set fuzzy mode to split at 99%.

**Additional context**
Crash report included

**Environment**
Tested on fresh install of forge with no other mods.
[crash-2021-02-26_14.41.53-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6052405/crash-2021-02-26_14.41.53-server.txt)

**Comment by yueh** [comment] 2021-02-26 21:58
Duplicate of #4821

**Closed by yueh** 2021-02-26 21:58 UTC
