### ISSUE TITLE
Crafting from Crafting Terminal causes huge TPS spikes

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#127] opened 2014-09-27 19:22 UTC
What is happening?

Crafting multiple stacks of items from the crafting terminal (forestry bronze, for example, with 4 copper and 1 tin in a square) causes a long pause followed by a spike in TPS before the crafted items are put into your inventory.

What is expected?
Not such a huge TPS spike from crafting more than 1 stack at a time.

How to reproduce?
In my example, try to craft 5-6 stacks of forestry bronze using the easy recipe (3 copper + 1 tin) by shift clicking the crafting window inside the crafting terminal in quick succession (6-7 times). You will notice that the game/server gets hung up for a second and when the stacks do finally pop into your inventory, you can do a quick /tps to see that the tps has spiked upwards of 50tps+ for the period of time that the system was calculating what you wanted.

Server or Single Player?: Both
Screenshot?:
Crash Log?:

Originally Posted by Oninaig

This issue was migrated; For original details see http://ae-mod.info/Tracker/1123/

**Comment by joshricker** [comment] 2015-03-11 09:38
For me this issues is worse than ever. If i craft say 10 stacks of iron blocks, rapidly shift clicking in a crafting termal, the entire server grinds to a halt for up to 30 secs. I did get a snapshot of it but i can't seem to see any other mod in it. But i may just be reading it incorrectly. Heres the snapshot http://puu.sh/gvDnh/8916ccb399.nps

**Comment by Cisien** [comment] 2015-03-11 15:53
Is this on beta9? If not, give that a try. I think yueh did some work in this area

**Comment by yueh** [comment] 2015-03-11 16:28
Will be included in the next build (b11).

But that snapshot looks extremely strange. There is no way ´ConcurrentSkipListMap.get()´ can have so much time spent on itself. It just forwards to `ConcurrentSkipListMap.doGet()`.

We are currently dealing with 2 or 3 different problems and just mix them together.

1. This might be caused by binnies mod. But I am not sure anymore, if it is really an issue with that or it just can easily show our own issues.

2. Autocrafting requires a hard copy done in the server thread. It can potentially be removed, but might introduce some rare and hard to track down issues.

3. Shift click crafting. This is a particularly nasty thing.
Currently it extracts each required item once at a time. Thus crafting a stack of iron blocks will extract 587 times a single iron ingot instead of just once 587.
We already calculate how often it needs to craft for a full stack, but ignoring the free space in the inventory. But that can be easily fixed. (I have already a version, which does this).
The hard part is completely rewriting the crafting, that it first does a simulated extract of all needed materials and use this to calculate how many are really possible to craft. Then extract them at once and craft all at once.

It might be a good idea to just close all these issues and make two new ones containing the actual important information for each one.

**Comment by joshricker** [comment] 2015-03-14 00:10
My issue seem to be more related to #676 so i have posted more there.

**Comment by brunyman** [comment] 2015-08-28 12:24
I confirm this issue on SkyFactory2 modpack with mod version appliedenergistics2-rv2-beta-28 .
I was getting random server timeouts and could not find the source until i got a report from a player.

Everything is recorded in this video: https://www.youtube.com/watch?v=_FucHAxq6XY

This is a major issue and should be fixed asp, or was it fixed an a newer version?

**Comment by thatsIch** [comment] 2015-08-31 15:38
please try out with newer version first, your version is like 4 month old

**Comment by cj89898** [comment] 2016-04-07 20:16
This is still happening. Kicked all my players from my server today on Project Ozone v1.7

**Comment by mindforger** [comment] 2016-04-08 05:38
@cj89898 your request is incomplete, please read the post riiiight above yours and state which exact version you are using

**Comment by cj89898** [comment] 2016-04-08 15:07
@mindforger I can't find out right now but it is on the mod pack page

**Comment by mindforger** [comment] 2016-04-10 13:28
i tried to watch the list, it's not accessible for unregistered people and i won't register

**Comment by cj89898** [comment] 2016-04-11 03:06
@mindforger The version is rv2 stable 10.

**Comment by mindforger** [comment] 2016-04-11 06:17
see, thats why i said to look at the post above your own 
>please try out with newer version first, your version is like 4 month old

there have been major improvements in rv3-beta and rv2 does not get many love anymore :p
try updating

**Closed** 2016-11-22 11:01 UTC
Labels: state-waiting, type-bug
