### ISSUE TITLE
ConcurrentModificationException On World Load

### ISSUE THREAD

**Issue by mattheufarmer** [AppliedEnergistics/Applied-Energistics-2#3831] opened 2018-11-23 22:08 UTC
**Describe the bug**
Whenever I load into my Stoneblock world, it crashes, almost instantly. The weird thing is that I was able to play up to a certain point with no issue, then the crash happened and I couldn't load back into the world, so I loaded a backup from 15 minutes prior to the crash. When I loaded into the backup, it happened instantly. Both crashes have the same error message.

My theory is that it has to do with me having my controller multiblock inside a compact machine, and using quantum bridges to connect to my storage area and the rest of my base. I use Flux Networks Flux Points to power each part separately (using a Dense Energy Cell as a go-between for the Flux Point and the Quantum Bridge, since the Flux Point will not connect to the Bridge itself).

I think there's a slight delay where power hasn't propogated into the Controller or one or more of the bridges and it tries to use power. I'm basing this on the lines in the crashlog about the EnergyGrid.

**To Reproduce**
1) Start Stoneblock instance
2) Load my world
3) Crash

**Expected behavior**
1) Start Stoneblock instance
2) Load my world
3) Play Stoneblock

**Additional context**
[Crashlog](https://pastebin.com/ffYMSUw4)
A full crashlog was not created for this crash, so I have linked to what I do have.

**Environment**
OS: Ubuntu 14.04
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2768
AE2 Version: rv6-stable-4

**Comment by yueh** [comment] 2018-11-24 10:34
Duplicate of #3800

**Closed by yueh** 2018-11-24 10:34 UTC

**Comment by mattheufarmer** [comment] 2018-11-25 22:16
I seem to have solved this by making sure my Controller Multiblock has a few Dense Energy Cells attached to it at all times, even though it is also being supplied power from the Flux Point.

I went back to an older backup and made sure to always have the Dense Energy Cells connected and I've not had this problem since, even with more Compact Machines and more Quantum Bridges than before.
