### ISSUE TITLE
Missing recipes for processors

### ISSUE THREAD

**Issue by Casper3** [AppliedEnergistics/Applied-Energistics-2#3265] opened 2017-12-02 16:24 UTC
#### Description
I can only put items in the middle slot of the inscriber. I can't put items in the top and bottom slot. I've tried putting items in the top and bottom with hoppers and itemducts, but this doesn't work either.
Also, the recipes for all the processors and processor parts aren't showing up in JEI.
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 14.23.1.2555

**Comment by fscan** [comment] 2017-12-02 16:42
Please post a log file. What other mods are installed?

**Comment by Casper3** [comment] 2017-12-02 17:51
Alright I'm not very experienced with this stuff, hope this will help:
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1524015/latest.log)
Modlist (typed over from mods folder):
Actually additions
ae2 stuff
appleskin
applied energistics 2
aroma1997core
aroma1997s dimensional world
badwithernocookiesreloaded
baubles
bdlib
betterbuilderswands
betterfps
bibliocraft
biomesOplenty
bookshelf
botania
brandonscore
chameleon
chest transporter
chisel
chisel and bits
codechickenlib
cofhcore
cofhworld
compacter
compact machines
compact solars
cooking for blockheads
crafttweaker2
ctm
cyclopscore
danknull
darkutils
diethopper
draconic evolution
dynamic surroundings
elevatormod
enderstorage
environmentaltech
etlunar
everlasting abilities
exchangers
extrautils2
extremereactors
fastleavedecay
fluxnetworks
forestry
forgelin
ftblib
ftbutils
funky locomotion
gamestages
gendustry
gravestone
hammercore
hwyla
ic2
inventory tweaks
iron backpacks
iron chests
jei
jei bees
jei integration
journeymap
just enough resources
librarianlib
LLOverlay reloaded
magicbees
mantle
mcjtylib
mekanism
mobgrindingutils
morebees
mousetweaks
natura
optifine
p455w0rdslib
pams get all the seeds!
pams harvestcraft
rangedpumps
redstone arsenal
redstuneflux
reliquary
rftools
rftoolsdim
roguelike dungeons
roots 2
SGExtraParts
SilentLib
SilentsGems
SolarFluxReborn
sonarcore
StorageDrawers
TConstruct
Thermal cultivation
thermal dynamics
thermal expansion
thermal foundation
TinkerToolLeveling
twilightforest
UniDict
valkyrielib
WailaHarvestability
WailaStages
WanionLib
WirelessCraftingTerminal
wizardry (by escapee)
zerocore

Please tell me if you need anything else.

**Comment by fscan** [comment] 2017-12-02 18:27
AE2 cannot load you recipe files. They should be located in "config/AppliedEnergistics2/aerecipes/generated". This is strange, as they should be generated from the jar if missing. Try to remove the "aerecipes" folder and start again.
Maybe some other mod is interfering. Try to remove AE2Stuff.

**Comment by Casper3** [comment] 2017-12-02 19:03
Removed the folder, didn't work
Removed the mod ae2stuff completely, didn't work
Removed the folder again after deleting ae2stuff, didn't do the trick either

Like I said, I really don't know a lot about files and behind-the-scenes stuff, but is it possible for me to maybe download the folder from someone else who can download it?
Or maybe make another modpack and copy the folder from that one? Just trying to think out of the box.

Thanks for the fast replies

**Comment by fscan** [comment] 2017-12-02 19:23
So, the file config/AppliedEnergistics2/aerecipes/generated/index.recipe does exist? 
Can you open it with a normal text editor? 
I guess his is on windows?

**Comment by Casper3** [comment] 2017-12-02 19:28
The file config/AppliedEnergistics2/aerecipes/generated/ is empty for me, there is no index.recipe for me.
I don't know real people who play modded minecraft, was referring to people on the internet
I'm playing on a windows laptop.

Maybe you can upload the index.recipe file so that I can put it in the .../generated folder manually?

**Comment by fscan** [comment] 2017-12-02 19:43
i mean, if you want to try you can download them from github (content of https://github.com/AppliedEnergistics/Applied-Energistics-2/tree/rv5-1.12/src/main/resources/assets/appliedenergistics2/aerecipes into generated). But to me it seems there is something wrong with your setup. Maybe some kind of (anti)virus software is preventing us from creating the files. Or some file permissions are f'd up.

**Comment by Casper3** [comment] 2017-12-02 20:21
Well this is interesting,
Tried launching twitch as administrator first, no luck there.
Made another modded profile, with only ae2, jei, jer and jei integration.
Launched that profile and the inscriber worked totally fine, recipes showed up in jei and I could acces all the slots in the inscriber.
So I took out all the files from the .../generated folder and put them in my main profile.
Launched the profile with good hopes, but still no luck (no recipes, still only acces to middle slot of the inscriber)
Checked the .../generated file of my main profile and it was empty (?)

I'm really confused now, as you've probably noticed I have no idea what I'm doing. As far as I know I don't have any antivirus software installed. I don't know where to find file permissions. It seems to be specific to my main modpack though, as the other small modpack I made (with only ae2 and jei things) could get all the files.
Hope this helps.

**Comment by Casper3** [comment] 2017-12-03 00:00
Alright I've been busy, no luck so far but I think I'm on the right track;
First I tried disabling a couple of mods at a time to see if some mod caused trouble, but couldn't find any.
Tried launching minecraft with the log open, filtered on ae2 and found a line that said my index.recipe file was missing (you were right). I googled a bit on this file and found this thread:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1890
So I tried what they said, couldn't find an in-game option for resetting recipes, but I did extract the jar file. Since then I've been trying to put the  extracted files in my folder, but I don't really know what I'm doing. I feel like I'm close though.

**Comment by fscan** [comment] 2017-12-03 00:34
Sorry, i had this wrong. The "generated" folder gets recreated at every startup (except in your case it somehow doesn't). You will need to put the extracted recipes into the "user" folder.

**Comment by mindforger** [comment] 2017-12-03 08:48
you said you launches twitch a couple times in admin mode, did you try to remove (just rename it, you won't loose all configs yet) the config folder completely to let it regenerate the whole config folder with default file permissions? or did i miss that you already tried it?

**Comment by Casper3** [comment] 2017-12-03 13:00
Tried putting the extracted files into the user folder, no succes.
Renaming the config file to 'configbackup' didn't work either (it did create a new config file though, but still no recipes for processors).
I've tried putting files into the user folder in a lot of different ways, but every time I try something the file index.recipe won't load.
Where should I look when I want to mess with file permissions? This is the only thing I haven't tried yet.
I guess if nothing works I dabble with mods like minetweaker and crafttweaker, although this won't be the easy way for me since I don't know a single thing about coding.

**Comment by fscan** [comment] 2017-12-03 13:27
Ok, i found the issue. Don't know why it is happening yet.

**Comment by Casper3** [comment] 2017-12-03 15:13
Just found out I have more missing recipes, including (but not exclusively): terminals, p2p-busses
Also the only recipe for me to get silicon is by using a mekanism crusher.
If you need me to, I can click all of the ae2 items in jei to get you a list of missing recipes.

**Comment by fscan** [comment] 2017-12-03 15:17
No, we know the cause. It was just hard to reproduce because there are different code paths when debugging.

**Comment by fscan** [comment] 2017-12-03 16:17
Ok, we have a fix which will be in the next release. In the meantime you could remove the "+" from the folder name "Survival+".

**Comment by Casper3** [comment] 2017-12-03 17:41
Haha survival+ is what I named my pack, I always make my own packs so that I can play with the mods I like and without the mods I don't like. If you really want me to I can remove the +, just for you <3
Jokes aside, thanks a lot for your time and effort.

**Closed** 2017-12-03 20:40 UTC
