### ISSUE TITLE
A lot of the recipes don't work

### ISSUE THREAD

**Issue by Audixas** [AppliedEnergistics/Applied-Energistics-2#3382] opened 2018-02-09 18:57 UTC
#### Description
Some of the recipes don't work. The ones I have tested so far are: ME (Crafting, Interface) Terminal, Silicon, any of the Inscriber recipes, Molecular Assembler, Nether Quartz tools, Network Tool, Crafting Card, Storage Monitor, all P2P devices apart from the ME one.

#### Environment
First noticed on me and my friend's modded server. Testing also done in singleplayer with the same mods and then in singleplayer with just AE2 and JEI installed. The problem persists across all of these, meaning the problem is not with the other mods we're using.

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv5-stable-8
- Forge Version: 1.12.2-forge1.12.2-14.23.2.2613

**Comment by yueh** [comment] 2018-02-09 19:08
Cannot reproduce.

**Comment by fscan** [comment] 2018-02-09 19:16
Can you post some logs?

**Comment by Audixas** [comment] 2018-02-09 21:02
[fml-junk-earlystartup.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1712420/fml-junk-earlystartup.log)
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1712421/latest.log)
[fml-client-latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1712422/fml-client-latest.log)

Here are the logs that I think are relevant.

**Comment by fscan** [comment] 2018-02-09 21:28
Can you post the full path of the ae2 config folder? What are the contents of the "aerecipes" subfolder?

**Comment by Audixas** [comment] 2018-02-09 21:31
[config.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1712468/config.zip)

Here you go. There are a bunch of other configs for mods that I removed before testing to make sure it wasn't some sort of mod conflict. And the aerecipes folder is empty.

**Comment by fscan** [comment] 2018-02-09 21:36
Can you please post the full path? We had problems with some path names in the past. Although it should be fixed this issue looks awfully similar.

**Comment by Audixas** [comment] 2018-02-09 21:39
[!singleplayer.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1712491/singleplayer.zip)

This is in AppData/Roaming/.minecraft. I seperate all my profiles into different folders with an ! at the start so they appear at the top.

**Comment by fscan** [comment] 2018-02-09 21:41
hmm, yeah .. can you try withouth the "!" ? eg create a new instance with an alphanumeric name?

**Comment by Audixas** [comment] 2018-02-09 21:43
Removing the ! solved the problem. Thank you very much!

**Comment by yueh** [comment] 2018-02-09 21:56
This is most likely not an AE2 bug, but a vanilla or forge one as most of the mentioned recipes are handled by them.

**Comment by yueh** [comment] 2018-02-10 11:28
Forge does not even allow `!` as buildpath. Why it allows it for a normal instance compared to a dev one is beyond my grasp. But they should certainly display a warning in these cases.

**Closed by yueh** 2018-02-10 11:28 UTC
Labels: state-wontfix
