### ISSUE TITLE
IGridBlock.getMachineRepresentation is not @Nullable

### ISSUE THREAD

**Issue by ruifung** [AppliedEnergistics/Applied-Energistics-2#4178] opened 2019-10-20 00:50 UTC
Despite the interface itself claiming that the method *can* return null, returning null for this method will crash the game due to ContainerNetworkStatus.java:122 trying to call .isEmpty() on a null item stack.

**Comment by yueh** [comment] 2019-10-20 07:12
Duplicate of #3925

**Closed by yueh** 2019-10-20 07:12 UTC

**Comment by ruifung** [comment] 2019-10-20 07:26
Well, yeah, probably should remove that @Nullable annotation on that interface and update its javadoc to say that it shouldn't be null (the javadocs say that null is an acceptable value.)
