### ISSUE TITLE
Using a crafting card in ME Interface with the config slots freezes all ME Systems on the server

### ISSUE THREAD

**Issue by yorii** [AppliedEnergistics/Applied-Energistics-2#4839] opened 2020-11-24 17:31 UTC
**Describe the bug**
Something causes all ME Systems to freeze up when trying to use a crafting card in an ME Interface for automatic stockpiling and autocraft ordering of specified items.

**To Reproduce**
ME Interface with crafting card, a storage bus attached to it, and any items which have a corresponding pattern elsewhere in the system loaded into the Config slots.

**Expected behavior**
ME Interface holds the amount of items specified in config slots, orders autocrafting when the amount is below the configured value.

**Additional context**
Does not produce anything in any log output, server still runs fine, no player can access any of their ME storage as long as the ME Interface has the Crafting Card/Config Slots configured like this.

**Environment**
All of Fabric modpack 2.4.4
MC 1.16.4 + AE2 8.1.0-alpha.12 (Fabric)

**Comment by shartte** [comment] 2020-11-24 17:47
I tested this with this setup, and cannot repro your problem:
![grafik](https://user-images.githubusercontent.com/1261399/100132161-4fd7c180-2e85-11eb-8858-684a85f08a54.png)

Setup:
- Interface next to the MAC has a pattern for "crafting table"
- Interface next to the storage bus stocks crafting tables
- I can access and extract crafting tables from the terminal attached to the storage bus

I cannot observe anything out of the ordinary otherwise.

**Comment by yorii** [comment] 2020-11-24 18:25
Hm... gimme an hour or two and I'll try replicating it on a local server.

**Comment by Accia121** [comment] 2020-12-25 14:10
I may have a similar issue but I have not been able to connect it to anything as of yet on an open server, I'll try to recreate on a local server also.
Same modpack, however the server has been updated to the 2.5.4 version (the issue still persists)
Some descriptions of whats happening to me:

1.When logging in after a while it will work for around a minute.

2.At some point, taking an item out, will visually cause the type of item (number of items is irrelevant) to disappear, I can continue in this manner, other items are still visible. Note once this effect starts to occur all auto crafting/interface recipes will stop working (I can click to craft up untill the start button which shows the recipe is available, but clicking yeilds no effect or change on UI)

3.After the above point has begun to occur, leaving and re-entering the interface (or any interface on the system) will result in no items being available (visually, it is similar to not having any storage in the system, bright interface - indicating power - but nothing there). At this point items can still be deposited (given there is space in storage drives) however there is no representation of deposited items; items can not be removed from the system through an interface in this stage (Import/Export buses and other peripherals will still work).

4.leaving the interface to shuffle the ME drive disks (or break and replace the ME drive) will cause the issue to revert back to stage 2 (indicated at the start of each paragraph) upon re-enering the interface.

If I collect more evidence/experimentation I will upload it here, I'll try and get a short video to describe what's occuring. unfortunately I have yet to replicate on a local server (although I haven't tried extensively yet).
Each separate ME system seems to go through this progression but stage 1 will only occur when you initially log into the server.
As this is a multiplayer server I am unable to isolate any constructs that may cause this issue if it is an effect serverwide (which is likely as creating a new ME system with no extra peripherals also recieves these issues and other people have been reporting this.

If this is not the same issue as the post author let me know and I'll move it to a new thread.

**Comment by Faustvii** [comment] 2020-12-28 23:03
So I have encountered the same/similar issue and posted my finding in this issue https://github.com/TeamAOF/All-of-Fabric-3/issues/256 in there I've also attached video showing the issue and a world download to a local copy of a world where the issue can be reproduced.
I'm also running the All of Fabric modpack on version 2.5.4 which is running appliedenergistics2-fabric-8.1.0-alpha.13

The issue I'm experiencing for sure seems to have something to do with the quantity/fullness of the storage.

I've also been able to replicate it in a single player world with just AE2 (appliedenergistics2-fabric-8.1.0-alpha.13) and Roughly enough items (RoughlyEnoughItems-5.8.10) and Fabric API (fabric-api-0.28.4+1.16)

Demonstration of the issue when storage bus is connected.
https://user-images.githubusercontent.com/4357216/103247971-a93d7f80-4960-11eb-922b-686ce4962840.mp4
and showing the result when it's disconnected
https://user-images.githubusercontent.com/4357216/103247980-b5c1d800-4960-11eb-8243-391de72d00c0.mp4

Here's the world for I'm using to produce the issue, without All of Fabric modpack.
[TestWorld.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5749041/TestWorld.zip)

**Comment by jinkhya** [comment] 2021-01-06 21:08
To add some information on this it looks like it's not just crafting cards doing it but also buses.
An easy setup to reproduce this issue is this : 
https://cdn.discordapp.com/attachments/577535257356664845/796401439773687888/unknown.png
- A cell (I used creative for convenience)
- A terminal (can be crafting, pattern or normal terminal, they all break)
- Some drives in a ME drive
- An export bus to some kind of inventory

Everything is fine until you configure the export bus with an item. As soon as it starts exporting the terminal shows empty.

**Comment by coolsa** [comment] 2021-01-15 11:59
I believe I have figured out a reliable way to produce this bug.
**To Reproduce**
The issue seems to be between AE2 for fabric and REI. Ensure you have both of those mods running on a world, single player or multi player.

Create a system that can auto craft an item. The minimum requirements would be this system here:

![image](https://user-images.githubusercontent.com/1697614/104724668-3cf7a580-56ee-11eb-9999-2b0a779b76db.png)

Ensure that the ME Interface connected to the storage bus is set up to auto-craft, and the Storage Bus is able to show the items contained in the Interface in the Terminal, as seen here:

![image](https://user-images.githubusercontent.com/1697614/104724744-54cf2980-56ee-11eb-8014-4d276338353e.png)

Now that the system is set up, it is possible to cause all ME systems to fail.

1. Make sure that the ME Interface can use a Crafting CPU to fill itself.
2. Enter an ME Crafting Terminal, or an ME Pattern Terminal. 
3. Using REI, find a recipe and click "Move Items" to attempt to craft any item.
4. If the items do not move to fill the Crafting Table on the Terminal, you have successfully caused the bug and rendered all ME systems unusable.. 
5. Any change to an ME Systems item count will cause any attached Terminal to fail to display the contents of the System.

Exceptions to the bug: 
1. Exporting items with a Bus will still pull items from the system.
2. Items can still be inserted to the system in some circumstances, such as through an ME chest.
3. An Export Bus with a Crafting Card pushing into a chest will not cause this issue, even if the chest has a Storage Bus attached.
4. If the Storage Bus is not configured to display the items in the attached Interface, this bug will not occur.
5. This bug does not impact Portable Cells.

Some things to note about this bug:
1.  Without REI, it is not possible to cause this bug. Minecraft's recipe book does not appear on the terminals in any circumstance, but I imagine that if they did, this bug would occur *without REI.* This is a hypothesis, and is untested.
2. This bug is resolved (in most circumstances) by removing the offending Interface from the network and restarting the server.
3. In some circumstances the world will stop ticking upon a restart, preventing saving and requiring a client restart if playing in single player, or a hard server reboot.
4. This bug affects all players on a server, across all ME systems. Once any system is updated, said system will stop rendering to Terminals.

**Comment by dillonwastaken** [comment] 2021-06-22 09:23
bug still exists on fabric v8.3.0-alpha.3

**Comment by Xechorizo** [comment] 2021-08-30 01:39
Bug persists in Fabric v8.4.0-alpha.2

**Comment by Technici4n** [comment] 2021-10-05 23:08
Fabric 1.16 is not supported anymore, this is probably fixed in 1.17.

**Closed by Technici4n** 2021-10-05 23:08 UTC
Labels: fabric
