### ISSUE TITLE
when used with bewitchment it crashes (fabric)

### ISSUE THREAD

**Issue by rtb523** [AppliedEnergistics/Applied-Energistics-2#5326] opened 2021-07-04 22:47 UTC
**Describe the bug**
when this is used with bewitchment it crashes with error code 0 and when i talked to the creator of bewitchment they said that it is running code that it only runs with origin and that causes it to crash but without applied energestics it doesent do it (still talking to creator of bewitchment about this though if it is resolved by them i will close)

**To Reproduce**
use bewitchment and all its dependencies with applied energestics

**Expected behavior**
minecraft to launch as normal and for it to not detect applied energestics as orgin
**Additional context**
https://pastebin.com/1RR2RdvB

**Environment**
its in fabric on an intel cpu with 8gb ram and i cant get far enough into launch to force crash with f3+c for 10 sec

- Environment:

**Comment by Infinidoge** [comment] 2021-07-07 00:46
Can reproduce, though an additional note, this only seems to happen with Fabric API versions >= 0.35.1. Using 0.35.0 and below allows both to run together without issue.

**Comment by Technici4n** [comment] 2021-07-07 09:59
Duplicate of #5301

**Closed by Technici4n** 2021-07-07 09:59 UTC
