### ISSUE TITLE
Server crashes when ME Terminal and glass cables are interacted with/placed.

### ISSUE THREAD

**Issue by connormo** [AppliedEnergistics/Applied-Energistics-2#4644] opened 2020-08-26 01:55 UTC
Server just crashes when ever a EME terminal is opened and the glass cables are placed. Running forge 1.15.2, 31.2.36 dedicated server. Screenshots + crash log below.
We think this may be because of bad integration with other mods but not sure. 
![image](https://user-images.githubusercontent.com/58981484/91246320-8fbfc900-e71d-11ea-9bc5-2b6799ee9b5e.png)
[crash-2020-08-25_21.45.45-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5127120/crash-2020-08-25_21.45.45-server.txt)
[crash-2020-08-25_15.47.55-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5127121/crash-2020-08-25_15.47.55-server.txt)

**Comment by yueh** [comment] 2020-08-26 03:57
Duplicate of #4467

**Closed by yueh** 2020-08-26 03:57 UTC
