### ISSUE TITLE
1.16.5 UnloadChunk Error, only mod to see is Applied Energistic 2 that is causing it

### ISSUE THREAD

**Issue by Myzumi** [AppliedEnergistics/Applied-Energistics-2#5091] opened 2021-03-24 23:59 UTC
**Describe the issue**
While im alone on my modded server and walking arround and exploring the map, some errors are comming up and the only mod i can identify is applied energistics 2 in it
**Environment**
Error: https://pastebin.com/1LKu6RGw
Mod Version: 8.3.0-alpha (as the crash report says)
Version: 1.16.5
Modpack: Slightly Vanilla Flavoured modified with some tech mods

-> Im not sure if its related to Applied Energistics 2, its the only thing that i found in the error

**Comment by Myzumi** [comment] 2021-03-25 00:08
Something to add to this: When you die, you cannot pick items up in that area, after respawning and trying to open a chest, dosent do any sounds anymore but still opens

**Comment by shartte** [comment] 2021-03-25 00:11
Duplicate of #5069

**Closed by shartte** 2021-03-25 00:11 UTC
