### ISSUE TITLE
Crash when displaying AE2 advancements in modpack Sky Adventures (1.12.2)

### ISSUE THREAD

**Issue by Pyeroh** [AppliedEnergistics/Applied-Energistics-2#3861] opened 2018-12-16 07:30 UTC
**Describe the bug**
When I open the AE2 advancements tab in game, my client crashes, with a NPE.

**To Reproduce**
1. Connect to a world (single or multi-player)
1. Go to escape menu
1. Advancements menu
1. Click on AE2 tab

**Expected behavior**
The advancements tab should be displayed.

**Additional context**
Crash log : https://pastebin.com/4Zc6rU7y

**Environment**
- Modpack FTB Sky Adventures, version 1.3.0 
- Minecraft 1.12.2
- Forge 14.23.5.2770
- AE2 rv6 stable 4
- 6 GB RAM
- First produced on MP
- No modification of the modpack (same mods, same versions as provided by the pack version)

**Comment by yueh** [comment] 2018-12-21 20:07
Duplicate of #3810

**Closed by yueh** 2018-12-21 20:07 UTC
