### ISSUE TITLE
Weirdest bug ever : crafting window not opening

### ISSUE THREAD

**Issue by assombrance** [AppliedEnergistics/Applied-Energistics-2#2365] opened 2016-09-04 16:49 UTC
So, i'm playing Sky factory 2.4, and autocrafting was working perfectly.
But one day, it apparently stoped working for no reason.
On a terminal, when trying to launch an autocraft, the window always closed after the first step (when the quantity of items is asked)
Later on, I realized this only append when I had the wireless terminal on my hotbar and when it wasn't selected.
Any idea of how to fix it ?

**Comment by mindforger** [comment] 2016-09-05 06:23
please press ingame f3 + c for minimum of 6 seconds to produce a forced crash and attach the crashlog as file or via pastebin to your report, there is no public visible mod list of Sky factory 2.4 so it is hard to say what you are using! (do not textwall it)

and just for clarification, you have at least one or more energy cells attached to your network?
Your entwork is not too big to have issues with unloaded chunks or is generally chunkloaded properly? (with which chunkloader)

**Comment by evandixon** [comment] 2016-09-14 03:08
I've encountered the same bug on FTB Infinity Evolved 2.6.0, which uses AE rv3 beta 6.  Only one terminal connected to the network errors, and moving it to face a different direction fixes it.  Then moving it back makes it error again.  Checking the progress of a crafting job disconnects the client.

Error message as shown by the server:
http://pastebin.com/NcyBD42u

Crash report as requested by @mindforger:
http://pastebin.com/TWD5NcVL

**Closed** 2016-10-01 10:12 UTC
Labels: state-waiting

**Comment by assombrance** [comment] 2016-10-07 11:18
No, my network was fine, and the bug stoped occurring one week later, without me really doing anything. Sorry my explanations are not clearer

**Comment by 4papuce** [comment] 2017-04-17 20:37
This happened to me also. But I did A LOT of troubleshooting. I am running the DireWolf 20 1.10 pack in version 1.9.1, I have added a lot of other mods like: TATW, ProjectE, dualhotbars etc. And I created my first AE2 system. NOTHING WAS WORKING. After a lot of troubleshooting I came to a conclusion: failure of the human factor. 
But that is not the issue. I found out some weird bug. First off I thought that it was between ProjectE and AE2, having items with 1 EMC in the hhotbar. Then I thought it was between DualHotbars, but that is bullshit, because it happened even after I disabled DualHotbars. Note that I did not disable ProjectE. 
I came to a conclusion: When having and item in the 4th hotbar slot. It is the exact same issue you were talking about. Press craft and it just exits out. The same happens if you click on the crafting monitor in the ME crafting terminal. 
I also have the Crash report: https://pastebin.com/hvxAKhQM

**Comment by mindforger** [comment] 2017-04-18 05:27
Can you reproduce without the dual hotbar? Make a backup of your world

**Comment by mindforger** [comment] 2017-04-18 05:28
Oh whoops you already did

**Comment by 4papuce** [comment] 2017-04-18 09:29
BUT! When I try this bug in a test world with the EXACT same configuration this bug doesn't occur. I just don't know anymore.
