### ISSUE TITLE
Unable to Craft items when used in the Crafting Pattern

### ISSUE THREAD

**Issue by jonnygrove** [AppliedEnergistics/Applied-Energistics-2#3262] opened 2017-12-02 04:21 UTC
I have a few processing & crafting patterns that involve using the item itself that is being crafted. For example, crafting food items using a phytogenic insolator. I can pull up the simulation for the processing recipe, however it will not allow me to start the process. I'm not sure if there's a limitation with crafting items using the item itself, but it almost seems like this could be a bug since AE2's crafting stores away the items used in the crafting processors in the crafting storage units.

Is this something that can be fixed or is there a setting that should be adjusted in a config?

Attached a screenshot of what I'm trying to accomplish.
![ae2](https://user-images.githubusercontent.com/22922033/33511715-0ed41734-d6ee-11e7-83b6-4a989b127354.PNG)

- Minecraft Version: FTB Beyond 1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1.jar
- Forge Version: 12.18.3.2511

**Comment by yueh** [comment] 2017-12-10 22:56
Duplicate of #dunnoTooMany. 

In short: Intentional. If you want a detailed explanation, there are a couple of duplicates. But I can't currently find them.

**Closed by yueh** 2017-12-10 22:56 UTC
