### ISSUE TITLE
Mixin error on startup when using gradle dependency

### ISSUE THREAD

**Issue by Lothrazar** [AppliedEnergistics/Applied-Energistics-2#4919] opened 2021-01-08 19:53 UTC
I followed the README instructions for the Maven, except i need the actual mod to be installed so i can for example place blocks and build a network, so the API is not enough.  

it wont start

**Describe the bug**
 Caused by: `org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_242421_g:Ljava/util/Map; in net/minecraft/world/biome/Biome for appliedenergistics2.mixins.json:structure.BiomeAccessor->@Accessor[FIELD_GETTER]::getBiomeStructures()Ljava/util/Map; [INJECT Applicator Phase -> appliedenergistics2.mixins.json:structure.BiomeAccessor -> Apply Accessors ->  -> Locate -> appliedenergistics2.mixins.json:structure.BiomeAccessor->@Accessor[FIELD_GETTER]::getBiomeStructures()Ljava/util/Map;]`

**To Reproduce**

Add the following lines to the gradle dependencies of any mod

`  
    compileOnly "appeng:appliedenergistics2:8.1.0:api"

    fg.deobf "appeng:appliedenergistics2:8.1.0"

    runtime "appeng:appliedenergistics2:8.1.0"`

**Expected behavior**
I expect minecraft to start and not crash
**Additional context**
Full log

https://pastebin.com/ttugcr3e

Main error caused by the mixin as shown

**Environment**

mc_version=1.16.4
forge_version=35.1.36
mappings_version=20201028-1.16.3

JVM 1.8.0_251 64 bit

**Comment by yueh** [comment] 2021-01-08 20:07
Duplicate of #4908

**Closed by yueh** 2021-01-08 20:07 UTC

**Comment by Lothrazar** [comment] 2021-01-08 20:54
Aha thank you!.

For anyone seeing this in the future just add          properties 'mixin.env.disableRefMap': 'true'  

 https://github.com/Vazkii/Botania/blob/2916f3e1154106cd598e97241d84916926943bb9/build.gradle#L54
