### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by matyklugDebbuged** [AppliedEnergistics/Applied-Energistics-2#3645] opened 2018-07-23 12:09 UTC
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6 alpha 3
- Forge Version: 14.23.4.2739

crash report: https://pastebin.com/rjiFKJ3H

**Comment by fscan** [comment] 2018-07-23 18:16
Duplicate of #3621

**Closed by fscan** 2018-07-23 18:16 UTC
