### ISSUE TITLE
duplicate item stacks/ items not stacking properly

### ISSUE THREAD

**Issue by Mikecolle** [AppliedEnergistics/Applied-Energistics-2#7461] opened 2023-11-03 17:51 UTC
### Describe the bug

importing items causes a second "stack" of the same item, pulling the itmes out and manually reinserting them causes them to stack properly. this happened in the 1.18.2 version and is also happening in the 1.19.2 version as well now. this causes massive issues with autocrafting as it will say the items arent there despite them being there

### How to reproduce the bug

import large amounts of items from automation 

### Expected behavior

items show in a single stack

### Additional details

![2023-11-03_10 49 10](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/29614860/6b5eddd8-f0aa-4217-9682-ed5e8324b867)
![2023-11-03_10 49 16](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/29614860/e913e84a-2348-4336-8f90-3be567eac73b)
![2023-11-03_10 49 21](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/29614860/955f3901-e581-45b7-9adf-ff68ba5248e4)
![2023-11-03_10 49 25](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/29614860/55edb795-ffac-4887-88d5-13af540b44c5)

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

no crash

**Comment by Mikecolle** [comment] 2023-11-03 18:47
this is also leading to autocrafting not completing because its not recognizing the final item

**Comment by Mithi83** [comment] 2023-11-12 11:15
Can you provide a more detailed description of a minimal setup showing this behavior so a developer can try to reproduce it. Maybe then a specific special condition can be identified that causes this problem.

A few questions that came to my mind when reading this bug report:
* What kind of storage is used?
** Is there enough free space in the storage at all times?
* How is the automation set up?
* How are items from the automation imported into the AE2 system?
** Pattern Provider? Import Bus? Interface?
** Do you have multiple import point running in parallel, i.e. multiple import busses (for performance reasons) on a single producer?
* Is the AE2 system online all the time? Are there some power outages in between, perhaps due to the automation drawing too much power?

I also did not quite understand the part about autocrafting. Is your automation something that generates items by itself (i.e. some sort of cobblestone generator with an import bus) or is it something that gets used in a crafting recipe?

**Comment by Mari023** [comment] 2023-11-12 11:42
duplicate items happen when there is a difference in NBT between the different stacks of the same item.
One way this can be caused by some other mod attaching empty NBT tags (which is different than no NBT at all)

**Comment by Mithi83** [comment] 2023-11-12 12:11
Good point. But why would only some generated items have those empty NBT tags? What also does not add up for me is the description of picking those items up manually and putting them back into the AE2 system that fixes item stacking. If I pick up items with empty NBT tags and put them back in I‘d expect that they would continue to not stack.

**Comment by Mari023** [comment] 2023-11-12 12:44
> Good point. But why would only some generated items have those empty NBT tags? What also does not add up for me is the description of picking those items up manually and putting them back into the AE2 system that fixes item stacking. If I pick up items with empty NBT tags and put them back in I‘d expect that they would continue to not stack.

Ah, I somehow missed this part

it could be that some mod attaches NBT to all items in the inventory, or removes empty tags (in this case the machines would produce stacks with junk NBT)

also because this is forge, it might also be caps instead of NBT? tho I am really not sure how those work
---
either way, we need the NBT data of the items or even better the NBT data of the storage cells (which contain the NBT of the items, but it won't get modify when picked up)

**Comment by Mikecolle** [comment] 2023-11-12 20:13
everything is  coming in from create to applied energistics through interfaces, its fine when using an import bus, its only on applied energistics as refined storage doesnt have this issue.

**Comment by Mithi83** [comment] 2023-11-14 20:09
By chance I found something similar in my current ATM9 world. I isolated two item storage cells containing the two stacks of non-merging items, in my case both had "id: mysticalagriculture:inferium_essence" and "#c: ae2:i". One however additionally had one "tag" labeled "Picked: 1". So your assumption was correct for my case Mari023.

In contrast to the original bug report picking up stacks and putting them back in does not fix the stacking issue.

In my opinion it would be helpful if you (Mikecolle) could provide us with a sample of your problematic discs. The way I did it was to find out which two item storage cells held the two non-merging stacks, put them in my player inventory, save the game and analyse the save file (level.dat) in NBTExplorer. To find the discs I took them out one by one and put them in a small ad-hoc-network containing only a power source, a ME drive and a terminal.

Finding out which mod set that tag will be more challenging though I guess.

**Comment by Mikecolle** [comment] 2023-11-14 21:06
https://drive.google.com/drive/folders/1R3gxxIWuKAlo_0bmK-5q2jPSrKSJY6bG?usp=sharing modpack is struxsmp 1.19.2

**Comment by Mithi83** [comment] 2023-11-16 18:14
Thanks for your world. I could not find any AE2 related item in your player inventory and therefore could not see any relevant data. Please locate the item storage cells that contain the relevant non-stacking items (both stacks!) and place the cells in your player inventory, then reupload your playerdata. Searching blindly in a non-familiar world is rather complicated.

**Comment by portres** [comment] 2023-12-04 23:30
I have the same Issue with same items not stacking and items not being recognized for Crafting e.g Quartz is "missing" for autovrafts but I can use it normally in the terminal and also craft with it manually

**Comment by Mikecolle** [comment] 2023-12-07 04:42
> Thanks for your world. I could not find any AE2 related item in your player inventory and therefore could not see any relevant data. Please locate the item storage cells that contain the relevant non-stacking items (both stacks!) and place the cells in your player inventory, then reupload your playerdata. Searching blindly in a non-familiar world is rather complicated.

ive reuploaded the player data folder with the issue

**Comment by Mikecolle** [comment] 2023-12-07 04:45
https://drive.google.com/drive/folders/1aJl64Ki2p1HYUbl1yCQyJIZ8R3NW4meN?usp=sharing

all my drives in inventory to check data

**Comment by Mikecolle** [comment] 2023-12-20 21:28
The issue has been solved its only items being inserted through an me interface, items imported through a import bus are put into the system normally

**Comment by Mikecolle** [comment] 2023-12-20 21:39
correction issue is linked to mega cells

**Comment by portres** [comment] 2023-12-20 21:40
So no Mega cells and its fine?

**Comment by Mikecolle** [comment] 2023-12-20 21:42
i swapped the drives from mega cells to regular ae2 drives and the issue goes away
but if i put the mega cells back in it starts up again

**Comment by portres** [comment] 2023-12-20 21:43
So you mean the cells from AE2 Things?

**Comment by Mikecolle** [comment] 2023-12-20 21:45
no, the mod is called mega cells

**Comment by portres** [comment] 2023-12-20 21:47
ah okay I don't have that one

**Comment by Mikecolle** [comment] 2023-12-20 21:49
im wondering if its something with all the addon cell mods
as the ae2 things cells do the same thing

**Comment by portres** [comment] 2023-12-20 21:55
I found a thread talking about Dungeons Mobs not sure if you have it. Testing it now if thats the problem for me

**Comment by Mikecolle** [comment] 2023-12-20 22:01
nope im running a completely custom pack been chasing this issue since our pack was 1.18.2, thought going to 1.19.2 would solve it as someone suggested but it didnt

**Comment by portres** [comment] 2023-12-20 22:11
So you don't have the mod Dungeons Mobs?

**Comment by Mikecolle** [comment] 2023-12-21 02:43
so with advanced tool tips shown the items have different serial numbers what could be changing this

**Comment by Mikecolle** [comment] 2023-12-21 02:57
![2023-12-20_18 52 27](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/29614860/2084f071-e5ae-4b0f-995d-a43c6ffcc512)
![2023-12-20_18 52 28](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/29614860/16ddf76b-46de-4be1-8d63-56330d1754fc)

its only added to items in storage cells as replaceing the storage cells with drawers vaults and chests using busses does not cause this issue

Message #general

**Comment by Mikecolle** [comment] 2023-12-21 17:15
ISSUE SOLVED! remove Dungeon Libraries

**Comment by portres** [comment] 2023-12-21 22:00
Nice, did you still have to remove all items manually?

**Comment by Mikecolle** [comment] 2023-12-21 22:10
> Nice, did you still have to remove all items manually?

i just used a creative power cell drive io and storage bus into a chest then imported the items into the system it removed the tags from dungon libraries when it put them in the chest

**Comment by portres** [comment] 2023-12-22 19:58
Can you explain a bit better? As for now I can only make it work when I put items in my inv and re add them to the ME, exporting to a chest and importing does not fix. I have more than 3 million items :D

**Comment by Technici4n** [comment] 2024-02-16 15:51
Apparently, problem came from another mod (dungeon libraries). Closing.

**Closed by Technici4n** 2024-02-16 15:51 UTC
Labels: bug
