### ISSUE TITLE
Old Terminal Block Suggestion

### ISSUE THREAD

**Issue by 34486** [AppliedEnergistics/Applied-Energistics-2#4295] opened 2020-02-23 23:41 UTC
**Describe the feature**
Just wondering if you all could add the old ME system terminal blocks, so you can have your crafting terminal, as a physical block and not just a face, OR if it would be possible if you all could add a block that had the same side texture as the old termianl, so it can be made into a facade and put on to LOOK like an old style me terminal. 

**Reasons why it should be considered**
Nostalgic reasons, decorative reasons. I wouldn't imagine it would be the end of the world to add, I would only assume you could copy the old texture, add a block, and allow it to be crafted into a facade. Maybe a full-sized block could also have other features, such as storing maybe 1-4 ME drives in it, or a crafting terminal also able to act as a pattern terminal. Just things like that.

**Additional Context**
-

Thank you!

**Comment by leagris** [comment] 2020-02-24 01:12
A terminal block could also allow up to 5 interfaces to interact with it, the same way interface blocks can interact with 5 inventory blocks, while still using a singe channel.

Getting the aesthetic aspect of the old terminal could be achieved by having interface use a full cover part rather than an edge trimmed panel. I've often found it frustrating to require small rod parts or holed covers of the surrounding wall material to have a terminal seamlessly fills the void around the terminal part.

**Comment by yueh** [comment] 2020-02-24 09:19
Duplicate of #42

**Closed by yueh** 2020-02-24 09:19 UTC
