### ISSUE TITLE
Server crash on startup [Exception in server tick loop]

### ISSUE THREAD

**Issue by catchra** [AppliedEnergistics/Applied-Energistics-2#3789] opened 2018-10-19 03:00 UTC
Minecraft Crash Report
https://gist.github.com/catchra/7067745d78ebbb3e1537b372e1a97d76

Debug.txt
https://gist.github.com/catchra/e07a5330cbb9ed2cf2dd9fd69fc4d9ba

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-2
- Forge Version: 14.23.5.2770

**Comment by yueh** [comment] 2018-10-19 06:35
Duplicate of #3377

**Closed by yueh** 2018-10-19 06:35 UTC
