### ISSUE TITLE
ConcurrentModificationException causing serve crash- FTB Revelation

### ISSUE THREAD

**Issue by tommynov1000** [AppliedEnergistics/Applied-Energistics-2#4038] opened 2019-05-14 14:21 UTC
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2796

Log: https://pastebin.com/4PqziE0z

I am hosting a FTB revelations 2.7.0 server via Shockbyte, and I am getting a ConcurrentModificationException multiple times a day (Occurs every 20-60 minutes) that causes a crash. I read up on some tickets which have almost identical crash logs errors, which recommended added multiple dense energy cells just to be sure, which seemed to have fixed the issue for them. However, upon doing so, I no longer have access to my ME network, so trying to connect dense cells causes them to just break. If I place the ME controller after the dense energy cell, it crashes the server again.

**Comment by yueh** [comment] 2019-05-14 17:31
Duplicate of #3800

**Closed by yueh** 2019-05-14 17:31 UTC

**Comment by tommynov1000** [comment] 2019-05-15 20:59
Ticket #3800 describes adding dense energy power cells, and while I have added an additional 20 to my, and everyone else's network since opening the ticket, the crashes still happen. However, they happen less often, but they do still occur about every 3 hours now.

**Comment by Shybella** [comment] 2019-06-03 21:07
Yeah, it's because the error is very vague and the related error requires lots of debugging that yueh doesn't want to do.

**Comment by mindforger** [comment] 2019-06-04 01:41
@shybella this is very rude to say, how can you debug such a mess of mods in your opinion? 
@tommynov100 how often does this happen? Can you try running without foamfix for testing? Next probable targets would be all the ae2 addon mods, but that would hurt your server too much

**Comment by Shybella** [comment] 2019-06-04 01:56
It's not rude, it's the truth, nor was it meant to be rude.

It seems the error occurs with multiple mods. I found the cause of mine being a item causing a chunk unload on player logout and the ME system inside that chunk become affected by the error by the mod causing the chunk unload. 

There seems to be atleast 1-2 reports open a month about this error with different modpack/mod configurations, so I understand why such a vague error is getting such vague attention as it's difficult and requires a lot of work to target.

**Comment by runescapejon** [comment] 2019-06-20 22:19
I am having the same issue, I do not have foamfix install. It seem sponge is not likely the issue because i have seen other who are experiencing the same issue who doesn't have sponge installed. What i have done to possibly better help this situation. I have gone through many others and myself mods list in crash report and compare them side by side and see what possible mod that hook onto AE2 and the only thing that i found was EnderIO. 

I will be doing more testing with EnderIO and AE2 and see if i can reproduce the issue with just those two mods and see what happen with just AE2. This will help determine if the cause it's really from Enderio.
