### ISSUE TITLE
Spatial IO Ports inside Spatial Storage Cells don't capture/deploy entities

### ISSUE THREAD

**Issue by gdavid04** [AppliedEnergistics/Applied-Energistics-2#5157] opened 2021-04-16 15:21 UTC
**Describe the bug**
Spatial IO Ports inside Spatial Storage Cells don't capture/deploy entities.

**To Reproduce**
- Get stored in a Spatial Storage Cell
- Build a SCS inside it, connect it to power and a Spatial IO Port with a blank Spatial Storage Cell in it
- Get an entity inside the SCS
- Activate the Spatial IO Port
- The entity isn't stored in the cell, but blocks are

**Expected behavior**
The entity should get stored in the cell, just like blocks

**Environment**
mc version: 1.16.5
forge version: 36.1.0
mods: only ae2 8.2.0
forced crash report: https://paste.ee/p/0m9v2

**Comment by yueh** [comment] 2021-04-19 09:05
Could not reproduce this with the 8.3-beta.1 release.

Teleporting entities in 1.15 and 1.16 was always a bit unstable and forge broke it like every dozen builds or so.
Further 8.2 was build for forge 35.x with 36.x being explicitly marked as incompatible. Just that Forge does not care about it and loads it anyway.

So I guess the best option would be to downgrade forge to a recommended build of 35.x or potentially the latest build of it and test it again.

**Comment by gdavid04** [comment] 2021-04-24 19:00
The problem persists with 8.3.0-beta.2 with 1.16.5, forge version 36.0.21, the minimum required version for that build.

**Closed** 2021-05-01 08:33 UTC
Labels: awaiting-feedback
