### ISSUE TITLE
NoSuchElementException in NetworkMonitor.postChange

### ISSUE THREAD

**Issue by StephenLujan** [AppliedEnergistics/Applied-Energistics-2#3784] opened 2018-10-16 02:48 UTC
Minecraft crashed with a stack trace

**Describe the bug**
Crash

**To Reproduce**
No idea how to reproduce. I was moving away from the area so the chunk may have been unloading.
I had played many hours with a sizeable ae2 network, the same mods, and left the area many times without a crash however. Judging by the stack trace it shouldn't be that hard to add a safety check though even if postChange shouldn't be in a situation where it's popping from an empty ArrayDeque

**Additional context**
[stack trace](https://paste.dimdev.org/zovupaxawo.mccrash)

**Environment**
Windows 10
Single player.
I added Optifine and TickDynamic to the mod pack to attempt to improve lag. 

- Minecraft Version: 1.12.2 
- AE2 Version: rv6-stable-2
- Forge Version: 14.23.5.2769

**Comment by StephenLujan** [comment] 2018-10-16 03:11
I just looked at the code myself, and I have no idea how this crash was even possible. It does not seem possible. If my RAM is going bad or something, I'll come back and update.

**Comment by yueh** [comment] 2018-10-16 10:09
Most likely a duplicate of #3777.

**Closed by yueh** 2018-10-16 10:09 UTC
