### ISSUE TITLE
ME system refuses to accept power

### ISSUE THREAD

**Issue by Flux-Adept** [AppliedEnergistics/Applied-Energistics-2#8078] opened 2024-07-30 00:16 UTC
### Describe the bug

I am playing Prominence 2 Modpack and randomly my ME System will stop accepting power from all sources. I have tried every single cable in the pack, ender cells, with and without energy acceptor, hard wiring the ME system to my power production and everything else INCLUDING tearing down and rebuilding the entire controller. I have approximately 700 channels active on the network, and occasionally the system will just stop accepting power. I have tried everything in my power and the only thing that seems to work, is a complete tear down and rebuild and a jumpstart from a superdense cell that has power already. It will function as intended for a while, but then randomly will stop accepting power, and eat through the internal buffer and then shut off. I have tried everything, reported this to staff on my server, and they told me to inform the mod devs. I have even placed more controller blocks on the controller multiblock to increase the internal storage buffer, I have 188 Controller blocks as part of the multiblock structure. 

### How to reproduce the bug

I am unsure what exactly causes this, but I think it is tied to leaving the dimension and coming back. I am unsure when it happens, I usually just notice when my system no longer is online. 

### Expected behavior

I expect my system to continue accepting power while it is being directly powered by a 4 Billion RF ender cell and power acceptors, and directly powered with an ender cell touching the controller directly. I have multiple locations on the controller for power to be inputted into it, but sometimes the power refuses to enter the ME controller. 

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/ha9F0KiE

**Comment by Flux-Adept** [comment] 2024-07-30 12:19
https://pastebin.com/KDgTFmBz This is a link to the new crash log that I just created while the error is occurring. The other crash log is while the error has just been fixed.

**Comment by Mithi83** [comment] 2024-07-31 11:53
You selected 1.21 as your Minecraft version, but the crashlog shows 1.20.1. Since 1.21 does not support Fabric, I would rather believe your crashlog.

The bug description reminds me of #8064 and I think I‘ve read it before somewhere, but I can‘t remember where.

**Comment by Mithi83** [comment] 2024-07-31 20:09
On the top right corner of your original bug report you should find three dots and the option to edit your report.

**Comment by Mithi83** [comment] 2024-08-01 21:00
Finally found the bug I had in mind: #7819

**Comment by Technici4n** [comment] 2024-08-01 22:03
Duplicate of #7819

**Closed by Technici4n** 2024-08-01 22:03 UTC
Labels: bug
