### ISSUE TITLE
The game grash with the latest version of fabric 0.11.6

### ISSUE THREAD

**Issue by JatzCarlea469** [AppliedEnergistics/Applied-Energistics-2#5303] opened 2021-06-17 19:18 UTC
The mod is in the latest version but with the latest version of fabric it crashes and I would like to understand if I have to wait for an update if so when or is there a way to fix it?

**Comment by Technici4n** [comment] 2021-06-17 19:31
Duplicate of #5301

**Closed by Technici4n** 2021-06-17 19:31 UTC
