### ISSUE TITLE
Interface which controls connected storage interfaces, input and export bus settings

### ISSUE THREAD

**Issue by someoldman** [AppliedEnergistics/Applied-Energistics-2#4223] opened 2019-12-16 14:49 UTC
**Describe the feature**
The user should have an interface available, similar to the ME Interface Terminal, which allows the settings of the individual storage interfaces, input and export bus's placed on the network to be changed.   This wouldn't alter any of the existing functionality of these devices. 

**Reasons why it should be considered**
When playing the game, most networks are hidden behind decorative blocks.  If the user wants to make a change to the Input/Output mode for example of a specific ME Storage Interface, those blocks need to be removed in order to access the interface.  This feature would remove the need to do this as the functionality could be accessed from a single console.

**Additional Context**
Interfaces and Buses could be named to allow easier network management.

**Comment by mindforger** [comment] 2019-12-16 16:28
Tried using an interface terminal? At least interfaces can be configured there.

**Comment by someoldman** [comment] 2019-12-16 21:35
To be honest, it's the one of the only things I find lets the mod down, for me anyway.   I tend to use it with other storage mods and not being able to isolate say a bank of draws without going to the connected storage interface, removing a section of wall and then changing the settings is a pain in the arse.   Hence the request to have all of the settings available in one place. :)

**Comment by bookerthegeek** [comment] 2019-12-17 00:57
How about only ones that you have named?

**Comment by mindforger** [comment] 2019-12-17 04:23
> How about only ones that you have named?

Also okay imho, how does that sound @someoldman ?

**Comment by someoldman** [comment] 2019-12-17 07:47
The naming is so they can be identified.  In the current version I haven't been able to get naming to work on the ME Interface Terminal so if I have multiple alloy smelters connected (EnderIO), after I've named them they still just show as a group although I appreciate this could be my lack of knowledge rather than a thing with AE2.

**Comment by XFactHD** [comment] 2019-12-17 16:06
How did you name them? Did you rename the machine or the interface?

To rename an interface you rightclick a quartz cutting knive into the air, put a metal ingot into the slot, enter a name and take out the resulting inscriber name press. Then you put that into an inscribers top slot and the interface in the center slot. The name press won't get used up in this process.

**Comment by yueh** [comment] 2019-12-18 17:20
Duplicate of #50

**Closed by yueh** 2019-12-18 17:20 UTC
