### ISSUE TITLE
Energy acceptor constant drain

### ISSUE THREAD

**Issue by hello13579** [AppliedEnergistics/Applied-Energistics-2#1005] opened 2015-03-11 10:25 UTC
I seem to have a problem when using the energy acceptor. Im playing on a survival server with my friend and after progressing half way through galacticraft stuff and noticing I need the ME system, i started with AE. When I got the energy acceptor, I hooked it up to the solar panels from galacticraft. However, the energy acceptor drains all the power from my energy storage module and i have nothing left for anything else. Nothing gets stored into the energy acceptor and there is nothing hooked up to it. I dont know if this is intentional, a bug, or something i did wrong, but i would like to figure this out. 

The mods i am running are extra utilities, galacticraft, not enough items, tinkers construct, metallurgy 4, AE2, extraTiC, CoFHcore, bibliocraft, forge and biomes o plenty. 

I am running minecraft version 1.7.10. 

Thanks

**Comment by gixbit** [comment] 2015-03-11 11:28
Most ME network blocks have a passive power drain. An me network never stops using power. In my smp world i have a network that runs 2.5k RF/t passive which is small compared to some people on here. This can fluctuate based on certain factors to my knowledge. A small system starts using upwards of 150RF really quickly. Crystal accelerators and inscribers and pretty much every storage drive you add adjusts your power usage up.

Are you sure you arent misunderstanding your ME power consumption? Make one of those network wrenches that is an upgrade of a basic wrench and check your network generation and usage.

**Comment by hello13579** [comment] 2015-03-11 14:21
The thing is there shouldn't be any power drain, as there is only an energy acceptor. Nothing else is hooked up to it. But it seems as it can take in as much power as there is possible. I made a creative world and hooked a fully charged x64 generator from extra utilities to only a energy acceptor, and it took all the power from it in 5 seconds. using the network tool, it shows no usage whatsoever but it somehow is still draining power from any power source I can hook up to it. I haven't tried a vibration chamber but I'm trying to stay away from coal based power sources. I would be fine if I had other AE blocks hooked up, but there shouldn't be any power usage when there is nothing connected to the energy acceptor except the power source.

**Comment by thatsIch** [comment] 2015-03-11 14:57
Is GalactiCraft based on RF?

**Comment by hello13579** [comment] 2015-03-11 15:07
It uses Galacticraft joules, but the same happens with RF from extra utilities generators.

**Comment by thatsIch** [comment] 2015-03-11 15:12
I am pretty sure, we do not support GalactiCraft Joules as of now.. do they have auto conversion to RF or something?

**Comment by hello13579** [comment] 2015-03-11 15:21
Thats weird, because I am still able to power things with it, and am currently using a temporary solution of charging enough to fill up an energy cell to power things for now. even if AE does not support gJ, this still happens with RF, which I'm pretty sure is supported by AE.

**Comment by thatsIch** [comment] 2015-03-11 15:32
Well we support Mekanism Joules, are these the same?

**Comment by yueh** [comment] 2015-03-11 15:46
To verify it, you are not using rv1-stable?

I cannot reproduce it, either by using the latest ExtraUtilities or TE with the latest rv2.

**Comment by hello13579** [comment] 2015-03-11 15:49
oh, it may be because Im using rv0. My bad.

**Comment by yueh** [comment] 2015-03-11 15:51
Ok. rv1 (and probably rv0) had an issue with it, but that is fixed with rv2.

**Closed by yueh** 2015-03-11 15:51 UTC

**Comment by hello13579** [comment] 2015-03-11 15:54
Just to verify, do I simply replace the old .jar with the new one?

**Comment by thatsIch** [comment] 2015-03-11 16:01
This should do the job

**Comment by Cisien** [comment] 2015-03-12 13:49
If you are running rv0, then there is a good chance that many of the other mods you have are outdated. I know for sure that the RF API changed between rv0 and now. You may want to consider getting the latest versions of all of the mods you are using. You will also most likely need to update forge.
