### ISSUE TITLE
Chargers no longer work on Certus Quartz when using hopper to pull items out.

### ISSUE THREAD

**Issue by Shivneel7** [AppliedEnergistics/Applied-Energistics-2#6526] opened 2022-09-02 00:09 UTC
### Describe the bug

If you place a charger, it works to make Charged Certus Quartz like normal, but once you try automating it with hoppers, the first two crystals get charged and pulled out, but the third one gets stuck, does not get pulled out, and once removed with right click, any future crystals disappear upon being inserted, whether manually or with hoppers/pipes. Once this bug is triggered, it no longer works for any chargers in the whole world. The bug can be resolved by restarting the server, so it is easy to fix on singleplayer, however this poses a problem for multiplayer servers.

### How to reproduce the bug

Place a charger and power it. Now you can charge crystals like normal, however as soon as a hopper is placed underneath the first couple crystals will craft like normal, but the 3rd crystal will appear to craft but then disappear leaving no charged crystal in its place. Removing the hopper still makes the crystal disappear. Replacing the charger, or even crafting a new one does not fix the bug either. Relogging does work (but only on singleplayer). Server needs a server restart to fix the issue.

### Expected behavior

Charged Crystals appear and are removable

### Additional details

1.19.2
Like I said, if I restart the server, the bug is fixed. It always seems to be the third crystal and its weird that all chargers in the world, even 6000 blocks away, get affected by this bug. Item transported with mekanism transpoters work fine and are exempt from this issue. I have not tried automating with AE buses yet. Only triggered by hoppers.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/wuyPj1sD

**Comment by Technici4n** [comment] 2022-09-02 06:37
Duplicate of #6509

**Closed by Technici4n** 2022-09-02 06:37 UTC
Labels: bug
