### ISSUE TITLE
seeds dissapearing

### ISSUE THREAD

**Issue by tubaplayer112** [AppliedEnergistics/Applied-Energistics-2#6286] opened 2022-05-21 01:29 UTC
### Describe the bug

while playing direwolf20 1.18.2 pack, certus quartz seeds and flux seeds are disappearing despite saying item will not despawn. have not try nether quartz seed yet.

### How to reproduce the bug

im just puttting them in water in the world. 

### Expected behavior

I would expect them to not dissapear while still a seed

### Additional details

tried put a vacculator from thermal to pick up grown crystals.i notice it wont pick up seed but will pick up grown versions however the seeds are disappearing before they finish growing. thought it was the backups but them a group disappeared before next backup came

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

N/A

**Comment by Technici4n** [comment] 2022-05-22 12:28
Duplicate of #6292

**Closed by Technici4n** 2022-05-22 12:28 UTC
Labels: bug
