### ISSUE TITLE
Please Add Disable Channels 

### ISSUE THREAD

**Issue by Holyasgard** [AppliedEnergistics/Applied-Energistics-2#5406] opened 2021-08-28 06:37 UTC
Please bringt back the Disabled Channels. 
Iam Using Refined Storage but AE2 is a better Mod. 
Please Add the Featuere for Noobs like me. 

Thanks

**Comment by yueh** [comment] 2021-08-28 06:55
Duplicate of #4621

**Closed by yueh** 2021-08-28 06:55 UTC
