### ISSUE TITLE
Energy Acceptor randomly stops accepting power

### ISSUE THREAD

**Issue by trunksbomb** [AppliedEnergistics/Applied-Energistics-2#7819] opened 2024-04-02 05:42 UTC
### Describe the bug

Seemingly randomly, my ME network will power down. My entire ME network is chunkloaded. I play on a locally hosted server on the All of Fabric 7 modpack.

The only 2 things that have resolved the issue for me are breaking and replacing the Energy Acceptor, and restarting the server.

During this time I have more than sufficient power available for the network to consume.

My best guess is that the Energy Acceptor is getting into some kind of error state where it is unable to receive energy from the Fabric Transfer API.

Minecraft 1.20.1
Fabric 0.15.7
AE2 15.0.23

### How to reproduce the bug

No idea, it seems completely random. The way I reproduce it is by waiting for a random time when I'm standing in my base.

### Expected behavior

No unexplained power loss.

### Additional details

The issue has happened intermittently over the past 2-3 weeks on 2 major version of the modpack (1.3.2 and 2.0.0). The 3 most recent times I've been at my base, standing still, looking at REI; or decorating (not interacting with the ME network directly).

I have a decently sized network with P2P tunnels connecting my large Modern Industrialization ME network. The MI subnetwork has a constant, largely unchanging load on its ME network at the times of these power losses (i.e. I did not request a massive craft on either the main network or the MI subnetwork).

Additionally, I can separate the Energy Acceptor and a small length of cable with some terminals on it entirely from my actual network, but power is still not restored in this situation. So it is not the case of massive energy drain from the ME system sustaining the outage.

I've also tried different energy cables, even attaching a Lazuli Flux battery block to it directly.
I also tried removing the chunkloading on my base and leaving (both by travelling far away and also by going to the Nether), but the issue persisted.

This is one of my posts discussing it, if you happen to be in (or want to join) the AOF7 Discord.
https://discord.com/channels/570630340075454474/1137454902625443840/1224267916757827614

This is a video I took of exploring the issue and eventually resolving it by breaking and replacing the Energy Acceptor.
https://cdn.discordapp.com/attachments/1137454902625443840/1224267916078223491/2024-04-01_03-57-17_compressed.mp4?ex=661cdf58&is=660a6a58&hm=b1001974ee7f33f40097212345f8f8a0a48b19ae753c3c8a43669d5f6125702a&

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/MXq9Zrv1

**Comment by trunksbomb** [comment] 2024-04-06 21:24
Breaking and replacing one block of my 3x3 Controller and replacing it also restored power when I tested just now.

**Comment by RealRTTV** [comment] 2024-04-08 20:42
this happens for me too

**Comment by trunksbomb** [comment] 2024-04-09 19:07
Adding to this - others have suggested putting an energy cell on the network to resolve the issue. I didn't have one on my network, and never have, historically, in any pack I've played.

I put one on anyways and the issue still happens. It just delays the system turning off until the cell drains.

**Comment by mindforger** [comment] 2024-04-09 19:18
Math is simple, you hold X amount of energy, you can empty and fill it once a tick, if thatvX is below your powerspike your out of power. Reboot made power spike loops in the past, dont know the 1.20 mechanic though

**Comment by trunksbomb** [comment] 2024-04-09 23:57
> Math is simple, you hold X amount of energy, you can empty and fill it once a tick, if thatvX is below your powerspike your out of power. Reboot made power spike loops in the past, dont know the 1.20 mechanic though

The implication being that I'm having energy spikes in excess of the capacity of a dense energy cell on a typical power draw of <1k AE/t? That would be like my house suddenly drawing more power than the nearby football stadium on game night. It's just not going to happen, unless you know of some ME device or combination of devices that can run with a reasonable amount of power and suddenly draw exponentially more power with no changes to the network (aside from Spatial IO, obviously, which I'm not using).

If I accept the implication that it's a surge, then adding a charged energy cell to the network and allowing the network to normalize should resolve the problem, but it doesn't. The network powers on and drains power from the cell but when the cell is removed it powers off again *because the network is not receiving power* from an external source. I have only found 2 fixes - break and replace a controller block, or break and replace the energy acceptor.

**Comment by mindforger** [comment] 2024-04-10 04:55
It was just an example fact to clarify, because you argumented like having no cell did always work and you also made clear that it did not help, no need to get defensive friend :) 

i did not want to imply anything and i did not say anything yet since i had no details about the size, thank you for trying out a cell anyways

**Comment by trunksbomb** [comment] 2024-04-10 07:06
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/5ef29599-f78a-460b-a8f2-1d7cb77818d2)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/55a83fc0-6fb0-470a-96ac-115c18de5372)


I wrote a CC script to monitor energy input, usage, storage, and total capacity of the system. It will log any sudden changes on the big monitor, and if the power ever completely drains it will sound an alarm that I can hear anywhere in my base. Should be able to find out what specific type of event is causing this next time this happens by reviewing the events on the monitor. I suspect it will be a sudden loss of input power.

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/b41be209-1e4f-4f1f-9040-19f4f8b19c1d)

I am curious, though, what causes my stored power to stay consistently about 100 kAE under max capacity, considering the energy usage is < 1 kAE. I've never had a reason to look at the controller much in the past so I don't know if this is typical behavior or not.

**Comment by trunksbomb** [comment] 2024-04-10 14:42
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/5c2f03bb-4454-4400-b5c0-5b926d276210)

Lost power overnight. Didn't have the script logging to a file so I'm missing the initial events here - I've corrected that and now I'll be able to review a log file after power loss. But you can see here the load stayed consistent (first number, average energy usage) while the network was losing power (third number, stored energy) and drained from 1.6 MFE stored to 0, while the incoming power was 0 (second number).

Of note, when I broke and replaced a controller block, the network came back but the Dense Energy Cell did not start receiving power. Breaking and replacing the Dense Energy Cell allowed it to start storing energy again. The next screenshot is after bringing the controller back online but before breaking/replacing the Cell. You can see that the system detects the 1.6 MFE storage capacity of the dense cell, even though it's not receiving power.

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/33daf715-3d5a-4401-bc5c-b3f55fb0476e)

**Comment by trunksbomb** [comment] 2024-04-11 07:19
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/d02ec990-1c0b-4f19-a904-463a95a4fc32)

Interesting.. this time, a different ME network went offline. First time for this one. Slightly different, though, I broke a random Controller block that wasn't receiving power and replaced it with no effect, then another - power was only restored after I broke and replaced the one receiving power. This one is powered by the MI Diesel Generator seen here. Boosted Diesel is stored in this ME network, and I've got 55k buckets of it.

**Comment by thecolonel63** [comment] 2024-04-14 04:31
I can confirm this bug is happening to me as well. My setup has an isolated power generation room inside of spatial storage powered by steam engines from Create. Occasionally, this bug occurs and I need to manually replace all of my energy acceptors to temporarily resolve it.

My workaround to the issue is to pick up and place back down all the acceptors at once with minecart contraptions, also from Create, every time the stored power on the network dips below a certain threshold. This effectively reboots the network and temporarily fixes the issue every time it occurs.

Of note: This bug seems to occur regardless of if the network has energy cells. From my testing, the only way to temporarily fix this bug seems to be to temporarily sever the energy cells and acceptors from the network and then reconnect them as previously mentioned.

**Comment by mindforger** [comment] 2024-04-14 05:19
@thecolonel63 knowing more than one having the issue is nice, but the devs require a hint on where to start the search or how to recreate the issue, if you could provide a crashlog we would know your setup better, but recreating the issue with dozends of mods and very large and old game saves wont be very much possible

if ANYONE could recreate the issue in a more controlled savegame with less mods this would be way easier to recreate and fix

**Comment by trunksbomb** [comment] 2024-04-19 16:30
The problem is just so intermittent that you would have to dedicate an instance to running a test world for (IRL) days at a time to try to replicate in the hopes that you've narrowed it down to *the right* set of mods.

It, at the very least, doesn't appear to be related to a specific mod that is delivering the power because I've tried both Powah and Indrev cables, and an Indrev battery directly. 

**When I isolate just the energy acceptor + a few cables + a few terminals from the rest of the network, power is still not restored**. This part I've already mentioned. While this isn't the absolutely "simplest" network you can make, it's already a pretty simple network. No controller, no subnetworks, no P2P, no quartz fiber. Just an energy acceptor, some cables, and some terminals. I would expect this little network to receive power from the Energy Acceptor and boot up after severing it from the main network, but it didn't. This is the part that's tripping me up the most.. a dead simple network like this should *just work*, and it always has for me in the past.
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/d0ef3156-5aae-48f7-a6c8-3092fa9aa215)

I'll continue to gather more information.

**Comment by trunksbomb** [comment] 2024-04-19 18:23
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/fd539909-0ff9-4d59-80e9-c9b7d660ae55)

So the network in my processing facility just lost energy while I was standing here. I don't have the ME Energy Monitor on this network so idk when it happened, but I was AFK in the chunk next to it when it happened.

To verify I was still getting power from the MI Diesel Generator, I installed one MI power cable and attached an Energy Acceptor + cable + terminal on it, and that powers on. But as you can see, the same MI power cable going to the ME Controller does not power the controller. You can also see the Dense Energy Cell in the picture on this network, to know that I've got more than enough available buffer energy to sustain spikes.

The diesel generator is putting out 1024 EU/t (2048 AE/t) and I'm consuming just above 300 EU/t (600 AE/t). I've got 53K buckets of Boosted Biodiesel in my system, so I'm definitely not losing power generation.
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1904331/39482382-c4d9-4066-ac34-aa9ace30465f)

**Comment by bluejorts** [comment] 2024-04-20 20:29
This issue is also occurring for me. Using a simple AE2 system built directly from the guide example "Main Network". I am powering it with an isolated bank of TechReborn thermal generators, connected directly to one of my AE2 Controller blocks. Seemingly randomly, usually overnight when I am offline (every chuck here is forceloaded on a server level), the AE2 controllers, and any energy acceptors, all stop accepting input power. I log back on to drained Dense Energy Cells, and a completely full TechReborn HV cable, a saturated Thermal Generator array, and no energy being delivered to the AE2 system.

Interestingly, if I look at the AE2 controller blocks individually as I break and replace them, _only_ the ones I break and replace begin accepting power. The others stay at 0/8kAE.

This is definitely a bug on the AE2 side.

I am going to disable nightly server restarts for my server, to see if this is an issue with the server coming back and AE2 not initializing it's power draw correctly.

**Comment by bluejorts** [comment] 2024-04-22 05:36
Update, regrettably this has nothing to do with server restarts.

**Comment by RealRTTV** [comment] 2024-05-12 18:48
I just added a quantum ring to my network on a new server I'm playing on and the issue started again. Never happened before I had it.

**Comment by LazyDope** [comment] 2024-06-26 01:27
Also encountering this issue with this mod list. The chunks are loaded by a spatial anchor.
[modlist.txt](https://github.com/user-attachments/files/15981123/modlist.txt)

**Comment by Bazzi89** [comment] 2024-07-18 19:33
Same issue here... own modpack on Fabric 0.15.11 (MC 1.20.1) with appliedenergistics2-fabric-15.2.9, not chunkloaded, happens randomly.

**Comment by Technici4n** [comment] 2024-08-01 22:03
Fixed in AE2 version 15.2.12. Very nasty bug! 😓

**Closed by Technici4n** 2024-08-01 22:03 UTC
Labels: bug
