### ISSUE TITLE
Cant craft anything

### ISSUE THREAD

**Issue by CrimsonIvory** [AppliedEnergistics/Applied-Energistics-2#1177] opened 2015-04-02 17:27 UTC
I've started a new world and everything is fine, nothing is crashing, but when I try to craft, for example an ME Cable, the crafting recipe does not show up on NEI, and even after looking up the recipe, I'm still not able to craft most of the items, and I'm talking about manually crafting in a workbench, not automated.

**Comment by XFactHD** [comment] 2015-04-02 18:22
Are you using Mekanism 8 and which ae2 version are you using?

**Comment by CrimsonIvory** [comment] 2015-04-02 18:30
The AE2 version is rv1.stable build 1, and yeah I'm using Mekanism 8

**Comment by XFactHD** [comment] 2015-04-02 18:44
rv1 stable 1 is enormously out of date. You should update to rv2 beta 18.

**Comment by CrimsonIvory** [comment] 2015-04-02 19:00
Oh, awesome, now it's working amazingly, thanks!

**Comment by Ianaver** [comment] 2015-04-03 00:23
the latest beta fixes a crap ton of issues go to that one :)

**Comment by XFactHD** [comment] 2015-04-03 01:17
The official download of the latest beta (beta 22) is broken at the moment.

**Comment by yepidoodles** [comment] 2015-04-03 05:28
I was using  rv1.stable build 1, and updated to beta 22, not knowing it was broken and now can't back date to 18, had to disable all the buses to stop the server crashes.

**Comment by yueh** [comment] 2015-04-03 09:47
@yepidoodles you can always downgrade. The worst which can happen with AE2 would be missing blocks/items, but then we did not add any new blocks/items since the start of rv1.

Otherwise closing as mostly a duplicate of the mekanism issues.

**Closed by yueh** 2015-04-03 09:47 UTC

**Comment by yepidoodles** [comment] 2015-04-04 15:36
@yueh I tried downgrading to beta v18, but the server crashed on start up - It's all fixed now though, thanks to v23, so thank you for that :)
