### ISSUE TITLE
when crafting items the craft button greys out 

### ISSUE THREAD

**Issue by direworld** [AppliedEnergistics/Applied-Energistics-2#1640] opened 2015-06-24 09:55 UTC
I have 64k crafting units and I tested all the other ones and tried adding more plus I also tried adding co processing units and the craft button is still greyed put

**Comment by direworld** [comment] 2015-06-24 09:57
I have all the items required to craft it and it still has the same problem (I'm trying to craft interface and plus I tried to craft other things and it has the same problem)

**Comment by TheJulianJES** [comment] 2015-06-24 15:35
What version of AE2 do you? Try update to the latest rv2 stable release.

**Comment by amezick** [comment] 2015-06-24 18:16
I have something similar with AGSKIES2 AE2-rv2-5.  I have two walls of sorting barrels/chests each with a refined relocation sorting interface attaching them to the same AE system.  Autocrafting doesn't work when both walls are connected.  Both walls do have a barrel of redstone if that helps.

**Comment by direworld** [comment] 2015-06-25 06:17
I have ae2 rv2 beta 28

**Comment by direworld** [comment] 2015-06-25 06:18
I tried updating and it still doesn't work my friend on the server can craft but I can't

**Comment by yueh** [comment] 2015-06-27 09:45
Could you please provide more information besides "it does not work"? Like screenshots of the GUI.
Also please ensure that it is not a duplicate of an already fixed issue like #1036.

**Comment by amezick** [comment] 2015-06-29 13:23
My part of this problem seems to have been related to Storage drawers.  I updated to the latest storage drawers and I could craft with the contents of the compacting drawers.

**Comment by yueh** [comment] 2015-07-04 09:43
No further feedback.

**Closed by yueh** 2015-07-04 09:43 UTC
Labels: state-waiting
