### ISSUE TITLE
Color Applicator: can't switch colors

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3282] opened 2017-12-17 16:01 UTC

**Comment by Xiaminou** [comment] 2017-12-17 16:30
no?

**Comment by Xiaminou** [comment] 2017-12-18 00:28
Why was this closed?

**Comment by gabor6505** [comment] 2017-12-21 11:11
I have the same issue, I am also using rv5-stable-3. Also tried without OptiFine.

**Comment by fscan** [comment] 2017-12-21 11:47
Please reproduce with only AE2.

**Comment by Xiaminou** [comment] 2017-12-21 11:54
Yes, we get it, this might not be an AE2 issue, which I already pointed out in the original post, However there is a reason I still chose to open an issue, it's to ask for help in tracking what might be causing it.

**Comment by fscan** [comment] 2017-12-21 12:05
I have no idea. I have  a server with a fair amount of mods and never had this issue. Just do the usual stuff: remove half the mods - test - remove the other half - test - etc ... there's nothing "better" any of us can do.

**Comment by Xiaminou** [comment] 2017-12-21 12:08
Okay, just so we're clear the whole "Remove half of the mods" method, isn't practical, half them mods use coremods. AND It takes over 5 minutes for my minecraft to boot.
I am not going to put 10+h on a single bug.

**Comment by gabor6505** [comment] 2017-12-21 12:13
This is actually an AE2 issue, I have just tested this out with only AE2 and Forge 2531. It happens when there is more than 127 of the same paint ball in the Color Applicator. (Note that I have tested this with having 64 of all 16 types of the paint balls in it) So for example if I only have more than 127 of brown paint ball, it closes everything else off and I can only select white, black, red and green.
https://youtu.be/L45OEaVQoKc

**Comment by fscan** [comment] 2017-12-21 12:17
Ok, i'll look into the issue

**Comment by yueh** [comment] 2017-12-21 12:17
Because the original issue did not contain any details besides "does not work". And no some random video does not count, because I won't waste time trying to deduce, if a slight change in the camera angle might indicate holding shift or just a mouse movement due to using the scroll wheel and accidentally moving the mouse.

These things are clearly stated in the readme as well as the issue ticket. They do not exist to annoy you, but to get as much information as possible without having to waits days for basic details. 

Also you said, you won't waste 10 or more hours on a bug. So do not expect, that we have the time to do it. If it is a modpack, report it to their authors, they should know about incompatibilites. If you're the author, that's basically your task to do. If we know which mods cause it (or just a description to reproduce it), we will fix it. But we won't spend time on fetching every single one of your mod and debug your modpack.

**Comment by Xiaminou** [comment] 2017-12-21 12:23
Nice attitude there, I guess all these other bugs I reported don't count for shit. Was it too hard to put a "state-waiting" like you did on other issues?

**Comment by yueh** [comment] 2017-12-21 12:42
The other issues at least have some useful information. This was nothing but a video link. And a video simply does not hint about anything you did. E.g. you could assume that shift + right click does switch the colours. Or shift and the +/- key. We don't know it.

"Does not work" without any information are pretty much the only issues I immediately close, because there is absolutely no effort done by the reporter. So simply do not expect that I put more effort into it and waste half an hour to imagine most things you might have done wrong and put them into some reasonable questions.

**Comment by Xiaminou** [comment] 2017-12-21 12:50
Yes let's assume I don't know how to use the color applicator instead of taking a minute to think about it and say "off the top of my head I can't think of anything that could cause a problem with the color applicator".
The video is literally the same kind of video I posted in the P2P Desync issue, let's close that one too.

**Comment by fscan** [comment] 2017-12-21 15:36
We are generally thankful for bug report if they are well documented and ideally reproducible. Your original report was "There's something wrong, but it's not your fault .. help me fix it". A issue like this will get closed in **every** bug tracker i know of. 
And remember that this is a community project. Nobody is getting paid or has a obligation to work on it. We like to do it and keep it as bug free as possible, but our time is limited and we cannot look at every issue in detail if there's not enough information attached to it.
As it turns out, thanks to @gabor6505 it was actually a bug on our end and got fixed in the end.

**Closed** 2017-12-21 16:28 UTC
