### ISSUE TITLE
Autocrafting crystals & Duplicating Redstone

### ISSUE THREAD

**Issue by Grexnarl** [AppliedEnergistics/Applied-Energistics-2#3104] opened 2017-09-21 16:56 UTC
Im playing in a single player world and am moving over from Refined Storage to AE2 but have hit a problem

Following this tutorial from TKH (yes i know its marked as a tutorial for 1.7.10 but i cant find any for 1.10.2)

https://www.youtube.com/watch?v=yArP-IGr_sQ&t=1086s

I have set everything up as shown in the tutorial but when i try to craft any form of crystal redstone gets dumped into the water even if its one of the pure crystals im trying to craft and way more redstone than i have in the system 

I tried just having one redstone in the system then tried crafting i ended up getting almost a full stack 

Id love to know if anyone else has had this issue or if there is another way of auto crafting crystals 

Thanks

**Comment by yueh** [comment] 2017-09-21 17:00
Duplicate of #2791.

**Closed by yueh** 2017-09-21 17:00 UTC
