### ISSUE TITLE
Cable facades cause falling blocks to break or entities to get stuck while sliding past them

### ISSUE THREAD

**Issue by TheRealWormbo** [AppliedEnergistics/Applied-Energistics-2#5246] opened 2021-05-23 18:46 UTC
**Describe the bug**

The collision model of cable facades appears to be smaller than a full block in the direction the facade is facing. You can best see this near the bottom of the world, when standing on a cable with a facade attached to the top. Your Y coordinate will be something like 4.99375. Similarly, if you only attach a facade to the side of a cable and walk up to it, your corresponding X or Z coordinate will end in .294 or .706 instead of the .3 or .7 you would see when walking up to a full block.
Other than that, the facade's face area is exactly 1x1 and aligned to the block. If you place facades on all four horizontal sides and walk diagonally into the block, you can get stuck on the slight indention between the facades, because the one facing your location is ever so slightly recessed.
(Various other cable attachments display similar behavior, even though they also look like they should be level with adjacent blocks.)

**To Reproduce**

Scenario 1:
1. Place a fluix glass cable, or a cable with any combination of properties (colored, covered, dense, smart).
2. Attach a cable facade, e.g. "Cable Facade - Stone") to the top of the cable.
3. Stack two blocks of sand on top of the facade.
4. Break the bottom of the two sand blocks. – The top sand block will fall and turn into an item when it touches the facade.

Scenario 2a:
1. Place a fluix glass cable, or a cable with any combination of properties (see above).
2. Attach a cable facade to the north, east, south and west sides of the cable. (No facades on the top/bottom and no other blocks above/below the cable.)
3. Try to walk/fly past the cable while pressing against it. – You get stuck on the "inside" corners at coordinate .425 or .575.

Scenario 2b:
1. Place a fluix glass cable, or a cable with any combination of properties (see above).
2. Attach a facade only to one side (north, east, south or west) of the cable. (No facades on the five other sides. No blocks above or below the cable.)
3. Place a full block adjacent to the cable on either side, such that the three blocks form a visually flat surface.
4. Try to walk/fly past the cable and adjacent blocks, while pressing against it. – You get stuck on the full blocks at coordinates .3 or .7, and you can see your other horizontal coordinate ending in .294 or .706.

**Expected behavior**

Scenario 1:
The falling sand entity should turn back into a block when it touches the cable facade.

Scenario 2:
You should not get stuck while sliding along the side of a cable facade. 

**Additional context**

**Environment**

- Environment: Linux Mint 20.1 Cinnamon, GDLauncher with default JVM (see forced crash log for details)
- Forced crash report: https://pastebin.ubuntu.com/p/DN3QRYKSDV/

**Comment by yueh** [comment] 2021-05-23 19:40
Duplicate of #5219

**Closed by yueh** 2021-05-23 19:40 UTC
