### ISSUE TITLE
placing objects

### ISSUE THREAD

**Issue by israpps** [AppliedEnergistics/Applied-Energistics-2#4186] opened 2019-10-27 13:16 UTC
**Describe the bug**
when I connect 3 dense cables together or any terminal to the ender IO ME dense conduit the game crashes and when i attemp to enter to the world again it crashes instantly. nothing happens if I connect a me cable to the block where you place disks(i forgot the name sorry)

**To Reproduce**
place 3 dense cables together. place a line of ME dense conduits of ender io and connect any terminal

**Expected behavior**
Not crashing

**Additional context**
https://paste.dimdev.org/raqeqomumo.mccrash

**Environment**

- Minecraft Version:  1.12.2
- AE2 Version:   appliedenergistics2-rv6-stable-7.jar
                         appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-1.12.2-14.23.5.2847
                         forge-1.12.2-14.23.5.2838

**Comment by yueh** [comment] 2019-10-28 07:07
Duplicate of #4113

**Closed by yueh** 2019-10-28 07:07 UTC
