### ISSUE TITLE
Autocrafting Wireless Crafting Terminal doesn't work correctly if you use the recipe with the Dense Energy Cell in it

### ISSUE THREAD

**Issue by AlienXAXS** [AppliedEnergistics/Applied-Energistics-2#6279] opened 2022-05-19 21:12 UTC
### Describe the bug

When attempting to autocraft a Wireless Terminal using a Dense Energy Cell, it cannot be completed as AE2's crafting states a Dense Energy Cell cannot be crafted as a prereq.

Attempting Craft:
![image](https://user-images.githubusercontent.com/1773445/169404434-0e9cad9d-431b-4d94-8856-96c1d2f4767d.png)

Dense Energy Cell Pattern is there:
![image](https://user-images.githubusercontent.com/1773445/169404568-9685a3f4-a562-4a89-b33e-4820a2d282ee.png)

Have tried the pattern with both Subs with and without.
![image](https://user-images.githubusercontent.com/1773445/169404645-a86fdcd4-f01c-40f4-b52d-77269993008c.png)

Note:
This crafting recipe works as intended:
![image](https://user-images.githubusercontent.com/1773445/169405162-ebefa691-112b-4fa1-b319-c0de4bac659a.png)

### How to reproduce the bug

1. Create patterns to create the Wireless Crafting Terminal using this recipe:
![image](https://user-images.githubusercontent.com/1773445/169404828-44ecc9b6-f824-4cf6-a5d2-ea4457644012.png)

2. Also ensure this recipe is auto-craftable too, as well as any others you would like to automate.
![image](https://user-images.githubusercontent.com/1773445/169404947-05f59538-1e9d-4b6c-a206-d87b82a4b9af.png)

3. When attempting to craft the Wireless Terminal, you will see the following problem:
![image](https://user-images.githubusercontent.com/1773445/169405007-7cac2c50-ccd0-422a-b5e4-4587cd2aacd4.png)

Note:
Crafting the Dense Energy cell is possible if you tell AE2 to do that by itself.  However having Dense Energy Cells in your AE2 storage still does not count towards the recipe for the wireless crafting terminal.

### Expected behavior

I expect the AE2 auto crafter to be able to craft either using an item that already exists in storage, or to craft the required prereq from a existing pattern.

### Additional details

This is ATM7 0.4.0 if that helps.
appliedenergistics2-11.0.0.jar

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

No Crash

**Comment by AlienXAXS** [comment] 2022-05-20 20:16
Just a small update.

The same happens when attempting to craft Advanced Mekanism Power Cubes from a Basic Cube, as well as the next tiers to Ultimate.
![image](https://user-images.githubusercontent.com/1773445/169604296-dcf0b44f-6edf-46fe-958f-c2a211756bd8.png)

Maybe some NBT data is trying to compare?

**Comment by AlienXAXS** [comment] 2022-05-20 20:17
Sorry, I accidently clicked Close haha :D

**Comment by Technici4n** [comment] 2022-05-28 21:27
Can't reproduce on Fabric, will check on Forge later.

**Comment by Qiota** [comment] 2022-06-21 11:38
I used 4 or 64K crafting storage to make it work.

**Comment by Technici4n** [comment] 2022-10-01 23:53
This should be addressed by #6646.

**Closed by Technici4n** 2022-10-01 23:53 UTC
Labels: bug, forge
