### ISSUE TITLE
Redstone Duplication Bug (Formation plane/Import Bus)

### ISSUE THREAD

**Issue by FileDotZip** [AppliedEnergistics/Applied-Energistics-2#3685] opened 2018-08-18 15:46 UTC
Redstone taken from a chest via import bus and spit out through a formation plane. Import bus never takes the redstone out. Formation plane infinatly generates redstone. 

https://youtu.be/pB32WrPYPtg

#### Environment

- Minecraft Version: appliedenergistics2-rv5-stable-11
- AE2 Version: 1.12.2
- Forge Version: 14.23.4.2705

**Comment by fscan** [comment] 2018-08-18 15:48
Duplicate of #3590

**Closed by fscan** 2018-08-18 15:48 UTC

**Comment by FileDotZip** [comment] 2018-08-18 15:58
Why isnt it fixed yet?
