### ISSUE TITLE
Wireless Crafting Terminal Removes Energy Cards on Shift-Click/Drag

### ISSUE THREAD

**Issue by bmill8254** [AppliedEnergistics/Applied-Energistics-2#7429] opened 2023-10-03 03:53 UTC
### Describe the bug

When removing items from the wireless crafting terminal by shift-clicking and dragging over multiple items, the energy cards are removed even though they were not shift-clicked.

### How to reproduce the bug

Have wireless crafting terminal with energy cards installed, remove multiple items by shift-clicking and dragging.

### Expected behavior

Energy cards are not to be removed when shift-clicking and dragging over items.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Mzft6v3Y

**Comment by Technici4n** [comment] 2024-08-03 10:52
Duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7594

**Closed by Technici4n** 2024-08-03 10:52 UTC
Labels: bug
