### ISSUE TITLE
Illuminated panels do not emit light

### ISSUE THREAD

**Issue by TheBigerGamer** [AppliedEnergistics/Applied-Energistics-2#4716] opened 2020-09-10 08:36 UTC
Bright Illuminated panels, when connected to an energy source, they light up, however light is not emitted.

**Describe the bug**

I tried to use Bright Illuminated panels to provide a light source to my base, but no matter how much I tried, they didn't emit any light level. Neither connected directly to an Energy Cell nor to my ME system.

**To Reproduce**

Place a Bright Illuminated Panel connected to a fluix cable in an ME system or connected to an Energy Cell.
Bug happens.

**Expected behavior**

Bright Illuminated Panel should emit light.

**Additional context**

![2020-09-10_09 30 33](https://user-images.githubusercontent.com/39341546/92701874-712a1680-f348-11ea-95f3-799ee9674cdd.png)

**Environment**

- Environment: https://pastebin.com/TD6Qaz3q

**Comment by yueh** [comment] 2020-09-10 08:56
Cannot reproduce. Does this also happen without optifine?

**Comment by shartte** [comment] 2020-09-13 12:56
Closing since this now works using blockstates in 1.16.x, which should actually also fix this for optifine.

**Closed by shartte** 2020-09-13 12:56 UTC
Labels: awaiting-feedback
