### ISSUE TITLE
Smart Cables Disconnecting

### ISSUE THREAD

**Issue by Gowcu** [AppliedEnergistics/Applied-Energistics-2#5104] opened 2021-03-28 23:41 UTC
My friend is building his computer in a floating island created by the Laputa shard from Botania. Whenever i go over there and check up on his computer, all the dense cables have disconnected from everything

**Describe the bug**
I am on version 8.2.0-beta.3.jar and forge version forge-36.0.21

**To Reproduce**
As far as i can tell, just leaving the area unrendered for a little while will cause it to happen

The cables to not become disconnected

**Additional context**
![2021-03-28_18 31 42](https://user-images.githubusercontent.com/12003222/112772148-e31c3180-8ff4-11eb-8d32-19d04fea9acb.png)
![2021-03-28_18 32 02](https://user-images.githubusercontent.com/12003222/112772160-f0392080-8ff4-11eb-8479-e1b7b5e29a7f.png)
![2021-03-28_18 32 23](https://user-images.githubusercontent.com/12003222/112772161-f6c79800-8ff4-11eb-8e50-2c8494e57aa5.png)

**Environment**
Pretty sure it's the way that the Laputa island is formed that's causing the dense cables to disconnect

- Environment:

**Comment by yueh** [comment] 2021-03-29 06:27
Duplicate of #5017

**Closed by yueh** 2021-03-29 06:27 UTC
