### ISSUE TITLE
block interface camouflage 

### ISSUE THREAD

**Issue by PRavenhold** [AppliedEnergistics/Applied-Energistics-2#1792] opened 2015-08-12 06:54 UTC
I've read a thread somewhere that facades to these interfaces were impossible to implement in ae 2. 
So is it possible to make the interface block to work like the carpenter mod blocks? Shouldn't it just be to change the blocks appearance that way? No need for facades.

**Comment by PRavenhold** [comment] 2015-08-12 07:01
Or maybe use a painting machine like in the ender io mod? Or may it maybe be easier to ask the coders of enderio to accept interfaces as acceptable blocks to paint?

**Comment by TheJulianJES** [comment] 2015-08-12 12:14
Duplicate of #1294 ?

**Comment by PRavenhold** [comment] 2015-08-12 12:15
No

**Comment by yueh** [comment] 2015-08-12 12:39
Yes, duplicate of #1294. Just a different idea about how to potentially implement it.

**Closed by yueh** 2015-08-12 12:39 UTC
