### ISSUE TITLE
Sodium support (+ "Fabric" tag on CurseForge)

### ISSUE THREAD

**Issue by CamperSamu** [AppliedEnergistics/Applied-Energistics-2#5095] opened 2021-03-25 17:04 UTC
**Describe the feature**
Since Sodium is the "OptiFine of Fabric", it would be nice to be able to use this mod alongside Sodium.
Also I din't even know that this mod was Fabric compatible since it's missing the tag on CurseForge.

**Reasons why it should be considered**

I'd love to see this mod working with Sodium, so who has a crappy PC can enjoy this mod too (I know it's very hard to fix compat with sodium, but you should be able to at least set in place a legacy/safe mode model when sodium is loaded instead of letting minecraft display the missing model texture) and I think that if more mods that support Fabric but don't say it add the Fabric tag on CurseForge finally we will be able to have nice and light Fabric modpacks!

**Additional Context**

None.

**Comment by Technici4n** [comment] 2021-03-25 17:43
Duplicate of #4760.

The Fabric tag would cause issues for Forge players, so no.

**Comment by Technici4n** [comment] 2021-03-25 17:43
Duplicate of #4760.

**Closed by Technici4n** 2021-03-25 17:43 UTC

**Comment by Technici4n** [comment] 2021-03-25 17:48
Duplicate of #4760
