### ISSUE TITLE
[Suggestion] [AE3] How to improve AE

### ISSUE THREAD

**Issue by Skillotic0703** [AppliedEnergistics/Applied-Energistics-2#2954] opened 2017-07-11 23:33 UTC
When AE2 came out, people were so angry because it was much harder than AE1. I personnally really liked AE2 and some of its new functionnality but some of them were just bad ideas.
Problem n°1) Presses!!!!!!!!?????????!!!!!!!!! WTF!!!!
To start AE2 you have to find presses that are located in sky stone meteorites. What is the point of that? Is applied energistics an alien technology? You craft a compass with certus quartz to find those. Why is the certus quartz even pointing towards sky stone. There isn't any logic!
Furthermore, the presses are really a pain to find. That's more tedium than balance.
Solution n°1) As the fabrication of processors didn't make sense either in AE1. I think that you should do sth more realistic (find informations about how processors are created).
Problem n°2) Channels were a bad way to balance things. You could still interconnect different networks to spam drives filled with 64k storage cells. And that created a lot of lag so it was a bad design choice.
Solution n°2) Don't really have one. Just don't use channels or find sth that works well.
Problem n°3) That wasn't a real problem for me but I know that some people didn't like the crystal growing mechanic.
Solution n°3) Crystal growing didn't make sense so idk, do sth.
Enhancement n°1) Support fluids. Allow using fluids along with items in auto-crafting patterns.
Enhancement n°2) Expose the inventory of the interface. That would allow to extract items and fluids you want with other pipe systems (I'm looking at you Thermal Dynamics)
Enhancement n°3) Void upgrade for storage buses and export buses. Every excess material is destroyed when the storage bus can't output it to an inventory;
Enhancement n°4) Allow different crafts for the same result.
Enhancement n°5) Add a wireless crafting terminal
Enhancement n°6) Allow planes to be used with interfaces (to auto-craft)
Positive point n°1 aka "Don't change this please") Space calculation system. I found that really cool.
Positive point n°2) Interfaces are an all-in-one thing (item transport, auto-craft) and I hope that you'll also allow fluid transfer with them.
Positive point n°x) Keep the mod exactly like it is but remove annoying parts please!

**Comment by mgdgfbhevdyeh** [comment] 2017-07-12 00:03
i think you can use RS.

**Comment by mindforger** [comment] 2017-07-12 05:34
yeah yeah fine ... another rant without proper solutions ... just some "i don't know how, do something"s

Fluid Support is a Pain that was already stated and there are addons providing this ... but they induce other issues and aer not fixing it for whatever reason (no blame, just as a matter of fact)

The Interface already presents you an API that everyone can use and given that you configure it, the interface acts like a chest already

Voiding stuff has lead to dozends of false bugreports already when you used quantum storage in the past, this has been declined already
>Allow different crafts for the same result.

you ... i ... what ? examples please 

wireless crafting terminal ... again there is a mod but it induces another bug that hasn't been fixed by them yet

>Allow planes to be used with interfaces (to auto-craft)

don't know what you mean but you can already use planes to make autocrafting .... i always automate botania with it! Or did i misunderstand something? If you man give it a slot so it can request to craft thigns, this is already possible ... just make a tiny subnetwork of an interface with an plane and attach an exportbus to the interface with a crafting card ... the plane spits out whatever the interface receives!

the "annoying" parts are by design and you can already disable them ... you can add your own recipes to get your pure crystals in a different way if you want to with only AE2.

**Comment by yueh** [comment] 2017-07-12 10:56
If being perfectly realistic is a requirement for you, maybe playing a game which allows you to carry 4.45 * 10^7 kilograms in your pockets is not the right one.

**Comment by Skillotic0703** [comment] 2017-07-12 10:57
1) About crafts, when you set 2 recipes for sticky pistons (this is a simple example) you should be able to choose between recipes. Say the first recipe is one slimeball and one piston and the other one is one raw rubber and one piston. When there are no slimeballs in the network, the network will not allow you to craft the sticky pistons with raw rubber, it will just tell you that you're missing slimeballs.
Don't tell me to enable oredict, this is just an example.
2) About the planes I know that you can do subnetworks and that's the annoying part. I wish you could just attach an interface behind a plane and it works. But eh it may not be fair to complain about that.
3) Channels are a bit useless because of the possibility of doing subnetworks.
4) For voiding stuff, it's ok, it's a bit useless when you have DSUs
5) Ok you were right AE2 is perfect, the only problem are the two missing features (native liquid support and wireless crafting terminal)

**Closed by yueh** 2017-07-12 10:56 UTC

**Comment by piedpipr314** [comment] 2017-07-12 11:01
@yueh Even more with Shulker boxes :P

**Comment by mindforger** [comment] 2017-07-12 11:10
@Skillotic0703 
1. yeah i see what you mean, but look at the consequences, complex crafting will become a severe pain in the butt then ... i did not yet test what happens when i add two recipes with different input content and same output .. which one will it prefere and if the prefeered one runs out of inputs ... will it switch over ? ... i think the logic required for that would be pretty hard to implement in the current crafting logic
2. well AE was never intended to stay as "cheap" as it was, that was always a goal of AE to let you use at least 1 brain cell :P i do not want to say you are stupid, only that it is intended to challenge you a bit
3. well subnetworking was an intended feature ... but the excessive use that has been going on was not expected ... and with your phrasing you just negated your 2nd point .. you need to put a bit effort in setting up the subnets the right way!
4. no it is not useless ... but people tend to blame AE2 when the system acts funky and voids items, just because it is not setup the right way (as in the case with DSUs) ... an overflowing DSU (no void upgrade, just full) with high prio set on the bus and a locked input voids the incoming items just by accident because they do not fit the DSU and are never returned to the system when rejected
5. well as long as AE2 is not perfect ... and heck there are still a ton of kinks and quirks .. you leave the rest to third parties as long as they do their job .... when AE2 devs have a bit more time, i can imagine they would love to take over a few addon ideas that fit the plan of AE2
