### ISSUE TITLE
Add filter support to ME (Fluid) Annihilation Plane - MC 1.16.1

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4587] opened 2020-08-11 02:20 UTC
**Describe the feature**

For `ME (Fluid) Annihilation Plane` attach a same functionality(Contains GUI) as `ME (Fluid) Import Bus`.
Check all items on the front side of the front in some ticks to see if they match the marked item.

**Reasons why it should be considered**

 The current version of the filter is achieved through `ME Annihilation Plane`+ `ME Storage Bus`. 
However, if there are multiple items in front side of `ME Annihilation Plane` and one mismatch is mismatched, the filter will be invalid.
If considering balance to add a `Sticky Piston` into `ME Annihilation Plane` recipe.

**Comment by yueh** [comment] 2020-08-11 05:59
Duplicate of #671

**Closed by yueh** 2020-08-11 05:59 UTC

**Comment by sagesse-cn** [comment] 2020-08-11 06:26
@yueh 

In mc 1.16.1 the situation is a little different. If there are a large number of items (10 items) that need to be recipe, the `ME Annihilation Plane` will drop item and place item at fast speed. 

Recipe could not execute correctly.

**Comment by sagesse-cn** [comment] 2020-08-11 06:30
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89864710-ffdb3480-dbde-11ea-8127-7847760b744a.png">
