### ISSUE TITLE
[1.16.5 Forge] ME Fluid Level Emitter Bugs

### ISSUE THREAD

**Issue by ScottCTD** [AppliedEnergistics/Applied-Energistics-2#5413] opened 2021-09-01 04:48 UTC
# Bug Description
I'm using appliedenergistics2-8.4.0.jar and forge 36.2.4 (Latest version at least at this time)
I tested these bugs with pure forge and ae2 without any other mods.

Basically, the GUI of fluid level emitter broke like this:
![image](https://user-images.githubusercontent.com/35100768/131612596-6afdb3b1-461f-4dca-9f37-30f70ce9236f.png)

**Evidently, the water should go into that slot after "mB", but it did not.**

**Environment**
- TBH I don't really think this is necessary.
- But, [here it is](https://pastebin.pl/view/a2b48290).

**Comment by ScottCTD** [comment] 2021-09-01 04:50
By the way, the official wiki of ae2 doesn't seem to include everything about fluid like fluid level emitter.

**Comment by mindforger** [comment] 2021-09-01 05:34
that one has never been updated since it has been handed over to the current devs :P no worries

**Comment by yueh** [comment] 2021-09-01 07:55
Duplicate of #5365

**Closed by yueh** 2021-09-01 07:55 UTC
