### ISSUE TITLE
Allow inscribers to use capacity cards

### ISSUE THREAD

**Issue by Trevinlc1997** [AppliedEnergistics/Applied-Energistics-2#4910] opened 2021-01-07 01:15 UTC
This is a quality of life feature.

**Describe the feature**

The inscriber should be able to use capacity cards to increase the inventory size. Instead of accepting one printed silicon/gold/etc it should be able to hold more.
**Reasons why it should be considered**

The reason this should be considered is because what slows down inscribers the most is transfer times. Loading material into the inscriber and then pulling out. If you were constantly have it loading the material in the inscriber can continue to work instead of being slowed down. 

The loading times may not be an issue on some servers but many that I play on either have a low TPS, or simply edit source to slow down item transfer to keep a higher TPS.
                        
**Additional Context**

**Comment by Tahakk** [comment] 2021-01-07 08:38
Or consider implementing Advanced Inscriber that already exists as addon. Works like charm.

**Comment by yueh** [comment] 2021-01-07 08:58
Duplicate of #271

**Closed by yueh** 2021-01-07 08:58 UTC
