### ISSUE TITLE
Cable recipies not working in rv2-beta-14

### ISSUE THREAD

**Issue by halvors** [AppliedEnergistics/Applied-Energistics-2#1072] opened 2015-03-22 01:14 UTC
Cable recipies not working in rv2-beta-14.
The recipe simply doesn't show up NEI, or the craftbench when trying to craft it.

Tested with Quartz Fiber, doesn't work :(

**Comment by simlhawk** [comment] 2015-03-22 06:58
Can confirm, I have the same issue. However, I also had this in an older version of rv2, so I have the feeling its actually a mod interaction. Care to post your modlist, so I can cross reference them?

**Comment by thatsIch** [comment] 2015-03-22 06:59
Care you do not use MineTweaker or other recipe changing mods. Some mods inject also their own stuff into NEI and if it fails meanwhile, NEI will also stop working

**Comment by simlhawk** [comment] 2015-03-22 07:04
Its not caused my MineTweaker or ModTweaker. I have also tested without a few AE2 addons that I use, and those aren't the culprits either.

Afaik, I don't have any other mods that change recipes. I'll do a bit more investigating.

**Comment by thatsIch** [comment] 2015-03-22 07:09
Can not confirm, tested it and working perfectly fine with NEI

![ss 2015-03-22 at 08 08 56](https://cloud.githubusercontent.com/assets/2210496/6768427/d2561a8c-d06a-11e4-94be-84fefe580869.png)

**Comment by simlhawk** [comment] 2015-03-22 07:17
yea, its a mod interaction breaking it. Seems to be something that's happening relatively recently, so I'm removing mods one by one that I've recently added/updated.

**Comment by simlhawk** [comment] 2015-03-22 07:29
MEKANISM. Its the new Mekanism v8 update that's breaking it. I'll try with newer Mek builds and see if that fixes it.

**Comment by simlhawk** [comment] 2015-03-22 07:34
To further explain this issue: All recipes are broken, except for the quartz tools.

AidanCBrady says that the issue is on AE2's end: https://github.com/aidancbrady/Mekanism/issues/2283

**Comment by simlhawk** [comment] 2015-03-22 08:24
Compiled a new version of Mekanism just now, issue still remains. Will also post bug on Mekanism's tracker, since I can't tell if the bug posted above is the same issue or not.

**Comment by thatsIch** [comment] 2015-03-22 08:54
Ah I remember,

we already have this one https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061

we need some preparations to do that, since Mekanism does not provide a compile api jar for us somewhere, so we need to host it ourself.

Closing this in favor of the other one.

**Closed by thatsIch** 2015-03-22 08:54 UTC
Labels: state-waiting
