### ISSUE TITLE
Forge 34.1.24 Minecraft 16.3 no ores and no meteor are generated, the same for vanilla ores

### ISSUE THREAD

**Issue by Silbersurfer01** [AppliedEnergistics/Applied-Energistics-2#4798] opened 2020-10-28 14:59 UTC
no ores and no meteor are generated, the same for vanilla ores. Minecraft 16.3 and Forge 34.1.24

**Comment by Spoke666** [comment] 2020-10-29 02:33
and also, no villagers in minecraft 1.16.3 Forge 34.1.33

**Comment by Ommina** [comment] 2020-10-29 06:41
That's lovely and all, but how are we concluding that any of this is an issue with AE2?

**Comment by yueh** [comment] 2020-10-29 09:51
Duplicate of #4777

**Closed by yueh** 2020-10-29 09:51 UTC
