### ISSUE TITLE
Cooler from the Coolers Mod - Can't take it back from ME System

### ISSUE THREAD

**Issue by MrAmericanMike** [AppliedEnergistics/Applied-Energistics-2#1596] opened 2015-06-14 18:05 UTC
I'm using Cooler Mod 1.7.10-1.1.5.0 and Applied Energistics RV2 Stable 5

Whenever I put a Cooler inside the ME System, I can't take it back out of it. The cooler lose his texture, it shows his information, but you can't take it back.

The mod is:

http://www.curse.com/mc-mods/minecraft/gud_coolers

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293031-coolers

**Comment by yueh** [comment] 2015-06-14 18:19
Duplicate of #951, #1581

**Closed by yueh** 2015-06-14 18:19 UTC
