### ISSUE TITLE
Level emitter not emitting when crafting

### ISSUE THREAD

**Issue by Xolroc** [AppliedEnergistics/Applied-Energistics-2#816] opened 2015-01-29 15:04 UTC
Using version rv1-beta7.

The level emitter supposedly can be given a crafting card and configured to emit redstone when an item is crafting. However, it doesn't appear to do so; after configuring it and starting a crafting job, it does nothing at all. The items to be crafted do go where they should (dropped into the world to make pure crystals) but the level emitter does not emit redstone (meaning my crystal growth accelerators don't turn on). The emitters (three, one for each type) are configured with a pure crystal in the single slot and set to "emit while crafting". This, presumably, should make them emit redstone when a crafting cpu is working on crafting a pure crystal. They do have channels, so it's not a missing channel problem.

Am I doing something wrong, or is this a bug?

**Comment by riking** [comment] 2015-01-31 16:28
You're thinking of the level emitter crafting card wrong. A crafting card makes the level emitter be treated as a *crafting source* - i.e., "If I give this a redstone signal, it will craft the item".

**Comment by Cisien** [comment] 2015-01-31 16:30
Also, the emitter should be configured with the pattern, and not the output item

**Comment by yueh** [comment] 2015-01-31 16:34
I would recommend an update from rv1 to the latest rv2.

@Cisien using the pattern sounds interesting. But it actually is watching the output item.
So just putting the item in there makes it easier to handle it and not have a special case where it needs to fetch data from some other source.

**Comment by Xolroc** [comment] 2015-01-31 18:08
@riking I have it on "emit while crafting". It works sometimes, and fails to work other times, which makes me think there's a problem with the messaging system.
@yueh I can't do that, actually! The server's run by a friend, who doesn't want to use any alpha versions due to instability issues.

I think what's happening is that the message being sent to the level emitter saying "turn on, this is being crafted" is somehow not making it there sometimes. The network is large and sprawling, crossing several chunks; could this be why?

In any case, I've got a workaround for now.

**Comment by riking** [comment] 2015-02-02 02:53
> large and sprawling, crossing several chunks

If they're not all loaded at the same time, stuff gets weird, yeah.

**Comment by Xolroc** [comment] 2015-02-02 03:16
They -are- all chunkloaded though.

**Comment by yueh** [comment] 2015-02-07 10:50
Cannot reproduce it

**Comment by dcbartlett** [comment] 2015-02-12 03:29
I have the same issue.  Emitter is not activating when the crafting cpu has the item to be crafted in its schedule.

I have the following attach and in the same chunk.

ME Pattern Terminal
1k Crafting Storage x 9
ME Controller
ME Level Emitter x 3 ( configured with crafting card and different products )
ME Interface ( Panel Mode )
Molecular Assembler
Creative Energy Cell
ME Drive w/ 1k ME Storage Cell ( illed with materials needed to craft and other various materials )
White Lamp x 3 ( To see when signal is on )
Various Lengths of Smart Cable

Overview:
https://www.dropbox.com/s/oqn70mb1ynl0s9h/Screenshot%202015-02-11%2021.12.26.png?dl=0
ME Interface:
https://www.dropbox.com/s/vw1nnfwm006x8nz/Screenshot%202015-02-11%2021.12.53.png?dl=0
CPU Crafting Status:
https://www.dropbox.com/s/krrsn4ui3213msp/Screenshot%202015-02-11%2021.13.09.png?dl=0
ME Level Emitter:
https://www.dropbox.com/s/gfbqjn9c0w4fths/Screenshot%202015-02-11%2021.13.18.png?dl=0

As the times of the screenshots show, the Level emitter is not emitting after the cpu has already queued up the items.

**Comment by yueh** [comment] 2015-02-12 08:37
The screenshots look like it is Wirkung as intended. The crafting tables are only scheduled and not crafting, so no redstone will be emitted.

**Comment by dcbartlett** [comment] 2015-02-12 15:13
right, but why wouldn't they be crafting, the molecular assembler is powered and the required materials is there.

**Comment by dcbartlett** [comment] 2015-02-12 15:16
n/m this seems to work with the assymbler, for some reason my assymbler has a malformed pattern in it.

**Comment by dcbartlett** [comment] 2015-02-12 15:18
It appears that processing patterns are the ones that the cpu has issues with.  What blocks at a minimum are needed for a processing pattern to be crafted?

**Comment by KlutzLament** [comment] 2015-02-12 15:23
Processing patterns are for processing via a machine, for example using a TE pulverizer to turn 1 iron ore into 2 iron dust. The pattern would be put into a ME Interface attached to the machine and a ME Import Bus would pull the product back into the ME network.

**Comment by dcbartlett** [comment] 2015-02-12 16:52
I got it working today.  Apparently i had a loop in the system that wasn't allowing my materials to get to the ME Formation Plane for the processing pattern request.

This ticket is indeed marked as closed because this works like a charm...just confusing to setup at first :D

**Closed** 2015-02-18 17:16 UTC
Labels: state-waiting
