### ISSUE TITLE
NPE with Rendering screen message while opening Crafting Status

### ISSUE THREAD

**Issue by lilmayu** [AppliedEnergistics/Applied-Energistics-2#5166] opened 2021-04-19 20:22 UTC
**Describe the bug**
After opening a crafting status, the game crashes. Does not happen ALWAYS, but in like 4 out of 10 times of opening this GUI.

**To Reproduce**
Open a crafting status?

**Expected behaviour**
Working crafting status.

**Additional context**
Crash report: https://pastebin.com/raw/RZthNLNM

**Environment**
MC Version: 1.16.5
AE2 version: 8.2.0
Forge version: 36.1.4
MCP version: 20210115.1115550
Java: 8
Singleplayer world
All mods are in the list within the crash report.

Sorry if this issue was resolved/noted in a different issue.
I can provide video footage or anything you'd like.

**Comment by shartte** [comment] 2021-04-19 20:26
Duplicate of #5132

**Closed by shartte** 2021-04-19 20:26 UTC
