### ISSUE TITLE
Pickblocking Dense Cable Crashes Game (Plus Cables Not Connecting till Rejoin)

### ISSUE THREAD

**Issue by ScorcherOfAwesomeness** [AppliedEnergistics/Applied-Energistics-2#4034] opened 2019-05-12 14:25 UTC
#### Description
What was expected on middleclick was it to switch to the hotbar item, but it crashes instead

#### Environment
Singleplayer
Mods: The AE2 Instal;ation
BetterHUD 1.4-beta.3
Big Reactors 0.43A
Chisel 1.12.2 - 0.2.1.35
Chisels & Bits 14.31
CodeChicken Lib 2.22.353
CoFH Core 4.6.2.25
CoFH World 1.3.0.6
CTM 1.12.2 - 0.3.3.22
Mekanism 1.12.2 - 9.6.4.356
Nuclearcraft 2.13e - 1.12.2 (I was building it nearby a fusion reactor)
OpenComputers 1.7.4.153
RedstoneFlux 2.1.0.6
Thermal Dynamics 2.5.4.17
Thermal Expansion 5.5.3.41
Thermal Foundation 2.6.2.26
Xtones 1.12 - 1.0.8 - 11 

Computer Enviroment:
Software:
Java 8 update 201
MultiMC 0.6.5
64 bit Windows 10 latest Insider Build
Hardware:
Processor: Intel Core i5 CPU 650
RAM: 8 GB allocated 4 GB

Crash Info: https://pastebin.com/7XV2nzef

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2768

**Comment by yueh** [comment] 2019-05-14 11:29
Duplicate of #3996

**Closed by yueh** 2019-05-14 11:29 UTC
