### ISSUE TITLE
Inscriber not accepting power from ME net. & hopper not pulling out of them

### ISSUE THREAD

**Issue by MrAnima** [AppliedEnergistics/Applied-Energistics-2#3065] opened 2017-09-01 09:04 UTC
#### Description
-When an inscriber is next to an ME cable, it connects to it, but power is not provided to the machine.
-Second issue with this exact same block, hoppers cannot take the output of an inscriber, which would be quite logical and practical.

#### Environment
Personal "modpack" created with Twitch app. If there's an easy way to get the list of all the mods as text, I can provide it.

- Minecraft Version: 1.12
- AE2 Version: rv5-alpha-4
- Forge Version: 14.21.1.2443

**Comment by yueh** [comment] 2017-09-01 09:22
Duplicate of  #1316. 

I would also recommend reading the wiki page about inscribers regarding the inputs/outputs.

**Closed by yueh** 2017-09-01 09:22 UTC

**Comment by MrAnima** [comment] 2017-09-01 09:30
Okay thank you, and sorry for not looking enough 😛.
However, the wiki says that the output can be `automated from any side without press`. But then, how to extract with a hopper when there's a press ? We must use an importer ?

**Comment by fscan** [comment] 2017-09-01 09:45
The inscriber can be rotated with a wrench.

**Comment by MrAnima** [comment] 2017-09-01 09:46
Completely forgot that, thanks @fscan !
