### ISSUE TITLE
Network disconnects through chunk borders, and doesn't function anymore.

### ISSUE THREAD

**Issue by Vladisomire** [AppliedEnergistics/Applied-Energistics-2#5144] opened 2021-04-11 13:15 UTC
The Ae network disconnects upon loading the world. The Controller broke at the chunk border. Everything which is disconnected doesn't function anymore so it's not a graphical thing. Also, breaking a single cable and replacing it doesn't make it reconnect. the entire string of cable has to be replaced for it to function again, This also appplies functional blocks i.e Controllers, interfaces and assemblers.

Attempting to open the UI of a broken interface block will instantly close it.

The system had been working fine for several weeks, and hasn't happened untill now. Reloading the area after leaving it for a while without logging off the server doesn't break it a second time. 
Restarting the server fixed the issue. Cables reconnected themselves, and work as intended.
So far, seems to be incidental.
(it's been a long time since I've seen this error reoccur now, haven't seen it since the early versions of AE2)

![image](https://user-images.githubusercontent.com/82318656/114303652-87ab7280-9acf-11eb-9845-27e3e2f6f8f6.png)
![image](https://user-images.githubusercontent.com/82318656/114303658-9134da80-9acf-11eb-8742-61c597117aef.png)
![image](https://user-images.githubusercontent.com/82318656/114303667-9bef6f80-9acf-11eb-8ec2-5bcba215eb9c.png)
![image](https://user-images.githubusercontent.com/82318656/114304125-d2c68500-9ad1-11eb-91b3-4a0f0d3c62da.png)
![image](https://user-images.githubusercontent.com/82318656/114304282-93e4ff00-9ad2-11eb-90af-f04f79e5eab1.png)

**Environment**
ATM6 Server: Minecraft version 1.16.5. Modpack version 1.5.7
Appllied Energistics version: Appliedenergistics2-8.3.0-alpha.1

**Comment by yueh** [comment] 2021-04-11 17:38
Duplicate of #5017

**Closed by yueh** 2021-04-11 17:38 UTC
