### ISSUE TITLE
Memory card only clears when both hands hold items

### ISSUE THREAD

**Issue by Tsukero** [AppliedEnergistics/Applied-Energistics-2#5316] opened 2021-06-29 11:26 UTC
As titles says, while having any item on "shield slot???" memory card only clears its memory even when right click + shift on a p2p to make a new channel, memory card is in the main hand.

**Comment by yueh** [comment] 2021-07-12 10:49
Duplicate of #4123

**Closed by yueh** 2021-07-12 10:49 UTC
