### ISSUE TITLE
Huge performance issue - happened from one day to another

### ISSUE THREAD

**Issue by Slind14** [AppliedEnergistics/Applied-Energistics-2#670] opened 2015-01-01 13:25 UTC
http://i.imgur.com/q1whSVf.png
In AE1 it was possible to track those down due to the ticktime of the controller, is there any way with 1.7?

**Comment by Xfel** [comment] 2015-01-01 13:42
The actual issue in this case seems to be in these lines: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/crafting/MECraftingInventory.java#L109

I guess extractItems has to look through all entries to find a matching one right? I see that the item list must be copied, and that the action source has to be passed as reference for security, but there should be a better way then performing a full lookup for every item in the system.

**Comment by thatsIch** [comment] 2015-01-01 14:41
This happens if you try to craft very NBT heavy items. The problem lies within the fact, that you can not just use an existing NBT Tag but need to copy it to prevent modification from other sources.

There is also the problem, that you probably want to craft a very high tier item which requires a lot of steps. If you reduce the amount of steps done one at a time, you reduce the overall calculation time done at once. 

Example:

If you want to create a boat, **dont** craft it from logs, **but** tell your system to auto-craft wood-planks first to pre-provide the materials needed if you request a boat.

**Comment by Xfel** [comment] 2015-01-01 14:52
I might be mistaken, but as far as I see this has nothing to do with the type of item I craft. 

The heavy operation I can identify here is Copying The Whole List Of Stored Items One By One. And only half of the time comes from copying the NBT tag (which admittably cannot be avoided), the other half comes from the findPrecise call which could be optimized away. 

Of cource, this would probably require some API changes as there currently exists no such method as IMEInventory.getAvailableItems(BaseActionSouce source), but it could be done.

Anyways, what about the original question? is there any way to find the me network causing this?

**Comment by Slind14** [comment] 2015-01-02 07:40
40ms of 5 export bus with crafting upgrade providing steel balls (not much nbt around) with a 1270v3, seems unusable for me considering that the average computer has about half the single thread performance where 1-2 upgrades might kill a single player world. (do I miss something?)

**Comment by thatsIch** [comment] 2015-01-02 10:41
Can you provide a minimal setup (world download), cause I can not reproduce this.

**Comment by Slind14** [comment] 2015-01-02 11:28
at -544,60,169 are a few ender io machines connected to export bus modules. 5 of them have a free upgrade slot, put a crafting upgrade into it to get things started.

https://mega.co.nz/#!Zc9E3Z6Q!UW_Y8nGQlSawdCDGMSBN_mf4iP7T-j31Q2lUQZZeMvg

**Comment by thatsIch** [comment] 2015-01-02 14:24
I hope 129 MB world is a real **minimal** setup (only AE2 in a new creative world should be only ~3MB big)

**Comment by Slind14** [comment] 2015-01-02 14:31
Tt only includes one region file. Sorry, in order to keep the system online I couldn't remove all the mods. You will need the The Dark Trilogy Modpack Version 1.0.6.

**Comment by thatsIch** [comment] 2015-01-02 14:33
Are you serious, also you using Cauldron, are not at least on the recommended Forge Version and you send me a server to setup?

**Comment by Slind14** [comment] 2015-01-02 14:38
mhh everything is included, you only need to start the forge included or the latest if you prefer. If I would only send you the region file, the setup wouldn't work anymore with only AE or you would need to setup all the mods configs, too..
If you ask for a simple setup with AE only, I'm not able to reproduce it, but I'm also not able to fill the me system with the thousand of different items and put down the ender io machines and the other stuff with ae only.

**Comment by thatsIch** [comment] 2015-01-02 14:46
I need to set it up indev, to see what is actually happening. Using cauldron and bukkit plugins, make it impossible to do so.

Send me the complete NPS file please.

**Comment by Slind14** [comment] 2015-01-02 14:48
Alright, sorry while it is possible to reproduce it with forge, I was not able to with AE2 only and a small setup.
The NPS file doesn't exist anymore, I'll need to create a new one.

**Comment by Slind14** [comment] 2015-01-04 14:07
sorry, won't get to it any time soon.

**Comment by Cozza38** [comment] 2015-01-09 04:09
Hi @thatsIch. I am seeing the same performance issues. I don't have a bps file to provide however I do have warmroast output which is showing the same thing.

I can attempt to setup a world download for you, but like @Slind14's, it won't be small.

https://dl.dropboxusercontent.com/u/82904851/WarmRoast.html

We had a player remove a crafting card in an export bus creating yellorite ingots, server TPS went from 1.6 back to 19.

If this cannot be easily fixed, I would love to see an option to remove just the crafting card via config. At this rate we are having to remove all cards via minetweaker as we cannot separate them.

**Comment by vlad20012** [comment] 2015-02-04 18:22
Hello. See my issue was linked here. I repeat, reached the point that ONE export bus with crafting card requires 18ms per one craft request. Now it is a big problem for me. Does anyone have any idea how to fix it? Now I see the following options, but not sure about their adequacy:
1. Remove multithreaded crafting calculation. Too radical, right? When I see 18ms per one craft request, I'm not sure that anything can be slower.
2. Optimize inventory copying and make cache. Why we copying NBT? How it can be changed in ME grid? Also we can store immutable copy of inventory to cache and invalidate it... But it is a half measure. 

Any other ideas?

**Comment by yueh** [comment] 2015-02-05 11:06
1. I do not see why removing the crafting thread will improve the performance. It just moves more computation to the main server thread.


2. This is exactly what we are making with the MECraftinInventory. Creating a cache of the current inventory and we also need to copy NBT as it can make the difference between the item is the cobblestone of a mod or the highest tier machine. We also need to assume a non thread safe environment as well as other mods interacting with AE2 in a separate mod and changing the inventory.

To some degree we are depending on the performance of other mods (like using NBT, which is mostly slow). This does not really happen on a small scale, but AE2 can be get large scale pretty quick and this is where you will notice it.

One (temporary ) solution would be design your networks more efficiently. For example if you are constantly crafting torches with an export bus, do not place this in the main crafting network.
Just make an interface exporting logs/coal and a small subnetwork with a storage bus on the interface to have acess to the logs/coal plus a small crafting setup to craft the logs into planks, sticks and finally torches and export this into the interface providing the materials.
So the crafting request will not need to cache the whole network. Just the few items provided by an interface.

**Comment by Xfel** [comment] 2015-02-05 11:41
As I said, the issue is that this method cannot use the optimized copy method. It iterates over the list of items and then extracts every item on it's own, which means that the system has to iterate over all items again to find the corresponding entry. This is unnecessairy complexity.

**Comment by vlad20012** [comment] 2015-02-05 14:43
1. Removing crafting thread removes the need to copy the inventory. I just want to make sure that the inventory copying does not hold up more time than recipe calculating. Specific numbers I quoted (up to 18ms per export bus with crafting card in high-load grid).
2. Ok, we have item X with NBT in our grid. How it can be changed? We can put the same item and incerement it's quantity, can extract, can place item X with other NBT (will be treated as new type). How it can be changed? Why we copying NBT?

About other advices. I am server owner, not player, not network designer. I can't force people to design the network more efficient, this should be resolved by software. To fix performance issues I constantly am submitting patches in mods. Currently I can't do anything. I forbade crafting card usage on my server. This is not my usual way, so I want to find another solution to this problem and hope for your support.

**Comment by yueh** [comment] 2015-02-05 15:33
I assume @AlgorithmX2 had a pretty good reason to do it the current way. So until I find a better way or someone can provide an in depth analysis of the problem including a potential solution, I can only assume this currently the best way to do it.

I know the CSLM has O(log n) for get(), which is not the best solution. But the only one as we need a (Concurrent)NavigableMap for the fuzzy filtering. I would appreciate any idea to improve it.

@vlad20012 
1. Removing the threads means you trade 18ms per export bus for crafting calculation, which can easily require minutes to complete. I am pretty sure, you would be very happy, if a request will lock you server for several minutes instead of just some ms.
2. No idea what could change it. But I could assume some (addon) mods iterating over the itemlist and breaking stuff. Copying is just done as it needs to be happen. If we do not copy it, it could mean, as earlier said, that a high tier machine changes to a piece of cobble. This is just how some mods handle different item types in the same item id and we cannot ignore it.

**Comment by vlad20012** [comment] 2015-02-05 16:19
As I can see, crafting thread uses an order of magnitude less CPU time than the copy operations in main thread (that I showed in my original issue)
![ae2](https://cloud.githubusercontent.com/assets/3221931/6063482/afa3ea34-ad68-11e4-8192-b724797b8bd9.png)

![ae](https://cloud.githubusercontent.com/assets/3221931/6027626/7bd7c7c2-abf4-11e4-9e66-9f3c10b8c299.png)

But I understood that you do not see this as a solution and don't know of other possible solutions. Ok... Anyone else? Any ideas?

**Comment by yueh** [comment] 2015-02-05 16:57
No this is not a possible solution.

I can only recommend to setup a small test instance just with AE2 and IC2.
Setup a small crafting setup to craft copper cables with hammers and cutters and look how long it takes to craft several hundreds or thousands of them.

Hint: It scales linearly with the amount of requested items and HV solars take it to a ridiculous amount.
And to add some real results:
![ic2 crafting](http://i.imgur.com/JGGefo9.png)
This is requesting 5k electronic circuits, what would look your server for about 50secs, if runs in the server thread. Make it 10k and it will take about 1 min 40 secs. Your users will not need to have the materials available. Just going to a terminal and calculating a ridiculous amount will lock your server for hours.

**Comment by vlad20012** [comment] 2015-02-05 18:04
Yes, I tested this only with 1 item requesting (by export bus only). Maybe add some threshold? If requeting < N items, task is executed in main thread. And as I see in your results, again all CPU time spends in extractItem() method (I suppose, in CSLM.get() next). No options to optimize it? CSLM is really required in findFuzzyDamage() only, not in infindPrecise(). Why not add HashMap parallel?

**Comment by yueh** [comment] 2015-02-05 18:37
Wrong line. `extractItems` just took 19ms compared to the 53k ms for calculating the crafting tree in `request`

And no limit it to 1 item is not possible. This can still be a single HV solar, which takes a good minute to calculate. Without knowing the complete crafting tree, it is not possible to enforce any threshold on where to run it (not even considering the complexity of it at all). A user will always be able to lock you server. For example making a recipe saying 576 HV solars make 1 cobble in a processing pattern. Nest it enough by requesting a single piece of octuple compressed cobble and see the server die.

I considered adding a second ConcurrentMap, but there are only the CSLM and a ConcurrentHashMap, both with their own issues. And it would add more complexity in terms of processor/memory requirements as well as keeping them synchronized.

**Comment by vlad20012** [comment] 2015-02-05 18:48
Haha, my mistake...
Some dead end comes, no options...

**Comment by yueh** [comment] 2015-02-05 19:00
As said, it should be possible to remove the copying alltogether as the CSLM and its iterators are threadsafe. Just need a way for a test, which is allowed to fail horribly and will not affect anything real. But still works similar to a production environment.

**Comment by vlad20012** [comment] 2015-02-05 19:40
Hmm, did not notice this editing. It can be tested on my server (or full copy), but there is such a large scale ... I think people would not have noticed the duplication of few items

**Comment by yueh** [comment] 2015-02-05 21:15
If you want, you can test this [build](http://ci.tsr.me/repository/download/AppliedEnergistics_PullRequests/1070:id/appliedenergistics2-rv2-alpha-pr853.jar)
It just uses a reference to the inventory instead of copying it.

**Comment by vlad20012** [comment] 2015-02-05 21:22
you forgot about this methods:
MECraftingInventory.injectItems()
MECraftingInventory.ignore()

They will break real storage instream of local copy.

**Comment by yueh** [comment] 2015-02-07 14:51
Not really, `MECraftingInventory.injectItems()` and `MECraftingInventory.ignore()` will never be called on the real inventory. The thread itself will create a copy of it again and use that.

---
For whatever reason the comment was still stored locally and not submitted..
@vlad20012 any new findings already?

**Comment by Entoarox** [comment] 2015-02-12 06:04
@yueh, I've got a setup I can test the 'no-copy' build on, It is exactly the kind of setup that is causing the issues (auto-crafting pushing TPS to an average of 150ms)
But when clicking that link I'm send to a login page, so I cant download the build to try it.

**Comment by yueh** [comment] 2015-02-12 14:29
There is a link to login in as guest.
But I have a more recent version (not pushed), which has some more changes.
So you might want to hold back until I could clean it up a bit.

**Comment by tf101-wizard** [comment] 2015-03-13 04:23
This is a big issue and really needs to be fixed.

**Comment by Slind14** [comment] 2015-03-13 16:41
@tf101-wizard a minimal test setup is required, unless one is provided it is unlikely to be solved. If you can manage to build, thatsIch would be happy.

**Closed** 2015-04-07 22:01 UTC
Labels: state-waiting

**Comment by PrestonTaylor** [comment] 2015-05-01 06:22
Strongly recommend you re-open this and put some effort into recreating the issue. It obviously exists.

**Comment by thatsIch** [comment] 2015-05-01 07:57
If you can provide some actual useful data, I will gladly re-open it, but due to lack of responses, I will close those issues, especially if the original report is like 30 versions (not builds) apart.

**Comment by babyblasphemy** [comment] 2015-09-04 05:12
I'm happy to report that we've unbanned crafting card on all of our servers. After testing setups that previously caused massive tick timing increases, the issue seems to have been fixed. The oldest version that was tested was RV2 beta 14, so anything after that should also be fixed.
