### ISSUE TITLE
remove the cpu max size

### ISSUE THREAD

**Issue by william64644** [AppliedEnergistics/Applied-Energistics-2#4244] opened 2020-01-07 16:46 UTC
**Describe the feature**

you won't be limited on build a 17^3 cpu

**Reasons why it should be considered**

everyone who have the resources for this should can do it

**Additional Context**

**Comment by yueh** [comment] 2020-01-07 16:54
Duplicate of #1783

**Closed by yueh** 2020-01-07 16:54 UTC
