### ISSUE TITLE
Lighting Problem with Slabs

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#2534] opened 2016-10-30 10:42 UTC
Supposed to look like this:

![](https://i.imgur.com/7Ly995I.jpg)

![](https://i.imgur.com/EG0biML.jpg)

**Comment by ItzKdoge20YT** [comment] 2016-10-31 12:02
try rv4 alpha 2

**Comment by ken-noland** [comment] 2017-01-10 11:39
nope, the light shouldn't pass through slabs, just like vanilla slabs

**Comment by VT-14** [comment] 2017-01-11 13:37
The top picture is of Vanilla's Purpur slabs.  The bottom picture should look similar.

**Comment by fscan** [comment] 2017-10-08 17:24
I cannot reproduce this with the current version. Probably fixed with the registration rework.

**Closed by fscan** 2017-10-08 17:24 UTC
Labels: type-bug
