### ISSUE TITLE
filter card for importers,exporters and storage buses.

### ISSUE THREAD

**Issue by ThornIcy** [AppliedEnergistics/Applied-Energistics-2#6920] opened 2023-02-01 20:24 UTC
### Describe the feature

You would add a filter card to one or more of your importers,exporters or storage buses and the card would allow you to filter by mod or nbt as an example you could create a drawer network with a storage bus that only allows vanilla items to be stored in them and keep modded items in an ME drive or import and export minecraft:stone nbt blocks to and from the system

### Reasons why it should be considered

This would allow for more advanced importing, exporting and storing of items

**Comment by Technici4n** [comment] 2023-02-26 18:11
Duplicate of #6853

**Closed by Technici4n** 2023-02-26 18:11 UTC
