### ISSUE TITLE
Spatial storage biome lacks translation in en_us (Fabric)

### ISSUE THREAD

**Issue by saltyseadoggo** [AppliedEnergistics/Applied-Energistics-2#5008] opened 2021-02-25 21:42 UTC
**Describe the bug**
The spacial storage biome has no translation, so it appears as
appliedenergistics2:spatial_storage
in the Single Biome/Caves/Floating Islands biome selection menu, as well as in any other mod that displays biome names, such as minimap mods.

**To Reproduce**
- Start Minecraft with the Fabric mod loader and AE2 in the mods folder.
- Go to Single Player -> Create New World -> More World Options -> change Default to Single Biome -> Customize, and see the name at the top of the list.

**Expected behavior**
appliedenergistics2:spatial_storage
would appear as *Spacial Storage* or the like.

**Additional context**
![ae2 dimension name](https://user-images.githubusercontent.com/69029346/109222859-b2837680-776e-11eb-80d6-b7da01399070.png)

**Environment**
Minecraft version: 1.16.5
Fabric Loader version: 0.11.1
AE2 version: 8.2.0 alpha 1
Other mods are loaded, but, given that this is a missing translation entry, they have no effect on this issue.

**Comment by yueh** [comment] 2021-02-26 10:57
Duplicate of #4946

**Closed by yueh** 2021-02-26 10:57 UTC
