### ISSUE TITLE
IC2 and AE2

### ISSUE THREAD

**Issue by EnterFor** [AppliedEnergistics/Applied-Energistics-2#4277] opened 2020-02-08 03:19 UTC
**Describe the bug**
AE2 cannot automatically synthesize items containing Energy Crystal, Lapotron Crystal, re-battery, Generator... Automatic short process stuck.
This problem has for a long time, I wonder if you can fix it.
Sorry, my English is not good. I'm Chinese:D

IC2 version: industrialcraft-2-2.8.170-ex112.jar
This error was also found at industrialcraft-2-2.8.188-ex112.jar
Industrialcraft -2-2.8.164-ex112. Jar has no such error

I didn't know who the fault belonged to, so I submitted the report
IC2：https://bt.industrial-craft.net/view.php?id=2641

- Minecraft Version: 
- AE2 Version: appliedenergy istics2-rv6-stable-7
- Forge Version:2847

**Comment by yueh** [comment] 2020-02-10 08:02
Duplicate of #3974

**Closed by yueh** 2020-02-10 08:02 UTC
