### ISSUE TITLE
[FABRIC] Texture bug with Sodium mod

### ISSUE THREAD

**Issue by L0ND4RK** [AppliedEnergistics/Applied-Energistics-2#5041] opened 2021-03-06 17:01 UTC
Minecraft Version: 1.16
Fabric Version: 0.11.2

Mods:
  [✔️] appliedenergistics2-fabric-8.2.0-alpha.3
  [✔️] fabric-api-0.31.0+1.16
  [✔️] sodium-fabric-mc1.16.3-0.1.0

[13:47:13] [Worker-Main-5/WARN]: Unable to load model: 'appliedenergistics2:dummy_fluid_item#inventory' referenced from: appliedenergistics2:dummy_fluid_item#inventory: java.io.FileNotFoundException: appliedenergistics2:models/item/dummy_fluid_item.json

[13:47:17] [main/WARN]: Method overwrite conflict for getSprite in appliedenergistics2.mixins.json:unlitquad.BakedQuadAccessor, previously written by me.jellysquid.mods.sodium.mixin.pipeline.MixinBakedQuad. Skipping method.
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:drive#': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=3': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=4': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=1': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=2': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=7': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=8': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=5': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=6': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=9': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=0': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:quartz_vibrant_glass#': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:facade#inventory': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=11': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=10': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=13': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=12': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=15': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=14': java.lang.NullPointerException
[13:47:18] [main/WARN]: Unable to bake model: 'appliedenergistics2:quartz_glass#': java.lang.NullPointerException

Without Sodium
![2021-03-06_13 46 20](https://user-images.githubusercontent.com/80168484/110214575-f91a5480-7e83-11eb-8d4d-57274a6faa3c.png)

With Sodium
![2021-03-06_13 47 46](https://user-images.githubusercontent.com/80168484/110214597-1c450400-7e84-11eb-80fb-0b627cebf8ad.png)

**Comment by yueh** [comment] 2021-03-06 18:06
Duplicate of #4760

**Closed by yueh** 2021-03-06 18:06 UTC
