### ISSUE TITLE
GregTech Community Edition Compability Request

### ISSUE THREAD

**Issue by HonzaVinCZ** [AppliedEnergistics/Applied-Energistics-2#4087] opened 2019-07-05 11:19 UTC
Hello, I'd like to ask you if there could be implemented compability with GTCE. I mean it is not possible to allow EU from GTCE to be connected with Applied Energetics. We're working on tehnic modpack and honestly we're using Thermal Expansion just because Applied Energetics. If there was compability with GTCE, we would not must use the Thermal Expansion mod and that's why we'd really like compability with GTCE. I was asking for help on GTCE discord but I was told to ask for help here. We're using 1.12.2 Minecraft version.

**Comment by JRHerlehy** [comment] 2019-07-05 19:24
CEU Mod adds converters to go GTCE EU to fe/rf.

**Comment by yueh** [comment] 2019-07-05 19:50
Duplicate of #3770

**Closed by yueh** 2019-07-05 19:50 UTC
